### ISSUE TITLE
Wiki: Initial Setup

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#1]
### Overview
We want to have a central location for interns and the internship team to store and communicate information so that we can be as effective as possible.

### Action Items

- [x] Clone wiki from template
- [x] Copy next steps from AMA into Our Process section
- [x] Formatting/cleanup of Our Process section
- [x] Review Homepage Question and write draft content in the comments below
   - [x] Review w/Bonnie
   - [x] Revise
- [ ] Review rest of wiki pages and figure out which pages are not needed, make a list of NOT needed page names and links in comments below

### Resources/Instructions
[Internship AMA Summer 2021](https://docs.google.com/document/d/138TuoRoHN9S3IhbklFjge9QO4hBV2-eKGR0yR7CttzY/edit#heading=h.o31w6jmip2eh)
[Internship Wiki](https://github.com/hackforla/internship/wiki)
[Last messaging sent after the acceptance letters were sent](https://docs.google.com/document/d/1U6J-cf_Hm63rV2z5JidG4rupmGSS3Lht8VxmDTUHF5I/edit)
[Summer Internship Check In Survey](https://docs.google.com/forms/d/1dLnvtsApjcWHgcvzjNoBAy_5LJSZ8YJpfJNV4NkeFIM/edit#responses)

**Comment by Zytko** [comment]
**_DRAFT NOT YET FILLED OUT_**. -- see the [Civic Tech Index wiki](https://github.com/civictechindex/CTI-website-frontend/wiki) for a working example.

# Welcome to the [REPLACE WITH YOUR WIKI NAME] Wiki!

## Project Definition

[ADD DEFINITION]

## Introduction To The Project

### What is [REPLACE WITH YOUR WIKI NAME]?

[ADD SHORT DESCRIPTION]

### Why do it? 
[ADD SHORT WHY]
 
### Hasn't it been done already?
[ADD SHORT ...]
  

### So how is this different?
[ADD SHORT ...]

## Guiding Objectives

### What are our guiding objectives?
[ADD SHORT ...]


## Project One Sheet

You can access our [project one sheet here]().

**Comment by Zytko** [comment]
Don't need: Hasn't it been done already, how is it different sections

**Comment by ExperimentsInHonesty** [comment]
Initial Setup is completed
