### ISSUE TITLE
Review wiki and google drive to identify what is missing from our onboarding

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#100]
### Overview
We need the wiki to have clear and concise documentation for new team members so that they can get up to speed fast.

### Action Items
- [ ] Make a Google Doc and put it in the folder
- [ ] Review wiki, making notes (questions and comments) as you go in the doc:
  - [ ] Information that doesn't flow (its there, its just not where you would need it if you are new to the project)
  - [ ] information missing
  - [ ] incomplete information
- [ ] Review Google Drive (start with Justin's doc)
  - [ ] Information that doesn't flow (its there, its just not where you would need it if you are new to the project)
  - [ ] information missing
  - [ ] incomplete information

### Resources/Instructions
- [Internship Google Drive Main folder](https://drive.google.com/drive/folders/1z3I2SLQzYWBHIypNZO-sTdSO0A8c5pvt)
- [Folder to put any documents that are guidance for new team members (not interns)](https://drive.google.com/drive/folders/1dEHKb8bi7ucTehEb5hXH4hyzu4k2fEVd?usp=sharing)
- [wiki](https://github.com/hackforla/internship/wiki)
- [Justin's FAQ for new User Researchers](https://docs.google.com/document/d/1SP9gu86aXQUldd_SiyIBJ5sGRHS7CzWElZ_kfjTn9hQ/edit)

#### Draft of questions and notes
- [IP: Review of Wiki and Drive](https://docs.google.com/document/d/1Cgd6WFbGS5W1qI8Og00mRq_GaRo3MUhdLg-BV6wbZD8/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Agreed Action Items
- Add linkedin Profiles to https://github.com/hackforla/internship/wiki/Interns-summer-2021 (the profiles can be found in the linkedin issues with each of their names on them)
- Current team needs to be updated
- Bonnie to make an image (two circles) that represents Internship experience being an add on to Volunteering that makes the interns successful.

**Comment by ExperimentsInHonesty** [comment]
After the above is done, we will review together and figure out next steps.

**Comment by ExperimentsInHonesty** [comment]
@aditipaulphd I ended up writing up the meetings part, and have added it to the wiki. I ended up needing the list to finish the image I was creating.  See here https://github.com/hackforla/internship/wiki/Meetings

**Comment by ExperimentsInHonesty** [comment]
We have signed off on the volunteer onboarding: and the remaining item is 
- [ ]  Add linkedin Profiles to https://github.com/hackforla/internship/wiki/Interns-summer-2021 (the profiles can be found in the linkedin issues with each of their names on them

**Comment by aditipaulphd** [comment]
linkedin Profiles added to https://github.com/hackforla/internship/wiki/Interns-summer-2021

**Comment by aditipaulphd** [comment]
all issues resolved.
