### ISSUE TITLE
Create wiki page: Prospective Interns

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#102]
### Dependency
- Define the information architecture of the wiki #119 

### Overview
We need a page on the wiki to send prospective interns to, so that they can get more information than is possible in the internship listing from their school.

### Action Items
- [x] Define content for wiki
  - [x] landing page
     - [x] review with Bonnie and possibly rest of the team
     - [x] Build page content in a comment below
     - [x] Add page to wiki
     - [x] provide a link in the Wiki additions section below
  - [x] role postings
     - [x] review with Bonnie and possibly rest of the team
     - [x] Build page content in a comment below
     - [x] Add page to wiki
     - [x] provide a link in the Wiki additions section below
  - [x] meetings
      - [x] review with Bonnie and possibly rest of the team
     - [x] Build page content in a comment below
     - [x] Add page to wiki
     - [x] provide a link in the Wiki additions section below
  - [x] type of meeting description
     - [x] review with Bonnie and possibly rest of the team
     - [x] Build page content in a comment below
     - [x] Add page to wiki
     - [x] provide a link in the Wiki additions section below
  - [x] FAQ (see issue #119)
      - [x] review with Bonnie and possibly rest of the team
     - [x] Build page content in a comment below
     - [x] Add page to wiki
     - [x] provide a link in the Wiki additions section below

#### Drafts 22

- [Summer 22 Internship Description - Text for Wiki](https://docs.google.com/document/d/10nQkeFlzPe3GvzJQNWOjTZmxMVf8bB8cAKQt7yciV0k/edit?usp=sharing)

#### 2021 Resources

- [IS21: Project Management Intern Value Delivered](https://docs.google.com/document/d/1-JhAoQ_ADknihfhLct_5kOmulzjpp_QllwL0lUt7UtU/edit)
- [IS21: UI/UX and Software Engineering Interns Value Delivered](https://docs.google.com/document/d/1PXbjABAcwpb8_83PicPHISxU9IsNXasX0yTVB6iMdck/edit#heading=h.mco89j8thjkt)

#### Relevant Issues

- #114 
- #120 

### Wiki additions
- Edited the landing page
  - https://github.com/hackforla/internship/wiki/Project-Introduction-for-Interns
- Created role recruitment pages
  - https://github.com/hackforla/internship/wiki/Summer-2022-Software-Engineer-Intern-Posting
  - https://github.com/hackforla/internship/wiki/Summer-2022-Project-Manager-Intern-Posting
- Created Meeting Time Pages:
  - [Meetings Summer 2022 for Software Engineers](https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Software-Engineers) 
  - [Meetings Summer 2022 for Project Managers](https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Project-Managers)
  - [IS22 Cohort overview](https://github.com/hackforla/internship/wiki/IS22-Cohort-Overview)

**Comment by ExperimentsInHonesty** [comment]
# Prospective Interns

**Comment by Rabia2219** [comment]
@aditipaulphd...I believe this is the correct issue...link is under resources...

**Comment by Rabia2219** [comment]
Add [this](https://us02st1.zoom.us/web_client/ylhwn7x/html/externalLinkPage.html?ref=https://docs.google.com/document/d/1-JhAoQ_ADknihfhLct_5kOmulzjpp_QllwL0lUt7UtU/edit#) document as an example of work done by past interns.

**Comment by Rabia2219** [comment]
We need to add a meeting calendar so that interns know exactly what hours they need to block out for Hack for LA during the week so that they have an opportunity to decide before applying whether the timings work for them or not.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 

This is the issue that needs to be updated once the listings are ready.

**Comment by ExperimentsInHonesty** [comment]
I have created the following pages, the software one is done but the project manager one remains to be be updated.
- Created Meeting Time Pages:
  - [Meetings Summer 2022 for Software Engineers](https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Software-Engineers) 
  - [Meetings Summer 2022 for Project Managers](https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Project-Managers)
