### ISSUE TITLE
Recruit New Product Manager

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#112]
### Overview
We need a product manager to help us drive the next phase of our project and oversee the preparation of the internship for next summer. As a PM you will be responsible for working with the UI/UX and other PMs, managing the Kanban board, creating issues for milestones, and helping to prioritize the backlog. 

### Action Items
- [x] Edit note
- [x] Post it in opportunities
- [x] Post opening on Slack PM channel
- [ ] When candidates reach out in our slack
  - [ ] Send them the following:
```
Thanks for you interest.  We look forward to meeting you.  Have you have been to the General Hack for LA Onboarding yet (https://meetup.com/events).  
- If yes, please write us back with your email so that we can add you to our next PM meeting.  
- If no, please reach back out to us after you have sucessfully completed onboarding
```
  - [ ] Add them to our next PM meeting calendar invite, or the All Team meeting, whichever comes first
- [ ] Once onboarded to our team, move the issue to filled on product open roles board if we don't need anymore PMs

### Resources/Instructions
- [Product Management Open Roles board](https://github.com/hackforla/product-management/projects/8)
- HTML to put at the top of the open role card so that the logo appears above the content
```
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">
```
- [Current Post](https://github.com/hackforla/product-management/projects/8#card-64639834)

```
**Project Name**: TechWorkExperience

**Volunteer Opportunity**: This project provides internship opportunities for high school & college students. Our 2nd cohort is underway. This is the project for you if you want hands on experience in service delivery, building website requirements and improving processes through extensive research.

**Duration**: open ended

**Communicate your interest**
- Slack channel: #[internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of contact: Elizabeth Pierotti

[Read more about the project](https://github.com/hackforla/internship/wiki)

#### When we meet:
- **Required for PM**
   - Mondays 9:30-11:00 am PST (PM Meeting)
   - Thursdays 9:30-10:00am PST (PM Prep Meeting)
   - Thursdays 10:00-11:00am PST (All Team Meeting)
- **Recommended**
   - Wednesdays 9:00-11:00 am PST (Optional PM Meeting)
```
- Old Post Wording
```
**Project Name**: TechWorkExperience

**Volunteer Opportunity**: Building off of the successful Internship program we ran in '21.  We will be running a second pilot Internship program this summer with high school and college students.  We will be building a website and tools to support this program.

**Duration**: open ended

**Who to communicate your interest to**
- Slack channel link: #[internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of person to contact in the channel: Priyanka or Rabia

[Read more about the project](https://github.com/hackforla/internship/wiki)

#### When we meet:
- **Required for PM**
   - Mondays 9:30 -11:00 am PST (PM Meeting)
   - Thursdays 9:30 -10:00am PST (PM Prep Meeting)
   - Thursdays 10:00 -11:00am PST (All Team Meeting)
- **Recommended but not required**
  - Tuesday 12:00 - 12:30pm PST (product/BA)
  - Tuesdays 3:00 - 4:00pm PST (Product/Research Meeting)
```

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar This issue is called "Recruit New Product Manager" however there is a checkbox in it that says 
"Talk to potential UX researchers"  I assume that is a typo, please fix

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar please update status in this issue

**Comment by priyatalwar** [comment]
Oops, just fixed it.

**Comment by priyatalwar** [comment]
Update 2/17 onboarding completed so closing this issue.

**Comment by Rabia2219** [comment]
We have onboarded Annie Troung and Elizabeth Pierotti as PMs. 
The card is still in the open roles as we are in need of more PMs.

**Comment by priyatalwar** [comment]
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project Name**: TechWorkExperience

**Volunteer Opportunity**: This project provides internship opportunities for high school & college students. Our 2nd cohort just finished. This is the project for you if you want hands on experience in service delivery, building website requirements and improving processes through extensive research.

**Duration**: open ended

**Communicate your interest**
- Slack channel: #[internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of contact: Priyanka Talwar

[Read more about the project](https://github.com/hackforla/internship/wiki)

#### When we meet:
- **Required for PM**
   - Mondays 9:30-11:00 am PST (PM Meeting)
   - Wednesdays 9:00-11:00 am PST (PM Meeting)
   - Thursdays 9:30-10:00am PST (PM Prep Meeting)
   - Thursdays 10:00-11:00am PST (All Team Meeting)

**Comment by priyatalwar** [comment]
Made the posting concise and posted on 6/28

**Comment by ExperimentsInHonesty** [comment]
We no longer use this format. See https://github.com/hackforla/internship/issues/602
