### ISSUE TITLE
IS22: Search for potential partners

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#113]
### Overview
We need to reach out to other schools to find out if they have any internship opportunity offerings and if its not too late to be included.

### Action Items

- [x] Find appropriate contact
- [x] Send Email
   - [x] Marlborough
   - [x] Havard-Westlake
   - [x] Archer (second choices)
   - [x] Buckley (second choices)
   - [x] Crossroads (second choices)
   - [x] Loyola

### Findings/Progress
**Note:** Brentwood mentions the Internship program on their website but there is no contact information for potential sponsors. Also HackforLA is not listed in the list of past sponsors.

**Marlborough:**
Internship program not mentioned on website.
Spoke to Amy at the Front Office who said she could forward my email to Allison Ponzio. I found the email listed on the website.
Front Office Phone Number:
323.935.1147
AMY RIECKELMAN
Front Office Coordinator
Amy.Rieckelman@marlborough.org
DR. ALLISON PONZIO
Honors Research in Science Program Head, Science Instructor
allison.ponzio@marlborough.org

**Havard-Westlake:**
Internship program not mentioned on website.
Spoke to Maria who directed me to Pat Notle who did not pick up and Maria isn't even sure that she's the right person to talk to.
Front Office Phone Number:
818-980-669
MARIA ARIAS
Receptionist and Admission Assistant
Div: MS
310-288-3207
(Not a 100% if this is the Maria I spoke to as she did not give me her last name)
PAT NOLTE
Administrative Assistant
Div: US
818-487-6655
(Their emails are not listed but there's an option to SEND MESSAGE which opens up a form)
**Note:**
I had to rewrite the email into a 500 word message to fit the form requirements:
Hello Pat,
I am reaching out to you on behalf of HackforLA's Internship Program, which had partnered with Brentwood School as a sponsor last year. This year we would like to extend our program to more LA area high schools and would like to know:
If Harvard-Westlake has a summer internship placement program that HackforLA could sponsor? Is there still time for HackforLA to officially sign up as a sponsor? What is the process to do so?
I look forward to hearing from you soon.
Regards,
Rabia Shaikh

**Archer:**
Internship program not mentioned on website.
Spoke to ---- who directed the call to the Communication Office. Spoke to Amanda who also had no idea and asked to email at communications@archer.org. She will try to locate the appropriate person and forward it to them.
Front Office Phone Number:
310.873.7000
Amanda
Communication Office
communications@archer.org

**Buckley:**
Internship program not mentioned on website.
Reaching out to:
Abi Basch
Upper School Director of Service and 6-12 Experiential Learning Coordinator
(818) 783-1610 ext. 562
abasch@buckley.org

**Crossroads:**
Internship program not mentioned on website.
Talked to Christina at the main office (310-829-7391). I was directed to Jennifer Gerber who did not answer. I left her a message with our email address to reach out if they were interested.
Called Christina back and asked for Jennifer's email. She is the Director of Alumni Relations and does handle student internship placements. I have reached out to her via email as well.
Christina
Main Office
310-829-7391
Jennifer Gerber 
Director of Alumni Relations
Email: jgerber@xrds.org

**Loyola:**
Sent an email to:
JENAVI HERNANDEZ
Administrative Assistant, Main Office
x1220
jhernandez@loyolahs.edu

#### Notes

- Some opportunities require students to receive course credit. Please note that Brentwood School does not offer course credit. Students are eligible to receive community service hours if interning at a non-profit organization. College students must check with their university’s registrar to verify internship course credit. 
- [Resource](https://www.thebalancecareers.com/internship-for-credit-1986652) with explanation of the above statement.

#### Relevant Issues

- #125 

#### School Websites

- [Marlborough](https://www.marlborough.org/)
- [Havard-Westlake](https://www.hw.com/)
- [Archer](https://www.archer.org/)
- [Buckley](https://www.buckley.org/)
- [Crossroads](https://www.xrds.org/)
- [Loyola](https://www.loyolahs.edu/)

**Comment by Rabia2219** [comment]
Discussion points from call with Bonnie on 01/28/22

For the future cohorts:

1. We should have a UX researcher:

   - Put a together a list of schools, both public and private to reach out to with a list of questions about internship programs (do they have one? why? what is the set up? would they be interested in 'internship in a box', etc)
   - Do an analysis of the situation about internships in LA school areas that we can use to our advantage

2. It would be a good idea to put together a guide for future PMs on how to research and find future partners for the Internship program

**Comment by Rabia2219** [comment]
Update:
Heard back from Marlborough:
```
Hi Rabia,

We don't have a formal internship placement program here at Marlborough, but we do have a lot of girls interested in coding.

Could you tell me about your internship program?

We often have student coders interested in data science projects during the school year.  Would this be helpful for Hack for LA projects, and who should I contact about that?

Thanks!
Darren / Dr. Kessner

Darren Kessner, Ph.D.
Mathematics and Computer Science Instructor
STEM+ Program Co-Head
he | him | his
http://stem.marlborough.org

**Comment by Rabia2219** [comment]
Write back to Darren and mention:
Gaby Cohen
gabriellecohen20@marlborough.org
Food Oasis
Will let you know once our Community Service pipeline is formalized. We will reach out to you once this summer gets under way about partnering for next summer.

**Comment by Rabia2219** [comment]
> Write back to Darren and mention: Gaby Cohen [gabriellecohen20@marlborough.org](mailto:gabriellecohen20@marlborough.org) Food Oasis Will let you know once our Community Service pipeline is formalized. We will reach out to you once this summer gets under way about partnering for next summer.

Done.

**Comment by Rabia2219** [comment]
Received an out-of-office auto reply from Abi at Buckley.

**Comment by Rabia2219** [comment]
Update on Marlborough:
Regina from Marlborough reached out to ask if we could include at least one student this summer. It is a tentative yes. The student will need to go through the whole application and interview process and we will open up a new spot.

Update on Crossroads:
Rachael from Crossroads reached out and had a conversation with Bonnie. They do have an internship placement program in place. Reached out to her today asking about their decision.

**Comment by Rabia2219** [comment]
Received application from the Marlborough student.
Waiting to receive applications from Crossroads.
Paused reaching out to schools. Will resume if needed and ask Emily from Brentwood for help in doing so.

**Comment by Rabia2219** [comment]
Emailed Rachael from Xroads informing her that we are still accepting new applications till EOD Sunday, April 3rd.

**Comment by ExperimentsInHonesty** [comment]
Spoke to Emily, she recommended 
Kwaisi France at Harvard Westlake, Director of HW Works
https://www.hw.com/about/Faculty-Staff-Directory/individual/807d183d-b88e-47f4-b896-de4838434fa5


Robin Rickett rpickett@windwardschool.org
https://www.windwardschool.org/student-life/windward-network - this is their internship page

**Comment by Rabia2219** [comment]
Update:
Extended deadline for applications to April 22nd for Xrds
Bonnie reached out to Robin from Windward via email. I reached ~ a week later via phone. We have not heard back.
Send message to Kwaisi France via the school's messaging system.

**Comment by Rabia2219** [comment]
Xrds is on Spring Break. Drafting this email and will send it out on April 22nd:
```
Hi Rachael,

I hope you had a wonderful Spring Break. 

Now back to business! We would like to know the dates for when Xrds expects:

1. To notify students about which internships they have been selected for
2. The students must confirm their participation in an internship

We will be sending out our first batch of acceptance letters on April 13th and expect confirmation from students in that batch no later than April 29th. Having these dates from Xrds will help us plan our coming weeks.

Best,
Rabia
```

**Comment by Rabia2219** [comment]
Although there was a positive response from Crossroads, the school did not participate in the IS22 cohort as no students applied for our program.
Buckley, Archer and Loyola did not show an interest.
