### ISSUE TITLE
IS22: Create new intern opportunity listings

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#114]
### Overview
We need to add all the information to the wiki for the new intern opportunity listings we are going to have to provide to the schools sometime between the 28th and the 4th when their listing go live.

### Action Items

- [x] Create New Listing
  - [x] a combined version
  - [x] separate for each version
  - [x] what will appear on the wiki when they go there
- [x] Review
- [x] Add to wiki

### Resources/Instructions
- [IS22 Google Drive Folder](https://drive.google.com/drive/folders/1R2-Jjc5pHBM1jUFkxOgTigPB6sm4_Ktm?usp=sharing)

#### Drafts 2022
- [IS22:  Internship Description - Individual](https://docs.google.com/document/d/14QBxiq0qSMSEDH_v6BruyAlv--RriXSkzHS4zHeCE3k/edit?usp=sharing)
- [IS22: Internship Description - Text for Wiki](https://docs.google.com/document/d/10nQkeFlzPe3GvzJQNWOjTZmxMVf8bB8cAKQt7yciV0k/edit?usp=sharing)<strike>
- [IS22:  Internship Description - Combined](https://docs.google.com/document/d/1feNvK3ezu8xRqK3YnHIU46twX1nn5BcOXaN83-9ZcBw/edit?usp=sharing)</strike>

#### 2021 resources
- Intern Open Roles listing
  - [IS21: Brentwood Internship posting](https://docs.google.com/document/d/1L-BGJo2CV7Hj7AZDtCm5IDRBxBjjfqmD_AoLGeplCrE/edit#)
- Value Delivered documents (sent to Brentwood with their Sponsor Reflections form
  - [IS21: Project Management Intern Value Delivered](https://docs.google.com/document/d/1-JhAoQ_ADknihfhLct_5kOmulzjpp_QllwL0lUt7UtU/edit)
  - [IS21: UI/UX and Software Engineering Interns Value Delivered](https://docs.google.com/document/d/1PXbjABAcwpb8_83PicPHISxU9IsNXasX0yTVB6iMdck/edit#heading=h.mco89j8thjkt)
  - [Screen capture PDF of Brentwood's 2021 listings](https://drive.google.com/file/d/11RuR0rhBwhJ-qtb8LebOgJesIeKgiW__/view?usp=sharing)

#### Brentwood School internship listing
- [Brentwood's listing of  internship opportunities](https://www.bwscampus.com/alumni/career-resources/summer-internship-opportunities)
- see 2021 above for screenshot of what it looked like last year.

#### Relevant Issues

- #102

### Type of Information we need to provide
- Eligibility: 
- Industry: 
- Compensation: 
- Location: Virtual
- Number of Positions Available: 
- Time Frame: _ days per week/ _ weeks / ____ of hours per day
- Description/Main Responsibilities:
- More about ______ name of org____:

**Comment by Rabia2219** [comment]
@aditipaulphd...this is the document for the wiki text: [Summer 22 Internship Description - Text for Wiki](https://docs.google.com/document/d/10nQkeFlzPe3GvzJQNWOjTZmxMVf8bB8cAKQt7yciV0k/edit?usp=sharing)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty I've linked the Sponsor Feedback Form document and the 2 sub documents from IS21 in the resources above...

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty sorry I think we were adding the links at the same time...

**Comment by ExperimentsInHonesty** [comment]
This document 
[Document attached in original email from Emily that contains details of intern positions we offered in Summer 21](https://docs.google.com/document/d/1aNz-s8lrqo8sY_UUeCQQDY64Nrod2ZZo/edit?usp=sharing&ouid=111151316933729112141&rtpof=true&sd=true)

has been replaced by 

[IS21: Brentwood Internship posting](https://docs.google.com/document/d/1L-BGJo2CV7Hj7AZDtCm5IDRBxBjjfqmD_AoLGeplCrE/edit#)

**Comment by Rabia2219** [comment]
I have moved the IS21 document into the IS21 folder on our drive...

**Comment by Rabia2219** [comment]
Note: we have a separte draft document for Wiki text.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 

The shorter version for the listing we will provide to Brentwood needs to go in this document:
[Summer22 Internship Description - Individual](https://docs.google.com/document/d/14QBxiq0qSMSEDH_v6BruyAlv--RriXSkzHS4zHeCE3k/edit?usp=sharing)

The longer version with the added fields/text for the Wiki page needs to go in this document:
[Summer 22 Internship Description - Text for Wiki](https://docs.google.com/document/d/10nQkeFlzPe3GvzJQNWOjTZmxMVf8bB8cAKQt7yciV0k/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Content for schedule page for pms - needs to be updated
<img src="https://user-images.githubusercontent.com/37763229/147723134-3e360ba4-14ed-47db-8d87-1c13a289d70c.png" alt="Internship Meetings" width="600"/>

## Internship only meetings

### Daily Meetings
- Stand up (15 min-1 hour daily 4 days)

### Weekly Meetings
- 1-on-1 Soft Skills Coaching (15-30 min weekly)
- LinkedIn Workshops (1 hour weekly)
- 1-on-1 LinkedIn Writing (3 hours)
- Community of Practice (1 hour weekly)

## Project Team Meetings
Interns attend these weekly meetings as part of their participation on the team
- All Team (2 hours)
- Project Management meetings (from 2-4 hours weekly)
- Software Engineering (1 hour weekly)
- Office Hours (1 hour weekly/optional)

**Comment by priyatalwar** [comment]
Most of the scheduled meetings for Project Manager interns are negotiated between the Mentor and the Intern, except for project meetings, which are already scheduled. There are several projects to choose from, and we will find the best fit (availability, and capability) for the candidate and the org when we do interviews. [2] Exceptions to scheduled meetings can be arranged if disclosed during the application process (e.g., last year, two of the interns needed to miss meetings for travel time to arrive at their family's vacation destination, one intern had a church time conflict and could only attend a portion of a specific weekly meeting, etc.). Additionally, we realize that emergencies do come up and will work with you to help successfully complete the internship.

Rewording

We will work around your availability to schedule meetings for the Project Manager interns, except for project meetings, which are already scheduled.  Exceptions to scheduled meetings can be arranged if disclosed during the application process (e.g., last year, two of the interns needed to miss meetings for travel time to arrive at their family's vacation destination, one intern had a church time conflict and could only attend a portion of a specific weekly meeting, etc.). Additionally, we realize that emergencies do come up and will work with you to help successfully complete the internship. There are several projects to choose from, and we will find the best fit (availability, and capability) for the candidate and the org when we do interviews
