### ISSUE TITLE
IS22: Schedule AMA and figure out who will need to be there and what we will cover

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#119]
### Overview
We need to schedule an AMA so we can answer any questions our summer cohort 22 may have

### Action Items

- [x] Write to BWS about the best time to schedule
- [x] Figure out logistics
- [x] Revise AMA presentation

### Resources/Instructions
- #116
- [IS21 AMA](https://docs.google.com/document/d/1v_ZUO0sK-CFkkOCcTA1MejDS-ohCHCzDFFG2bVciJQY/edit?usp=sharing)
- [IS22 FAQ](https://docs.google.com/document/d/1TpacAma_vmAZ4MGq_VAQme22BsgKm1DW5rFBhYgm6vM/edit#heading=h.o31w6jmip2eh)
- [IS22: AMA Slide deck](https://docs.google.com/presentation/d/1Uy3c1ZbWbytllA1KqL4pu3LI5ma8IDxwLQSjRe3h0g0/edit#slide=id.gea24f90547_0_3)
- [IS22: AMA Recording](https://drive.google.com/drive/folders/1WgVNybPeN09rTYQ23_NojC7PCWtJ9aSe?usp=sharing)

**Comment by Rabia2219** [comment]
Brentwood will get back to us with if and when we can do it on campus.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty is setting up the Zoom link now and will email it to Emily. The AMA is scheduled for Wednesday Feb 16th at 1 pm PST.

**Comment by ExperimentsInHonesty** [comment]
Update the deck with addition resources:
Chat from AMA 
Meeting times: https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Software-Engineers
Free Code Camp: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/
Example of Intern Linkedin: https://www.linkedin.com/in/sakari-salminiitty/

contributing file
confidence (kpi)
