### ISSUE TITLE
IS22: Provide details we will require from Students to their Schools

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#125]
### Overview
We need to ask for the same information across all the applicants so that we can evaluate them together

### Action Items
- [x] Ask Brentwood if we may use the questions (Emily said yes to Bonnie on 2022-02-16, she understood the reason we need to ask similar questions)
- [x] Create Google Doc (use same branding and format that is on the IS22: Internship Description)
- [x] Review with Bonnie

### Resources/Instructions
- [IS22 Internship Application Process Questionnaire - Information collected by the Internship Project](https://docs.google.com/document/d/1U1CS6lDg-buD72dSHBn24gXxepyrqliF7919UWOI1jM/edit)
- [Brentwood Internship Application](https://docs.google.com/forms/d/e/1FAIpQLSdlXH6X5QzAWw83zsXBjpKfne8y6MJpbmbeFBdEBzjASG0F7Q/viewform)
- [IS22:  Internship Description - Individual](https://docs.google.com/document/d/14QBxiq0qSMSEDH_v6BruyAlv--RriXSkzHS4zHeCE3k/edit)

**Comment by priyatalwar** [comment]
@Rabia2219 and I created the [doc ](https://docs.google.com/document/d/1U1CS6lDg-buD72dSHBn24gXxepyrqliF7919UWOI1jM/edit#)and reviewed with Bonnie. Working on some formatting before emailing to Marlborough.

**Comment by priyatalwar** [comment]
Update 2/17: email sent to Marlborough with the attached doc so closing this issue.
