### ISSUE TITLE
IS22: Create and send acceptance letters

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#129]
### Overview
We need an acceptance letter draft to send to interns once we select the 2022 cohort

### Action Items
- [x] Define when it will need to be sent out and add that date to this issue. April 13th (for BWS & Marlborough students)
- [x] Review prior messaging
- [x] Update the 2022 FAQ
- [x] Make a copy of IS21 acceptance letter
- [x] Revise for IS22
- [x] Review with Bonnie
- [x] Setup Mail Merge
   - [x] To produce bulk acceptance letters
   - [x] To email in bulk
- [x] Create PM only roster to test out bulk emailing
- [x] Test bulk emailing
- [x] Send out final draft on April 13th (for BWS & Marlborough students)

#### Drafts
- [IS22: Internship acceptance email](https://docs.google.com/document/d/1Mgr3lJw_vwi5BpWVamX-4u5SSKnW0lNL3yvrVrQPn-Q/edit)
- [IS22: Template Offer letter with Mail Merge setup](https://docs.google.com/document/d/16nwdEGkeaC29BfPs1jFN_wRTC3INRVPdvOuKmWXQD-k/edit)
- [PM only Roster for Mail Merge](https://docs.google.com/spreadsheets/d/1PRvGU9e1Gj8HzmTZup1JcYBbuSp5iid-I_Pyo-v-fOQ/edit#gid=0)
~- [IS22: Internship Acceptance Letter - For BWS Without Emojis](https://docs.google.com/document/d/1cN88wADLrhTeO7tkTzIsESYv6hYJhJonRTwa2w-bDiY/edit)~ **See Notes**
- See prior acceptance letter [IS21: Internship acceptance messaging](https://docs.google.com/document/d/1qW1Jo2217HpJZRw-NtOlPBWCF03WiCH-bQMPfyZ91cc/edit)
- [IS22 Cohort candidates](https://docs.google.com/spreadsheets/d/1gQaHDEongGiP_CawghV0YGvO1l9c4qhT0lMll8iFdYw/edit#gid=0)
- [IS22 Timeline/Milestones](https://docs.google.com/spreadsheets/d/1rELYpwDNs_HQSkQvjr0JX2UmHBSKJD6PT1XXoHk9Phs/edit#gid=0)

#### External Resources
- Spreadsheets shared by BWS:
  - [HackforLA Software Engineer BWS Interns 2022](https://docs.google.com/spreadsheets/d/1hCyCYsXJETPW_UFFLFWgIP6MYqZvxUS9DXclvnO3-XI/edit#gid=0)
  - [HackforLA Project Manager BWS Interns 2022](https://docs.google.com/spreadsheets/d/1TDHBwhH_APaEzNt_QjHPaS2C2bWbPg6KgEpvFotgUwY/edit#gid=0)

- [ Folder shared by BWS](https://drive.google.com/drive/folders/1j-9BLsaKUZPA5PTXejplj_TWtzOtqlhz?usp=sharing)

#### Relevant Issues

- #119 -FAQ is in this issue
- #158 

#### Notes
~- We created a draft for the acceptance email with 3 customized sections, therefore we do not need separate documents for each school~ We were able to create an email template using mail merge
- We created an acceptance letter template using mail merge 
- The 2022 FAQ needs to be updated for PM roles

### Acceptance letters (to be made into PDFs)
[IS22: Offer letters](https://docs.google.com/document/d/1p1P4VvmzQeBndrX8VOc0kt5X8L82RTj9xEvYmkLZ6nU/edit)

### PDFs of offer letters
[Folder to store them in]

**Comment by ExperimentsInHonesty** [comment]
Make a new label that matches messaging to students

**Comment by ExperimentsInHonesty** [comment]
Apr/13/22: TWI to notify Alumni Office of intern selection decision
Apr/18/22: Brentwood will notify students about which internships they have been selected for
Apr/29/22: The students must confirm their participation in an internship by this date

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty before we can send out the acceptance letter the [Internship FAQ Summer 2022](https://docs.google.com/document/d/1TpacAma_vmAZ4MGq_VAQme22BsgKm1DW5rFBhYgm6vM/edit#) needs to be updated with the Meetings Summer 2022 for Project Managers. We could send it now because we don't have any PMs yet.

**Comment by gracieama** [comment]
This needs to go out on or before April 13th.

**Comment by Rabia2219** [comment]
Xrds will send application on April 22nd. Waiting on dates from them to finalize when we will send letters to them

**Comment by gracieama** [comment]
The letter was created and sent to the following people:
Melodie
Riya
Sakari
Beckett
Jason
Mateo

- [email acceptance message](https://docs.google.com/document/d/1TogHrEOqUD5H0xpShKJG58VqrK7nJVFsRE1yF-8DehM/edit)
- [spreadsheet we used to merge from](https://docs.google.com/spreadsheets/d/1-IMev2TnzusPg99mAl2orloIHZN8r8QMjF9zWvFouK4/edit?usp=sharing)
- [Mateo's offer folder](https://drive.google.com/drive/folders/1c4O3h9uwHinITsO8IGsa16FWVBUeAS-L)

**Comment by Rabia2219** [comment]
A second batch of acceptance letters was sent out on May 25th to:

- Lily
- Charity
- Asher
- Brian
- Tung
- Clayton 

We are not accepting any more applications. Closing this issue...
