### ISSUE TITLE
TWE: LinkedIn recommendations: Research Plan: Gather people links from HfLA LinkedIn

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#130]
### Overview
We need to know the status of recommendations on HfLA volunteer LinkedIn profiles so that we can interview them about the asking for recommendations process

### Action Items
- [x] Create a spreadsheet with the following columns
   - [x] Name
   - [x] Role Type (see list below)
   - [x] LinkedIn URL
   - [x] Has recommendations (true/false)
- [ ] Review Hack for LA LinkedIn to find people using Hack for LA on their resume and fill out the spreadsheet
### Resources
[Hack for LA LinkedIn](https://www.linkedin.com/company/hack-for-la/people/?viewAsMember=true)
#### Role type list**
- Front End
- Back End
- Full Stack
- PM
- Writer
- Designer
- Researcher
- Designer/Researcher
- Designer/Front End
- Designer/Writer
- Researcher/Writer

[LinkedIn Profile Sheet](https://docs.google.com/spreadsheets/d/1LITkDq6XewgI-GoDyCRZaHZf8Jx3O8gnoeFXGDhCAws/edit?usp=sharing)

[LinkedIn recommendation: Research Plan](https://docs.google.com/document/d/15_iabeCRzoB8FLML2xW5MpWtQxUIhfkt6mi6NDJJDG0/edit)

**Comment by ExperimentsInHonesty** [comment]
@Justlee98 Don't forget to link your spreadsheet in the issue details above

**Comment by Justlee98** [comment]
> @Justlee98 Don't forget to link your spreadsheet in the issue details above

I just added the spreadsheet

**Comment by ExperimentsInHonesty** [comment]
When you are done with the spreadsheet, make a new issue for creating a research plan.  Use the template and guide from this issue: https://github.com/hackforla/UI-UX/issues/120

**Comment by Justlee98** [comment]
@ExperimentsInHonesty I have finished working on a draft in regards to research plan for LinkedIn Recommendation 
[Research Plan for LinkedIn Recommendation](https://docs.google.com/document/d/15_iabeCRzoB8FLML2xW5MpWtQxUIhfkt6mi6NDJJDG0/edit)

**Comment by Rabia2219** [comment]
> @ExperimentsInHonesty I have finished working on a draft in regards to research plan for LinkedIn Recommendation and the google sheet information. Please let me know what I should fix or edit [Research Plan for LinkedIn Recommendation](https://docs.google.com/document/d/15_iabeCRzoB8FLML2xW5MpWtQxUIhfkt6mi6NDJJDG0/edit)

@Justlee98...Hi Justin...the document that you've linked above is not in the Internship drive...please move it there so we can access it for review...thanks...

**Comment by Justlee98** [comment]
> > @ExperimentsInHonesty I have finished working on a draft in regards to research plan for LinkedIn Recommendation and the google sheet information. Please let me know what I should fix or edit [Research Plan for LinkedIn Recommendation](https://docs.google.com/document/d/15_iabeCRzoB8FLML2xW5MpWtQxUIhfkt6mi6NDJJDG0/edit)
> 
> @Justlee98...Hi Justin...the document that you've linked above is not in the Internship drive...please move it there so we can access it for review...thanks...

I'm sorry about that. I have moved it to the Internship drive

**Comment by Justlee98** [comment]
@ExperimentsInHonesty Hi bonnie, I have created a new issue for the LinkedIn recommendation. Please do let me know how it looks. https://github.com/hackforla/internship/issues/147

**Comment by ExperimentsInHonesty** [comment]
We added a category column and categorized all the people
