### ISSUE TITLE
Comparative Research (Mood and Inspiration): Color Palette: Cherilyn

### ISSUE THREAD

**Issue by bilkishgautham** [hackforla/internship#132]
### Overview
We need to decide on colors for the internship logo and project so that we can start building out templates

### Action Items
- [x] Add items of inspiration from across the internet into the color mood board figma page with your name on it

### Resources/Instructions
- [Internship Figma, Color Mood Board - Cherilyn ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A14)
- [Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2)

#### Other teams
- [Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2) - they are in the process of figuring out what they want to do 
- [Hack for LA website team Figma, Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) - this team has a working design system and color palette

**Comment by seetho-c** [comment]
Favicon updated on the [Internship, Style Guide on Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/?node-id=2%3A2)

[Internship, Color Mood board](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/?node-id=2%3A14) is in progress

**Comment by ExperimentsInHonesty** [comment]
@seetho-c Please provide update prior to the meeting
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by seetho-c** [comment]
Primary color, secondary color and color accent suggestion is on the Figma [file](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A17)

Photos from the file that will be presented at the team meeting:
![logo-reference](https://user-images.githubusercontent.com/29762834/161101139-ad0a5886-792c-4028-88e3-33c997656d12.PNG)
![example of color usage](https://user-images.githubusercontent.com/29762834/161101146-858f422b-f430-41a3-92ba-6c77c476b2da.PNG)
![color mood board from photos and photo usage suggestions](https://user-images.githubusercontent.com/29762834/161101150-049382b2-03c8-4445-96d8-3b061d42463f.PNG)

**Comment by ExperimentsInHonesty** [comment]
This was an example mentioned during todays meeting https://a.slack-edge.com/4d5bb/marketing/img/media-kit/slack_brand_guidelines_september2020.pdf

**Comment by seetho-c** [comment]
Color Palette for the Style Guide is in progress - @Susanz7  and I made updates for the Primary, Neutral, Secondary (Functional and Accent) and Text colors.

We used Hack for LA and CivicTech as a reference to define the color shades and color usage.

Below is the screenshot from the [Internship Figma file](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A17)
(Color suggestions with Airtable's website as a reference for color usage)
![Screenshot (14)](https://user-images.githubusercontent.com/29762834/162100287-21e94746-ab25-466f-987f-706c5630dacc.png)

**Comment by seetho-c** [comment]
[Internship Figma - Color Mood Board team presentation](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A17) - Color Palette is still a work in progress

Overview
![Screenshot (22)](https://user-images.githubusercontent.com/29762834/163242043-ec7b95f8-408d-4860-a090-87c817a98af1.png)

New color palette suggestions for primary and secondary colors
![Screenshot (20)](https://user-images.githubusercontent.com/29762834/163242035-403f8de3-2142-4459-b02a-511235d1ba76.png)

Email signature with color suggestions used for hyperlinks
![Screenshot (21)](https://user-images.githubusercontent.com/29762834/163242040-ab890183-5b65-4830-9f3b-6c7f83d426af.png)

**Comment by seetho-c** [comment]
Color palette suggestions for Google Slides
![Screenshot (25)](https://user-images.githubusercontent.com/29762834/164349893-f2ad340c-7233-4a64-bc3c-f27782262e39.png)

**Comment by ExperimentsInHonesty** [comment]
@seetho-c Wow!  just Wow! I love how you brought in the inspiration while not overpowering the logo!  🤩
