### ISSUE TITLE
Comparative Research (Mood and Inspiration): Color Palette: Susan

### ISSUE THREAD

**Issue by bilkishgautham** [hackforla/internship#133]
### Overview
We need to decide on colors for the internship logo and project so that we can start building out templates

### Action Items
- [ ] Add items of inspiration from across the internet into the color mood board figma page with your name on it

### Resources/Instructions
[Internship Figma, Color Mood Board - Susan](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A18)
[Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2)

Other teams

- [Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2) - they are in the process of figuring out what they want to do
- [Hack for LA website team Figma, Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) -  this team has a working design system and color palette

**Comment by bilkishgautham** [comment]
@ExperimentsInHonesty I am not able to create mood boards on Figma for the other team members. Looks like I do not have access to create it. Can you give me access or we can do this together in the next session?
In the meanwhile I will create issues and keep everything else ready.

**Comment by bilkishgautham** [comment]
@Susan I have created the color mood board and ticket is ready to be worked on.

**Comment by Susanz7** [comment]
> @susan I have created the color mood board and ticket is ready to be worked on.

Sounds good, thank you

**Comment by Susanz7** [comment]
Color Moodboard still work in progress

**Comment by ExperimentsInHonesty** [comment]
@Susanz7 Please provide update prior to the meeting
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Susanz7** [comment]
Progress updated on 3/30 by Susan: Cherilyn and I came up with 2 color palette options for team to choose from and images references to use for the project
[Internship Figma, Color Mood Board - Team Presentation](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A17)

**Comment by ExperimentsInHonesty** [comment]
This was an example mentioned during todays meeting https://a.slack-edge.com/4d5bb/marketing/img/media-kit/slack_brand_guidelines_september2020.pdf
