### ISSUE TITLE
IS22: Internship Interviews

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#135]
### Overview

We need to create an email draft and set up Calendly for the Summer 22 intern applicants.

### Action Items

- [x] Set up Calendly
```
- [x] Draft an email
- [x] Check if Calendly is working properly
- [x] Get reviewed by Bonnie
```
- [x] Finalize email and send
- [x] Monitor for response
- [x] Note responses and required actions in comments below

#### Drafts:
- [IS22: Interview Messaging](https://docs.google.com/document/d/1-12BTUxEgdzXd78dPKf584irPEF5CpC7ERriUcMhdpI/edit)

#### Calendly:
- [Internship Team Account](https://calendly.com/event_types/user/me)
- [Booking Link 3](https://calendly.com/internship22/intern-interview-second-round-clone)
- Depreciated Booking Links:
  - [Booking Link 1](https://calendly.com/internship22/intern-interview)
  - [Booking Link 2](https://calendly.com/internship22/intern-interview-round2)

**Comment by Rabia2219** [comment]
Draft of interview invite email:

Dear Student,

I hope this email finds you well.

We have reviewed your application and CV for the Hack for LA Summer 22 Internship and would like to invite you to interview with us.

We have set up days and time slots on our [Calendly](https://calendly.com/internship22/intern-interview) for you to select what works best for you. This is on a first come, first serve basis. If the day/time slot that works for you is already taken, please reach out to us and we will try to negotiate with the students in that time slot. We, however, cannot make any guarantees that your desired day/time slot will be released.

As a reference, here is the General Internship FAQ.

Please do not hesitate to reach out if you have any issues with booking the interview time or any other related questions.

We look forward to our interview with you.
Best Regards,

**Comment by Rabia2219** [comment]
Emails were sent out by Bonnie on Thursday, March 3rd. Received a booking request from Melodie (Marlborough). Waiting on BWS students.

**Comment by Rabia2219** [comment]
We have the following responses for booking:
Monday March 14th:
Riya at 5 pm (Not through Calendly)
Melodie at 6 pm (through Calendly)
Saturday March 19th:
Jason at 12 pm (through Calendly)
Beckett at 2 pm (through Calendly)
Sakari at 5 pm (through Calendly)

**NOTE: The time slots for Monday March 14th have become unavailable, working on fixing them**

**Comment by Rabia2219** [comment]
Send a message to Riya letting her know that the 5 pm slot has opened up and she can book it.

**Comment by Rabia2219** [comment]
We had a glitch with Calendly that took the longest time to fix. @ExperimentsInHonesty will play around with the bookings again and if it turns out to be just as complicated then we will start a guide on how to use Calendly.

**Comment by Rabia2219** [comment]
We did not receive a response from BWS students till Monday March 7th and reached out to Emily to ask for help. Flor sent them a reminder and we got 2 responses by Tuesday. I sent another reminder on Wednesday and got 2 more responses by Thursday.

**Comment by ExperimentsInHonesty** [comment]
We rescheduled Sakari and interviewed him

**Comment by Rabia2219** [comment]
Reopening this to setup interviews with Mateo, Lily and Charity...

**Comment by Rabia2219** [comment]
2022-04-28:
Sent emails with new Calendly time slots to Mateo, Lily and Charity.

**Comment by ExperimentsInHonesty** [comment]
Here are the new dates and times for the interviews we are going to setup
Dates and times for interviews
17-22
17th
6pm Bonnie, Rabia, Grace
7pm Bonnie, Rabia

18th
1pm Bonnie, Grace
5pm Bonnie, Priyana, Rabia

22nd 
2pm Bonnie, Rabia
4pm Bonnie, Rabia, Pryianka


Next steps is to setup Calendly

**Comment by ExperimentsInHonesty** [comment]
Rabia and Priyanka to meet and record setting up the calendly for the dates above

**Comment by priyatalwar** [comment]
Rabia & I met up and recorded our calendly session to the cloud. Also updated the messaging doc with the new calendly link.

**Comment by Rabia2219** [comment]
The second round of interviews has been conducted. The application window is closed. This issue is ready to be closed.
