### ISSUE TITLE
IS22: Interview Questions

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#138]
### Overview
We need to ask the same questions of each of the candidates so that we can set a baseline for their responses.

#### Details
We will use this data in
- [ ] #139
- [ ] #140

### Action Items
- [x] Define questions
- [x] Ask questions in interviews
- [x] Record Interviews
- [ ] Use recordings to comment on other issues (see details above)

#### Interview checklist
- [x] 5 min prior, login to 1password and get hostkey for zoom 4 
- [x] Join the meeting via the calendar link in your invite or here in this issue
- [x] Claim host
- [x] Turn on recording and then pause

#### Script
- [x] When they enter room, ask if we can record and transcribe
> We would like your consent to record this meeting so that our research team can review it to create a lesson plan around helping students prepare for job interviews.   We will not share this recording with anyone outside the internship team without prior written permission.
- [x] Turn on transcript, unpause recording
- [x] Use script in interview
- [x] upload recording and transcript and a chat file if applicable
- Hi, Im Bonnie - etc. pause
- Hi, Im ____ - etc. pause
- BW: I am about to ask you a question, and it has no bearing on you being accepted, its just a baseline question for later use in coaching during the internship.  - How prepared do you feel for this interview 1-not at all to 5-well prepared
- Tell me about yourself
- BW: Have you looked at our website?  If so, what did you explore?
- What was your most challenging project?
- BW: Tell us about a project you enjoyed most or are passionate about.
- Tell us about a time when you created documentation for something.
- BW: Tell us about a project you had to resolve an interpersonal conflict.
- Tell us about a time when you failed.
- BW:Tell us about a time when you owned a mistake
- Do you have any questions for us?
- BW: How would you rate your preparedness for this interview now 1-not at all to 5-well prepared

**Comment by gracieama** [comment]
We are done
