### ISSUE TITLE
IS22 Interview: Melodie

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#141]
### Overview
We need to track the interview for Melodie so that we don't drop the ball or lose data about it.

### Action Items
- [x] Add the zoom link
- [x] Add date and time to resources
- [x] Add people (Panel to the invite) Bonnie and Bilkish
- [x] Recruit a UX researcher to attend the interview Aditi
- [x] Add them to the invite
- [x] Create folder for interview recording

#### Interview checklist
- [x] 5 min prior, login to 1password and get hostkey for zoom 4 
- [x] Join the meeting via the calendar link in your invite or here in this issue
- [x] Claim host
- [x] Turn on recording and then pause
- [x] When they enter room, ask if we can record and transcribe (see script)
> We would like your consent to record this meeting so that our research team can review it to create a lesson plan around helping students prepare for job interviews.   We will not share this recording with anyone outside the internship team without prior written permission.
- [ ] Turn on transcript, unpause recording
- [x] Use script in interview
- [x] upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [candidate recordings](https://drive.google.com/drive/folders/15t2xTew8IfbREzvQxyuERqDux-yZW4E4?usp=sharing)
  - [Melodies's recording folder](https://drive.google.com/drive/folders/1ZGXIruTWtaC2pGzEKPgTYBQlxe9_vOQL)

#### Resume and Application
- [Melodie's folder](https://drive.google.com/drive/folders/1-_tKQGSjT-Bvze8WFvLVlpH0cBOoSBcZ)

#### Interview details
- [Zoom link for interview](https://zoom.us/j/92292223543?pwd=blA3cmMwb29rQTBqS0s1bHVZSnRLQT09)
- Date and time for interview: 2022-03-14 at 6 pm PST

#### Other links
- [Internship Roster](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit?usp=sharing)
- #138 

#### Text once you are ready to send invite update
```
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you! 
```

**Comment by Rabia2219** [comment]
@aditipaulphd and @bilkishgautham this will be a cameras on interview. Please plan accordingly. Thank you!

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty...please comment here if you have any feedback...we need to check of the action items...upload the recording and close this issue...

**Comment by Rabia2219** [comment]
Sorry...my keyboard got possessed and did something to close the issue...reopened...

**Comment by Rabia2219** [comment]
Interview done and recording uploaded. We didn't turn transcript on. Closing the issue.

**Comment by gracieama** [comment]
Melodie's drive folder for the recording ha Riya's instead. I have uploaded the right one

**Comment by Rabia2219** [comment]
**2022-06-17, 9:10**
I just finished watching the interview video and at 25:18 minutes, she mentions SAT prep and that she may join a summer camp, but it would not conflict with the internship and she will be able to work outside of meeting hours to complete projects. At 26:39 she says her tutorial schedules are not ready yet but she can make sure that they don't conflict with the internship schedule. She also mentions that the evening meetings and Sunday meetings will not be a problem.
