### ISSUE TITLE
IS22 Interview: Sakari

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#144]
### Overview
We need to track the interview for Sakari so that we don't drop the ball or lose data about it.

### Action Items
- [x] Add the zoom link
- [x] Add date and time to resources
- [x] Add people (Panel to the invite) 
- [x] Recruit a UX researcher to attend the interview 
- [x] Add them to the invite
- [x] Create folder for interview recording

#### Interview checklist
- [x] 5 min prior, login to 1password and get hostkey for zoom 4 
- [x] Join the meeting via the calendar link in your invite or here in this issue
- [x] Claim host
- [x] Turn on recording and then pause
- [x] When they enter room, ask if we can record and transcribe
> We would like your consent to record this meeting so that our research team can review it to create a lesson plan around helping students prepare for job interviews.   We will not share this recording with anyone outside the internship team without prior written permission.
- [ ] Turn on transcript, unpause recording
- [x] Use script in interview
- [x] upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [candidate recordings](https://drive.google.com/drive/folders/15t2xTew8IfbREzvQxyuERqDux-yZW4E4?usp=sharing)
  - [candidates recording folder](https://drive.google.com/drive/folders/1aqg6-RMRp5_O8BkerZDZaLsDnsE1W3WA?usp=sharing)

#### Resume and Application
- [candidates folder](https://drive.google.com/drive/folders/1TrYceZ27RYGyEYpXF3UrzDa7FHrVWa9_?usp=sharing)

#### Interview details
- [Zoom link for interview](https://zoom.us/j/93854979705?pwd=b25abnpPNm11OHoxc0VidHUwQWJMZz09)
- Date and time for interview: 2022-03-21 at 6pm PST

#### Other links
- [Internship Roster](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit?usp=sharing)
- #138 

#### Text once you are ready to send invite update
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you!

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty here's the links you asked:
https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Software-Engineers
https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team

**Comment by Rabia2219** [comment]
We were not able to interview Sakari's on the original scheduled time. Rescheduled for Tuesday, March 22nd.

**Comment by gracieama** [comment]
Video has been uploaded to drive. Didn't see the transcript file on zoom
