### ISSUE TITLE
IS22 Interview: Beckett

### ISSUE THREAD

**Issue by bilkishgautham** [hackforla/internship#145]
### Overview
We need to track the interview for Beckett so that we don't drop the ball or lose data about it.

### Action Items
- [x] Add the zoom link
- [x] Add date and time to resources
- [x] Add people (Panel to the invite) 
- [x] Recruit a UX researcher to attend the interview 
- [x] Add them to the invite
- [x] Create folder for interview recording

#### Interview checklist
- [x] 5 min prior, login to 1password and get hostkey for Zoom [Zoom meeting room#]
- [x] Join the meeting via the calendar link in your invite or here in this issue
- [x] Claim host
- [x] Turn on recording and then pause
- [x] When they enter room, ask if we can record and transcribe
- [x] Turn on transcript, unpause recording
> We would like your consent to record this meeting so that our research team can review it to create a lesson plan around helping students prepare for job interviews.   We will not share this recording with anyone outside the internship team without prior written permission. 
- [x] Use script in interview
- [x] upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [Candidate Recordings](https://drive.google.com/drive/folders/15t2xTew8IfbREzvQxyuERqDux-yZW4E4?usp=sharing)
  - [Beckett's recording folder](https://drive.google.com/drive/folders/1p35TaAt8qqM3GoxmVV9Z9bcSJBE5tm5R?usp=sharing)

#### Resume and Application
- [Beckett's folder](https://drive.google.com/drive/folders/1Rs-p6w9Zj1iWMPMu-NuoXPfCMidUTNze)

#### Interview details
- [Zoom link for interview](https://zoom.us/j/98953392517?pwd=bWZSQVhwcE9rWVkxaHNNa2ZDYU9pUT09)
- Date and time for interview: 2022-03-19 at 2 pm PST

#### Other links
- [Internship Roster](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit?usp=sharing)
- #138 

#### Text once you are ready to send invite update
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you!

**Comment by Rabia2219** [comment]
@aditipaulphd @MariaSailo
Are either of you available to sit in on this interviw?
Beckett's Interview:
Date and time for interview: 2022-03-19 at 2 pm PST

**Comment by Rabia2219** [comment]
Thanks Maria...I'll add you to the invite...and Bonnie will give you the details when you meet her on Tuesday...thank you!

**Comment by gracieama** [comment]
I have uploaded the video and transcript to the drive folder

**Comment by Rabia2219** [comment]
I need to remove the video from the folder, edit and upload again...

**Comment by Rabia2219** [comment]
I've uploaded the edited video to Beckett's folder. (This was done with Bonnie's permission...I needed to cut out parts of the video which contained my personal information...shared by mistake while sharing my screen...lesson learned: be careful when sharing your screen...close/minimize all open tabs with personal info and start the meeting in a new window)
