### ISSUE TITLE
IS22 Interview: Jason

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#146]
### Overview
We need to track the interview for Jason so that we don't drop the ball or lose data about it.

### Action Items
- [x] Add the zoom link
- [x] Add date and time to resources
- [x] Add people (Panel to the invite) 
- [ ] Recruit a UX researcher to attend the interview 
- [ ] Add them to the invite
- [x] Create folder for interview recording

#### Interview checklist
- [x] 5 min prior, login to 1password and get hostkey for Zoom [Zoom meeting room#]
- [x] Join the meeting via the calendar link in your invite or here in this issue
- [x] Claim host
- [x] Turn on recording and then pause
- [x] When they enter room, ask if we can record and transcribe
> We would like your consent to record this meeting so that our research team can review it to create a lesson plan around helping students prepare for job interviews.   We will not share this recording with anyone outside the internship team without prior written permission.
- [x] Turn on transcript, unpause recording
- [x] Use script in interview
- [x] upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [Candidate Recordings](https://drive.google.com/drive/folders/15t2xTew8IfbREzvQxyuERqDux-yZW4E4?usp=sharing)
  - [Jason's recording folder](https://drive.google.com/drive/folders/1K3hSDfbztK4pNA4QxswR0bq6meLwcd_H?usp=sharing)

#### Resume and Application
- [Jason's folder](https://drive.google.com/drive/folders/1gv6ytYGTkW_QuYepfqdbSEDj1XINVMOh?usp=sharing)

#### Interview details
- [Zoom link for interview](https://zoom.us/j/92308920252?pwd=eVJhTC8yaFBlNXNTY1k5ZVN2OXoyZz09)
- Date and time for interview: 2022-03-19 at 8am PST

#### Other links
- [Internship Roster](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit?usp=sharing)
- #138 

#### Text once you are ready to send invite update
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you!

**Comment by Rabia2219** [comment]
https://zoom.us/j/92308920252?pwd=eVJhTC8yaFBlNXNTY1k5ZVN2OXoyZz09

**Comment by Rabia2219** [comment]
@aditipaulphd @MariaSailo
are either of you available to sit in on this interview?
Jason's interview:
Date and time for interview: 2022-03-19 at 12pm PST

**Comment by gracieama** [comment]
I have uploaded the video and transcript to the drive folder
