### ISSUE TITLE
Usability testing for Logo design

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#151]
### Overview
We need to perform usability testing so we can find out which logo and favicon that people prefer.

### Action Items
- [x] Cleanup the favicon examples in Figma, 
  - [x] making sure its possible to see the way the logo looks on different backgrounds
    - [x] white
    - [x] light gray
    - [x] dark gray
    - [x] charcoal
    - [x] black
   - [x] Icons represented should be
     - [x] Facebook
     - [x] Google
     - [x] Microsoft
     - [x] B and D from last set
- [x] Setup [usability](https://usabilityhub.com/) account
  - [x] use the username in 1 password as the email
  - [x] use the password in 1 password as the password
- [x] write up the text you will use (including emojis, and add to a comment on this issue)
- [x] setup usability test (add link to test under resources)
- [x] show the test and text to product managers for sign-off
- [x] Bonnie will @ channel it

### Resources/Instructions
- [Internship Figma, Color Mood Board - Susan](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A18)
- [Issue about using UsabilityHub](https://github.com/hackforla/product-management/issues/211)
- [Usability test link](https://app.usabilityhub.com/do/1b8c44e8179f/b8dc) 2022-03-05
- [Spreadsheet for analizing the results](https://docs.google.com/spreadsheets/d/1tLc2s-vZnaR_V8gQlSnPMknyC6oYV1Wl9QOxfKoGwyc/edit?usp=sharing)

#### Email used with Usability hub
- Email for UsabilityHub internship-ux@hackforla.org
- Password is from 1Password is under "UsabilityHub"

#### Wording used during usability testing
> Hack for LA's internship project (helping high school students get tech experience) has designed two logos and matching favicons. We are trying to decide which to use. Please let us know which you prefer and why.

#### Posted Usability hub survey 2022-04-07

> 👋🏻 ```@channel``` Our Hack for LA Internship team needs your help to pick our logo and favicon!!! Please visit our [usability hub link](https://app.usabilityhub.com/do/1b8c44e8179f/b8dc) to vote now!🙏🏻🤗

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/159981290-626f2402-b1f9-4ff3-9542-eda95a2fbcea.png)

**Comment by seetho-c** [comment]
### Update 3.25.2022
Usability Test is setup

Referenced from Access the Data's Usability Test.

Usability test link
[(https://app.usabilityhub.com/do/1b8c44e8179f/b8dc)]

**Comment by ExperimentsInHonesty** [comment]
@seetho-c 

Currently, the wording is

> Making the transition from student life to a successful career requires skills not being taught in high school, college and bootcamps. The Internship project provides an opportunity for students to work on open source projects in the fields of software, product development, project management, and UI/UX research and design at LA’s fastest growing Civic Tech non-profit organization during their summer.

Change to
Hack for LA's internship project (helping high school students get tech experience) has designed two logos and matching favicons.  We are trying to decide which to use.  Please let us know which you prefer and why.

additionally, we need to add a place at the end for them to tell us why they preferred it.

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar @seetho-c its unclear in this issue who setup the usability hub content.  If it was @seetho-c please make the changes I have asked for above.  If it was Priyanka, let us know in comment on this issue so that we can log in and try to fix it, or get you access to it.

**Comment by priyatalwar** [comment]
Cherilyn did.

**Comment by seetho-c** [comment]
@ExperimentsInHonesty I made the changes with the new wording for the intro and added a follow up question at the end "Please let us know why you chose that specific favicon variations."

**Comment by Susanz7** [comment]
@ExperimentsInHonesty Here is the text I created for posting Usability Test on Slack channel:

👋🏻 Hi everyone! Our TechWork Experience team is testing and collecting feedbacks on our logo design. Would be really appreciated if you can take a few moments to answer the questions,  thank you so much!🙏🏻🤗

**Comment by ExperimentsInHonesty** [comment]
👋🏻 Hi everyone! Our Hack for LA Internship team needs your help to pick our logo and favicon!!! Please visit our [usability hub link](https://app.usabilityhub.com/do/1b8c44e8179f/b8dc) to vote now!🙏🏻🤗

**Comment by ExperimentsInHonesty** [comment]
Posted on slack, in general channel

**Comment by ExperimentsInHonesty** [comment]
This is what the test looked like
![image](https://user-images.githubusercontent.com/37763229/168139002-c8a04213-0872-41c6-b278-387fea718168.png)

**Comment by seetho-c** [comment]
Full screenshot of usability test results from UsabilityHub
![screenshot-usabilitytest](https://user-images.githubusercontent.com/29762834/168139167-45327260-8d63-4569-9b4b-5cee865358cb.png)

**Comment by ExperimentsInHonesty** [comment]
We reviewed all the answers and made a spreadsheet of the votes and the why, so that we could determine which logo/favicon to go with.  

Final determination was that the one that got fewer votes was more appropriate because the reasons people liked the favicon and the logo completely aligned with our brand, where the one that got more votes, the favicon often reminded people of Microsoft and the reasons why they liked for the logo did not align with our brand as closely.
