### ISSUE TITLE
Figma Cover Page: Add logo

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#159]
### Overview
As a project team on a shared platform, we need to have a cover page so that our Figma is easily distinguished from other projects.

### Action Items
- [x] Meet with Design systems team so that they can user test their instructions on you
- [x] Make the changes to our Figma file

### Resources/Instructions
[Internship Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=0%3A1)
[Figma Foundations tutorials + templates](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A16)

**Comment by seetho-c** [comment]
Changes have been made on the [Figma file of the Cover Page](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=0%3A1) based on the Design System Team's cover page guidance. 

![Screenshot (24)](https://user-images.githubusercontent.com/29762834/164336176-1991290a-08f7-40cb-8985-5559ba67a130.png)
