### ISSUE TITLE
IS22: Compare '21 BWS Sponsor Reflection form to '22 and submit new responses

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#160]
### Overview

As one of BWS's internship partner, we need to evaluate the post internship form provided by the school so that we are prepared to answer and submit it at the end of the internship.

### Action Items

- [ ] Review '22 Internship Sponsor Feedback Form (Sponsor Reflection Form on BWS's website)
- [ ] Compare to '21 Internship Sponsor Feedback Form

#### Forms
- ['22 Internship Sponsor Feedback Form](https://docs.google.com/forms/d/e/1FAIpQLSdKZKyPmQ1Wgb_ZjwuNGP2mN-BnojGJ9ZTlLZwBBLs9tjv9_g/viewform)
  - [Google doc with survey answers](https://docs.google.com/document/d/1mzzHXm79mrDJ47PEbyzVusllzmRRVLTmhXl9juVEp1c/edit)
- [ '21 Internship Sponsor Feedback Form](https://docs.google.com/document/d/1Wf9gVTV0XrLG0ODfXutvkyorDoDwReNwMMJ0J-dELSo/edit)
  - Note: We do not have the actual '21 Internship Sponsor Feedback Form. This is the converted Google doc that we used to fill it out and submit.

**Comment by sharongupta1** [comment]
Google doc with survey answers

https://docs.google.com/document/d/1mzzHXm79mrDJ47PEbyzVusllzmRRVLTmhXl9juVEp1c/edit

**Comment by ExperimentsInHonesty** [comment]
@sharongupta1 I have updated the document with the answers.  Make sure to login to internship@hackforla.org email account to fill out the form.

**Comment by sharongupta1** [comment]
Submitted the google form with the internship@hackforla.org account
