### ISSUE TITLE
Comparative Research: Google Docs

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#166]
### Dependency
- Revise the logo 
  - We need to add a green (similar to the green of the logo but more suited) and the Gray from our logo to our palette and revise the logo to match

### Overview
We need to create competitive letterhead and other google doc templates so that when we send documents they stand out.

### Action Items
- [ ] Identify sample document templates
   - [x] Google Docs: letterhead
   - [ ] Google Docs: report
   - [ ] Google Sheets
- [ ] Create new versions for our project
   - [ ] Google Docs: report
   - [ ] Google Sheets
- [ ] Revise existing Letter template (it doesn't have the right colors yet)

#### TWI
- [Figma, Google Docs (letter head, sheets)](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A27)
- Draft [TWI: Letter Template](https://docs.google.com/document/d/1KmZ9qIBXiqd1Cadbkhwlk2IsL9HaE4F6gIVaWgv3dGo/edit)

#### Examples
- Reports
  - https://www.template.net/pro/49800/university-lab-report
- Spreadsheets
  - Example of a [Spreadsheet from the Open Community Survey](https://docs.google.com/spreadsheets/d/1jDY5qr3FsYwIqvl4oYAoqDLqYyiFoRCch3Q4ImLZ22o/edit#gid=0) team
  - Example of another spreadsheet https://9to5google.com/2015/01/13/google-sheets-header-images/

**Comment by ExperimentsInHonesty** [comment]
We have created a spreadsheet template, doc template and slide template
