### ISSUE TITLE
Comparative Research: Slides *

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#167]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.
- [ ] Release dependency on #53 
- [ ] update the [wiki page for research plan 1](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
We no longer need to do this.  We have made a slide deck template and used it a few times.
