### ISSUE TITLE
Comparative Research: Email Signature

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#172]
### Overview
We need to see how other organizations logos appear in their email so that we can confirm our signature stands up, or make a different version.

### Action Items
- [ ] Identify 5 different email signatures
- [ ] Use the Email Signature Test page in Figma
   - [ ] Add screenshots of other signatures
   - [ ] Compare with our signature
- [ ] Discuss findings with Product Team
- [ ] If we do not think it holds up
   - [ ] define constraints
      - [ ] must look good when email is forwarded
   - [ ] mock up other versions

### Resources/Instructions
- [Figma, Email Signature Test](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A25)

**Comment by ExperimentsInHonesty** [comment]
This has been completed already.  The signature can be found in the wiki https://github.com/hackforla/internship/wiki/Design-Process-Overview#email-signature-design-system-email-signature

<img src="https://user-images.githubusercontent.com/37763229/168136883-fa6e5d76-05aa-4bae-9d59-d737781bdc61.png" width=300px>
