### ISSUE TITLE
Comparative Research: logos in sponsorship section of other websites

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#173]
### Overview
We need to see how logos appear on other website so that we can confirm our log stands up, or make a version to share that is different.

### Action Items
- [ ] Identify 5 different websites that have many logos in their sponsorship or partnership section of the website.
- [ ] Use the Logo Placement Test page in Figma
   - [ ] Add screen shots from the websites
   - [ ] Replace one of the logos with our logo
- [ ] Discuss findings with Product Team
- [ ] If we do not think it holds up, do the following
  - [ ] Copy those screenshots to a lower section
  - [ ] make logo variations that would stand out more.
<details>
<summary>e.g., black and white on a black chip</summary>

![TWIbw](https://user-images.githubusercontent.com/37763229/169392678-7f888364-6b6c-40ec-b514-7fe2f7e685be.png)
</details>

### Resources/Instructions
- [Figma, Logo placement test](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A23)
1.  [Brentwood Example](https://www.bwscampus.com/alumni/career-resources/summer-internship-opportunities)
1. https://www.hoohacks.io/ - screen shot has been added to figma
1.
1.
1.

**Comment by ExperimentsInHonesty** [comment]
This is no longer needed.  We have settled on a logo.
