### ISSUE TITLE
IS22: Interview Charity

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#176]
### Overview
We need to track the interview for Charity so that we don't drop the ball or lose data about it.

### Action Items
- [x] Add the zoom link to invite
- [x]  Add panel to invite (Bonnie and  Rabia (Priyanka TBC )
- [x] Add date and time to resources
- [x] Create candidate folder for interview recording

#### Interview checklist
- [ ] 5 min prior, login to 1password and get hostkey for zoom 4 
- [ ] Join the meeting via the calendar link in your invite or here in this issue
- [ ] Claim host
- [ ] Turn on recording and then pause
- [ ] When they enter room, ask if we can record and transcribe (see script)
 ```
We would like your consent to record this meeting so that our research team can review 
it to create a lesson plan around helping students prepare for job interviews.  
We will not share this recording with anyone outside the internship team without 
prior written permission.
```
- [ ] Turn on transcript, unpause recording
- [ ] Use script below in interview (also linked in resources)

```
- Hi, Im Bonnie - etc. pause
- Hi, Im ____ - etc. pause
- BW: I am about to ask you a question, and it has no bearing on you being accepted,
  its just a baseline question for later use in coaching during the internship. - 
  **How prepared do you feel for this interview 1-not at all to 5-well prepared**
- Tell me about yourself
- BW: Have you looked at our website? If so, what did you explore?
- What was your most challenging project?
- BW: Tell us about a project you enjoyed most or are passionate about.
- Tell us about a time when you created documentation for something.
- BW: Tell us about a project you had to resolve an interpersonal conflict.
- Tell us about a time when you failed.
- BW:Tell us about a time when you owned a mistake
- Do you have any questions for us?
- BW: How would you rate your preparedness for this interview now 1-not at all to 5-well prepared
```
- [ ] Upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [candidate recordings](https://drive.google.com/drive/folders/15t2xTew8IfbREzvQxyuERqDux-yZW4E4?usp=sharing)
  - [Charity's recording folder](https://drive.google.com/drive/u/2/folders/1tIELLClN0E2LAqN8H0dc6BG7nJivoOGg)

#### Resume and Application
- [Charity's folder](https://drive.google.com/drive/folders/1I3-1_SbQHXUfOXitdaxDlGoEZZYIF5Lj)

#### Interview details
-[Zoom link ](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)for interview
- Date and time for interview:  May 7th, 12 pm PST

#### Other links
- [Internship Roster](https://docs.google.com/spreadsheets/d/1G6IgfvTdfnJRPbqxPkqfQ3dOSf8nvYqy0JVifhY6QdU/edit?usp=sharing)
- #138 

#### Text once you are ready to send invite update
```
We have added the zoom invite info and the panelist for your interview.
Looking forward to seeing you! 
```

**Comment by ExperimentsInHonesty** [comment]
uploaded recording
