### ISSUE TITLE
Create WIKI navigation Assets

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#183]
### Overview
We need the wiki to be a stand in for our future website (e.g., has the same navigation and design feel that the website will have), so that we can both create website content requirements and communicate to our audience in the meantime.

### Action Items
- [ ] Review the existing navigational wiki assets 
- [ ] Create replacements for the existing
- [ ] Create new ones for new sections (defined below)
- [ ] Hand off to Product: When this issue is completed, a new issue will need to be made that adds these items to the wiki and addresses how we are going to handle sections that are not ready to be live yet.

### Resources/Instructions
- [Figma, WIKI Navigation Items](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A6)

#### New sections
* Partnership
  * (about our partnership)
  * (become a partner)

* Funding
  * (help us bring this program to more people)

**Comment by designer2209** [comment]
- Re-Designed the Wiki Navigation, used a gradient (combination of 2 colors from the brand color palette) and sort of color-coded them with the heading.
  - For Example:
    - "Interns" is color coded with "Yellow(F9C80A) + Orange(F86525)"
    - "Volunteers" is color coded with "Violet(662E9A) + Blue(43BCCC)"

![image](https://user-images.githubusercontent.com/83784264/170546261-7d0eea7f-456d-4abd-8217-7ba046ccbcc4.png)

**Comment by ExperimentsInHonesty** [comment]
Hi @designer2209, I think the current navigation items are getting to busy and not really capturing what we are inspired by.  Please see what I have provided below:

Please see the images I have provided a screen shot of below on the [Internship Figma, Slides test](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A31) ) for an understanding of what inspires us (design wise)
![image](https://user-images.githubusercontent.com/37763229/171479553-7c34f5ab-0b05-4285-a474-767da1509596.png)

Also see how I have simplified things in [Design Test #2](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A6)

**Comment by epierotti3** [comment]
This is complete see WIKI
