### ISSUE TITLE
Design System: Create hero

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#185]
### Overview
We need a hero so that this project can appear on the website.

### Action Items
- [x] Review the one sheet draft
- [x] Review the wiki
- [x] Ask any questions of product and UX
- [x] Post draft ideas for hero in comments
- [ ] once a serviceable or temporary hero is completed, release the dependency on #57 

### Resources
- Size requirement is 1500x700
- [Internship Figma, hero](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A29)
- [one sheet](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/preview)
- [wiki](https://github.com/hackforla/internship/wiki)
- <img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png" width=50px>
- Example of a good hero image https://www.hackforla.org/projects/100-automations

**Comment by ale22arevalo** [comment]
Hero designs ready for review: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A29

**Comment by ExperimentsInHonesty** [comment]
background: linear-gradient(to bottom, rgba(3,13,45,0) 30%, #030d2d 100%)

**Comment by ExperimentsInHonesty** [comment]
From Me to Everyone 09:37 AM
https://docs.google.com/document/d/1dnz80FVNTH8lTIBGsdM0cMT8tfmE5YjtXIeAPiGO_Cc/edit#heading=h.y50qquqqm5t7
From Annie Truong to Everyone 09:57 AM
All team meeting agenda: https://github.com/hackforla/internship/issues/101
From Rabia Shaikh to Everyone 10:06 AM
I like how it shows different solo activities and depicts team work as well.
From Elizabeth Pierotti to Everyone 10:06 AM
#7: the variety of roles/activities that an intern could be engaged in
From Annie Truong to Everyone 10:07 AM
I like all the icons used - they represent the internship (e.g. team work, books etc)
From Me to Everyone 10:07 AM
images that convey different working environments that range from the technical to the non technical and also have team collaboration image
From Tin Do to Everyone 10:07 AM
it shows the values of internship program including technical skills and soft skills
From Bilkish Jain to Everyone 10:08 AM
# team collaboration and yet working on their own
From Me to Everyone 10:10 AM
cons are detached imagery and that the styles are not consistent
----
From Rabia Shaikh to Everyone 10:11 AM
Pros: The yellow at the bottom blends well and matches our documents (like Bonnie said)
From Me to Everyone 10:11 AM
yellow matches our document style
From Elizabeth Pierotti to Everyone 10:12 AM
#8: love the purple consistency, also shows diversity in STEM, and the yellow edge looks matchy with our other docs.
From Me to Everyone 10:12 AM
I also like how the image circle intersects with the yellow area
images are cohesive with each other
From Bilkish Jain to Everyone 10:13 AM
#8 implying women(of minority) in the workforce. It looks like she's giving a demo so I take her to be from senior position.I like that she has combined two different scenes togther seamlessly.
From Annie Truong to Everyone 10:13 AM
+: yellow at the bottom matches our templates, consistency of icons, looks like it's a scene from a story, depiction of DEI (women in business, women of color)
From Rabia Shaikh to Everyone 10:13 AM
Cons: lack of diversity, the 'arrow' looks like a stethoscope and makes me think that the person on the left is a doctor! 
From Elizabeth Pierotti to Everyone 10:14 AM
cons: depicts a workplace, implying that there might be non-virtual aspects of the internship
From Me to Everyone 10:14 AM
cons: the design and colors are so similar, if I didn't see the hairstyle as being different I might not know this was a different woman.
From Annie Truong to Everyone 10:14 AM
-: not sure if this looks more like a business setting rather than tech/STEM setting
From Bilkish Jain to Everyone 10:14 AM
Not sure what the little icons next to the arrow imply so looks like a filler
From Me to Everyone 10:16 AM
con: seems to office
----
#9
From Elizabeth Pierotti to Everyone 10:16 AM
pros: teamwork, diversity, shows both product and developer roles
From Rabia Shaikh to Everyone 10:17 AM
Pros: I like that the charts depict the engineering and PM tasks...
From Bilkish Jain to Everyone 10:17 AM
Teams collaboration and communication, kanban board and developer tools implying PM and S/W roles
From Me to Everyone 10:17 AM
I love the Kanban board and the collaboration and the software references
and the multi ethnicity
From Annie Truong to Everyone 10:18 AM
+: imagery consistency, shows collaboration, diverse humans, shows tech-y side of internship (kanban board, programming languages)
From Bilkish Jain to Everyone 10:18 AM
Love how the yellow implies the stick on notes
From Me to Everyone 10:19 AM
cons: The gears and the clouds are not really tying things together, even though they could if they were bigger and actually intersecting
From Annie Truong to Everyone 10:20 AM
-: maybe stick to one/two color palettes
From Bilkish Jain to Everyone 10:20 AM
not sure of what is being passed on to each other.Letters and cellphone?
From Rabia Shaikh to Everyone 10:20 AM
Cons: doesn't flow...our colors are missing
From Elizabeth Pierotti to Everyone 10:20 AM
colors lack consistency, maybe could do orange in the middle instead of blue to show the intersection of yellow PM and red software
From Tin Do to Everyone 10:21 AM
if we can have more bright colors in the middle to show the dynamic workspace
From Me to Everyone 10:21 AM
#10
From Rabia Shaikh to Everyone 10:21 AM
Pros: matches our slides...shows teamwork...
From Elizabeth Pierotti to Everyone 10:22 AM
love how it fills the whole space, shows diversity and teamwork, consistent color schemes
From Bilkish Jain to Everyone 10:22 AM
Love that standup is literally stand up meeting and implies that they are talking about stats and meetings targets.
From Me to Everyone 10:22 AM
multi ethnicity
From Annie Truong to Everyone 10:22 AM
+: the yellow ties in with our templates, shows collab, diversity
From Bilkish Jain to Everyone 10:22 AM
the way they are standing implies that it is a casual workspace
From Me to Everyone 10:23 AM
cons:
From Rabia Shaikh to Everyone 10:23 AM
Cons: too much yellow...the colors in the background should be brighter...
From Bilkish Jain to Everyone 10:23 AM
a little less yellow maybe.could make the plant green and shoes a different coloue
From Elizabeth Pierotti to Everyone 10:23 AM
maybe move the woman to the middle so she doesn't look "left out”? lol idk
From Me to Everyone 10:23 AM
the two dudes are connecting and the woman is saying "same old bro culture no one listening to me"
From Bilkish Jain to Everyone 10:24 AM
not sure what the girls chart is implying
From Me to Everyone 10:28 AM
background is not really working for me, the lines.  Possibly because there is grey behind the girl
#11
I love how they are all celebrating together equaly
From Rabia Shaikh to Everyone 10:28 AM
Pros: the people look like our age group...it feels like students working together...the background is fun...
From Me to Everyone 10:28 AM
and the girl with the glasses has his attention for her idea
From Elizabeth Pierotti to Everyone 10:28 AM
like the little geometric backgrounds bits. also the teamwork is great, the womxn are definitely involved here! each is talking about different ideas but all are getting lots done
From Bilkish Jain to Everyone 10:28 AM
seems like a brainstorming session with checklists and ideas.
From Elizabeth Pierotti to Everyone 10:28 AM
they look like students
From Me to Everyone 10:29 AM
the circles and shapes go perfectly with our deck
From Annie Truong to Everyone 10:29 AM
+: love the depiction of collab, shows diversity, the humans look young (students), very cheerful image (high fives)
From Bilkish Jain to Everyone 10:29 AM
multidiversity here as well
From Me to Everyone 10:31 AM
its also very flexible in terms of all kind of work
cons: it only shows students working with each other not with people of all ages.
From Rabia Shaikh to Everyone 10:31 AM
Cons: a little more diversity, one more student standing at the back? and different colored shirts for the ladies?
From Annie Truong to Everyone 10:31 AM
-: maybe we can incorporate our yellow color more in order for it to match our template? not sure what cogwheels imply…
From Elizabeth Pierotti to Everyone 10:31 AM
cons: probably could be moved up a little more (easy fix) so it's not overlapping w gradient
From Bilkish Jain to Everyone 10:32 AM
Cons - don't like purple square on the top left ,it doesn't go well with other shapes,the guy not having a laptop feels like the guy is mgmt. and the girls working for him
From Me to Everyone 10:32 AM
can the speech bubbles be outlined?
From Bilkish Jain to Everyone 10:32 AM
hands could be little thinner
From Elizabeth Pierotti to Everyone 10:33 AM
10 or 11 are my favorites
From Me to Everyone 10:33 AM
--
From Rabia Shaikh to Everyone 10:33 AM
11
From Elizabeth Pierotti to Everyone 10:33 AM
10 or 11
From Annie Truong to Everyone 10:33 AM
#11
From Bilkish Jain to Everyone 10:33 AM
0 or 11
10 or 11
From Me to Everyone 10:34 AM
10/11

**Comment by ExperimentsInHonesty** [comment]
[meeting_saved_chat.txt](https://github.com/hackforla/internship/files/8921163/meeting_saved_chat.txt)
