### ISSUE TITLE
Define intern communication prior to start

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#186]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
May 31 send email reminding them to accepted if they havent

Define what happens on first day (for ourselves) and setup calendar invite

June 2nd Send email reminding them their start date and adding them to a calendar invite.  Ask them to accept it.

June 6th send email reminder for the calendar invite to those who have not accepted it

June 13th Send email saying we are excited for their start next Monday

**Comment by Rabia2219** [comment]
- rename all intern folders starting with TWE:
- show them how to access their folders on the first day
- do a LinkedIn workshop on the first day

**Comment by ExperimentsInHonesty** [comment]
Students are guided through a day of Intake interviews to create baselines, Meet and Greet with the other interns, Overview about schedules,  Code of Conduct , Introduction to Team members who will provide guidance, scheduling of negotiable meetings, Technical onboarding (GitHub, Google Docs, Slack, Roster), etc. and creating their first two issues.

**Comment by ExperimentsInHonesty** [comment]
[Day 1 activities spreadsheet](https://docs.google.com/spreadsheets/d/1GTA7ULcliiQY7NvI199i6r8XrqC3CN-Sm98UWzP3ZA4/edit#gid=0)
