### ISSUE TITLE
IS22: Consent forms: Draft and format

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#188]
### Overview
We need consent forms so that we can interview minors and reuse the data in the future.

### Action Items
- [x] Gather existing form examples
   - [x] assent form for minor
   - [x] consent form for parents
- [x] Create HfLA internship versions
- [ ] Format using our logo letterhead, etc.

**Comment by christine-el** [comment]
I think we need to think about how we are going to make sure to receive parent consent in advance of the June 20th meeting, as it could be potentially difficult to get a response.  Do we have parent emails to send them a link a form?  Or will we be relying on the interns to communicate this to their parents?  What will we do if parents haven't responded by June 20th?

**Comment by christine-el** [comment]
Here is the document that lays out ideas about the informed consent process, plus the template we can discuss using:  https://docs.google.com/document/d/1jFKrOWw_kr3A1ZbgIQzhGhgjzCA3s-5yoC_ScWWRp10/edit.

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/172738705-904d2932-0691-49e3-9e55-47993d890cb4.png)

**Comment by christine-el** [comment]
Here is the draft of the consent form:  https://docs.google.com/document/d/1eVe-fW2I_H10e2E0WYkBAFTMiH56u4TzCpaucPVjXJk/edit.

**Comment by ExperimentsInHonesty** [comment]
The letter has been revised and can be found on this wiki page along with the other consent information for parents/guardians https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals

**Comment by ExperimentsInHonesty** [comment]
I have added a link to the parent/guardian page on consent to the rp006 wiki page
https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews#consent
