### ISSUE TITLE
RP1: Audit

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#189]
### Overview
We need to Audit Research Plan 1 to make sure it is completed and well documented

### Action Items
- [x] Review the overview google doc to see what is missing
- [x] Go over all the materials in the drive
- [x] Update document
- [x] Review with UX lead
- [x] Once you have signoff, Update relevant WIKI page

### Resources/Instructions
- [TWE: RP1: Overview Google Doc](https://docs.google.com/document/d/1fIyValhfnDxRKOu3trEj_tB3YaaDFwi8MeOdD6gHizk/edit)
- [TWE: Internship: Research: RP1 Google drive](https://drive.google.com/drive/u/0/folders/1uKUY_izpds3dHInNkiexZsU32ELF_Hze)
- [TWE WIKI, Research Plan 1: IS21 Interns](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)

**Comment by bradyse** [comment]
This issue has been updated and replaced with
- #295
