### ISSUE TITLE
IS22 final pre internship email

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#190]
### Overview
We need to send a final email to interns prior to the start of the internship that includes important reminders such as code of conduct.

### Action Items

- [x] Decide date this should be sent to interns (June 8th 2022)
- [x] Add this date to timeline
- [x] Identify all items to include in email
- [x] Draft an email to the interns 
   - specifically instruct to read carefully 
   - include deadline to respond
- [x] Review with team
- [x] Use mail merge to send email
- [x] Monitor for responses
   - Accepted Invite
     - [x] Melodie
     - [x] Riya
     - [x] Sakari
     - [x] Beckett
     - [x] Lily
     - [x] Charity
     - [x] Clayton
     - [x] Tung
     - [x] Brian
     - [x] Asher
     - [x] Mateo
   - Replied back with passcode
     - [x] Melodie
     - [x] Riya
     - [x] Sakari
     - [x] Beckett
     - [x] Lily
     - [x] Charity
     - [x] Clayton
     - [x] Tung
     - [x] Brian
     - [x] Asher
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [When2meet Intern Availibility](https://www.when2meet.com/?15873330-c9cFr)
- [Main IS22: Cohort list](https://docs.google.com/spreadsheets/d/1gQaHDEongGiP_CawghV0YGvO1l9c4qhT0lMll8iFdYw/edit#gid=0)
- [TWE: Monitor Response to Final Email](https://docs.google.com/spreadsheets/d/1Z24g6RWVWluAnU37hQYgJrXrx42BDJYuY6Y1v83d45U/edit#gid=0)
- [IS22 Cohort List not including Mateo](https://docs.google.com/spreadsheets/d/1BCwbpPYFO0NibgrW0Z_mCgWRvqYIrwHj8_ezWBFxV7U/edit#gid=0)
- [IS22 Timeline](https://docs.google.com/spreadsheets/d/1rELYpwDNs_HQSkQvjr0JX2UmHBSKJD6PT1XXoHk9Phs/edit?usp=sharing)
- [Final Pre-Internship Email folder](https://drive.google.com/drive/folders/1x6xlzjowpI81ZmRb7jL-h8sU9g0VV2ss?usp=sharing)
- [Final Pre-Internship Email draft](https://docs.google.com/document/d/1G8YsTfxIxBFqGPtzSAuLR2coU_ef2UeoB7bNUG1PEg0/edit)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

#### List of items to include
- [Code of Conduct](https://www.hackforla.org/CODEOFCONDUCT.html)
- When2Meet poll for updated availability (this seems to work better than Doodle)
- General idea of first day activities (meet with mentor, meet other interns, etc.)

**Comment by epierotti3** [comment]
- [Code of Conduct](https://www.hackforla.org/CODEOFCONDUCT.html)
- When2Meet poll for updated availability (this seems to work better than Doodle)
- General idea of first day activities (meet with mentor, meet other interns, etc.)

**Comment by Annie-Truong** [comment]
Here is the link to the When2Meet poll with the availability of the interns: https://www.when2meet.com/?15873330-c9cFr
