### ISSUE TITLE
Design recruitment strategy for mentors

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#192]
### Overview
We need to recruit mentors for interns so that they are able to have one-on-one weekly guidance (help with LinkedIn, soft skills, etc). 

### Action Items

- [x] Determine deadlines for recruiting mentors (when to send out messaging)
   - [x] When to start recruiting
   - [x] When to cut-off reviewing mentor applications 
- [x] Draft collateral
   - [x] Draft an overview of what our expectations of mentors are (what we get out out of it)
   - [x] Provide benefits of being a mentor (what they get out of it)
   - [x] Persona (light) of the student interns (what the typical intern is like)
   - [x] Logistics of internship (where, when)
   - [x] Outreach messaging
   - [x] Form to express interest #197
   - [x] Acceptance email
- [x] Define recruitment channels
   - [x] Our Hack for LA slack
   - [ ] Email prior leads 
   - [ ] LinkedIn
- [x] Add mentor section to wiki 
- [x] Monitor for responses
- [x] Select mentors
- [x] Send acceptance letters
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [IS22 External Communications: Mentors](https://docs.google.com/spreadsheets/d/1GTA7ULcliiQY7NvI199i6r8XrqC3CN-Sm98UWzP3ZA4/edit#gid=1907978168)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ExperimentsInHonesty** [comment]
When to start recruiting: now 2022-06-08
When to cut-off reviewing mentor applications 
- first deadline 2022-06-16
- extended deadline 2022-06-19

### Time Expectations

- One time meet (2 hour),  Mentor onboarding
- One time meet (2 hour),  Mentor offboarding
- Weekly 1 hour, mentor and interns attend linkedin workshop
- Weekly 15-30,  soft skills coaching with mentor and Intern
- Weekly 30 min, mentor helps intern with their linkedin profile
- Weekly  30 mentor standup with Org

### Requirements
- Have LinkedIn profile (does not have to be in good shape)
- Has been at Hack for LA in the last two years
- Is currently employed
- Is a software engineer
- Can attend onboarding and offboarding
- Can meet hourly commitment of 2.5 hours a week for 6 weeks from June 20th - July 29th

**Comment by Annie-Truong** [comment]
We need to set up the interview strategy for the mentors which includes: 
- email with interview call
- setting up interviews with Calendly
- interview script 
- day of interview details which includes Zoom setup, interview panel setup etc.

**Comment by Annie-Truong** [comment]
### Mentorship Recruitment Slack Messaging
@channel 
The Internship Project is looking to recruit 9 software developers who have been part of Hack For LA in the past 2 years to mentor the 2022 Internship Cohort. 

Requirements: 
- Have LinkedIn profile (does not have to be in good shape)
- Has been at Hack for LA in the last 2 years
- Is currently employed
- Is a software engineer
- Can attend onboarding and offboarding
- Can meet hourly commitment of 2.5 hours a week for 6 weeks from June 20th - July 29th

Time Expectations: 
- One time meet (2 hour), Mentor onboarding
- One time meet (2 hour), Mentor offboarding
- Weekly 1 hour, mentor and interns attend LinkedIn workshop
- Weekly 15-30, soft skills coaching with mentor and Intern
- Weekly 30 min, mentor helps intern with their LinkedIn profile
- Weekly 30 mentor standup with Org

Please reach out to Bonnie, Rabia, Bilkish, Annie, Grace and Elizabeth if you are interested in mentoring!

**Comment by ExperimentsInHonesty** [comment]
Mentorship wiki: https://github.com/hackforla/internship/wiki/Mentors

**Comment by ExperimentsInHonesty** [comment]
Outreach messaging draft
```@channel we are looking for mentors for our Hack for Summer Internship program for students.  Last year we had 6 students, and they all said they would recommend it to friends, and this year two of them are coming back for a second round; choosing our internship over applying to a paid opportunity.  **If  you are interested in being a mentor** please see our Mentor Overview wiki page for  details and requirements https://github.com/hackforla/internship/wiki/Mentors-2022-Summer-Cohort
```

 Acceptance letter

**Comment by ExperimentsInHonesty** [comment]
Acceptance letter still outstanding

**Comment by ExperimentsInHonesty** [comment]
Sent to general and engineering on 2022-06-11 at 2:28pm
![image](https://user-images.githubusercontent.com/37763229/173205477-9cf76f65-9888-448c-9115-813ca0c70318.png)

```
@channel we are looking for some awesome mentors :ninja::skin-tone-4:for our Hack for LA Summer 22 Internship program for students.  If  you are interested in being a mentor please see our Mentor Overview wiki page:page_facing_up: for details and requirements.  Hurry :running:, the program starts on the 20th!
```

**Comment by Rabia2219** [comment]
Please see #208 for details as this was taken up by the researchers.
