### ISSUE TITLE
TWE: Draft time card setup solution for interns

### ISSUE THREAD

**Issue by Annie-Truong** [hackforla/internship#193]
### Overview
We need to create a time card setup for the interns to document hours worked. 

### Action Items

- [x] Brainstorm ideas on how to set up the time card
- [x] Create a draft
- [x] Review the solution
- [x] Finalize the solution 
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- TWE: IS22 Resources
   - [TWE: ISS Time Card - Form](https://docs.google.com/forms/d/1yc49thgEFeQ0AQS3b6QHHDXehPqkyX9J8tTw8tvBQbI/edit)
   - [TWE: IS22 Time Card - Spreadsheet(Responses)](https://docs.google.com/spreadsheets/d/10oqrFfqMELuBUPwQQGgBscmdF7FTG61aSLbXqju3wSM/edit#gid=1079713090)
   - [TWE: IS22 Time Card - makeup entry](https://docs.google.com/forms/d/e/1FAIpQLSdjRSZRoUU17y88J0DKq2QZ2TqqKqNZ3uzO2KEdJkvAPPe3Ig/viewform)
   - ~[TWE: IS22 Time Card - Form](https://docs.google.com/forms/d/1tbvcEAGnYQgF7-aWrX-LKdUOE-au-_pQlyQXEUe9Bbs/edit)~ depreciated
  - ~[TWE: IS22 Time Card - Spreadsheet(Responses)](https://docs.google.com/spreadsheets/d/18gbbFuub139ZF2y10OugXNLIslyjgM9NJeNExRheirg/edit#gid=592152513)~ depreciated
  - [Source Tutorial](https://www.youtube.com/watch?v=oa-CuxbTJ9g)
- [IS21 Time Card](https://docs.google.com/spreadsheets/d/11KC6P07dr_DEIq5lGZ_vqyakq-rfOEBSTqqduFLiVbs/edit#gid=31332939)

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty

**Comment by Rabia2219** [comment]
Will give Elizabeth a tutorial on how to do the manual part for the makeup data on Monday so this can be maintained.

**Comment by sofiatajide** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- [TWE: ISS Time Card - Form](https://docs.google.com/forms/d/1yc49thgEFeQ0AQS3b6QHHDXehPqkyX9J8tTw8tvBQbI/edit)
  - [ ] Have access, its located in ____
  - [x] public
- [TWE: IS22 Time Card - Spreadsheet(Responses)](https://docs.google.com/spreadsheets/d/10oqrFfqMELuBUPwQQGgBscmdF7FTG61aSLbXqju3wSM/edit#gid=1079713090)
  - [ ] Have access, its located in ____
  - [x] public
- [TWE: IS22 Time Card - makeup entry](https://docs.google.com/forms/d/e/1FAIpQLSdjRSZRoUU17y88J0DKq2QZ2TqqKqNZ3uzO2KEdJkvAPPe3Ig/viewform)
  - [ ] Have access, its located in ____
  - [ ] public
- [TWE: IS22 Time Card - Form](https://docs.google.com/forms/d/1tbvcEAGnYQgF7-aWrX-LKdUOE-au-_pQlyQXEUe9Bbs/edit) depreciated
  - [ ] Have access, its located in ____
  - [ ] public
-[TWE: IS22 Time Card - Spreadsheet(Responses)](https://docs.google.com/spreadsheets/d/18gbbFuub139ZF2y10OugXNLIslyjgM9NJeNExRheirg/edit#gid=592152513) depreciated
  - [ ] Have access, its located in ____
  - [ ] public
  - [Source Tutorial](https://www.youtube.com/watch?v=oa-CuxbTJ9g)
  - [ ] Have access, its located in ____
  - [ ] public
  - https://github.com/hackforla/internship/issues/254
  - [ ] Have access, its located in ____
  - [ ] public
  - [IS21 Time Card](https://docs.google.com/spreadsheets/d/11KC6P07dr_DEIq5lGZ_vqyakq-rfOEBSTqqduFLiVbs/edit#gid=31332939)
  - [ ] Have access, its located in ____
  - [ ] public
  - [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
  - [ ] Have access, its located in ____
  - [ ] public
