### ISSUE TITLE
Design an icebreaker activity for interns

### ISSUE THREAD

**Issue by Annie-Truong** [hackforla/internship#198]
### Overview
We need to design an icebreaker activity (in breakout rooms) with multiple choice activities for interns. 

### Action Items

- [x] Brainstorm icebreaker activities
- [x] Draft a list with options
- [x] Review the list 
- [x] Finalize the list
- [x] Create slides within [Onboarding Deck](https://docs.google.com/presentation/d/13tSA70FfojhQgiFoeKM5po29hOdH31wTROs1Ec2M4b8/edit#slide=id.g1356dfe23d0_0_39) with instructions on how to conduct icebreaker activities.
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Onboarding Deck](https://docs.google.com/presentation/d/13tSA70FfojhQgiFoeKM5po29hOdH31wTROs1Ec2M4b8/edit#slide=id.g1356dfe23d0_0_39)
- [Internet search for virtual icebreakers](https://www.google.com/search?q=virtual+icebreaker+activities+for+high+school&rlz=1CAJCUZ_enUS894&ei=VPmYYszMK_6vqtsPra-k-A8&ved=0ahUKEwjMxvOTq4_4AhX-l2oFHa0XCf8Q4dUDCA4&uact=5&oq=virtual+icebreaker+activities+for+high+school&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEB4yBQgAEIYDMgUIABCGAzIFCAAQhgM6BwgAEEcQsAM6BAgAEA06CAgAEB4QDRAFOggIABAeEAgQDUoECEEYAEoECEYYAFCaBli2GWDyH2gBcAB4AYAB1gWIAbITkgENMC4xLjIuMC4xLjEuMZgBAKABAcgBCMABAQ&sclient=gws-wiz)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Rabia2219** [comment]
@epierotti3 
Hi Elizabeth,
Can you please bring a few ideas for this to the PM meeting on Wednesday so we can brainstorm and finalize? Thanks...

**Comment by epierotti3** [comment]
**Tentative Details**
Allotted time: 10-30 minutes? Within the hour set aside for Welcome/Introductions
Format: 11 interns (and Internship team?) divided into breakout rooms of 3-4 people
(Or everyone could stay together in a big group, but this might be more intimidating.)

**Ideas:**
_- Two truths and a lie:_ each person shares 3 statements (two true, one false) about themselves and the others must guess which statement is the lie.
_- Table topics:_ pick a few thought-provoking but fun questions to prompt interns to get to know each other. E.g., "If you could have dinner with any person - past, present, or future - who would it be and why?", "Who is the funniest person you know, and why?", "What would you do if you won the lottery?", "What is the weirdest gift you've ever received?"
_- Same and different:_ people in breakout rooms are tasked with finding all of the things they have in common, beyond the obvious (such as living in LA or being interns). One person records all of the commonalities, and then after 10 minutes all groups come back together and share their lists.

[Source](https://symondsresearch.com/icebreakers-for-online-teaching/)

**Comment by Rabia2219** [comment]
@epierotti3 
I like all three icebreaker activities...

**Comment by epierotti3** [comment]
@Rabia2219 Here are some of my thoughts, let me know what you think:
- Two truths and a lie: may be a little overused, but would be great if we are short on time or want to keep the ice breakers quick (15 min max)
- Table topics: could be fun to do this in rounds, as Bonnie mentioned earlier. E.g., interns would go to multiple different breakout rooms with different questions, and meet new interns in each room. This way they get to know a lot of people all at once.
- Same and different: this might be the most aligned with creating a sense of community amongst interns. After all, we're tasking them to figure out what they all have in common! It might help interns relax and realize that they are amongst like-minded friends. I predict this would leave them feeling the most "warm and fuzzy" afterwards.

**Comment by epierotti3** [comment]
Slides within the [Onboarding Deck](https://docs.google.com/presentation/d/13tSA70FfojhQgiFoeKM5po29hOdH31wTROs1Ec2M4b8/edit#slide=id.g1356dfe23d0_0_39) have been included for option A (Two Truths and a Lie - 15 min) and option B (Same and Different - 30 min). 

Still to be determined - do we want PMs to participate with interns in this activity, too? Or interns alone?

**Comment by ExperimentsInHonesty** [comment]
@epierotti3 please update the https://github.com/hackforla/internship/wiki/The-2022-Internship-Program-Process-Overview with the deck and mention that it contains icebreakers
