### ISSUE TITLE
Add TWE and new partner logo to One Sheet

### ISSUE THREAD

**Issue by Annie-Truong** [hackforla/internship#201]
### Overview
We need to add the new TWE logo and the new partner logo to the One Sheet so that it is updated. 

### Action Items
- [ ] ~Create draft letter to send to school~ (changed "partners" to "schools", so no permission needed)
- [x] Find the logo of the new partners
   - [x] Harvard-Westlake
   - [ ] ~Marlborough~ this did not work out
   - [x] UCLA
   - [x] Bolsa Grande High School (not a partner but we did have student from there)
   - [ ] ~Princeton~ (did not work out)
- [x] Add TWE logo to One Sheet
- [x] Add all partner logos to One Sheet  and names of schools that we had students from
- [x] ~Update relevant WIKI page (See resources)~
    - WAITING TO UPDATE WIKI UNTIL ONE SHEET HAS BEEN FULLY UPDATED

### Resources/Instructions
- ~[Project One Sheet](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/preview)~
- [Draft 2023 Project One Sheet](https://docs.google.com/document/d/1eIHIq3zKZ4fB7fMYRuU1WgDYK5XTMFsSQmCvo5iuMz4/edit#heading=h.9lflh9bmk0a)
- [TWE Logo](https://github.com/hackforla/internship/issues/4#issuecomment-1112534286)
- Partner Websites
  - [Harvard-Westlake](https://www.hw.com/)
  - [Marlborough](https://www.marlborough.org/)
  - [UCLA](https://www.ucla.edu/) 
  - [Bolsa Grande High School](https://www.bolsagrande.org/) 
  - [Princeton ](https://www.princeton.edu/)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
Bonnie, I have questions/concerns.
- With Brentwood we had a very formal partnership process
- They used our logo on their website and we are using their logo in our one sheet

With the newer partners, it hasn't been so formal. Mostly phone and email correspondence. UCLA does have our listing on their website, but they are not using our logo. With Princeton, not even that, it was directly from Mateo. So is it okay for us to add their logos to our One Sheet without explicit permission?

**Comment by ExperimentsInHonesty** [comment]
We would need to reach out to Harvard Westlake and ask if we could use their logo and name for this years internship summer 2022.  We would have to do same with UCLA
