### ISSUE TITLE
TWE: Send out UX researcher recruitment message (for Intern Intake Interviews) to internal and external slack channels

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#207]
### Dependencies
- #187
- #202

### Overview
We need to send out a message on the appropriate Hack for LA and external slack channels so that we can recruit UX researchers for the Intern Intake Interviews and Training.

### Action Items
- [x] Draft a message
- [x] Review with Bonnie
- [x] Internal Channels
   - [x] Bonnie to ```@channel``` message in appropriate channels on the Hack for LA slack
- [x]  External Channels
    - [x] Check the TWE: RP6: UX Recruitment Pipelines for finding researchers spreadsheet for appropriate channels
    - [x] Post message on channel 
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- Slack message to be sent

```
@channel Hack for LA's #Internship project is :eyes:  looking for researchers to conduct interviews.
:tada:Training will be provided Wednesday, June 15 from 5-6pm PST.
:alarm_clock: Interviews are scheduled for Monday, June 20th at 12pm (noon) PST.
:interrobang:Read our overview page to find answers to all your questions and [Let us know you are interested](https://github.com/hackforla/internship/wiki/RP6:-UXR-Training)!
```

![image](https://user-images.githubusercontent.com/37763229/173205209-2651801d-52a6-4b27-9408-e934f7e21787.png)

- [TWE: RP6: UX Recruitment Pipelines for finding researchers](https://docs.google.com/spreadsheets/d/1smQ2jWwh6e8oI5R3jFjqAHvjlIbSDtxc-7YfCsIcJ5g/edit#gid=716489189)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ale22arevalo** [comment]
Sent messages to multiple slack, Facebook and LinkedIn.

**Comment by ExperimentsInHonesty** [comment]
I have added all the links to the https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews page
