### ISSUE TITLE
TWE: Create a spreadsheet with intern project assignment and meetings

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#210]
### Overview
We need to create a spreadsheet that contains information on what project each intern has been assigned to and a list of meetings they need to attend so that they can be added to the calendar invites.

### Action Items

- [x] Create spreadsheet
   - [x] First Name
   - [x] Last Name
   - [x] Email Address
   - [x] Assigned Projects
   - [x] Meetings to Attend
- [x] Collect meeting data for said project
- [x] Check that all interns have been invited to all relevant meetings
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1T1HCbqeEQ_jK1ahQ9EiRU1d5BLNqRZKGVP6dmB215uM/edit#gid=0)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Annie-Truong** [comment]
The spreadsheet has been updated with all the meetings and I double checked the attendees as well as the Zoom4 account. It looks good now except for the column "Team meetings".

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
We just need your input on the Team Meetings and then this issue can be closed...thanks...

**Comment by Rabia2219** [comment]
I just need Mateos' project name to add to the spreadsheet and then this issue can be closed.

**Comment by Rabia2219** [comment]
We have all the information in the spreadsheet so closing this.
