### ISSUE TITLE
TWE: Create Mentor Onboarding

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#212]
### Overview
We need to create a mentor onboarding for Day 2 or 3 of Internship.

### Action Items

- [x] Create Slidedeck: See Bonnie's comment for what to include https://github.com/hackforla/internship/issues/212#issuecomment-1159186191
- [x] Set up Easy Retro for Q&A
- [X] [Update Wiki for IS22 Program Process Overview](https://github.com/hackforla/internship/wiki/The-2022-Internship-Program-Process-Overview)

### Resources/Instructions
[Slidedeck for Mentor Onboarding](https://docs.google.com/presentation/d/1k7vWfOaXEnVebC5qkU9n7WLp_PLCfT0vcLkKC96e1J4/edit?usp=sharing)

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ExperimentsInHonesty** [comment]
intern slack channel
intern contact info
bios from them
pm contact workflow
reminder of expectations
LinkedIn workshop
training for how to get the intern to talk about what they did beyond what is written in the issue
calendar negotiation with intern

**Comment by ExperimentsInHonesty** [comment]
introduction slide
agenda slide

**Comment by Aparna1Gopal** [comment]
**Notes:** Removed RP008 label and added Dependencies https://github.com/hackforla/internship/issues/208 in keeping with the current documentation kit clean-up for Mentor Research
