### ISSUE TITLE
Create LinkedIn Workshop and Standup Meeting Surveys

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#239]
### Overview
We need to create surveys to administer to interns each week after they attend the LinkedIn Workshops in order to understand what they learned and what can be improved about each workshop.  We also need to create a survey to give to interns each Friday to assess what they are getting out of the standup meetings.  

### Action Items

- [x] Create a template with informed consent disclaimer and opt-out option for all surveys to be used with interns.
- [x] Send template plus questions for standup survey to Rabia to format for Friday.
- [x] Create LinkedIn survey before next Tuesday.
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Survey Template](https://docs.google.com/forms/d/1m0rTEzHg2BZcaSqy0rSUvHB5-Oqg2t8jaOimQPX9uVE/edit) 

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by christine-el** [comment]
@Rabia2219 I've created the survey template with the informed consent disclaimer and opt-out option here:  https://docs.google.com/forms/d/1m0rTEzHg2BZcaSqy0rSUvHB5-Oqg2t8jaOimQPX9uVE/edit

**Comment by christine-el** [comment]
@Rabia2219 Here are the questions that we wanted to ask in the survey to administer to the interns each Friday, when asking for their feedback.  I don't think I'll have time to format it into a google form before tomorrow morning:
@Rabia  The questions for the standup survey that Bonnie wants to give to interns tomorrow--not sure I'll have time to format it before tomorrow morning:
![image](https://user-images.githubusercontent.com/101530476/175364439-809064d8-f557-492b-8e00-cbe5730a5eeb.png)

**Comment by ExperimentsInHonesty** [comment]
@christine-el please provide the notes you took (just cut and paste them here) on what we were going to ask them about linkedin workshops

**Comment by Rabia2219** [comment]
1.     Do you feel more/less/same amount of confidence in using LinkedIn after this workshop?

2.     On a scale from 1-5, how confident do you feel in [fill in a specific skill….]

3.     Would you recommend this workshop to other people?  [yes/no]

4.     How could we improve this workshop>

**Comment by priyatalwar** [comment]
Linkedin Sections:

- Top (Name, Photo, Title, Organization, City, Email)
- About
- Featured
- Activity
- Experience
- Education
- Skills and Endorsements
- Licenses and Certifications
- Volunteering
- Honors and Awards
- Recommendations
- Courses
- Projects
- Languages
- Interests

**Sections covered on the survey** 

- Top (Name, Photo, Title, Organization, City, Email)
- About (Description, List of Skills)
- Featured
- Activity
- Experience
- Licenses and Certifications
- Education
- Skills and Endorsements
- Honors and Awards
- Recommendations
- Courses
- Projects
- Languages
- Interests
