### ISSUE TITLE
Consent Forms_Mentor Program

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/internship#245]
### Overview
We need to create Consent Form templates for the following:
Mentors to participate in various interviewing activities, audio+video+surveys + for interns to be recorded during their interaction with their mentors 

### Action Items

- [x] Identify Best Practices, Consent form templates 
- [x] Examples to collect: From RP6, Code for America, UserInterviews, IRB etc.
- [x] Create Email requesting for consent 
- [x] Create Consent template for one-on-one interviews/focus groups/audio+video recording 
- [x] Transfer contents of interview consent form to Google Form
- [x] Create consent template for surveys
- [x] Transfer contents of survey consent form to Google Form
- [x] Create template for interns to be recorded during their interaction with their mentors [Ethnography-currently on hold]
- [x] Update relevant WIKI page with Consent Forms
- [x] Update relevant WIKI page with snapshots of Survey Guides

### Resources/Instructions

- [Google Drive](https://drive.google.com/drive/folders/1qTW_AoCPvA1c1-Qckg-7qXiA19ZcA2JN)
- [Google Form Consent](https://docs.google.com/forms/d/13Hj9alj786A2a24upGr4CuC56TgjpIHnkbZR9thPoEU/edit)
- [Informed Consent Overview Document](https://docs.google.com/document/d/1c6SKPty8dP6J58x5n7FrcomH6ryc0iZW_ZrvrE58M0Q/edit)
- [Mentor Research Plans and Goals - Wiki](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals)
- [Mentor Research Informed Consent Overview](https://docs.google.com/document/d/1c6SKPty8dP6J58x5n7FrcomH6ryc0iZW_ZrvrE58M0Q/preview#heading=h.f11vvn81qc2n)

**Other Resources** 
RP8 Research Plans ([Notes on All Research Plans](https://docs.google.com/document/d/123ylPvkIlpGyHssOXNpWoxeD2isf3iS6LzYlJ-PKLB4/edit#))

[Weekly Intern Evaluation of Mentors](https://docs.google.com/document/d/1OPpNYnRh6Dl1VyyQ6-QuPgUhgahgSX8_pwwh6Kg9ZQA/edit?usp=sharing)
[Mentor Post-Onboarding Survey](https://docs.google.com/document/d/1Y2f6_PQd4Gyo7rOwgFm7OYg7FAUg_1yIrsww2MCrsGE/edit?usp=sharing)
[Summer 2022 Internship Mentor Interest Form](https://docs.google.com/forms/d/1rs530vY6vVZ3nonHqEbWxpt4rBf0zgBdXiRAlTVkafo/edit)
[Google Drive](https://drive.google.com/drive/folders/1v1MPBJsWSl_xoHJ2ntCO53AZlNziciNn)
[Wiki](https://github.com/hackforla/internship/wiki/Research-Plan-8:-Mentor-Intake-Interviews)
Mentor Onboarding: TWE: Create Mentor Onboarding https://github.com/hackforla/internship/issues/212
Consent Forms Templates: https://drive.google.com/drive/folders/1qTW_AoCPvA1c1-Qckg-7qXiA19ZcA2JN

Intern Research Plans and Goals
Wiki : https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals

Mentor Research Plans and Goals
Wiki: https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals

**Comment by Aparna1Gopal** [comment]
**Notes:**

**Consent Forms**

Consent Forms for UX Research: A Starter Template
Do you have permission for that? How to write an easy-to-understand informed consent form, plus the template we use at User Interviews.
https://www.userinterviews.com/blog/how-to-write-research-participant-consent-forms?utm_source=autopilotResearcher&utm_medium=email&utm_campaign=FV&utm_content=220

**Comment by bradyse** [comment]
Hi @Aparna1Gopal and @adarosh 

I am currently working on updating this page on the Wiki so that Bonnie can use it during the mentor onboarding process: 
[Mentor Research Plans and Goals](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals).

In order to add some of the Consent materials to this page, I copied the intern parent consent Google Form into this [Google Drive folder](https://drive.google.com/drive/folders/1qTW_AoCPvA1c1-Qckg-7qXiA19ZcA2JN?usp=sharing). Here is the template file that I created: [TWE: Mentor Consent Form for Surveys/Interviews](https://docs.google.com/forms/d/13Hj9alj786A2a24upGr4CuC56TgjpIHnkbZR9thPoEU/edit).

I saw that you all were doing some work in this folder already, and I thought it would be helpful to add some template-like materials. I also included this[ email template](https://docs.google.com/document/d/1_OFu77bRbJ3oYb_TcEE6ghCBAmeNoCD67kGD2ndpLls/edit) in case we need to email the mentors the consent form. 

If you both could work on filling in the templates with the actual consent form info, that would be helpful. The onboarding is supposed to happen next Tuesday.

Thanks!
Sara

**Comment by adarosh** [comment]
Hi @bradyse 

Thanks for the update!

Yes, the folder should contain Code for America’s example consent form and template (pulled from their Qualitative Research Practice Guide, 2020). I also included a version of their template that I edited based on the mentorship program research.

I’m happy to fill in the templates in time for others to review before Tuesday, but have a few clarifying questions. Any chance you have a few minutes later tonight to connect via Zoom?

Thank you!
Angela

**Comment by Aparna1Gopal** [comment]
@bradyse  Many thanks for the update! And for sharing the onboarding timeline for Tuesday. I will review the above details and get back to you if I have any further questions.

**Comment by bradyse** [comment]
@adarosh, I finished writing the items for the mentor intake surveys and included consent information in the document: [here](https://docs.google.com/document/d/1Y2f6_PQd4Gyo7rOwgFm7OYg7FAUg_1yIrsww2MCrsGE/edit#heading=h.ljd18g2tzhed). It might be a bit over-the-top, but I can't seem to get past my academic training. 😂

Feel free to give me feedback on it, use it, or suggest revisions before the onboarding on Tuesday.

**Comment by Aparna1Gopal** [comment]
**Notes** 

Current production pipeline for the Consent Forms

Angela: Currently working on draft of Consent Form 
Aparna: Finalizing Email template to send to mentors. Will review Consent form draft and transfer to google form and email template.

**Comment by adarosh** [comment]
@Aparna1Gopal I have uploaded a draft Consent Form for the post-onboarding survey to the Consent Forms_Mentor Interviews/Surveys folder on Google Drive. The title of the document is Mentorship Survey Informed Consent. Let me know if you have any questions/concerns!

**Comment by bradyse** [comment]
@Aparna1Gopal and @adarosh ,

Thank you for your hard work on the consent forms. I have taken what Angela wrote in the survey template and adapted it for use in the [mentor intake survey instructions](https://docs.google.com/document/d/1Y2f6_PQd4Gyo7rOwgFm7OYg7FAUg_1yIrsww2MCrsGE/edit#heading=h.zgpmukqxk19).

If we are going to do use similar procedures as the Parental Consent process, then we need to create a Google Form that encompasses _all_ the interviews and surveys in one Google Form. See the Parental Consent Form [here](https://docs.google.com/forms/d/e/1FAIpQLSe448BM3v-Q8DUPFX109oJVwWtV9q3UzMP_wSCQmPWesbbSdQ/viewform).

Therefore, I recommend that we use what Angela created and organize the Google Form with the main headers/sections being:

- Informed Consent for Research
- Survey Purpose & Procedures
- Interview Purpose & Procedures
- Participation in this survey is completely voluntary and up to you.
- Data will be kept confidential and shared only with the research team. 
- I have read and understand the above consent form.

That way the mentors provide broad consent over all of the research at the onset of their mentorship. Then, when we send surveys or interviews, we just include the abbreviated information from the Google Form and they can click a simple "yes/no" if they agree to participate (just like the interns do now). What do you think?

**Comment by Aparna1Gopal** [comment]
@adarosh @bradyse 

Mentor Informed Consent – Google Form is ready to go!

I have collated all the information from Angela’s consent form, Sara’s feedback on structure, the parental consent forms, added info regarding interviews/audio/video from existing intern docs to keep all language and formatting consistent. 

The following has been completed: 
- [ ] The consent form (broad consent across all categories at the onset of their mentorship) is complete
- [ ] Email to mentors complete 
- [ ] Wiki updated

**Comment by bradyse** [comment]
@adarosh @Aparna1Gopal 

During the UX lead/PM meeting on July 6 and in preparation for the [mentor onboarding](https://docs.google.com/presentation/d/1k7vWfOaXEnVebC5qkU9n7WLp_PLCfT0vcLkKC96e1J4/edit?usp=sharing), Bonnie, Rabia, and I worked on the following:
- Rebranded [informed consent document](https://docs.google.com/document/d/1c6SKPty8dP6J58x5n7FrcomH6ryc0iZW_ZrvrE58M0Q/edit) using TWE template.
- Removed purpose and procedure sections for surveys and interviews from document and redirected respondents to the [wiki page with the overview of research plans](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals).
  - @adarosh and @Aparna1Gopal: If you think what was removed from [this original document](https://docs.google.com/document/d/1DaEWDYA2qYgru2ZRqO07PZwaOdHbfZzp/edit?usp=sharing&ouid=108458790862240355603&rtpof=true&sd=true) needs to be included in the wiki page, please add the relevant info to the [wiki page](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals).
  - The wiki overview page should have all the relevant information that participants need to provided informed consent without duplicating information.
  - I created a [folder ](https://drive.google.com/drive/folders/1QCzOg7VkrddlHEXte1j0uWt6eKPSRZ9L?usp=sharing)to house all the wiki documents that are to be added to the [wiki page](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals).
- Created a ["stripped down" external view of the research plan](https://docs.google.com/document/d/131HMrA53YMC-a0lbGDauzs-D9tMTCZuFx9bZD3tNqwg/edit) for the surveys and linked in the wiki overview page.
- Took the [Google Form](https://docs.google.com/forms/d/1eQou3oATIYXoeApkD1ftY37HVNrIPOTUCyzsQfgbPGY/edit) that @sniux created and revised it, including doing the following:
   - Numbered the questions
   - Added mentor # to the top of the survey
   - Added informed consent question
   - Revised (with the help of Bonnie ) a few of the knowledge items to align with mentor onboarding
   - Added an open-ended question at end to end on a positive note (per Bonnie's recommendation)
   - Added instructions to the knowledge items and removed text-only items (to save space)

**Comment by Aparna1Gopal** [comment]
**Notes:** Removed RP008 label and added Dependencies https://github.com/hackforla/internship/issues/208 in keeping with the current documentation kit clean-up for Mentor Research
