### ISSUE TITLE
Create Interview Guide - Mentor Exit Interview

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/internship#246]
### Overview
We need to create an Exit Interview Guide for the TWE mentors to assess the extent to which they understand their role as a mentor. Any gaps they experienced during the course of their mentorship and perceived challenges or barriers to being an effective mentor.

### Action Items
- [ ] Create Research Plan
- [ ] Create Interview Guide (knowledge, gaps, and perceived challenges)
- [ ] Conduct Interviews 
- [ ] Data Analysis
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
RP8 Research Plans ([Notes on All Research Plans](https://docs.google.com/document/d/123ylPvkIlpGyHssOXNpWoxeD2isf3iS6LzYlJ-PKLB4/edit#))

[Weekly Intern Evaluation of Mentors](https://docs.google.com/document/d/1OPpNYnRh6Dl1VyyQ6-QuPgUhgahgSX8_pwwh6Kg9ZQA/edit?usp=sharing)
[Mentor Post-Onboarding Survey](https://docs.google.com/document/d/1Y2f6_PQd4Gyo7rOwgFm7OYg7FAUg_1yIrsww2MCrsGE/edit?usp=sharing)
[Summer 2022 Internship Mentor Interest Form](https://docs.google.com/forms/d/1rs530vY6vVZ3nonHqEbWxpt4rBf0zgBdXiRAlTVkafo/edit)
[Google Drive](https://drive.google.com/drive/folders/1v1MPBJsWSl_xoHJ2ntCO53AZlNziciNn)
[Wiki](https://github.com/hackforla/internship/wiki/Research-Plan-8:-Mentor-Intake-Interviews)
Mentor Onboarding: TWE: Create Mentor Onboarding https://github.com/hackforla/internship/issues/212
Consent Forms Templates: https://drive.google.com/drive/folders/1qTW_AoCPvA1c1-Qckg-7qXiA19ZcA2JN

**Comment by bradyse** [comment]
This issue is being tracked in RP 14: Create Mentor Exit Interview Guide #266 instead
