### ISSUE TITLE
Create project card image for HfLA website (600 x 400)

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#248]
### Dependencies
- https://github.com/hackforla/website/issues/2288

### Overview
We need to have an image to put on the project card for the hackforla website, so that we can get our project listed

### Action Items
- [x] Make a 600 x 400 image out of the logo with appropriate white padding on the sides.

### Resources/Instructions
https://hackforla.org/projects
[internship figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?)

**Comment by ale22arevalo** [comment]
![Project Card](https://user-images.githubusercontent.com/44823677/176914496-545eb0fb-d84d-411e-9710-308b3e7ca6ff.png)
