### ISSUE TITLE
TWE: IS22: Create a customized time card dashboard

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#254]
### Overview
We need to create an individual dashboard for each intern so that the hours they put in (using the time card) can be visually displayed.

### Action Items

- [x] Gather requirements
- [x] Create charts/tables using data in time card
- [x] Add design elements
- [x] Customize for each intern
- [x] Share with respective intern
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Time Card Spreadsheet](https://docs.google.com/spreadsheets/d/10oqrFfqMELuBUPwQQGgBscmdF7FTG61aSLbXqju3wSM/edit#gid=2026057936) - used as data source for the dashboards
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Rabia2219** [comment]
Notes:
I had to add another sheet to the existing spreadsheet that contained the expectations (added manually) for each week, intern ID (added manually), week number (pulled from the PD sheet through a formula) and the total for each intern per week (pulled and calculated from the PD sheet).

For the next cohort, I would suggest collecting the commitment vs expectation for each week through a form before the internship starts so that it is already recorded.

**Comment by sofiatajide** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- [Intern Dashboard Links](https://docs.google.com/spreadsheets/d/1h4NXc-oTfBv_9TBCoR9qvkWGPa9cnj7URRgUeOa6p2Q/edit#gid=0)
  - [ ] Have access, its located in ____
  - [x] public
- [Time Card Spreadsheet](https://docs.google.com/spreadsheets/d/10oqrFfqMELuBUPwQQGgBscmdF7FTG61aSLbXqju3wSM/edit#gid=2026057936)
  - [ ] Have access, its located in ____
  - [x] public
- [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
  - [ ] Have access, its located in ____
  - [ ] public
