### ISSUE TITLE
Update the brand platform page by changing all the heading text to Calibri

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#255]
### Overview
We need to update the Brand Platform document in Figma to match the fonts that we use.

### Action Items
- [x] Follow instructions on how to add Calibri font to Figma
- [x] Update the Brand Platform page by changing the heading font to Calibri
- [x] Save PDF of each brand book page
- [x] *ADD INSTRUCTIONS TO ADD pdf pages to team drive
- [x] Add link to Brand Book PDF (in Google Drive) to the Design Process Wiki Page

### Resources/Instructions
- [Figma Brand Platform Page](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=215%3A10)
- [How to install new fonts in Figma](https://help.figma.com/hc/en-us/articles/360039956894-Access-local-fonts-on-your-computer)
- [Design Process Wiki Page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
- [Internship google drive folder>Marketing>Branding](https://drive.google.com/drive/folders/1NeYnJpEEd9IjBJXt7B53vk9q6b6QLFNK)

**Comment by bryannalim** [comment]
Just to confirm, Calibri font is only changed for headers on the "Brand Platform Draft (as of 2021-12-20)" page. (If so, this is done)
**We are not implementing it onto the "design system" page of the figma file, correct?**

Also, unclear exactly what should be updated for the "relevant WIKI page (See resources)"
