### ISSUE TITLE
TWE: RP006: Intern Intake Interviews: Data Analysis

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#257]
### Overview
We need to analyze the intern onboarding interviews.  Some of this analysis will also require data from the the exit interviews to be conducted July 29th.  

### Action Items

- [ ] Locate the data and make sure that it is all de-identified
- [ ] Use Otter.ai to transcribe interviews
- [ ] Review research goals/interview questions
- [ ] Decide on a plan of action for analysis
- [ ] Carry out the analysis
- [ ] Update relevant WIKI page (See resources)
- [ ] Release dependency on #322 and if it's the last dependency, move 322 to the new issue approval column

### Resources/Instructions
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by priyatalwar** [comment]
We've added it to the next agenda so we know what templates we need to work on

**Comment by priyatalwar** [comment]
@priyatalwar to follow up with Ying

**Comment by pandanista** [comment]
We will create new issues for data analysis when the time comes. Closing this issue for now.
