### ISSUE TITLE
RP 16: Intern Productivity Dashboard Survey

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#258]
### Overview
We need to gather feedback about the productivity dashboard, in order to improve the usability of the product.

### Action Items
- [x] Draft Survey Questions
- [x] Create Google Form to Distribute
- [ ] Send out to interns
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
- [LinkedIn Weekly Survey](https://docs.google.com/forms/d/16QcDQtLTPEct44sJ_RIudj6XuKK0FwZdsAcu3B1BMeo/edit)
- [Intern Dashboard Links](https://docs.google.com/spreadsheets/d/1h4NXcoTfBv_9TBCoR9qvkWGPa9cnj7URRgUeOa6p2Q/edit#gid=0)
- [RP 16 - Intern Productivity Dashboard Survey Research Plan](https://docs.google.com/document/d/1GRj7dwAIdAJKwTDcUtvY54uN_w1LzC0f6rkl21S0Gak/edit)
- [Template Survey](https://docs.google.com/forms/d/1m0rTEzHg2BZcaSqy0rSUvHB5-Oqg2t8jaOimQPX9uVE/edit)
- [Public Facing Research Plan](https://docs.google.com/document/d/1__fdDhcOBPjtnwNQaQv3xR1pPkKJvZAAaB181YlhllA/edit)
- [Intern Productivity Dashboard Survey](https://docs.google.com/forms/d/1LIkRzx7QOwGqRR14fH90SY_UVXx3wxojOM1pN0Uo7JE/edit)  **This is the survey where the questions should be added.**
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by christine-el** [comment]
@ExperimentsInHonesty @koyelranu:   Here is a link to a draft of the email that needs to be sent out to parents:  https://docs.google.com/document/d/1oZ9MFTkVF4D28MzTp8FqPcUCA-WODO2MgQRspgQilx8/edit

1.)  The questions need to be added to the email.  2.)  The research plan and google form need to be added to the Guardians WIKI page.  3.)  The link to the WIKI may also be added to the email, once #2 is done.

**Comment by koyelranu** [comment]
Intern Productivity Dashboard Survey was created on Google Forms ([https://forms.gle/EckgGUXzTaVcyiV7A]. Survey Questions were taken from here: [https://docs.google.com/document/d/1__fdDhcOBPjtnwNQaQv3xR1pPkKJvZAAaB181YlhllA/edit#]

**Comment by ExperimentsInHonesty** [comment]
Example document with the goals: https://docs.google.com/document/d/11owu6zVKn2KkonqngAef5wXYQi3OEe6Q6x6fqn8Huts/preview

Document you are editing 
https://docs.google.com/document/d/1__fdDhcOBPjtnwNQaQv3xR1pPkKJvZAAaB181YlhllA/edit#

Original email: https://docs.google.com/document/d/1fvZ-SpEfYzu-GaRAOyemi5Gn5pCfkoncBtejAOuqYCo/edit

Email we are editing
https://docs.google.com/document/d/1oZ9MFTkVF4D28MzTp8FqPcUCA-WODO2MgQRspgQilx8/edit

Recording:

**Comment by christine-el** [comment]
This survey was never carried out because we ran out of time.
