### ISSUE TITLE
Create agenda for intern offboarding

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#259]
### Overview
We need to create an agenda for offboarding the inters
### Action Items
- [x] Review the onboarding issue and see which items need to be reversed.
- [x] Identify other resources they need to be removed from
- [x] Identify information we want to give them on exit

### Resources/Instructions
- [intern onboarding issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=role%3A+intern&template=create-self-onboard-issue.md&title=TWE%3A+Self+Onboard+%5BYOUR+NAME%5D)

**Comment by ExperimentsInHonesty** [comment]
#### Slack
You can stay in channel (if you want to communicate with other interns) or remove yourself

#### Google Drive
- [ ] Confirm access to Google Drive folders
  - [ ] Your Intern folder
  - [ ] TWE: All Interns

#### GitHub
- [ ] View GitHub Tutorial
- [ ] Create a GitHub account 
- [ ] Make sure you have a professional name  (if you have a GitHub account already you can rename)
- [ ] Setup 2FA
- [ ] Add a comment to this issue saying you have setup your GitHub
- [ ] Add your GitHub handle to the roster

#### Meetings
Confirm that you see the following meetings on your calendar and that you have setup the reminder for the number of min you need before the meeting to ensure you arrive on time.
- [ ] Standup
- [ ] All Team Meetings
- [ ] LinkedIn Workshop
- [ ] CoPs
- [ ] Mentor Meetings

#### Figma
- [ ] Accept invite

### LinkedIn
- [ ] Create LinkedIn Checklist issue

### Resources
- [roster](https://docs.google.com/spreadsheets/d/1wbYWX5ycNV-imK6e-5qO44sDtGAcsHXmI6Q3ZKtVM6M/edit#gid=0)
- [GitHub Tutorial](https://docs.google.com/presentation/d/1whmhdRGeqrz0FbPl5TsQ59_PiJSNVTKdKhAhYxx-GYQ/edit#slide=id.p)
- [Internship Wiki](https://github.com/hackforla/internship/wiki/Interns-summer-2022)

**Comment by epierotti3** [comment]
Figure out the exit interview schedule (Christine knows)
Finish form (text Bonnie when done)

**Comment by epierotti3** [comment]
Information to provide on exit:
- Thank you for participating
- Learned skills and new connections made
- How to continue with HfLA (come back as volunteer?)
- How to stay in touch with us/other interns/mentors

**Comment by epierotti3** [comment]
Going to create an issue where we can track interns' off-boarding status (if applicable) based on their [off-boarding form responses ](https://docs.google.com/spreadsheets/d/1-VC8lmBpYVjsl--ZK1YuHWIDIceFbwhuaxYPldM7DeI?resourcekey=&usp=forms_web_b#gid=958870979)
