### ISSUE TITLE
Create an offboarding issue template for the interns

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#260]
### Dependencies
- #259
- Determination that it is going to be helpful

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by epierotti3** [comment]
Example of onboarding issue #218

**Comment by epierotti3** [comment]
We used [this issue](https://github.com/hackforla/internship/issues/275) to track off-boarding activities for each intern and went through this with them during the last stand up.
