### ISSUE TITLE
RP 14: Create Mentor Exit Interview Guide

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#266]
### Overview
We need to create a mentor exit interview guide in order to collect feedback on the mentors' experience with the HFLA interns.  

### Action Items

- [x] Create and finalize the RP14 research plan, including interview questions
- [x] Create a google form to be used by interviewers during the interviews
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
-[RP14: Mentor Exit Interviews Research Plan Goals & Questions](https://docs.google.com/document/d/14oTKedGpwAHo-UWFiaCkHY1i-BohQsbu1eoKo1qMHMA/edit)
-[Example of the Google Form Exit Interview We Are Using for Intern Exit Interviews](https://docs.google.com/forms/d/1dl3c_AG8wxvBPb8COK0PWdCOEeBXva8MWKBIurpuqDw/edit)  You can make a copy of this and use it as a template--just copy and paste your questions here.  Please make sure to link a copy of the Google Form in the comments below and tag Christine El Ouardani, once you are finished.  

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by bradyse** [comment]
Hi @christine-el and @lkawentel, 

Bonnie reviewed the [research plan](https://docs.google.com/document/d/14oTKedGpwAHo-UWFiaCkHY1i-BohQsbu1eoKo1qMHMA/edit) and made some edits to it. I also furthered those edits according to what Bonnie and I discussed on Monday 07-25 in both the research plan and[ google form](https://docs.google.com/forms/d/1oJIf5Me_ZpfGL0cMRFle8dujcY_d-IZYjsGiSlrpXFs/edit). 

I have some concerns about the length of the interview. Bonnie added some probing questions after each quantitative question and I wonder if we'll be able to complete it within one hour. We can discuss this during our Tuesday UX meeting.

As a project management issue, we also need to make sure that we 

- Make sure documents are stored in the right Google drive folder according to the RP number.
- Use the document template (newly created instructions are [here now](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates)).
- Determine who should approve final documents (Bonnie reviewed this research plan and script but I'm not sure who should do this moving forward).
- Create a more streamlined version to put on the [wiki for mentors ](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals)(this research plan here was too long). The streamlined research plan needs to remove the script language used by the researchers.
- Figure out who should delete or close issues (like #246).

Thanks! Sara
