### ISSUE TITLE
Research Plan for Intern Interviews

### ISSUE THREAD

**Issue by sniux** [hackforla/internship#27]
### Dependency
~- [x] Development of one sheet #26 minus logo~

### Overview
We need a research plan to understand our impact on the interns, organization, areas of improvement & intern experience.

### Action Items

- [x] Read the one sheet
- [x] Get a template from Mina 
- [x] Write first draft
- [x] Conduct Mateo & Sakari's Interviews

By 8/19/21
- [x] Edit research draft based on comments
- [x] Send questions to Sophia
- [x] Create an issue to arrange hfLA website team interviews to understand the soft and hard skills required to transition into workspaces
- [x] Work with Bonnie to arrange these interviews

After Priyanka's Interview with Sakari
- [x] Transcribe interviews and take notes after Priyanka's done with the interview and Mateo's responses are obtained
- [x] Add insights to the research document
- [x] Edit the timeline in the research doc according the template

- [x] Revise Objectives and KPIs in the research plan, use the ones that made it into the presentation deck
- [x] Final review
- [x] Add to Wiki (moved to wiki update issue #33 

### Resources/Instructions

[Research Draft](https://docs.google.com/document/d/1t98oH0tAFTsiRm8QI75l93thdwjTxQMvXigmVFs7AbA/edit)
[Interview Recordings ](https://drive.google.com/drive/u/0/folders/1R8sXXGrx47PNj2GpMSUIpMXYllAEgy19)
[Issue where Mina is creating Hack for LA's research plan template](https://github.com/hackforla/UI-UX/issues/120
)

**Comment by sniux** [comment]
Plan of Action:

- Draft a research plan
- Finalize with Bonnie
- Write down interview questions
- Interview Thursday and Friday
- Add the insights to the problem statement

**Comment by sniux** [comment]
@ExperimentsInHonesty I have added the draft [here](https://docs.google.com/document/d/1t98oH0tAFTsiRm8QI75l93thdwjTxQMvXigmVFs7AbA/edit). Please add comments/notes and I'll refine the questionnaire and get it ready for the interviews.

**Comment by sniux** [comment]
8/9/2021

- Updated the script for the interview.
- Sophia did not show up.

**Comment by sniux** [comment]
8/13/21

- Completed [Jason's interview
](https://drive.google.com/file/d/1eGp05HSvmnIcfFyATht1Q_2BoGlhI1QH/view?usp=sharing)

**Comment by sniux** [comment]
Updates & Notes from the 8/17 Meeting:

- [ ] Priyanka will be conducting Mateo and Sakari's Interviews
- Snigdha needs to:
 - [ ]

**Comment by ExperimentsInHonesty** [comment]
Hi @sniux did you have a chance to review all the interviews this weekend and determine if we needed to repeat some of them?  If you put your notes on another issue, please let us know which issue they are on.

**Comment by sniux** [comment]
@ExperimentsInHonesty I did, and I think Sophia's interview needs to be repeated - everything else looks fine to me.

**Comment by priyatalwar** [comment]
@sniux @ExperimentsInHonesty All  intern user interviews including #46  done now

**Comment by Rabia2219** [comment]
@priyatalwar 
All action items have been checked off. Close and done?

**Comment by sniux** [comment]
@Rabia2219 I think there 3 action items left.

**Comment by priyatalwar** [comment]
@sniux Please add to the wiki before closing this issue.
