### ISSUE TITLE
RP 17: Productivity Dashboard Sakari Interview Upload

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#271]
### Overview
We need to upload Sakari's interview on the productivity dashboard to a Google Folder in order to further analyze the interview.  

### Action Items
- [x] Create folder called `sakari productivity dashboard interview` insie RP17
- [x] Bonnie needs to upload Sakari's interview on the productivity dashboard to the folder
- [x] add role: ux research and remove org rep
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [RP17 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
- [RP17 Google Folder](https://drive.google.com/drive/folders/1QJ-5eqtdYTPJZuoN51IcpG4ORGUeEMgZ)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ExperimentsInHonesty** [comment]
I need to know when it was conducted so that I can find it.

**Comment by bradyse** [comment]
@ExperimentsInHonesty @christine-el thinks that this interview was on July 13th at 4 pm.

**Comment by ExperimentsInHonesty** [comment]
I have uploaded the recording to the research plan folder.  Once the recording has been used, it must be moved to where we are keeping recordings that have PII in them.

**Comment by bradyse** [comment]
I moved the recording to the "My Drive" in the internship account. and updated the wiki page to say that this single recording will be used to write the research plan.

[RP17 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
[Folder that has PII](https://drive.google.com/drive/folders/1QqvHWGfyxrf-8hUBdhv5Vf1l18iaYvS2?usp=sharing)

**Comment by mayankt153** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- [RP17 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
  - [ ] Have access, its located in ____
  - [x] public
- [RP17 Google Folder](https://drive.google.com/drive/folders/1QJ-5eqtdYTPJZuoN51IcpG4ORGUeEMgZ)
  - [ ] I do not have access 
  - [x] public
- [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
  - [ ] Have access, its located in ____
  - [x] public
