### ISSUE TITLE
TWE: IS22: RP009: Weekly Standup Surveys Wiki Page: Update

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#278]
### Overview
We need to review and update the wiki page for RP9 so that future TWE team knows what has been completed and what needs to be done to replicate this research plan.

### Action Items

- [x] Review/Update Research Date
- [x] Review/Update Summary of Research
    - [x] Update Research Question
    - [x] Update Purpose
    - [x] Update Methods
- [x] Review/Update Current Status
- [x] Search all issues to make sure that there are no mislabeled issues. 
- [x] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [x] Review/Update Outstanding task items
- [x] Review/Update Assets
    - [x] Review/Update link to Research Plan (please mark external facing research plan doc and internal facing research plan doc with `external` and `internal` at the beginning of the research plan hyperlinks)
    - [x] Review/Update link to Scripts Docs
    - [x] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [x] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)(if nothing to report yet, leave blank)
    - [x] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [x] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [x] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [x] Review/Update Links to Related Wiki Pages
- [x] UX Research Lead sign-off
- [ ] Product sign-off

### Resources/Instructions

- [RP9 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-9:--Weekly-Standup-Surveys)
- [RP6 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- Don't link GitHub issues (because there is a link to all issues with the `Research: RP009` label
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues

**Comment by bradyse** [comment]
This issue is being closed because the wiki page has been updated.

**Comment by pandanista** [comment]
@priyatalwar I reviewed and updated this issue. It is now ready for product review. Thanks!

**Comment by priyatalwar** [comment]
@pandanista the link to the action items spreadsheet seems to be missing. Can you please add update the wiki with that link? Thank you.

**Comment by pandanista** [comment]
Hi @priyatalwar, I am not aware of the action item spreadsheet for internship. Instead, we've been listing the action items under "Outstanding task items" section on wiki pages. I've just specified a few action items in the "Outstanding task items" section for [RP009](https://github.com/hackforla/internship/wiki/Research-Plan-9:--Weekly-Standup-Surveys)
<img width="1036" alt="Screenshot 2023-07-20 at 2 13 13 PM" src="https://github.com/hackforla/internship/assets/57029070/ba0cb77f-077b-4132-849f-08ac6047a780">

If the "Outstanding task items" section meets Product's needs, please go ahead and close the issue.

If we are not using action item spreadsheet, we should also update the wiki template to avoid any future confusion. 

Thank you.

**Comment by priyatalwar** [comment]
@pandanista totally agree since it's has been confusing for me as well.

**Comment by pandanista** [comment]
Sounds good, @priyatalwar. I will list this in the meeting agenda.

**Comment by ExperimentsInHonesty** [comment]
I reviewed the RP009 comment about action items.  And added the following to outstanding tasks

> - Data Presentation
>    - Create Action Items spreadsheet
>    - Create presentation (slides) if necessary
