### ISSUE TITLE
Update RP8: Mentor Intake Interviews wiki page

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#279]
### Overview
We need to review and update the wiki page for RP8 so that future HfLA volunteers can replicate our processes.

### Action Items

- [x] Review/Update Research Date
- [x] Review/Update Summary of Research
    - [x] Update Research Question
    - [x] Update Purpose
    - [x] Update Methods
- [x] Review/Update Current Status
- [x] Search all issues to make sure that there are no mislabeled issues. 
- [x] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [x] Review/Update Outstanding task items
- [x] Review/Update Assets
    - [x] Review/Update link to Research Plan
    - [x] Review/Update link to Scripts Docs
    - [x] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [x] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [x] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [x] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [x] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [x] Review/Update Links to Related Wiki Pages
- [ ] Product reviews wiki page

### Resources/Instructions

- [RP8 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- Don't link GitHub issues (because there is a link to all issues with the `epic` and `feature:roadmap` label
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Aparna1Gopal** [comment]
@bradyse This issue is done and can be closed. Thanks!

**Comment by Aparna1Gopal** [comment]
**Notes:** @Aparna1Gopal 

To refer: Good example/ best practice for the following: 
- Making a Wiki related GitHub Issue 
- Details on the related Wiki Page

**Comment by Aparna1Gopal** [comment]
@bradyse This issue is done and can be closed. Thanks!
- [RP8 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)

**Comment by bradyse** [comment]
@Aparna1Gopal 
Recommended updates to this wiki page:
- [ ] Move some of the summary of research information on the reasons why this research was not conducted in 2022 to the "Current Status" section
- [ ] Move the relevant information from the research roadmap document to the various subsections of the wiki page. 
- [ ] Add placeholders for missing documentation (e.g., Research Plan)
- [ ] Leave missing information after Scripts blank
- [ ] Under "Outstanding Task Items," provide detailed instructions for what the next steps are for completing this research plan and carrying out the research 

See [RP9's Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-9:--Weekly-Standup-Surveys) for an example of an uncompleted research plan.

**Comment by Aparna1Gopal** [comment]
@bradyse I have completed the above task items. Could you please review [RP8 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)
and let me know if any further changes need to be made? Thanks!

**Comment by bradyse** [comment]
@priyatalwar This issue is complete. I will unassign @Aparna1Gopal and wait for your approval to close it.

**Comment by priyatalwar** [comment]
@bradyse Thanks for taking care of this issue. I am closing this issue now since it is complete.
