### ISSUE TITLE
Design System: Create logo

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#28]
### Dependency
Develop Personas #30 (can be worked on without this)
~Setup Figma #29~

### Overview
We need a logo so that this project can appear on the website and have a finished one sheet

### Action Items
- [x] Review the one sheet draft
- [x] Review the wiki
- [x] Ask any questions of product and UX
- [x] reach out to the UI/UX community of practice and the Design System team to find out what their current guidance is for making a logo
- [x] Post draft ideas for logo and hero in comments
- [x] once a serviceable or temporary logo is completed, release the dependency on #57 

### Resources
[Internship Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file)
- [one sheet](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/preview)
- [wiki](https://github.com/hackforla/internship/wiki)
- [#design-systems](https://hackforla.slack.com/archives/CH2U1CB9Q)  slack channel

**Comment by priyatalwar** [comment]
Update from Kelly:
Hello, there team,
Susan and I have worked on finalizing the logo we discussed last week. Please review the three options and let us know your feedback. Hopefully, there is an option that everyone likes. I know I have a favorite!  :)
(https://hackforla.slack.com/archives/C032AFW2PUY/p1643931241134129)
Rabia & Priyanka,  Can you please help upload the link into Github to share with the team? I still haven’t unlocked my account.
Attaching PDF, JPG, and Figma file link. It’s in the same page under  “style Guide” in the team’s file
[https://hackforla.slack.com/archives/C032AFW2PUY/p1643931276923919)
https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=443%3A540

**Comment by Rabia2219** [comment]
[Kelly Choe](https://app.slack.com/team/U02FFT9R0H2)  [6:25 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645575901844319)
Hi Rabia and Priyanka, We hope to try our logo on some of the documents and platforms that the logo will be used. Can you share with us a google slide, UX research, or an analytical report you’ve done? We want to drop our logo to see how it would look on these platforms.
[6:25](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645575905373029)
thanks!

[Rabia Shaikh](https://app.slack.com/team/U01QSJ10XRA)  [7:38 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645580293752719)
Hello team,
Tagged the design team on GitHub with links to doc/form/slide deck to test logo on...

[Susan Zhuang](https://app.slack.com/team/U02TE9A3F0E)  [8:08 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645582099288969)
okay, thank you

**Comment by Rabia2219** [comment]
@kellychoe @Susanz7 @seetho-c 

This is some of the material you can test the logo on. Please make sure you make a copy to work on and save all the work on the Internship drive. Thanks

- [IS22: Slides for AMA](https://docs.google.com/presentation/d/1Uy3c1ZbWbytllA1KqL4pu3LI5ma8IDxwLQSjRe3h0g0/edit#slide=id.gea24f90547_0_3)
- [Internship FAQ Summer 2022](https://docs.google.com/document/d/1TpacAma_vmAZ4MGq_VAQme22BsgKm1DW5rFBhYgm6vM/edit#heading=h.o31w6jmip2eh)
- [Summer Internship Check-In](https://docs.google.com/forms/d/1dLnvtsApjcWHgcvzjNoBAy_5LJSZ8YJpfJNV4NkeFIM/edit)

**Comment by Rabia2219** [comment]
> [Kelly Choe](https://app.slack.com/team/U02FFT9R0H2) [6:25 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645575901844319) Hi Rabia and Priyanka, We hope to try our logo on some of the documents and platforms that the logo will be used. Can you share with us a google slide, UX research, or an analytical report you’ve done? We want to drop our logo to see how it would look on these platforms. [6:25](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645575905373029) thanks!
> 
> [Rabia Shaikh](https://app.slack.com/team/U01QSJ10XRA) [7:38 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645580293752719) Hello team, Tagged the design team on GitHub with links to doc/form/slide deck to test logo on...
> 
> [Susan Zhuang](https://app.slack.com/team/U02TE9A3F0E) [8:08 PM](https://hackforla.slack.com/archives/C034LJ9HBCZ/p1645582099288969) okay, thank you

@kellychoe @Susanz7 @seetho-c 

This is some of the material you can test the logo on. Please make sure you make a copy to work on and save all the work on the Internship drive. Thanks

- [IS22: Slides for AMA](https://docs.google.com/presentation/d/1Uy3c1ZbWbytllA1KqL4pu3LI5ma8IDxwLQSjRe3h0g0/edit#slide=id.gea24f90547_0_3)
- [Internship FAQ Summer 2022](https://docs.google.com/document/d/1TpacAma_vmAZ4MGq_VAQme22BsgKm1DW5rFBhYgm6vM/edit#heading=h.o31w6jmip2eh)
- [Summer Internship Check-In](https://docs.google.com/forms/d/1dLnvtsApjcWHgcvzjNoBAy_5LJSZ8YJpfJNV4NkeFIM/edit)
