### ISSUE TITLE
Create Intern Research Documents by overview page

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#281]
### Overview
We need to create a wiki page for all intern research plans so that future HfLA volunteers can easily find all associated research plans for interns in one place.

### Action Items
- [x] Create New page on Internship Wiki
- [x] Name it "Intern Research Overview"
- [x] Copy and paste from below the Research Roadmap Template
- [x] Click "Save page" to create the new page
- [x] Edit the page you just created with all relevant links using the [Mentor Research Overview](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview) as an example
- [x] On the Main [Research Output Overview page](https://github.com/hackforla/internship/wiki/Research-Output-Overview), add the URL of the page you just created to "Intern"

### Resources/Instructions

- [Wiki Roadmap Template](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Internship Wiki Main Page](https://github.com/hackforla/internship/wiki)
- [Research Output Overview Wiki Page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- [Mentor Research Overview](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview)

**Comment by bradyse** [comment]
@christine-el, please add Shima to the GitHub internship team so that Shima can be assigned to this issue. Thanks!

**Comment by christine-el** [comment]
@bradyse I have not yet been trained on how to add people to the team, but will ask Bonnie today how to do this.

**Comment by shimahoush** [comment]
Page has been created. Linked to "Intern" under Research Output Overview page

**Comment by epierotti3** [comment]
@bradyse please ask UXRs to self-assign issues from this [link](https://github.com/hackforla/internship/projects/1?card_filter_query=label%3A%22role%3A+ui%2Fux+research%22) starting from the top of the column
