### ISSUE TITLE
Setup Figma for Internship

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#29]
### Overview
We need to have access to figma for creating designs for this project

### Action Items
- [ ] Reach out to Olivia to find out if there is a free figma account.  
- [ ] Create a figma section inside the account (we don't need a whole account)
- [ ] Setup email in vault
- [ ] write instructions for adding a new team member

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty asking again to close this issue as we have the Figma setup now...

**Comment by ExperimentsInHonesty** [comment]
The figma has been setup and we have instructions for how to onboard someone to figma.

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/internship/wiki/Onboarding-Process-for-Project-Team-Leads
