### ISSUE TITLE
Update RP5: Brand / Website Audience Alignment

### ISSUE THREAD

**Issue by shimahoush** [hackforla/internship#301]
### Overview
We need to review and update the wiki page for RP5: Brand / Website Audience Alignment so that future HfLA volunteers can replicate our processes.

### Action Items
- [x] Add milestone: 06.01.02 Research Audit and update wiki page
- [x] Review/Update Research Date
- [x] Review/Update Summary of Research
    - [x] Update Research Question
    - [x] Update Purpose
    - [x] Update Methods
- [x] Review/Update Current Status
- [x] Search all issues to make sure that there are no mislabeled issues. 
- [x] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [x] Review/Update Outstanding task items
- [ ] Review/Update Assets
    - [x] Review/Update link to Research Plan
    - [ ] Review/Update link to Scripts Docs
    - [ ] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [ ] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [x] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [x] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [x] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [x] Review/Update Links to Related Wiki Pages

### Resources/Instructions
- [RP5](https://github.com/hackforla/internship/wiki/Research-Plan-5:-Brand---website-Audience-Alignment)
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing) - you can find research  plans by type or by number/name
- Don't link GitHub issues, instead make sure that the wiki page has a link to all the issues using the label (e.g., `Research: RP006` label)
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- [Tech Work Experience Brand Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A3&t=46WFsuQDezl7WgDK-0)

**Comment by bradyse** [comment]
@Dewey-Tran 
- [ ] Look at the wiki page where it says "All Issues" and search by RP005 label.
- [ ] Review all the open and closed issues
- [ ] Add shortcuts or move documentation to the Google Drive folder for RP005
- [ ] If information is uncovered that could potentially update the wiki page, add that information in a comment and bring the link to the All Team meeting.

**Comment by Dewey-Tran** [comment]
Update 11/17/2022: Figma link for Brand Guide added, Figma file needs to be updated with correct font, waiting on designer to be added.

**Comment by bradyse** [comment]
@Dewey-Tran 

Update Outstanding Task items with the items we discussed (including research roadmap and research plan updates). Make sure that Current Status reflects what happened most recently with the plan (RP was stopped due to replication issues) and next steps.

**Comment by ExperimentsInHonesty** [comment]
@Dewey-Tran Hi!  Welcome back from the break.   We are confirming everyones interest and availability.  Please add a new update to this issue
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" - we know you just came back from break, please just summarize the progress from before then
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by Dewey-Tran** [comment]
1. Progress: No progress made due to methodological issues
2. Blockers: Needs formal research plan regarding #98 and #96 
3. Availability: Can contribute 6 hours per week
4. ETA: Unknown

**Comment by pandanista** [comment]
Confirm with Bonnie on the issue listed above.

**Comment by pandanista** [comment]
The auditing has been conducted for RP005. [RP005 wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-5:-Brand---website-Audience-Alignment) has been updated.
