### ISSUE TITLE
Find stats we can use

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#31]
### Overview
We need statistics for the issues we intend to address, so that when we interview the students we can develop baselines for our community and progress stats.

### Action Items
- [ ] Review Stem Attrition PDF and except relevant stats (supporting future problem statements) to comments below (mention page number)
- [ ] Identify if there are other publicly available stats we can reference (hopefully some more recent than Stem Attrition PDF)

### Resources/Instructions
[Stem Attrition PDF](https://nces.ed.gov/pubs2014/2014001rev.pdf)
[STEM Attrition insights](https://docs.google.com/document/d/1JxRRbt4Y52KbOO_MlN6zv4dUBAseMULPfQ2aFAt4i6E/edit)
[Other related STEM articles and stats](https://docs.google.com/document/d/1fL6RP-i1pjUMslv-__FqdHAEruUJ35m0bimE4DkwJyM/edit)

**Comment by priyatalwar** [comment]
@sniux can you please put a link to the summary you already created? Thanks

**Comment by sniux** [comment]
@priyatalwar @ExperimentsInHonesty [here you go.](https://docs.google.com/document/d/1JxRRbt4Y52KbOO_MlN6zv4dUBAseMULPfQ2aFAt4i6E/edit)
I have added this to the issue as well.

**Comment by maruja0516** [comment]
@ExperimentsInHonesty thank you!
