### ISSUE TITLE
UCLA Correspondence: Follow up with Tung 

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#316]
### Overview
We need to follow up with UCLA so Tung at UCLA can continue as an intern in the fall

### Action Items
- [x] Find the pages on UCLA website by looking at prior issues with UCLA (document them in resources)
- [x] Determine next steps (possible steps include)
  - [ ]  Send placement form to UCLA
- [ ] Check to see if UCLA sent any email
- [x] Follow up with Tung, and get exactly what she needs us to do, make her do any of the work she can do.

#### UCLA potential partner issue
- https://github.com/hackforla/internship/issues/157

#### UCLA website pages we appear on or have appeared on
 - https://www.psych.ucla.edu/undergraduate/fieldwork/psychology-195b/?wpv_aux_current_post_id=2362&wpv_aux_parent_post_id=2362&wpv_view_count=2361

#### form for getting listed
- https://www.psych.ucla.edu/undergraduate/fieldwork/psychology-195b-fieldwork-in-cognitive-science/psychology-195b-fieldwork-form/

**Comment by priyatalwar** [comment]
Slack message from Tung 
"Hi Priyanka, Elizabeth told me to reach to you for any questions regarding the internship. She sent a [Placement Form](https://www.psych.ucla.edu/undergraduate/fieldwork/psychology-195b-fieldwork-in-cognitive-science/psychology-195b-fieldwork-form/) for my fieldwork credit at UCLA. I was wondering if the internship team has received any emails about it?
UCLA Department of Psychology •UCLA Department of Psychology •
[Psychology 195B – Fieldwork Form • UCLA Department of Psychology](https://www.psych.ucla.edu/undergraduate/fieldwork/psychology-195b-fieldwork-in-cognitive-science/psychology-195b-fieldwork-form/)

**Comment by priyatalwar** [comment]
Email communication to Tung:
Hi Tung,
Thanks for reaching out. Yes, we see that the placement form has been already filled out and we are listed. We have only done it for you and once you've accepted the placement we need to close it out as soon as possible since we've been getting a ton of emails from other students. Let us know the next steps since this is time sensitive.

Thank you,
Priyanka

**Comment by priyatalwar** [comment]
Response from Tung:
I have filled out the contract I'm suppose to submit. I was wondering who would be signing as "Site Supervisor".
Here's the [contract](https://drive.google.com/file/d/1o0l2aEpVyPNc36CfV3tIecVlP4iU8Izd/view?usp=sharing). I have to submit by the 24th.

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar I can sign as the site supervisor, please let her know.  Please contact UCLA asap and get the opening listed on their site closed.

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty I just let Tung know and I'll work on getting the listing removed.

Working on drafting a response now.

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty Here is my response to Dylan at UCLA. Please feel free to review and/ or edit before I send it.

Hi Mr Dylan,

Hope you're doing well. Thank you so much for posting our internship on your website: 

https://www.psych.ucla.edu/undergraduate/fieldwork/psychology-195b/?wpv_aux_current_post_id=2362&wpv_aux_parent_post_id=2362&wpv_view_count=2361.

I am now writing to request that you please remove our posting from your website as we are in the process of signing the contract so the intern can start in the fall. We look forward to partnering with you in the future.

Best,
Priyanka
Internship Project

**Comment by ExperimentsInHonesty** [comment]
Letter is good to send

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty Just sent it via the internship email address. Please sign the contract before 24th and I'll let Tung know then.

**Comment by priyatalwar** [comment]
listing has been removed as per Dylan's response to my email:

Thank you for letting me know – I have removed the listing from the listings on our department website.

@ExperimentsInHonesty I can work on a draft to send to the students who applied and we can review on Monday.

**Comment by priyatalwar** [comment]
Dear Intern,

Thank you for your interest in our internship program. Unfortunately, we only had space for one and the candidate has been chosen. We look forward to welcoming you to our future cohorts so please keep an eye out.

We wish you luck for the rest of the school year.

Sincerely,
Priyanka

**Comment by priyatalwar** [comment]
@priyatalwar Create a doc for mail merge: Name and Email; and content of the doc before 9/28 meeting.

**Comment by priyatalwar** [comment]
Update: Here is the spreadsheet for [mail merge](https://docs.google.com/spreadsheets/d/1Y2M3EnkyzO6zLpHZ9rmeDqkOkGmvAkMmJj95nZKOPik/edit#gid=0)

**Comment by priyatalwar** [comment]
Mail has been sent to the non-interns from UCLA and Tung is our only intern for fall. All formalities have been completed for Tung to start in the Fall so closing this issue.
