### ISSUE TITLE
TWE: RP001: Interview Recordings: Transcribe

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#324]
### Overview
We need to transcribe the interview recordings from IS21's Exit Interview to determine if the insights generated last year are consistent with analysis using a new method (directed content analysis). Because last year's analysis did not involve transcription, we need to transcribe the data before it can be analyzed using the new method. 

### Action Items
- [x] Locate the interview recording folder in the Google Drive (link in Wiki page; see Resources)
- [x] Create a spreadsheet of the Intern's names with their Intern Number (spreadsheet template in Resources)
     - [x] Save spreadsheet in with the Interns Interview Recording folder (which will later be moved to a secure location where personally identifiable information is kept).
     - [x] Use this file name structure (replace with RP number): [TWE: RP001: Intern Number Spreadsheet](https://docs.google.com/spreadsheets/d/1x7jbTW95InppT-Q2Z5OHuO3B9ErS9_MCR2twcshFFtY/edit?usp=sharing)
- [x] Log into Otter.ai using the 1password vault for Internship-UI/UX
- [x] Create a comment below in this issue on the steps that you took to transcribe each interview. Consider people who are completely unfamiliar with Otter.ai and write your steps so that someone with very little knowledge could replicate your steps.
- [x] Create the final transcription files and save them in the Google Drive folder for RP001. 
     - [ ] De-identify all transcription files and name them according to a unique identifying number (e.g., Intern # 1, Intern # 2, etc.).
     - [x] Use this file name structure (replace with RP number): `TWE: RP[Replace 000]: Transcript: [Replace TYPE OF PARTICIPANT] # 1`
- [x] Update RP001 Wiki page (See resources)
- [ ] Review with UX Lead
- [ ] Product sign-off
- [ ] UXR Lead to write a new issue template for Transcribing Interview Recordings based upon action items generated in this issue
- [ ] UXR Lead to move recordings and spreadsheet to secure drive

### Resources/Instructions
- [Wiki Page: Research Plan 1: IS21 Interns](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)
- [TWE: Template: Generic Spreadsheet](https://docs.google.com/spreadsheets/d/1yK7U_waj1xfx3KcdQ10uyaLvWCSVVpqLMLHvWonDWL4/template/preview)
- [Otter.ai](https://www.otter.ai)
- [1password](https://www.1password.com)
- [2021 interns' video recordings in the google drive ](https://drive.google.com/drive/folders/1R8sXXGrx47PNj2GpMSUIpMXYllAEgy19?usp=share_link).

**Comment by pandanista** [comment]
The following process is only applicable when the recordings are available. Since we have conducted the interviews via Zoom, the video recordings have been saved and are accessible in the Internship folder.

1. Locate the interview video recording (I.e. mp4 file) in the Google drive
2. Download the recording to a location you can easily upload to Otter.ai in a minute.
3. Go to Otter.ai, and log on to the account using the account and password info saved in Internship project’s 1Password.
4. Click on “Import” on the upper right corner of the interface once logged in.
5. Upload the video file, and let Otter.ai transcribe the file for you.
6. Once finished, download the .txt file.
7. Upload the .txt file to the corresponding folder of the interview of the Google drive. Viola!

**Comment by pandanista** [comment]
De-identified 2021 in the google drive (https://drive.google.com/drive/folders/1R8sXXGrx47PNj2GpMSUIpMXYllAEgy19?usp=share_link) and 2022 interview recordings in

**Comment by bradyse** [comment]
@pandanista 
Create new issue template based upon the steps detailed in this issue:
- [ ] Create a [blank issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=&template=blank-issue.md&title=)
- [ ] Copy and paste the comment from this [issue template draft](https://github.com/hackforla/internship/issues/311#issuecomment-1314509500)
- [ ] Modify draft so that Bonnie can test it on Wednesday

**Comment by bradyse** [comment]
@cmistillarte and @sophie-delsaux 

I unassigned you so that others could take this issue back up. If you left off in the middle of a transcript, could you update where you left off in a comment below?

**Comment by pandanista** [comment]
@adarosh Hi Angela! Welcome back from the break. We are very close to get the latest transcription issue template approved so we can keep the process consistent across the team. Once approved, we will update [the top comment](https://github.com/hackforla/internship/issues/324#issue-1416861426) so you can keep working on this issue. Will keep you posted.

Meanwhile, we are confirming everyone's interest and availability.  Please provide a new update to this issue if you have any. Thank you.

1. Progress: "What is the current status of your project? What have you completed and what is left to do?" - we know you just came back from break, please just summarize the progress from before then
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by pandanista** [comment]
@adarosh Just removed you from this issue for now, and we can pick up the things once you are back on the team.

**Comment by pandanista** [comment]
The transcribing template has been tested using RP001's interview sessions.
- The updated template for transcribing is #335  
- Testings have been done in #355 #476 #478 #479 #480 #481 
- We can close this issue as we have created a new issue for the template.
