### ISSUE TITLE
TWE: Update Google Drive Links to Wiki Pages

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#325]
### Overview
We need to update the individual Research Plan Wiki Pages with the appropriate Google Drive links, because we changed the RP Wiki Page Template. We need to do this so that UX researchers do not have to dig around in the Google Drive to find what they need. 

### Action Items
- [x] Look at the Resource called `Example Wiki Page with Google Drive links` to see how the updated template now includes information below Assets with the link to the Research by Type folder and link to the Research Plan folder.
- [x] Look at the Resource called `Wiki Research Template` to see how this update appears in the Markdown code.
- [x] Copy part of the Markdown code below `##Assets` that includes the new Google Drive link template information.
- [x] Update the each of Wiki Pages below by completing the following:
 _As you tick off each step, untick them when you tick off the Research Plan's wiki page in the list below. So that you can start fresh with the next wiki page._
     - [x] Look at the Roadmap info to see which Roadmap this Research Plan is cataloged under. This will tell you where to find the appropriate Research by Type folder in the Google Drive
     - [x] Click into the Google Drive link (in the Resources below) and find the appropriate Research by Type folder
     - [x] Click "Edit" on the Wiki page and paste the Markdown code below `##Assets``.
     - [x] Paste the Type folder link into the parentheses of the first link and replace the text in square brackets to indicate the type of research (e.g., `Type folder: [Mentor](https://drive.google.com/drive/folders/19I3g9sDrITthv0z4xV6ORuH1vhq80RQI?usp=sharing)`
     - [x] Click into the Google Drive type folder and find the appropriate Research Plan folder. Make sure that the link you copy is to the actual folder and not a shortcut link. If it is a shortcut link, alert the UX Research lead that there may be some misidentification on the Google Drive and pause the update on the research plan's wiki page until the folders are fixed.
     - [x] Paste the Type folder into the parentheses of the second link and replace the `###` in square brackets with the Research Plan number.
- [x] Update Each Wiki Page
     - [x] [Research Plan 1: IS21 Interns](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)
     - [x] [Research Plan 2: Hack for LA volunteers transferrable skills](https://github.com/hackforla/internship/wiki/Research-Plan-2:-Hack-for-LA-volunteers-transferrable-skills)
     - [x] [Research Plan 3: LinkedIn Recommendation](https://github.com/hackforla/internship/wiki/Research-Plan-3:--LinkedIn-Recommendation)
     - [x] [Research Plan 4: Hypothesis: HfLA Internship leads to stem retention](https://github.com/hackforla/internship/wiki/Research-Plan-4:-Hypothesis:-HfLA-Internship-leads-to-stem-retention)
     - [x] [Research Plan 5: Brand / website Audience Alignment](https://github.com/hackforla/internship/wiki/Research-Plan-5:-Brand---website-Audience-Alignment)
     - [x] [Research Plan 6: Intern Intake Interviews](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
     - [x] [Research Plan 7: Onboarding TWE team volunteers](https://github.com/hackforla/internship/wiki/Research-Plan-7:-Onboarding-TWE-Team-volunteers)
     - [x] [Research Plan 8: Mentor Intake Interviews](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)
     - [x] [Research Plan 9: Weekly Standup Surveys](https://github.com/hackforla/internship/wiki/Research-Plan-9:--Weekly-Standup-Surveys)
     - [x] [Research Plan 10: Weekly Intern Survey Assessing Mentorship](https://github.com/hackforla/internship/wiki/Research-Plan-10:-Weekly-Intern-Survey-Assessing-Mentorship)
     - [x] [Research Plan 11: Weekly LinkedIn Workshop Survey](https://github.com/hackforla/internship/wiki/Weekly-Research-Plan-11:-Weekly-LinkedIn-Workshop-Survey)
     - [x] [Research Plan 12: Intern Exit Interviews](https://github.com/hackforla/internship/wiki/Research-Plan-12:-Intern-Exit-Interviews)
     - [x] [Research Plan 13: Mentor Intake Survey](https://github.com/hackforla/internship/wiki/Research-Plan-13:-Mentor-Intake-Survey)
     - [x] [Research Plan 14: Mentor Exit Interviews](https://github.com/hackforla/internship/wiki/Research-Plan-14:-Mentor-Exit-Interviews)
     - [x] [Research Plan 15: Mentor Exit Surveys](https://github.com/hackforla/internship/wiki/Research-Plan-15:-Mentor-Exit-Surveys)
     - [x] [Research Plan 16: Intern Productivity Dashboard Survey](https://github.com/hackforla/internship/wiki/Research-Plan-16:-Intern-Productivity-Dashboard-Survey)
     - [x] [Research Plan 17: Productivity Dashboard Interviews](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
     - [x] [Research Plan 18: Weekly Feedback from Mentors](https://github.com/hackforla/internship/wiki/Research-Plan-18:-Weekly-Feedback-from-Mentors)
     - [x] [Research Plan 19: Technical Skills of Incoming Interns](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns)
     - [x] [Research Plan 20: Intern Interaction with HfLA Teams](https://github.com/hackforla/internship/wiki/Research-Plan-20:-Intern-Interaction-with-HfLA-Teams)
     - [x] [Research Plan 21: Personas, Reasons, Targets](https://github.com/hackforla/internship/wiki/Research-Plan-21:-Personas,-targets,-reasons)

### Resources/Instructions
- [Example Wiki Page with Google Drive links](https://github.com/hackforla/internship/wiki/Research-Plan-10:-Weekly-Intern-Survey-Assessing-Mentorship)
- [Wiki Research Template](https://github.com/hackforla/internship/wiki/Research-Wiki-Template)
- [Google Drive Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing)

### Markdown Text to Copy Below `##Assets` on Each Wiki Page
```
### Google Drive folders
- Type folder: [TYPE]()
- RP Folder: [RP###]()
```

**Comment by jessieliu1219** [comment]
Availability for this week: M-TH
My estimated ETA for completing this issue:

**Comment by jessieliu1219** [comment]
No Google Drive folder was found for RP 19 & RP 21.

**Comment by bradyse** [comment]
@jessieliu1219 
Thank you for your update and adding the Google Drive links to the other folders. I added the Google Drive folders (and their shortcuts) for RP19 and RP21.

Please continue to work on this issue. Once you have finished updating all the Google Drive links on the wiki, then tick all the boxes above to indicate that all the steps in this issue are now complete.

Great job!

**Comment by jessieliu1219** [comment]
all task finished
