### ISSUE TITLE
TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] Interview Recordings: Transcribe - THIS IS A TEST ISSUE FOR ISSUE 335

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#337]
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [x] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (**Mac:** ?+F or  **PC**: Ctrl+F). 
    Search in the issue title, in addition to this issue comment. Complete these steps in order.
        - Other Information 
             - [ ] Search for `[Replace`
             - [ ] Replace with whatever the keyword or information is asking for.
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies
 - [ ] Org rep has purchased a premium version of Otter.ai

### Overview
We need to transcribe the Intern Intake interview recordings for further conducting data analysis and insights generation on Intern [Replace RESEARCH GOALS].

### Action Items
 - [ ] The assignee gets access to the 1Password's Internship's UI/UX vault and training in how to use it.

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (# 1.01 link in Resources)
    - [x] Find relevant wiki page for RP006
    - [x] Copy the link for the wiki page.
    - [x] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
 - Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Type Folder (# 1.02 link in Resources)
    - [x] Open the Intern Folder
    - [x] Right-click on the RP006 folder and copy the link.
    - [x] Update Resource # 2.02 with the link you just copied. Place it into parentheses at the end of the line.
- Customize Resource for Spreadsheet with Participant Numbers
    - [x] Click on [TWE: Template: Interview Recording Tracking Sheet] (# 1.03 link in Resources)
    - [x] Click on "File" to "Make a Copy"
    - [x] Rename document `TWE: IS22: RP006: Intern Intake Recording Tracking Sheet`
    - [x] Click File > Move (or Move icon)
    - [x] Click the back arrow to access all your drives
    - [x] Click Shared drives > Internships > Internships > Research > Research by Type > Intern> folder for RP006
    - [x] Click "Move here"
    - [x] Click "Move" when it asks if you want to change ownership to a shared drive
    - [x] Click "Share" and copy link
    - [x] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
- Customize Resource for Interview Recording Folder
    - [ ] The interview recordings are inside the Internship's private drive, do the following to access them:
         - [x] Log into 1password (link # 1.04)
         - [x] Click on internship-UI/UX vault
         - [x] Click <img src="https://user-images.githubusercontent.com/37763229/202265799-5ec6b622-1b77-44cb-95fd-1f89eb05a195.png" width=150px> to see login info for internship@hackforla.org account
         - [x] Log into Google Drive using the login information
         - [x] Locate the uploaded recordings inside the Internship Project's personal drive (link # 1.05)
         - [x] Update Resource # 2.04 with the link to the recording folder. Place it into parentheses at the end of the line.
#### Update Participant Spreadsheet 
- [x] Open the Number Spreadsheet (link # 2.03)
- [x] Update the title in the header so that the title is the same as the file name
- [x] In Column A `Intern Number`, make sure the count of `Intern Number` matches with the number of participants in the recording folder, and delete or add extra rows as needed
- [x] In Column B `Recording Link`, copy and paste the link of each recording video from Resource # 2.04 for each participant's row
#### Transcribe Interviews with Otter.ai
- [ ] Download each recording from the Google Drive's recording folder to a temporary folder locally
- [ ] Log into 1password (link # 1.04)
- [ ] Click on internship-UI/UX vault
- [ ] Access Otter.ai from 1password
- [ ] Confirm you are on a paid plan at the time of transcribing (Otter.ai only allows 3 uploads for the free tier lifetime), complete the following
     - [ ] Click on “Import” on the upper right corner of the interface once logged in.
     - [ ] Upload the video file, and let Otter.ai transcribe the file for you.
     - [ ] Once finished, download the .txt file.
     - [ ] Upload the .txt transcription file into the corresponding recording folder for the participant (link # 2.04)
     - [ ] Rename each file folder with the aforementioned unique identifying number (e.g., Intern # 1, etc.).
     - [ ] Retrieve each transcript file URL in the recording folder on Internship private drive and store it in the matching row of the participants' unique identifying number in Column C `Transcription Link` (link # 2.03)
     - [ ] De-identify all transcription files
         - [ ] Replace the participants' names with their unique identifying number 
         - [ ] If they mentioned any specific issues they worked on, make sure to remove the issue numbers and rephrase the issues they worked on
     - [ ] Move the de-identified transcripts to the research plan's shared Google Drive folder (link # 2.02)
     - [ ] Rename each transcript according to the file naming convention (replace participant ID numbers): `TWE: IS22: RP006: Intake Transcript: Intern # 1`
     - [ ] Retrieve each de-identified transcript file URL in the corresponding research plan folder on Internship shared drive and store it in the matching row of the participants' unique identifying number in Column D `Transcription Link - de-identified` (link # 2.03)
- [ ] Update the wiki page for this research plan (link # 2.01)
- [ ] Review with UX Lead
- [ ] Product sign-off
- [ ] UXR Lead to check that recordings and spreadsheet are moved to secure drive

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Interview Recording Tracking Sheet](https://docs.google.com/spreadsheets/d/1aeUFd5tZQoJCriTzJc2L-L0KS7sXmwhveewb1dviX3I/template/preview)
1.04 [1password](https://start.1password.com/signin?l=en)
1.05 [Google private drive recording folder](https://drive.google.com/drive/folders/1ytcgb_j5Nsl6ZIhGUCeqQkKzgo2FohRS)
1.06 [Otter.ai](https://www.otter.ai)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan 006](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
2.02 [Google Drive Folder: RP006](https://drive.google.com/drive/folders/1nNA2Qwg3HQjBYvnL6aFOKDFciEtFvhg1?usp=share_link)
2.03 [Intern Intake Recording Tracking Sheet](https://docs.google.com/spreadsheets/d/1mhBbG5UxPxRGz3C3ao8sC6GO5fTQDCl5PK5MNJXeYxg/edit?usp=sharing)
2.04 [RP006 Interview Recording Folder](https://drive.google.com/drive/folders/1FoyhEzUgiQe7GoVcGHqIbr0ABP_FYZPu?usp=share_link)

**Comment by pandanista** [comment]
@priyatalwar This issue was created to test the issue template for issue #335. I am not sure why the dependency label was added. I am moving this to icebox for now since this has the dependency label.

**Comment by pandanista** [comment]
Closing this testing issue because it is not needed any longer.
