### ISSUE TITLE
Recruit a UX Researcher

### ISSUE THREAD

**Issue by sniux** [hackforla/internship#34]
### Overview
We are recruiting a UX researcher who will be working with various methodologies to analyze the various scopes for improvement in enhancing the experience of the interns we have recruited for the program. They will also be working on drafting hypotheses and finding actionable insights for the problem statements, that will solidify the establishment of the program.

### Action Items

- [x] Edit note
- [x] Post it in opportunities
- [x] Talk to potential UX researchers

### Research
https://github.com/hackforla/UI-UX/projects/2

**Comment by ExperimentsInHonesty** [comment]
#### Post a Volunteer Opportunity
---

**Project Name**: [Internship]

**Volunteer Opportunity**: [UX Researcher]

**Duration**: 1 week - ongoing

**Who to communicate your interest to**
- Slack channel link: #internship
- Slack name of person to contact in the channel : Snigdha or @sniux

[One Sheet for the Internship Project
](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/edit)

**Comment by ExperimentsInHonesty** [comment]
@sniux please add a link to our Slack channel https://hackforla.slack.com/archives/C01VAUPU788 and post this here https://github.com/hackforla/UI-UX/projects/2

**Comment by sniux** [comment]
Opportunity posted [here.](https://github.com/hackforla/UI-UX/projects/2#card-67150536)

**Comment by ExperimentsInHonesty** [comment]
Please post a link to the opportunity in the UI/UX channel

**Comment by sniux** [comment]
> @sniux Please post a link to the opportunity in the UI/UX channel

Posted [here.](https://hackforla.slack.com/archives/C017ESHSMNG/p1629387375083600)

**Comment by priyatalwar** [comment]
Next steps:
@Rabia2219 Will go to the UI/UX meeting and recruit directly

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar will write back to Eakyt in slack asking them if they are interested in joining the team or internship.  Explain difference, and also provide them link to https://www.meetup.com/hackforla/events/

@Rabia2219 will reword the posting to reduce words and add the text "This opportunity is for a team member to help us build out next summers internship program. "

**Comment by priyatalwar** [comment]
8/30 update: Just sent a slack message to Eakyt

Hi, just wanted to clarify that this is not for an internship since we are not accepting new interns at this time, but it is as a team member on this project. if you are still interested, please join one of these meetings https://www.meetup.com/hackforla/events and let Bonnie know about your interest.

**Comment by Rabia2219** [comment]
> @priyatalwar will write back to Eakyt in slack asking them if they are interested in joining the team or internship. Explain difference, and also provide them link to https://www.meetup.com/hackforla/events/
> 
> @Rabia2219 will reword the posting to reduce words and add the text "This opportunity is for a team member to help us build out next summers internship program. "

Updated [here](https://github.com/hackforla/UI-UX/projects/2#card-67150536)

**Comment by priyatalwar** [comment]
> > @priyatalwar will write back to Eakyt in slack asking them if they are interested in joining the team or internship. Explain difference, and also provide them link to https://www.meetup.com/hackforla/events/

I wrote her on 8/30 and still waiting to hear back.

**Comment by sniux** [comment]
9/2 update

@priyatalwar @Rabia2219 Justin Lee reached out to me for the UX researcher role - I am giving him the project overview.

**Comment by priyatalwar** [comment]
> 9/2 update
> 
> @priyatalwar @Rabia2219 Justin Lee reached out to me for the UX researcher role - I am giving him the project overview.

@sniux Sounds good. He reached out to me too. Can you please make sure he attends or has already attended an onboarding meeting prior to the Tuesday meeting? Thanks!

**Comment by priyatalwar** [comment]
@sniux We are all good since I just heard from him that he attended an onboarding meeting on Tuesday.

**Comment by priyatalwar** [comment]
@Rabia2219 Please feel free to close this issue if you think we have everything we need. Thanks.
