### ISSUE TITLE
TWE: Create Template Issue: Interview Session and Roll Call Table Template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#343]
### Overview
We need to create a template issue for Interview Session and Roll Call Table Template so that we have consistent, transparent, defined and self-supporting structure for people creating them.

### Action Items
- [x] Add to the Project Board
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.
- [x] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for
- [x] Create a draft of new template by copying the content block below to a comment on this issue, which will be known as our Draft
- [x] In your draft, Fill out the top part (called front matter) with the info it needs.  See the Resources section below for definition and example.
- [x] Define any Dependencies (or remove the dependency section)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] the links provided by the issue creator should be in the same order as the Action Items 
- [x] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking the WIKI Templates by role pages.  
  - [x] if there is a template
     - [x] Add a link to the template into the ` ### Resources`  section of your draft
  - [ ] if there is no template yet
    - [ ] put a placeholder into the` ### Resources`  section of the draft `[TWE: Template: [replace with name of type]]`
- [x] Get sign-off by product on the draft
- [x] Create the template issue on the repo
- [x] Add the link to related "Get started" button in the Resources section below.
- [x] Update the appropriate place in wiki for your template (see resources section)

### Resources/Instructions
Getting started button link for creating new issue using the ["REPLACE with name and link of template"] template on the "New issue" tab

#### WIKI Templates
- by role pages
  - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
  - [Design]
  - [Product]
  - [Engineering]
- default document templates, in case you don't have one yet can found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Content to copy for draft
```
Draft of template issue for [Replace NAME OF ISSUE TEMPLATE]
---
**name:** Template Issue: [Replace NAME OF ISSUE TEMPLATE]
**about:** [Replace]
**title:** TWE: Template Issue: [Replace NAME OF ISSUE TEMPLATE]
**labels:** 'feature: board / google drive / tools', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue keywords
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, click gear, choose "Repository," and choose Program Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
1.
2.
```
### Resources
<details>
<summary>Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>Front Matter Field example</summary>

- name: 'Research: Roadmap'
- about: The start of a new roadmap
- title: 'TWE: Research Roadmap [name of type]'
- labels: 'feature: research, feature: roadmap, milestone: missing, role: UI/UX research,
-   size: 0.50pt'
- assignees: ''
</details>

**Comment by ExperimentsInHonesty** [comment]
Draft of template issue for [Replace NAME OF ISSUE TEMPLATE]
---
**name:** Template Issue: [Replace NAME OF ISSUE TEMPLATE]
**about:** [Replace]
**title:** TWE: Template Issue: [Replace NAME OF ISSUE TEMPLATE]
**labels:** 'feature: board / google drive / tools', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue keywords
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, click gear, choose "Repository," and choose Program Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
1.
2.

**Comment by pandanista** [comment]
@ExperimentsInHonesty I've updated the roll call and session [template](https://docs.google.com/spreadsheets/d/1dmJJLaBDBiZWy4-dmdxG3XqP4OemR5aJTOScD_GsoLc/edit?usp=share_link) and this template issue's instructions in this [comment](https://github.com/hackforla/internship/issues/343#issuecomment-1371585413). 

Also, I've updated previous roll calI and session tables [(RP006](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit?usp=share_link), [RP012](https://docs.google.com/spreadsheets/d/14TMOmeYX2yHEyHqttzhq9cDlqeAllcwAa2q33HA-dCQ/edit?usp=share_link), [RP014](https://docs.google.com/spreadsheets/d/1CTAOQirQsoh5XWgAo0IN3Nd45TNXC-Ox3xqMWMX1j30/edit?usp=share_link)) 

I tested myself based on the instructions and didn't spot any issues. 

Let me know if you or anyone else spots anything. Thank you!

**Comment by cbutcher318** [comment]
[1/16 testing recording and notes](https://drive.google.com/drive/folders/1XzSEaiDjgbiVkyoJ366ywUtXX4FlOcIn?usp=share_link)

**Comment by cbutcher318** [comment]
Tested and updated
@pandanista  will listen to recording and ensure everything addressed

**Comment by cbutcher318** [comment]
@cbutcher318 tested in issue #350

**Comment by pandanista** [comment]
Tested on 1/30. All feedback has been incorporated and reflected in [the latest template](https://github.com/hackforla/internship/issues/343#issuecomment-1371585413).

**Comment by cbutcher318** [comment]
Tested on 1/31. Made a few minor edits.

**Comment by cbutcher318** [comment]
All open issues that need to be reviewed for this template can be found [here](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+roll+call+%2F+session+table%22+label%3A%22feature%3A+test%22)

**Comment by pandanista** [comment]
Closing this issue because the Interview Roll Call and Session Table template has been approved and created.
