### ISSUE TITLE
Create Naming Conventions for Research

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#347]
### Overview
We need to create naming convention for deidentification of data, so we can know who a person is without having their name on the issue 

### Action Items
- [x] Come up with a naming convention
- [x] Create a spreadsheet with definitions
    - [x] [ TWE: Naming Convention for Research Participants and UX Researchers](https://docs.google.com/spreadsheets/d/1z7rj27ypy9ypzL5F_Dy3zwn8KkXPVPpc5aiG3vay744/edit?usp=share_link)
- [x] Added the spreadsheet to the [TWE Wiki research guides template page](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates)    
- [x] Review with Product Lead
- [x] Product sign off
- [x] Add abbreviations for participant type and spreadsheet from this issue to relevant wiki pages

### Resources/Instructions
[Research Output Review](https://github.com/hackforla/internship/wiki/Research-Output-Overview)

#### Roles
I = intern
M = mentor
U = UX researcher
G = Guardians
HfLAWTM = Hack for LA Website Team Member
HfLAV = Hack for LA Volunteers (people either not on a team or not on the TWE or HfLA website team)
TWETM= TWE Team Members
P = Partners

#### Naming Convention
- Format: Research Plan Number - UXR  - interviewee
- Ex. RP020-u005-HfLAWTM006 which means Research plan 20, ux researcher 05, Hack for LA Website Team Member 006

**Comment by cbutcher318** [comment]
I = intern
M = mentor
U = UX researcher
Research Plan - Researcher interviewer - interviewee
Ex. RP020-u05-htm06
Research plan 20, ux researcher 05, team member 06

**Comment by pandanista** [comment]
@priyatalwar @ExperimentsInHonesty Created [the naming convention sheet](https://docs.google.com/spreadsheets/d/1z7rj27ypy9ypzL5F_Dy3zwn8KkXPVPpc5aiG3vay744/edit?usp=sharing). Saved the file to [the guides and how to folder](https://drive.google.com/drive/folders/1ec1rqosULEIdKUHwixHMumMj0P__-334?usp=share_link) on the shared drive and added it to the [TWE Wiki research guides template page](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates).

Let me know if you have any questions. Thank you!

**Comment by priyatalwar** [comment]
Thanks @pandanista.  I'll add it to our agenda for next week to review at our PM meeting.

**Comment by cbutcher318** [comment]
In last research lead meeting we decided that abbreviations for participant type will be added to relevant wiki pages, and will be linked to spreadsheet from this issue.

**Comment by pandanista** [comment]
All action items are done. I am closing this issue.

**Comment by priyatalwar** [comment]
> All action items are done. I am closing this issue.

@pandanista please make sure to unassign yourself before you close the issue. Thanks!
