### ISSUE TITLE
[TEST] TWE: IS22: RP020: HfLA Team Member Exit Interview Roll Call and Session Table: Create

### ISSUE THREAD

**Issue by cbutcher318** [hackforla/internship#349]
### Overview

We need to create an interview roll call and session table for RP020 so that we can keep track of who we are interviewing, when, and related links.

### Action Items
- [x] Click on "TWE: Template: Interview Roll Call and Session Table" (Resources 1.03)
- [ ] Click on the Use Template button to save it to your own drive
- [ ] Customize both the Training Roll Call Table and the Session Table sheets
    - [ ] Use Search/Replace (**Mac:** ?+F or **PC**: Ctrl+F) to search for `[Replace` in order to replace the keyword strings (including text and the brackets) below with the appropriate values in both sheets (You will need to manually type in each replacement, ie., no "search and replace", in cells A1 on "Training Roll Call Table" tab, and cells A1 and C2 in "Session Table" tab)
        - Year (ie., YY)
            - [ ] Replace with `22`
        - Research Plan Number (ie., 000)
             - [ ] Replace with `020`
        - Type of Participant
            - [ ] Replace with `HfLA Team member` 
        - Type of Interview
            - [ ] Replace with `Exit`
- [x] Rename the file name by removing `Template` and replace the `[Replace` strings with appropriate information ![Screenshot 2023-01-09 at 2 49 52 PM](https://user-images.githubusercontent.com/57029070/211424282-e5a501d2-6c42-4a8d-8645-31f9baca59af.png)
- [x] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder
    - [x] Click File > Move (or Move icon)
    - [x] Click the back arrow to access all your drives 
    - [x] Click Shared drives > Internships > Internships > Research > Research by Type > HfLA Team member> folder for RP020
    - [x] Click "Move here"
    - [x] Click "Move" when it asks if you want to change ownership to a shared drive
    - [x] Click "Share" and copy link
    - [x] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.

####

- Update Wiki
  - [ ] Click on Resources 1.01 to open Wiki: Research Output Overview page
  - [ ] Select RP020 wiki page
  - [ ] Edit wiki page
  - [ ] Update "Interview recordings & Transcripts" by adding link to Roll Call Table and Session Table (resource 2.03)
  - [ ] copy link to RP020 wiki page and update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
- [ ] Open RP020 Google Drive folder (look under "Assets" in RP020 wiki page); copy link and update Resource # 2.02 with the link you just copied. Place it into parentheses at the end of the line.
- [ ] Check if the "Roll Call and Session Table" (resource 2.03) spreadsheet you just created is saved in the correct research plan folder on Google drive (resource 2.02) 
- [ ] Review with UX Lead
- [ ] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1dmJJLaBDBiZWy4-dmdxG3XqP4OemR5aJTOScD_GsoLc/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan 020]
2.02 [Google Drive Folder: RP020]
2.03 [TWE: IS22: RP020: HfLA Team member Exit Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1OdItAQY7Ep_q8U76gWZrBbS7tRfV37dVTAtZE4HQ4lw/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@pandanista  I have removed myself from this issue, this is one of the issues that requires to reconciled now that we have a template.

Reconciliation consists of making sure we didnt make duplicate assets, and if anything needs to get removed from the wiki, or if the item that got made can be kept, etc.

**Comment by pandanista** [comment]
Closing the issue for testing #343 as we checked and cleared out all the tests, wiki pages, and assets.
