### ISSUE TITLE
Interview Sakari

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#35]
### Overview
We need to interview Sakari so that we can analyze the results of the program from the participants perspective

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [x] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder (Bonnie) and place link to recording in resources

### Resources/Instructions
[Interview notes](https://docs.google.com/document/d/15RI126KEeUqycfGUClKT3Q-xFZScwHuMz8KsYxEnMns/edit)
[Sakari folder](https://drive.google.com/drive/folders/1GfQ_jkQolvP52xt8zqoeg-0QJoAh4vLa?usp=sharing)
[Sakari's recording](https://drive.google.com/file/d/1-8l4ue0SN9hotCgKwhNCGk1foiN-HLWv/view?usp=sharing)
[Transcript](https://drive.google.com/file/d/1yvy8Oo-h_tvsWD7vUILSBeQYovcb-XjT/view?usp=sharing)
Notes & Insights TBA

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty I still haven't seen an acceptance from Sakari for our 9:10 am meeting. I messaged him on slack, but he did not respond. Were you able to confirm?

**Comment by priyatalwar** [comment]
I have uploaded the recording and transcript. This issue will be closed and the analysis done on another issue
