### ISSUE TITLE
[test] TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings: Transcribe

### ISSUE THREAD

**Issue by dionw412** [hackforla/internship#351]
#### Instructions for creating this issue
The person who creates this issue should use links in the section "Resources for creating this issue" (i.e., 1.01, 1.02, etc.) to customize this issue.
- Customize the issue
    - [ ] Open the "Research Overview" wiki page (Resource 1.01)
    - [ ] Choose the appropriate research roadmap or research plan folder (ie., RP###) on the wiki page 
    - [ ] Gather the information on the wiki page and in research roadmap or research plan to customize this issue
    - [ ] Copy and paste entire template into text editor (ie., "TextEdit" on _Mac_, "Wordpad" on _PC_)
    - [ ] Use Search/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for `[Replace` in order to replace the keyword strings (including text and the brackets) below with the appropriate values in the text body 
        - Year 
            - [ ] Replace research year (ie., "22" for 2022) with `[Replace YY]` 
        - Research Plan Number
             - [ ] Replace the research plan number (ie., "001" for RP001) with `[Replace 000]`
        - Type of Participant
            - [ ] Replace the participant type (ex., "Intern") with `[Replace TYPE OF PARTICIPANT]`
        - Type of Interview
            - [ ] Replace the type of interview (ex., "Exit") with `[Replace TYPE OF INTERVIEW]`
    - [ ] Copy and paste the edited template from text editor back into Github Issue, replacing all original text
    - [ ] Re-check all the checkboxes above if they are unchecked after copying and pasting the edited template
    - [ ] Copy and paste `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings: Transcribe` into the issue title
- Customize the issue settings (located in right sidebar)
    - [ ] Under Assignees, assign a Researcher if it has been determined. Otherwise, leave it blank.
    - [ ] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Research: RP[Replace 000]`
    - [ ] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Participant Type: [Replace TYPE OF PARTICIPANT]`
    - [ ] Remove the `Research: 000: missing` and `Participant Type: missing` labels
    - [ ] Under Projects, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose "Repository," and choose Program Management
    - [ ] Add the milestone by choosing gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png) and choosing "Research Analysis"
    - [ ]  Remove the label `milestone: missing`

- Customize dependencies 
    - [ ] If you know of dependencies, add them below (a dependency is any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] If all the checkboxes above are completed and the issue is ready for assignment and work, delete all text above "Overview" (heading below). i.e., the issue assignee will never see this part

### Dependencies    /* After second thought, YO decided to leave the dependencies here because: 1. once the issue is created, there is a possibility that there is no assignee, and the UX lead needs to ask the admin of HfLA to add the assignee once decided to the Internship UX vault; 2. we only pay for otter.ai when needed, so UX lead needs to double check on the plan.*/    
 - [ ] Org rep has purchased a premium version of Otter.ai
 - [ ] UX Lead needs to ask admin to add the team member working on this issue to the 1Password internship-UX's vault

### Overview
We need to transcribe RP[Replace 000]'s [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] interview recordings so that we can move on to the data analysis and insights generation phase. 

#### Customize Resource Links 
- Customize Resource for Wiki Page Link
    - [ ] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [ ] Find relevant wiki page for RP[Replace 000]
    - [ ] Copy the link for the wiki page.
    - [ ] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
 - Customize Resource for this Research Plan's Google Drive Folder
    - [ ] Open the Google Drive's Research by Type Folder (Resources  # 1.02)
    - [ ] Open the [Replace TYPE OF PARTICIPANT] Folder
    - [ ] Right-click on the RP[Replace 000] folder
    - [ ] Choose "Get Link" and "Copy link"
    - [ ] Update Resource # 2.02 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for Spreadsheet with Participant Numbers
    - [ ] Choose "TWE: Template: Interview Recordings and Transcriptions Tracking Sheet" (Resources # 1.03 link)
    - [ ] Choose "USE TEMPLATE" to make a copy of the document
    - Rename the file by following the steps
        - [ ] Copy `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings and Transcriptions Tracking Sheet`
        - [ ] Choose File > Rename to paste the copied new file name
    - [ ] Copy `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings and Transcriptions Tracking Sheet` 
    - [ ] Choose Edit > Paste special to paste the new title into the title of the sheet (Row 1)
    - [ ] Copy `[Replace TYPE OF PARTICIPANT] Number`
    - [ ] Choose Edit > Paste special to paste into Cell A2
    - [ ] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder (Resource 2.02)
        1. Choose File > Move (or Move icon)
        2. Choose the back arrow to access all your drives
        3. Choose Shared drives > Internships > Internships > Research > Research by Type > [Replace TYPE OF PARTICIPANT]> folder for RP[Replace 000]
        4. Choose "Move here"
        5. Choose "Move" when it asks if you want to change ownership to a shared drive
        6. Dismiss the notification that says the file in now in the shared drive
    - [ ] Choose "Share" and copy link
    - [ ] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for Interview Recording Folder stored on the Internship's `My Drive` 
    - [ ] Log into 1password (Resources # 1.04) 
        - [ ] If this is your first time logging into Internship's Google account, please refer to the guide linked in Resources # 1.04.01 
    - [ ] Choose internship-UI/UX vault
    - [ ] Choose <img src="https://user-images.githubusercontent.com/37763229/202265799-5ec6b622-1b77-44cb-95fd-1f89eb05a195.png" width=150px> to see login info for internship@hackforla.org account
    - [ ] Follow the instructions linked in Resources # 1.04.01 to finish logging in 
    - [ ] Access `My Drive` by clicking on Drive in Google Apps under internship@hackforla.org's account
     <img width="150" alt="Screenshot 2023-01-25 at 3 38 42 PM" src="https://user-images.githubusercontent.com/57029070/214717943-313bd8c3-706b-4883-b0cb-95b154965e57.png">
    - [ ] Locate the uploaded recordings for RP[Replace 000] inside the folder `TWE Interview Recordings by Plan #` in the Internship Project's private drive (Resources # 1.05)
    - [ ] Update Resource # 2.04 with the link to the recording folder for RP[Replace 000]. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### Update Participant Spreadsheet 
- [ ] Open the Number Spreadsheet (Resources # 2.03)
    - [ ] Double check if the title in the header is the same as the file name. If not, please edit the file name the same as the header.
- [ ] Open `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table` inside `Google Drive Folder: RP[Replace 000]` (Resources # 2.02)
- [ ] Identify the highest `[Replace TYPE OF PARTICIPANT]` number in the "Session Table" tab of `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table` 
- [ ] In the `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings and Transcriptions Tracking Sheet`(Resource # 2.03), delete or add extra rows beyond the highest [Replace TYPE OF PARTICIPANT] number found in the "Session Table" tab of `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table` 
- [ ] Make sure each recording video file in the folder labeled Resource # 2.04 is named as `RP[Replace 000]-UX Researcher Abbreviation###-[Replace TYPE OF PARTICIPANT] Abbreviation###`
    -[ ] If not, please complete issue ### to rename the recording files first before taking any more actions
- [ ] Open the spreadsheet named `TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recording Upload Form (File responses)` inside `RP[Replace 000] Interview Recording Folder` (Resources # 2.04)
- [ ] Identify the [Replace TYPE OF PARTICIPANT] number in Column D, "2. [Replace TYPE OF PARTICIPANT] #"
- [ ] Copy the recording link in Column F, which says "4. Please upload the recording file..."
- [ ] Paste the link of each recording video into the matching participant's cell in Column B `Recording Link` of Resources # 2.03

#### Transcribe Interviews with Otter.ai
- [ ] Download each recording from the Google Drive's recording folder to a temporary folder locally
- [ ] Log into 1password (Resources # 1.04)
- [ ] Choose internship-UI/UX vault
- [ ] Access Otter.ai from 1password
- [ ] Confirm you are on a paid plan at the time of transcribing (Otter.ai only allows 3 uploads for the free tier lifetime)
- [ ] Complete the following steps using Otter.ai:
     - [ ] Choose “Import” on the upper right corner of the Otter.ai interface once logged in.
     - [ ] Upload the video file, and let Otter.ai transcribe the file for you.
     - [ ] Once finished, download the .txt file.
     - [ ] Upload the .txt file into the corresponding recording folder (Resources # 2.04)
     - [ ] Rename each .txt transcript file using the following format:
          - [ ] `RP[Replace 000]-UX Researcher Abbreviation###-[Replace TYPE OF PARTICIPANT] Abbreviation###`
              - An example looks like this: `RP006-U007-I001.txt`, which means this is an interview transcript for research plan 006, conducted by UX Researcher 007, and the interviewee is Intern 001
     - [ ] Retrieve each transcript file URL in the recording folder on Internship private drive (Resources # 2.04) and store it in the matching participant's cell in Column C `Transcription Link` (Resources # 2.03)
- [ ] Delete the local temporary folder with recording files from your device

#### De-identify all transcript files
- Prepare for de-identification by converting the .txt files into Google docs
    - [ ] Open a .txt transcript in Column C `Transcription Link` (Resources # 2.03)
    - [ ] Choose `Open with Google Docs` <img width="174" alt="Screenshot 2023-01-06 at 11 04 38 AM" src="https://user-images.githubusercontent.com/57029070/211081813-b49a22f4-1de2-4a5f-a10a-e7c7686ae1d0.png">  
    - [ ] A Google Doc is generated in a new window with the same .txt file name
    - [ ] Choose File > Rename
    - [ ] Rename the Google doc in the following format: 
        - [ ] `De-identified Interview Transcript-RP[Replace 000]-UX Researcher Abbreviation###-[Replace TYPE OF PARTICIPANT] Abbreviation###`
            - An example looks like this: `De-identified Interview Transcript-RP006-U007-I001`
- [ ] Move the renamed transcripts in Google doc format to the corresponding research plan's shared Google Drive folder (Resources # 2.02)    
    1. Choose File > Move (or Move icon) 
    2. Choose the back arrow to access all your drives
    3. Choose Shared drives > Internships > Internships > Research > Research by Type > [Replace TYPE OF PARTICIPANT]> folder for RP[Replace 000]
- [ ] Check if there is a folder named `RP[Replace 000] De-identified Transcripts` in the RP[Replace 000] folder (Resources # 2.02)    
    - [ ] If not, choose "New folder" icon  <img src="https://user-images.githubusercontent.com/57029070/211088373-c8af45cc-488d-4e80-a367-7c8b483737b3.png" width=35px>
        - [ ] Create a new folder named `RP[Replace 000] De-identified Transcripts`, and choose the blue checkmark.
            - For example,  <img width="174" alt="Screenshot 2023-01-06 at 11 44 27 AM" src="https://user-images.githubusercontent.com/57029070/211088840-c4f66b7d-1f9b-4749-8adb-dda0a9de0e88.png">
    - [ ] If yes, then choose the `RP[Replace 000] De-identified Transcripts` folder, and choose "Move here"
- [ ] Choose "Move" when it asks if you want to change ownership to a shared drive 
- [ ] Choose "Share" and copy link 
- [ ] Paste the file URL in the matching participant's cell in Column D `Transcription Link - de-identified` (Resources # 2.03)
- Search in the transcript and make edits to de-identify any personal information
    - [ ] Replace the participants' names with their participant number, i.e. I001
    - [ ] Replace any identifiable information in the interview with non-identifiable terms. For example, if they mentioned someone's name, we should use peers, mentors, manager, etc. instead based on their relationships with that person
    - [ ] If they mentioned any specific issues they worked on, make sure to remove the issue numbers and rephrase the issues they worked on

####
- [ ] Update the wiki page for this research plan (Resources # 2.01)
- [ ] Review with UX Lead
- [ ] Product sign-off
- [ ] UXR Lead to check that recordings and spreadsheet are moved to secure drive

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1aeUFd5tZQoJCriTzJc2L-L0KS7sXmwhveewb1dviX3I/template/preview)
1.04 [1password](https://start.1password.com/signin?l=en)
1.04.01 [Guide: Log into a Google Account with 2-Step Verification Using 1Password](https://docs.google.com/document/d/1hL3gYqoV6EWl4bUa2VYLgq0N__CjTvSw4Da2M4x2Hxk/edit) If this is your first time logging into Internship's private drive, please follow the instructions to log in.
1.05 [Google private drive recording folder](https://drive.google.com/drive/folders/1ytcgb_j5Nsl6ZIhGUCeqQkKzgo2FohRS?usp=share_link)
1.06 [Otter.ai](https://www.otter.ai)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan [Replace 000]]
2.02 [Google Drive Folder: RP[Replace 000]]
2.03 [TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Recordings and Transcriptions Tracking Sheet]
2.04 [RP[Replace 000] Interview Recording Folder]

**Comment by pandanista** [comment]
Hi Dionne, appreciate the feedback! However, I couldn't tell which part have been tested since no box were checked and certain parts hasn't been updated either, but I assume you tested the whole thing.

Also, were the `[Replace YY]` and `[Replace 000]` not clear in terms of the number of the digits? YY means only 2 digits for the year, 000 means 3 digits for research plan. So, for example, the name of a file should be `TWE: IS22: RP014: xxxxxx` instead of the following
 ![Screenshot 2023-01-20 at 6 09 12 PM](https://user-images.githubusercontent.com/57029070/213839350-97a97ccc-bb99-4704-af6c-68d6b27249ec.png)

Just going over your comments to reflect the edits I have made on the template.
 (need to tell person to reference research plan on wiki page) - edited the template in #335 by adding the following section
![Screenshot 2023-01-20 at 5 50 39 PM](https://user-images.githubusercontent.com/57029070/213835730-74f63c6d-9fe6-42ca-9cf4-217ad34c28d8.png)

(not clear what text to replace when looking at research plan) - Not sure how to make it more obvious since the year is reflected on the wiki page's roadmap document
![Screenshot 2023-01-20 at 5 21 28 PM](https://user-images.githubusercontent.com/57029070/213832243-1a1d2be0-4c41-4845-836b-edcb8015613d.png)

(specify what type of interview) - Not sure what you mean. Did you check out the wiki, folder on google drive, and the research plan title? They all specified the type of interview.
![Screenshot 2023-01-20 at 5 33 57 PM](https://user-images.githubusercontent.com/57029070/213833128-c83d93ed-d482-4f5c-bc7a-0f74f49c964c.png)
![Screenshot 2023-01-20 at 5 34 39 PM](https://user-images.githubusercontent.com/57029070/213832805-6578e436-93c9-4959-81a8-bd64b89dd7d5.png)
![Screenshot 2023-01-20 at 5 34 25 PM](https://user-images.githubusercontent.com/57029070/213832875-cb4a93e2-9941-4d67-9cd6-46612742c485.png)

(suggest to copy and paste from text editor into issue) - Added "- [ ] Copy and paste the edited template from text editor back into Github Issue, replacing all original text" in #335 

(copy and paste title for row 1 and paste into google foem file to remove template from title) (one check box for rename the file, one check change name title in row 1) - edited based on the feedback in #335 

(make order more clear) - not sure what it means since 1.05 is in order in the resources section

(file name not updated, not sure how to rename file) - Ummm. Not sure if you have read the instructions and examples listed right below. If the instructions are not clear to you, please feel free to edit them. But to avoid any confusion, I removed "in the format mentioned above" and added "by following the steps below" in #335 .
