### ISSUE TITLE
[Test] TWE: IS[Replace YY]: RP[Replace 000]: Presentation Slide Deck: Create

### ISSUE THREAD

**Issue by cbutcher318** [hackforla/internship#352]
### Dependencies
- [ ] Data analysis has been completed (link the issue that is tracking the analysis) 

### Overview
We need to create a presentation slide deck for IS22 Research Plan 017 to present the research findings and insights to all internal and external stakeholders. 

### Action Items
**Customize Resource Links**
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (# 1.01 link in Resources)
    - [x] Find relevant wiki page for RP017
    - [x] Copy the link for the wiki page.
    - [x] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
 - Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive Folder called Research by Plan # and Name (# 1.02 link in Resources)
    - [x] Right-click on the RP017 folder and copy the link.
    - [x] Update Resource # 2.02 with the link you just copied. Place it into parentheses at the end of the line.
- Customize Resource for Slide Deck Presentation
    - [x] Click on the TWE template called Presentation Slide Deck (# 1.03 link in Resources)
    - [x] Click on "Use Template"
    - [x] Rename document `TWE: IS22: RP017: Research Analysis Presentation`
    - [x] Click File > Move (or Move icon)
    - [x] Click the back arrow to access all your drives
    - [x] Click Shared drives > Internships > Internships > Research > Research by Plan # and Name > folder for RP017
    - [x] Click "Move here"
    - [x] Click "Move" when it asks if you want to change ownership to a shared drive
    - [x] Click "Share" and copy link
    - [x] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.

**Review Research Plan Documentation**
- Review wiki page
    - [ ] Briefly review all wiki documentation related to this type of research.
- Review the Research Plan Google Doc and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
    - [ ] Review the brief summary about the project/product.
    - [ ] Review the overall goals and/or objectives of the type of research.
    - [ ] Review the summary of the target participants.
    - [ ] Review research framework and methodologies.
    - [ ] Review existing research analysis templates
    - [ ] Review research findings and insights 
- Create the slide deck
    - [ ] Identify the narrative & storytelling that will best suit the research findings
    - [ ] Create presentation slides for the following categories
        - [ ] Project Introduction
        - [ ] Timeline
        - [ ] Types of stakeholders
        - [ ] Overview of research conducted
        - [ ] Research methods used
        - [ ] Data Collection
        - [ ] Data Analysis
        - [ ] Overview of research findings and insights
        - [ ] Research Impact 
        - [ ] Next Steps for the research
- Review with Team
    - [ ] Review with UX Research Lead
    - [ ] Product Sign-off
    - [ ] Update this research plan's wiki page with the link to the slide deck (link # 2.01)
    - [ ] Present at UXR Team Meeting

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [TWE: Slide Deck Template](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan 017](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
2.02 [Google Drive Folder: RP[000]](https://drive.google.com/drive/folders/1QJ-5eqtdYTPJZuoN51IcpG4ORGUeEMgZ?usp=share_link)
~2.03 RP[000] Synthesis [Replace TYPE OF DOCUMENT (e.g., Spreadsheet, FigJam, Miro]~
2.04 [IS22: RP017: Research Analysis Presentation](https://docs.google.com/presentation/d/1lVU6P-n7ZTVZdoItBZvhUxL5mM-3xTZdOv7GrFnNMHg/edit?usp=sharing)

**Comment by cbutcher318** [comment]
Stopped at "Review Research Plan Documentation" because of confusion about moving forward.

**Comment by bradyse** [comment]
Hi @cbutcher318 , I took a peek at your issue, and one reason why you probably couldn't move forward is because we don't have any TWE Team Member research completed. I recommend that you test it out on one of the research plans that we have the data analysis completed (see dependency). I hope that we can meeting soon!

**Comment by pandanista** [comment]
A new testing issue #475 has been created for re-testing. Closing this issue since it is outdated.
