### ISSUE TITLE
Formatting deck for printing

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#357]
### Overview
Slide deck formatting and/or settings need to be adjusted so the slides will print in full page.

### Action Items
- [x] Choose `current slide template` (resource 1.01)
- [x] Choose `Use Template` to create a new copy of the template
- [x] Change the page size to printer safe letter size
    1. Choose `File`
    2. Choose `Page Setup`
    3. From the drop-down menu, choose `Custom`
    4. Set the page dimensions to `10.5 x 8 inches` (or use your best judgement)
    5. Choose Apply
- [x] Reformat the template
    - Review each slide and reformat the elements as necessary 

### Moving the file
- [x] Move your edited copy into "Communication Guide", "Templates" folder (resource 1.02)
    1. Choose File > Move (or Move icon)
    6. Choose the back arrow to access all your drives
    7. Choose Shared drives > Internships > Internships > Communications Guide > Templates
    8. Choose "Move here"
    9. Choose "Move" when it asks if you want to change ownership to a shared drive
    10. Dismiss the notification that says the file is now in the shared drive
    
### Updating new resource link here
  - [x] Update Resource `copy of slide Template` link
    1. Choose "Share" button in your copy of the slide template
    2. Choose "Copy Link"
    3. Edit this issue
    4. Update Resources by pasting the link inside the parentheses at the end of the line and name it 2.01
    5. Choose 'Update comment'
    
  
### Testing and Sign-off
- [x] Print to PDF to evaluate if changes are properly formatted
- [x] Send to PM team to print test
- [x] Product sign-off

### Resources/Instructions
1.01 [current slide template](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/template/preview)
1.02 [Communication Guide > Templates Google Drive Folder](https://drive.google.com/drive/folders/1dzYpEI8I3xgHvLVy2-L6NOK2bbMG_T6O)
2.01 [copy of slide Template](https://docs.google.com/presentation/d/1LCvI_wv80DnCH2TQzd44jDDVsNhOdoiICWyA6OxM04w/edit?usp=sharing)

**Comment by cbutcher318** [comment]
Just tested the current template and print looks fine on my computer. Might be a local settings issue.

**Comment by priyatalwar** [comment]
@cbutcher318 thats great. Thanks! Can you please share a screenshot to test printout? We can review tomorrow and decide to close the issue then.

**Comment by cbutcher318** [comment]
Adjusting instructions: Need to reformat page size of the slides to print in full page.

**Comment by cbutcher318** [comment]
Good work so far. Can you adjust the formatting to account for the shifting of objects.

**Comment by ExperimentsInHonesty** [comment]
The half circle shapes that are part of the background need to be moved down or redesigned so that they continue to the bottom of the slide

The logo (bottom right) is too height

On slide 9 you can see the timer text and emoji.  That is the lowest any text or logo should go.  Shapes are exempted from this because it doesn't matter if they flow off the page

**Comment by bryannalim** [comment]
just reviewed comments on slides 1 and 9 & edited shapes on slide template

**Comment by bryannalim** [comment]
moved logo down on template/all slides to match "⏰ =4+11=15 min" (lowest pt text)
