### ISSUE TITLE
Interview Mateo

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#36]
### Overview
We need to interview Mateo so that we can analyze the results of the program from the participants perspective

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [x] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder (Bonnie) and place link to recording in resources

### Resources/Instructions
[Interview notes]
[Mateo's folder](https://drive.google.com/drive/folders/1P1eLdZOuXjI6V6X9saUOuWpEbPRNx-3g)
[Transcript](https://drive.google.com/file/d/1Yu-2PQsl5QdJAuFNq-lTdCscuY8z7ey4/view?usp=sharing)
[Recording](https://drive.google.com/file/d/1x05PjzYSbmgGgqb5Uuc55bXQ43KfUTpm/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Bonnie Sent this message via email.
Dear Mateo,

I can do the 24th.  I would like to both finish out our work on your linkedin and get you interviewed.  I know Snigdha sent you the questions but we really need to do the interviews in person so that they all are the same.  Sonia and I can do both on that day after 2.  She would go first and I could see you at 3.  Does that work?

Bonnie

**Comment by ExperimentsInHonesty** [comment]
In preparation for the interview @Rabia2219 please watch prior interviews and read through the questions.  If you are unclear about anything reach out to Snigdha

**Comment by Rabia2219** [comment]
@sniux Hey Snigdha, just wanted to ask if I could streamline the layout of the Interview issues? There are different items at the end, for example: 

In Mateo's we have
[Interview notes]
[Mateo's folder]
Transcript
Recording

For Sophia and Jason, we have:

Sophia's Recording
Notes & Insights (TBA)

If you can let me know which format is relevant, I can go ahead and fix it. 
Do we also need to make folders for the rest of the interns?
Thank you!

**Comment by sniux** [comment]
@Rabia2219 yes go ahead with your version.

**Comment by ExperimentsInHonesty** [comment]
Interview just happened today at 2pm

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
Hi Bonnie, we need the recording for Mateo's interview. Thanks.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
Hi Bonnie,
We are missing Mateo's interview recording and transcript needed to complete the synthesis. Thanks.

**Comment by ExperimentsInHonesty** [comment]
@sniux I have uploaded the Mateo recording link is above

**Comment by priyatalwar** [comment]
@sniux @ExperimentsInHonesty Closing this issue since we have everything we need.

**Comment by Rabia2219** [comment]
Just putting this here as an observation:
Check dates in the [Intern Interview Sheet](https://docs.google.com/spreadsheets/d/1j7DJltYPago3pZy_M-H_H_jBwOrBu6AN2LavTWTy2JU/edit#gid=1530446346) as they were filled in by Snigdha and are according to her time zone.
