### ISSUE TITLE
EasyRetro Q&A boards clean-up and consolidation

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#362]
### Overview
We need to consolidate all the Q&As collected from previous EasyRetro boards so we can reference those Q&As for future interview trainings and interview sessions.

### Action Items
- [x] UX Lead asks admin to add the team member working on this issue to the 1Password's Intership-UI/UX vault 
#### Create a Google Doc for consolidating all the Q&A 
- [x] Go to the "TWE Google Doc Template" in Resources 1.01
- [x] Choose `USE TEMPLATE`
- [x] A Google doc has been created in your Drive
- [x] Copy
```
TWE: Consolidated EasyRetro Q&A
```
- [x] Paste the texts you copied into the top field <img width="200" alt="Screenshot 2023-02-15 at 1 18 34 PM" src="https://user-images.githubusercontent.com/57029070/219168926-894f7578-a25e-41ab-bdfb-3ba4ba4c8f49.png">
- [x] Paste the texts you copied to replace the`TITLE OF DOCUMENT` <img width="100" alt="Screenshot 2023-02-15 at 1 18 53 PM" src="https://user-images.githubusercontent.com/57029070/219169553-b712c158-cae5-4489-9379-b477b648c53e.png">
- [x] Move the file into the Internship's shared drive in the "Templates" Google Drive folder
        1. Choose File > Move (or Move icon)
        2. Choose the back arrow to access all your drives 
        3. Choose Shared drives > Internships > Internships > Research > Guides and How-Tos
        4. Choose "Move here"
        5. Choose "Move" when it asks if you want to change ownership to a shared drive
        7. Dismiss the notification that says the file is now in the shared drive
- [x] Choose `Share` 
- [x] Choose `Copy link`
- [x] Choose `Get Link`
- [x] Update Resources # 2.01 by pasting the copied link inside parentheses at the end of the line
#### Customize the Google Doc structure
- [x] Copy `Header 1` and `Text sample` on the third page of the Google Doc <img width="60" alt="Screenshot 2023-02-15 at 1 40 57 PM" src="https://user-images.githubusercontent.com/57029070/219174584-c9b74fd9-0d97-476e-8c1f-c3f2746caac1.png">
- [x] Paste the texts you copied in a separate line twice, so it has three `Header 1` and `Text sample` in the doc <img width="100" alt="Screenshot 2023-02-15 at 1 39 39 PM" src="https://user-images.githubusercontent.com/57029070/219174322-3c596bd1-4969-4f8a-8214-f8acc1891a61.png">
- [x] Copy
```
Interview Instructions Q&A
```
- [x] Paste the texts you just copied into the first `Header 1` on the third page of the Google Doc 
- [x] Copy
```
Practice Interview Q&A
```
- [x] Paste the texts you just copied into the second `Header 1` on the third page of the Google Doc
- [x] Copy
```
Interview Q&A
```
- [x] Paste the texts you just copied into the third `Header 1` on the third page of the Google Doc
- [x] Delete `Header 2` and `Header 3` if the doc doesn't need those
#### Locate all the EasyRetro boards from previous interviews
- [x] In Shared Drive (Resources 1.02), conduct 2 searches using `EasyRetro` and `Easy Retro` respectively
- [x] Go through the docs and decks where `EasyRetro` or `Easy Retro` were mentioned
- [x] Identify the existing EasyRetro Q&A boards 
- [x] List each board's name under the subsection of Resources 2.02
- [x] Update the URL to each of the existing EasyRetro Q&A board inside parentheses at the end of the line in the subsection of Resources 2.02
- [x] Log into EasyRetro using 1Password to double check the existing boards /*YO logged in and only found 3 Q&A boards related to RP 6*/ 
    1. Log into 1password (Resources # 1.03)
    2. Choose internship-UI/UX vault
    3. Choose  <img src="https://user-images.githubusercontent.com/57029070/218932155-0cb0e653-8fe2-42ed-8d03-7758acc15239.png" width=180px> to see login info for EasyRetro account
    4. Go to EasyRetro website (Resources # 1.04)
    5. Log into EasyRetro with the [internship-ux@hackforla.org](mailto:internship-ux@hackforla.org) account using the login information in 1Password
    6. Double check if there is any board missing from the Resources 2.02 section. If so, add them to the 2.02 subsection. 
    
#### Customize the Google Doc content
- [x] Copy the questions and answers from EasyRetro boards that are under the interview instructions
- [x] Paste them into the `Text sample` of the `Interview Instructions Q&A` section of the Google Doc one by one
- [x] Copy the questions and answers from EasyRetro boards that are under practice interviews
- [x] Paste them into the `Text sample` of the `Practice Interview Q&A` section of the Google Doc one by one
- [x] Copy the questions and answers from EasyRetro boards that are under interview
- [x] Paste them into the `Text sample` of the `Interview Q&A` section of the Google Doc one by one
- [x] Read the Q&A you just copied and pasted and make sure they make sense
    - [x] Remove redundant questions
    - [x] Make edits to the questions and answers when they are not clear enough
- [x] Review with UX Lead
- [x] Product sign-off

#### remove dependency
- [ ] check off dependency on #361
- [ ] put #361 in the new issue approval column
- [ ] remove the dependency label

#### Resources for creating this issue
1.01 [TWE Google Doc Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/template/preview)
1.02 [TWE/Internship Shared Google Drive](https://drive.google.com/drive/folders/1z3I2SLQzYWBHIypNZO-sTdSO0A8c5pvt?usp=share_link)
1.03 [1password](https://start.1password.com/signin?l=en)
1.04 [EasyRetro](https://easyretro.io/)

#### Resources gathered during the completion of this issue
2.01 [TWE: Consolidated EasyRetro Q&A](https://docs.google.com/document/d/10tvWtCCIaxGisTUgGq4So4aQ5h7xhUNAz0E54pEjaM0/edit?usp=sharing)
2.02 EasyRetro Q&A boards
    2.02.01 [TWE: RP6: UXR Intern Intake Interview Instructions Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/3f10c27c-eb1f-4d6f-91ec-5ca0cc1b7c8e?sort=order)
    2.02.02 [TWE: RP12 UXR Intake Interview Instructions Q&A](https://easyretro.io/publicboard/dx4qnuQNQmNC6e3olk8CwCBeH7E3/e625f072-030c-4c6a-9c28-38cb1176932c)
    2.02.03 [TWE: RP6: UXR Intern Intake Interview Practice Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/f0870d06-9ad8-4f19-88f8-fd7d34c61c9b?sort=order)
    2.02.04 [TWE: UXR Interview Practice Q&A](https://easyretro.io/publicboard/dx4qnuQNQmNC6e3olk8CwCBeH7E3/a70b199b-df0c-4d67-a70b-9999e00ec236)
    2.02.05 [TWE: RP6: UXR Intern Intake Interview Clarifications](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/b3edd739-b713-4513-8480-88c9c03067ae)
    2.02.06 [TWE: UXR Interview Q&A](https://easyretro.io/publicboard/dx4qnuQNQmNC6e3olk8CwCBeH7E3/98396cdc-8699-45f1-8d53-9dadc9970e04)

**Comment by adarosh** [comment]
Provide Update
1. Progress: Created the Google Doc for consolidating the Q&A, customized document structure per instructions, and located 6 EasyRetro boards. I have added the Google Doc and EasyRetro board links under Resources. Need to complete search for any remaining boards and customize the document content.
2. Blockers: None
3. Availability: Approximately 6 hours
4. ETA: Next UXR meeting, 2/28/2023
5. Pictures (if necessary): N/A

**Comment by adarosh** [comment]
Provide Update
1. Progress: Created the Google Doc for consolidating the Q&A, customized document structure per instructions, and located 6 EasyRetro boards. I have added the Google Doc and EasyRetro board links under Resources. Need to complete search for any remaining boards and customize the document content.
2. Blockers: None
3. Availability: Approximately 6 hours
4. ETA: Next UXR meeting, 2/28/2023
5. Pictures (if necessary): N/A

**Comment by adarosh** [comment]
Progress Update:
1. Progress: Created the Google Doc for consolidating the Q&A, customized document structure per instructions, and located 6 EasyRetro boards. I have added the Google Doc and EasyRetro board links under Resources. Need to complete search for any remaining boards and customize the document content.
2. Blockers: None
3. Availability: Approximately 6 hours
4. ETA: Next UXR meeting, 2/28/2023
5. Pictures (if necessary): N/A

**Comment by adarosh** [comment]
Progress Update:

1.	Progress: Completed search on Shared Drive and EasyRetro account. Located all EasyRetro boards and added their links under Resources- there are 6 boards in total. Copied all questions and answers from boards. Will complete edit and customization of document over next week.
2.	Blockers: None
3.	Availability: Approximately 6 hours
4.	ETA: Week of 3/6/2023
5.	Pictures (if necessary): N/A

**Comment by adarosh** [comment]
Progress Update:

1. Progress: All questions and answers from EasyRetro boards have been moved to document. Content has been placed under relevant headings (Interview Instructions Q&A, Practice Interview Q&A, Interview Q&A). Removed redundant questions and made minor edits for clarity. Several questions did not have answers in EasyRetro- they have been flagged in the document.
2. Blockers: Document is ready for review with UX Lead
3. Availability: N/A
4. ETA: N/A
5. Pictures (if necessary): N/A

**Comment by pandanista** [comment]
@priyatalwar This one was reviewed at UXR meeting back in March. The deliverables looked good to me. Please take a look at the deliverables so we can close it.

**Comment by priyatalwar** [comment]
@pandanista please add the "ready for UX lead" label. Thank you.

**Comment by pandanista** [comment]
I will update the template. Releasing @adarosh from this issue, and will re-assign her and close the issue when the template is done.

**Comment by pandanista** [comment]
This is for cleaning up and consolidating post interview sessions for every RP. Will update the template.

**Comment by pandanista** [comment]
- I've reviewed the [consolidated, commonly asked questions and answers document](https://docs.google.com/document/d/10tvWtCCIaxGisTUgGq4So4aQ5h7xhUNAz0E54pEjaM0/edit?usp=sharing)
- I left two comments for Tim to see if he could help address those.
- Will close this issue after addressing those two comments.

**Comment by pandanista** [comment]
- Tim has helped addressed the remaining two comments in the document.
- [TWE: Consolidated EasyRetro Q&A](https://docs.google.com/document/d/10tvWtCCIaxGisTUgGq4So4aQ5h7xhUNAz0E54pEjaM0/edit?usp=sharing) now looks good. 
- Closing this issue now since we have cleared out EasyRetro dashboard and the Q&A document.
