### ISSUE TITLE
TWE: IS22: RP020: HfLA Website Team Members Exit Interview Roll Call and Session Table: Create

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#365]
### Overview
Create an interview roll call and session table for RP020 so that we can keep track of who we are interviewing, when, and related links.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Open relevant wiki page for RP020
    - [x] Copy the link for the RP020 wiki page.
    - [x] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
 - Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's "Research by Plan # and name" Folder (Resources # 1.02)
    - [x] Right-click on the RP020 folder 
    - [x] Choose "Get Link"  
    - [x] Choose "Copy link" 
    - [x] Update Resource # 2.02 with the link you just copied. Paste it inside parentheses at the end of the line.
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for RP020's Interview Roll Call and Session Table
    - [x] Open the template "TWE: Template: Interview Roll Call and Session Table" (Resources 1.03)
    - [x] Choose the "Use Template" button to save it to your own drive
    - Rename the file by following the steps:
        - [x] Copy 
        ```
        TWE: IS22: RP020: HfLA Website Team Members Exit Interview Roll Call and Session Table
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field    
       <img width="200" alt="Screenshot 2023-01-30 at 1 35 41 PM" src="https://user-images.githubusercontent.com/57029070/215600780-d8004229-17a3-409a-9d91-e4af9c904824.png">
       <img width="700" alt="Screenshot 2023-01-09 at 2 49 52 PM" src="https://user-images.githubusercontent.com/57029070/211424282-e5a501d2-6c42-4a8d-8645-31f9baca59af.png">
    - Customize both the Training Roll Call Table and the Session Table sheets
        - [x] Copy 
        ```
        TWE: IS22: RP020: HfLA Website Team Members Exit Interview Roll Call Table
        ```
        - [x] Choose "Training Roll Call Table" tab
        - [x] Choose the header row (row 1) 
        - [x] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text  <img width="700" alt="Screenshot 2023-01-30 at 12 13 20 PM" src="https://user-images.githubusercontent.com/57029070/215585369-4ddfaf59-ea1a-41e4-adeb-13911ecba5bc.png">
        - [x] Copy 
        ```
        TWE: IS22: RP020: HfLA Website Team Members Exit Interview Session Table
        ``` 
        - [x] Choose the "Session Table" tab
        - [x] Choose the header row (row 1)
        - [x] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text   <img width="700" alt="Screenshot 2023-01-30 at 4 01 19 PM" src="https://user-images.githubusercontent.com/57029070/215624294-49fbfcd4-df98-4165-8d4c-4d4bcdb29e75.png">
        - [x] Copy 
        ```
        HfLA Website Team Members #
        ``` 
        - [x] Choose cell C2 in "Session Table" tab
        - [x] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text   <img width="200" alt="Screenshot 2023-01-30 at 4 02 57 PM" src="https://user-images.githubusercontent.com/57029070/215624470-49809904-0a82-472b-a1ad-9475c9e09cd1.png"> 
    - [x] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder
        1. Choose File > Move (or Move icon)
        2. Choose the back arrow to access all your drives 
        3. Choose Shared drives > Internships > Internships > Research > Research by Plan # and name > folder for RP020
        4. Choose "Move here"
        5. Choose "Move" when it asks if you want to change ownership to a shared drive
        6. Dismiss the notification that says the file is now in the shared drive
    - [x] Update Resource # 2.03 link
        1. In the roll call and session table sheet, choose "Share" (upper right corner)
        2. Choose "copy link"
        3. Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
        4. Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### 
- Update the wiki page for this research plan (Resources # 2.01)
    - [x] Open the link in Resource 2.01
    - [x] Choose "Edit" to edit the page
    - [x] Find the "Interview Recordings & Transcripts" section
    - [x] Make a new line at the end of the list and add a new bullet by inserting `* ` at the beginning of the line
    - [x] Copy and paste Resource 2.03 (both the text and URL) from this issue to the right of this new bullet (`* `) in the "Interview Recordings & Transcripts" section
    - [x] Choose "Save Page"
- [x] Check if the "Roll Call and Session Table" (Resource # 2.03) spreadsheet you just created is saved in the correct research plan folder on Google drive (Resource 2.02)
- [x] Review with UX Lead
- [x] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [TWE: Template: Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1dmJJLaBDBiZWy4-dmdxG3XqP4OemR5aJTOScD_GsoLc/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan 020](https://github.com/hackforla/internship/wiki/Research-Plan-20:-Intern-Interaction-with-HfLA-Website-Team)
2.02 [Google Drive Folder: RP020](https://drive.google.com/drive/folders/1Mt099BzsWqhBe-y02ReDIEsRHB7vNdWR?usp=share_link)
2.03 [TWE: IS22: RP020: HfLA Website Team Members Exit Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1Gl4RK35YOeSwjuShfAQsKlgGSiEM7Es_MZ7kD72m_sQ/edit?usp=sharing)

**Comment by Dzotsen** [comment]
Did everything except the last two.

**Comment by pandanista** [comment]
The roll call and session table has been created for RP020.  The next step is to create a template for filling in the participants' information or to include the action items in the interview making issue.
