### ISSUE TITLE
TWE: Template Issue: Research: Consent Documents for Participants over 18: Create

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#368]
### Overview
We need to create a template issue for TWE: Research: Consent Documents for Study Participants over the age of 18: Create so that we have a consistent, transparent, defined, and self-supporting structure for people creating them.

#### Customize this issue
 - Customize this issue by adding the Name of Issue Template. 
    - _Note: An issue template's name is different from the issue title created from the template._
    - [x] Search for `TWE: Research: Consent Documents for Study Participants over the age of 18: Create` by using the browser search (**Mac**: ⌘+F; **PC**: Ctrl+F)
    - [x] Replace the keyword string (including text and the brackets) below with the name of your issue template according to the template naming convention: `TWE: Role: Direct object: Action verb`
        - The role is the primary owner of the issue template (e.g., Research, Design, Product)
        - Direct object should be the item that we're updating or working on (e.g., Wiki, Interviews, Roadmap)
        - Action verb should be the main descriptor of the action items (e.g., Update, Create, Transcribe)

#### Customize the issue settings (located in right sidebar)
Change the issue settings to ensure the issue is properly categorized and easy to manage.
- [x] Under Assignees, assign yourself.
- [x] Under Projects, choose gear, choose Repository, and choose TWE Project Management.
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.

#### Customize template draft
Create a draft of new template, which will be known as our "draft".
- [x] Copy resource 1.01 Content to copy for draft to a new comment on this issue.
- [x] In your draft, fill out the top part (called front matter) with the following information.  See resource 1.02 Front Matter Resources section below for definitions and examples.
    - [x] Name
    - [x] About
    - [x] Title
    - [x] Labels
- [x] Define any Dependencies (or remove the dependency section if there is no dependency)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] The links in the resources section provided by the issue creator should be in the same order as the Action Items 
      - [x] Refer to resource 1.03 Example Action Items for Finding Wiki Page and Template for an example of how to write clear instructions that avoid compound steps (steps within a step).
   - [x] Number each resource in the order each resource appears in the Action Items
       - [x] Group resources into numbers and decimals (e.g., Resource 1.01, Resource 2.01)
       - [x] Group the resources based on whether they are available when making the issues or they need to be created from this issue
           - If the resource is available, then group it under the Resources for creating this issue section (e.g., Resource 1.01, Resource 1.02, Resource 1.03)
           - If the resource will be delivered or created from this issue, then group it under the Resource links gathered during the making of this issue (e.g., Resource 2.01, Resource 2.02, Resource 2.03)
- [x] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking resource 1.04 WIKI Templates by role pages.  
  - [x] If there is a template
     - [ ] Add a link to the template into the ` #### Resources for creating this issue`  section of your draft
  - [ ] If there is no template yet
    - [ ] Put a placeholder into the` #### Resources for creating this issue`  section of the draft `[TWE: Template Issue: Role: [Replace ACTION VERB][Replace DIRECT OBJECT]`
- [ ] Get sign-off by Product on the draft
- [ ] Create the template issue on the repo if needed
- [ ] Add the link to the new issue template once created to resource 2.01.  Find by clicking on the Getting started button to the right of the new template listed on [new issue page](https://github.com/hackforla/internship/issues/new/choose)
- [ ] Update the appropriate place in the wiki for your template (see resources section)

#### Resources for creating this issue
- 1.01 Content to copy for draft
```
Draft of template issue for `TWE: Research: Consent Documents for Study Participants over the age of 18: Create`
---
**name:** TWE: Template Issue: [Replace ROLE]: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** This issue helps you structure your template issue to be consistent with our other template issues in [Replace DIRECT OBJECT]
** title:** TWE: [Replace ROLE]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]
**labels:** 'feature: board / google drive / tools, feature: missing, milestone: missing, role: missing, size: missing', 'Participant Type: missing', 'complexity: missing'
**assignees:**

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Copy and paste entire template text in this issue into text editor (ie., "TextEdit" on _Mac_, "Wordpad" on _PC_)
    - Use Find/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for and replace the keyword strings (including text and the brackets) below with the appropriate values 
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT OBJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, coding, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
```

- 1.02 Front Matter Resources
   <details>
   <summary>Front Matter Fields and Meaning</summary>

   - name: (name that appear on the new issue tab)
   - about: (is the description that appears next to the issue template on the new issue tab)
   - title: (the title that appears when the issue is created.  User then customizes this title for their issue)
       - Use the naming convention: TWE: Role: Direct object: Action verb
       - If more than one word should go into the direct object spot, use multiple square brackets with the keyword (see example below)
   - labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
   - assignees: 
   </details>
   <details>
   <summary>Front Matter Field Example</summary>

   - name: 'TWE: Template Issue: Research: Create Roadmap'
   - about:  This issue helps you structure your template issue to be consistent with our other template issues in roadmap
   - title: 'TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: Roadmap : Create'
   - labels: 'feature: research', 'feature: roadmap', 'milestone: missing', 'role: UI/UX research', 'Participant Type: missing', 'Research 000: missing', 'complexity: missing'
   - 'size: 0.50pt'
   - assignees: ''
   </details>

- 1.03 Example Action Items for Finding Wiki Page and Template
   <details>
   <summary>Example Action Items</summary>

   ```
   ### Action Items
   - Customize wiki page
        - [ ] Go to link 1.01 Internship Wiki, Join the team page
        - [ ] Find wiki page for this issue by looking at role pages.
        - [ ] Copy the link for the wiki page.
        - [ ] Add the link to Resource 2.01
           - [ ] Add the name of the link in square brackets
           - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
   - Customize document template.
       - [ ] Go to link 1.02 Design Process Overview
       - [ ] Find document template that should be used in this issue.
       - [ ] Copy the link for the template.
       - [ ] Add the link to Resource 2.02
           - [ ] Add the name of the link in square brackets
           - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
   ```

   </details>

   <details>
   <summary>Example Resource Lists</summary>

   ```
   ### Resources for creating this issue
   1.01. [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
   1.02. [Design Process Overview](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

   ### Resource links gathered during the making of this issue
   2.01. [Wiki page for [Replace TYPE OF ROLE]]
   2.02. [TWE: Template: [Replace NAME OF TEMPLATE]]
   ```

   </details>

- 1.04 WIKI Templates by role pages
   - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
   - [Design](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
   - [Product](https://github.com/hackforla/internship/wiki/Product)
   - [Business Analyst / Data Science]
   - [Software Engineer]
   - [Marketing]
   - default document templates, in case you don't have one yet, can be found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Resources gathered during the completion of this issue
- 2.01 [TWE: [Replace ROLE]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]]([Replace LINK])

**Comment by pandanista** [comment]
Draft of template issue for Interview Roll Call and Session Table Template
---
**name:** Research: Create Interview Roll Call and Session Table
**about:** We are creating a template to record future interview roll call and sessions so we can keep track of the interview to be conducted consistently
**title:** TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table: Create
**labels:** 'feature: roll call/session table', 'feature: research', 'Participant Type: missing', 'Research 000: missing', 'size: 0.25pt', 'role: UI/UX research', 'milestone: missing'
**assignees:**

---
#### Instructions for creating this issue
The person who creates this issue should use links in the section "Resources for creating this issue" (i.e., 1.01, 1.02, etc.) to customize this issue.
- Customize the issue
    - [ ] Open the "Research Overview" wiki page (Resource 1.01)
    - [ ] Choose the appropriate research roadmap or research plan folder (ie., RP###) on the wiki page 
    - Use the information on the wiki page and in research roadmap or research plan to customize this issue
    - [ ] Copy and paste entire template text in this issue into text editor (ie., "TextEdit" on _Mac_, "Wordpad" on _PC_)
    - Use Find/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for and replace the keyword strings (including text and the brackets) below with the appropriate values 
        - Year 
            - [ ] Find/Replace `[Replace YY]` with research year (Two digit format, ex: "22" for year "2022") 
        - Research Plan Number
             - [ ] Find/Replace `[Replace 000]` with the research plan number (Three digit format, ex: "001" for research plan "RP001") 
        - Type of Participant
            - [ ] Find/Replace `[Replace TYPE OF PARTICIPANT]` with the participant type (ex: "Intern" or "Mentor")  
        - Type of Interview
            - [ ] Find/Replace `[Replace TYPE OF INTERVIEW]` with the type of interview (ex: "Intake" or "Exit")
    - [ ] Copy and paste the edited template from text editor back into this Github Issue, replacing all original text
    - [ ] Re-check all the checkboxes above after copying and pasting the edited template
    - [ ] Close the text editor
    - Update the issue title
        - [ ] Choose "Edit" in the title section
        - [ ] Copy and paste 
        ```
        TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table: Create` into the issue title
        ```
        - [ ] Choose "Save"
- Customize the issue settings (located in right sidebar)
    - [ ] Under Assignees, assign a Researcher if it has been determined. Otherwise, leave it blank.
    - [ ] Under Labels,  choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Research: RP[Replace 000]`
    - [ ] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Participant Type: [Replace TYPE OF PARTICIPANT]`
    - [ ] Remove the `Research 000: missing` and `Participant Type: missing` labels
    - [ ] Under Projects, choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose `Repository`, and choose `Program Management`
    - [ ] Add the milestone: choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and choose `Research Plan Execution`
    - [ ] Remove the label `milestone: missing`
- Remove this section
    - [ ] After all the checkboxes above are complete and the issue is ready to be worked on, delete all text below the "Instructions for Creating this Issue" (top heading) and above "Overview" (heading below) -- i.e., the issue assignee will never see this part

### Overview
Create an interview roll call and session table for RP[Replace 000] so that we can keep track of who we are interviewing, when, and related links.

### Action Items
#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [ ] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [ ] Open relevant wiki page for RP[Replace 000]
    - [ ] Copy the link for the RP[Replace 000] wiki page.
    - [ ] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
 - Customize Resource for this Research Plan's Google Drive Folder
    - [ ] Open the Google Drive's Research by Type Folder (Resources  # 1.02)
    - [ ] Open the [Replace TYPE OF PARTICIPANT] Folder
    - [ ] Right-click on the RP[Replace 000] folder 
    - [ ] Choose "Get Link" and "Copy link" 
    - [ ] Update Resource # 2.02 with the link you just copied. Paste it inside parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for RP[Replace 000]'s Interview Roll Call and Session Table
    - [ ] Open the template "TWE: Template: Interview Roll Call and Session Table" (Resources 1.03)
    - [ ] Choose the "Use Template" button to save it to your own drive
    - Rename the file by following the steps:
        - [ ] Copy 
        ```
        TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table
        ```
        - [ ] Choose "File" > "Rename", and paste the text you copied into the top field    
       <img width="200" alt="Screenshot 2023-01-30 at 1 35 41 PM" src="https://user-images.githubusercontent.com/57029070/215600780-d8004229-17a3-409a-9d91-e4af9c904824.png">
       <img width="700" alt="Screenshot 2023-01-09 at 2 49 52 PM" src="https://user-images.githubusercontent.com/57029070/211424282-e5a501d2-6c42-4a8d-8645-31f9baca59af.png">
    - Customize both the Training Roll Call Table and the Session Table sheets
        - [ ] Copy 
        ```
        TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call Table
        ```
        - [ ] Choose "Training Roll Call Table" tab
        - [ ] Choose the header row (row 1) 
        - [ ] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text  <img width="700" alt="Screenshot 2023-01-30 at 12 13 20 PM" src="https://user-images.githubusercontent.com/57029070/215585369-4ddfaf59-ea1a-41e4-adeb-13911ecba5bc.png">
        - [ ] Copy 
        ```
        TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Session Table
        ``` 
        - [ ] Choose the "Session Table" tab
        - [ ] Choose the header row (row 1)
        - [ ] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text   <img width="700" alt="Screenshot 2023-01-30 at 4 01 19 PM" src="https://user-images.githubusercontent.com/57029070/215624294-49fbfcd4-df98-4165-8d4c-4d4bcdb29e75.png">
        - [ ] Copy 
        ```
        [Replace TYPE OF PARTICIPANT]#
        ``` 
        - [ ] Choose cell C2 in "Session Table" tab
        - [ ] Choose all text in the formula bar (double click), paste the text you copied, replacing the original text   <img width="200" alt="Screenshot 2023-01-30 at 4 02 57 PM" src="https://user-images.githubusercontent.com/57029070/215624470-49809904-0a82-472b-a1ad-9475c9e09cd1.png"> 
    - [ ] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder
        1. Choose File > Move (or Move icon)
        2. Choose the back arrow to access all your drives 
        3. Choose Shared drives > Internships > Internships > Research > Research by Type > [Replace TYPE OF PARTICIPANT]> folder for RP[Replace 000]
        4. Choose "Move here"
        5. Choose "Move" when it asks if you want to change ownership to a shared drive
        6. Dismiss the notification that says the file is now in the shared drive
    - [ ] Update Resource # 2.03 link
        1. In the roll call and session table sheet, choose "Share" (upper right corner)
        2. Choose "copy link"
        3. Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
        4. Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### 
- Update the wiki page for this research plan (Resources # 2.01)
    - [ ] Open the link in Resource 2.01
    - [ ] Choose "Edit" to edit the page
    - [ ] Find the "Interview Recordings & Transcripts" section
    - [ ] Make a new line at the end of the list and add a new bullet by inserting `* ` at the beginning of the line
    - [ ] Copy and paste Resource 2.03 (both the text and URL) from this issue to the right of this new bullet (`* `) in the "Interview Recordings & Transcripts" section
    - [ ] Choose "Save Page"
- [ ] Check if the "Roll Call and Session Table" (Resource # 2.03) spreadsheet you just created is saved in the correct research plan folder on Google drive (Resource 2.02)
- [ ] Review with UX Lead
- [ ] Product sign-off

### Resources/Instructions
#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link) 
1.03 [TWE: Template: Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1dmJJLaBDBiZWy4-dmdxG3XqP4OemR5aJTOScD_GsoLc/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan [Replace 000]]
2.02 [Google Drive Folder: RP[Replace 000]]
2.03 [TWE: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Roll Call and Session Table]

**Comment by pandanista** [comment]
@priyatalwar A team member is stilling testing this template, I am moving this to prioritized backlog for now.

**Comment by pandanista** [comment]
@bradyse Hi Sara, this is the consent form template, but I haven't incorporated the latest changes (such as the google form setting changes, etc) that I made in the testing template into this one yet. 

Let me know if you have more questions.

**Comment by pandanista** [comment]
Incorporated the changes suggested in #373  to include the distribution and collection of consent forms in the end of the template.

**Comment by pandanista** [comment]
@sunannie27 This template in [this comment](https://github.com/hackforla/internship/issues/368#issuecomment-1437482993) is ready to be tested. Please create a testing issue for this template, and let me know if you have any questions.

**Comment by pandanista** [comment]
Tested the issue template from this [comment](https://github.com/hackforla/internship/issues/508#issuecomment-2030257112) in the first [comment](https://github.com/hackforla/internship/issues/368#issue-1588236042) of this issue.

**Comment by ExperimentsInHonesty** [comment]
@pandanista what are next steps for this issue?  It's in the questions column, and your last comment does not provide any clarity.

**Comment by pandanista** [comment]
The research team has tested the template in issue #373. Waiting for Product team to test in issue #555.

**Comment by pandanista** [comment]
This template has been tested, and we can deploy it now. Let me know if there is any change to be made before we deploy it.

**Comment by pandanista** [comment]
- Deployed the template in the repo, closing this issue.
- [the upload form for interview recordings template](https://github.com/hackforla/internship/issues/new?assignees=&labels=complexity%3A+medium%2C+feature%3A+recording+transcription%2C+feature%3A+research%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&projects=&template=research--create-upload-form-for-interview-recordings--.md&title=TWE%3A+IS%5BReplace+YY%5D%3A+RP%5BReplace+000%5D%3A+%5BReplace+TYPE+OF+PARTICIPANT%5D+%5BReplace+TYPE+OF+INTERVIEW%5D+Interview+Recording+Upload+Form%3A+Create).
