### ISSUE TITLE
Interview Sophia

### ISSUE THREAD

**Issue by sniux** [hackforla/internship#37]
### Overview
We need to interview Sophia so that we can analyze the results of the program from the participants perspective

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [ ] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder and place link to recording in resources

### Resources/Instructions

[Sophia's Recording](https://drive.google.com/file/d/1bTPD7hI-YAch_jh1o32zc01_S640eGzQ/view?usp=sharing)
Notes & Insights (TBA)

**Comment by priyatalwar** [comment]
@sniux Please feel free to close this issue as I've created a new issue for repeating Sophia's interview #46

**Comment by sniux** [comment]
Interview was too short and the answers were slightly repetitive.
