### ISSUE TITLE
Revise project preview image

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#378]
### Overview
By adding the project's logo/image to your project's primary repository, we will be able to dynamically deliver up to date information about your project to the hackforla.org website.  Also when people add the link to the repository in LinkedIn or Slack, or other social media it will automatically use the image as well as the description, improving the link's chances of getting clicked on. 

We need to update the one we have, because currently it has mentors wanted on it
<details>
<summary>current image</summary>

<img src="https://user-images.githubusercontent.com/37763229/222258462-5e91d313-e502-433b-8fb4-273581ba0a29.png" width=300px>
</details>

<details>
<summary>social media preview from a phone</summary>

<img src="https://user-images.githubusercontent.com/75643389/222260988-588cccec-e42d-4c53-9639-8a0b54395604.png" width=200px>
</details>

#### Design to make a new preview image 
- [x] once image is created, move the issue to the questions/review column
- [x] review with product and get sign off
#### Product
- [x] unassign designer 
- [x] add the product label
- [x] move to prioritized backlog
- [x] Add the image to your primary GitHub repository using the instructions below.  You should use the same image as is on the hackforla.org website, or if another image is desired, please replace both with the same image.
- [x] test with phone message

### Resources/Instructions
- Tip: Your image should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend keeping the image at 640 by 320 pixels.
- Read Github's [Customizing your repository's social media preview](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview)

#### How to see the preview now
- Go to Slack
- Sent yourself the following message
  ```
  
  ```

**Comment by meetminji** [comment]
Original
![Internship Team Project Logo Original](https://user-images.githubusercontent.com/98001179/223550603-1eab838c-dbf2-494c-ba73-fe1f374823a8.png)
Option 2
![Internship Team Project Logo 2](https://user-images.githubusercontent.com/98001179/223550595-3cb2e2fc-ff32-407c-b8c1-7f51aa91a468.png)
Option 3
![Internship Team Project Logo 3](https://user-images.githubusercontent.com/98001179/223551068-476924d1-681c-473b-ac8a-e1fc56b75dd9.png)

**Comment by cbutcher318** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by meetminji** [comment]
Blockers:
"Add the image to your primary GitHub repository using the instructions below"

- Tried to follow instructions but could not find "Settings" from my end.
