### ISSUE TITLE
TWE Design System Components : Drop Down Menus

### ISSUE THREAD

**Issue by meetminji** [hackforla/internship#399]
### Dependencies
- [ ] https://github.com/hackforla/internship/issues/397

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] Update relevant WIKI page (See resources)
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by meetminji** [comment]
Check [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by RobinElayn** [comment]
Updated styles within component. Checked that all variations were properly linked to Master Component.

**Comment by meetminji** [comment]
<img width="709" alt="dropdown" src="https://github.com/hackforla/internship/assets/98001179/5834d9fa-f70f-4e63-8f1d-72ec3e38dcfd">

**Comment by joshfishman** [comment]
After reviewing this issue for dev I can see that we have combined two elements into one. The first couple items appear to be part of a Navigation header menu which should be its own component. Then the other pieces seem to be variations on a Select Input component. Can we break these into two designs 1. navigation and 2. select input?

**Comment by mklmrgn** [comment]
@joshfishman @karina-sato  - This is an old Issue / component that Minji had worked on. These dropdown menus are not current, and I have done updated for Material 3 components. My issue was https://github.com/hackforla/internship/issues/543, which has been approved and marked as done.
See ya'll in August...
