### ISSUE TITLE
Interview Bennett

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#40]
### Overview
We need to interview Bennet so that we can analyze the results of the program from the participants perspective

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [x] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder and place link to recording in resources

### Resources/Instructions
[Bennet's recording](https://drive.google.com/file/d/1pYCS1oBeMw4uH2l-_i015rbmA2Pxoy1g/view?usp=sharing)  | [Transcript](https://drive.google.com/file/d/17M4rO35u_-iJ2gc58YzXRJHKroaZ5ALV/view?usp=sharing)
Notes & Insights (TBA)

**Comment by ExperimentsInHonesty** [comment]
emailed him from internship account asking for his availability

**Comment by ExperimentsInHonesty** [comment]
I sent him a text message asking him to read emails.

**Comment by sniux** [comment]
@ExperimentsInHonesty I will go through them over the weekend and inform over our meeting.

**Comment by priyatalwar** [comment]
Update: Interview done on 8/27 and we have everything we need. @sniux @ExperimentsInHonesty @Rabia2219 Closing this issue.
