### ISSUE TITLE
TWE Design System Components: Buttons 

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#400]
### Dependencies

- [ ] #397 

### Overview
We need to create components for the TWE design system for future website development &b handoff.

### Action Items
 - [x] Design research of other buttons, create mood board
- [x] Lo-fi button version
- [x] Present to the team
- [x] Get sign off from product lead
- [x] Incorporate feedback; Hi-fi button version 
- [x] Create variations 
- [x] Update Layout to HfLA 2023 version (See link below)
- [x] Create CSS Size for each variation
- [x] Create CSS Color for each variation
- [x] Create organized component 
- [ ] Get sign off from product lead
- [ ] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [TWE Design System Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A45&t=93WtveGZFmUc5BtM-1)
- [Designs System Guide](https://docs.google.com/document/d/1zUVnInBcAi3HaoLFoHHjhlmWZvspPxYfg16kAm9nVVY/edit)
- [Design System Team's Figma](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?node-id=2%3A39&t=BDGY7MM0UVZKlHlD-1)
- [Update Layout to HfLA 2023 version](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?type=design&node-id=2%3A39&t=BKjviNPadl5SoWFB-1)

**Comment by RobinElayn** [comment]
Updated Buttons, Curated components in updated HfLA form, Blocker: Need support creating CSS Size and CSS Colors before being able to close issue.

**Comment by RobinElayn** [comment]
Waiting for CSS from Devs

**Comment by karina-sato** [comment]
Blocker: Need support creating CSS Size and CSS Colors

**Comment by karina-sato** [comment]
Get signed off: 
<img width="675" alt="image" src="https://github.com/hackforla/internship/assets/140572674/4f74d97c-e17e-4931-83ac-d1ecaee99e9d">

**Comment by karina-sato** [comment]
Updated. Ready to code.

**Comment by ExperimentsInHonesty** [comment]
- This issue has been replaced with #619
