### ISSUE TITLE
TWE Design System Components: Footers

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#408]
### Dependencies
- [x] #477 

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by joshfishman** [comment]
Test comment

**Comment by ExperimentsInHonesty** [comment]
Hi @Natalie-Aguilar thank you for taking up this issue! The TWE project appreciates you :)

Do let fellow developers know about your:-
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. ETA: (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by Natalie-Aguilar** [comment]
Hi @ExperimentsInHonesty, I was unable to attend last week's meeting, I would like to know if you had any additional requirements for the footer. In the last meeting, you mentioned that you would like me to meet with other designers from other teams. Do I contact them directly? and who are they?

If no additional requirements are needed, is there any way that I could take up another issue?

**Comment by ExperimentsInHonesty** [comment]
@Natalie-Aguilar Feedback on the footer. 
- remove the bullets and leave a text place holder, use the following (example to help people see how long the links could be)
   - link
   - longer link
   - even longer link
   - the longest link possible
- only have "credits", "privacy policy", "terms of use" on the bottom
- figure out where to put 
a project of Hack for LA <sub><img src="https://github.com/hackforla/internship/assets/37763229/bf751ac2-aca2-4ad2-aa29-065f34a27277" width=30></sub>

Thanks!

**Comment by sunannie27** [comment]
@Natalie-Aguilar We finished doing the requirements and this is what came out of issue #477 
### Footer Menu
About
Press
Terms & Conditions
Privacy Policy
Contact Us
FAQ

### Social Links
Github
Instagram
Facebook
Xitter

### Other Elements
Hack for LA link
Project Name / logo

**Comment by Natalie-Aguilar** [comment]
@sunannie27 Under the footer menu, which sections are for the bottom of the footer and which sections are meant for the tab sections

**Footer Menu**
About
Press
Terms & Conditions
Privacy Policy
Contact Us
FAQ

**Comment by bonniewolfe** [comment]
@Natalie-Aguilar  I assume you mean this when you say the tab section
![image](https://github.com/hackforla/internship/assets/107153148/d84d6fb6-8271-40f0-822d-6c7fd29801f4)


These are for that part

- About
- Press
- Contact Us
- FAQ

**Comment by ExperimentsInHonesty** [comment]
@Natalie-Aguilar Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by Natalie-Aguilar** [comment]
Hello @ExperimentsInHonesty 

I have added the changes to the footer and it is done.
I currently do not have blockers and waiting for sign off
Please let me know if you would like to make any changes to the current designs

**Comment by joshfishman** [comment]
@mklmrgn  there is no footer microsite page in ready for dev
