### ISSUE TITLE
Interview Jack

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#41]
### Overview
We need to interview Jack so that we can analyze the results of the program from the participants perspective

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [x] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder and place link to recording in resources

### Resources/Instructions
[recordings folder](https://drive.google.com/drive/folders/1R8sXXGrx47PNj2GpMSUIpMXYllAEgy19)
[Jack's recording](https://drive.google.com/file/d/165GYxV27QGgSOi7rtqwDrnKps1AVnLb_/view?usp=sharing) | [transcript](https://drive.google.com/file/d/1Ag1Fee5AkvQs9Wl5ijX2eJkS6KLvymmM/view?usp=sharing)
Notes & Insights (TBA)

**Comment by ExperimentsInHonesty** [comment]
@Rabia2219 @priyatalwar I spoke to Jack and here is his Availability for the next few days.  Please reach out via email to schedule with him.
Saturday 11-1
Sunday 12-3
Monday 11-12
Tuesday 10-2

**Comment by priyatalwar** [comment]
The interview happened on 8/22/21 at 1 pm PST

**Comment by ExperimentsInHonesty** [comment]
I have uploaded the recording and transcript.  This issue will be closed and the analysis done on another issue
