### ISSUE TITLE
TWE Design System Components: Toggles

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#410]
### Dependencies
- [ ] https://github.com/hackforla/internship/issues/397

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.
- [x] Create master component template with descriptive details
- [x] Create/indicate microsite layout for dev team

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by meetminji** [comment]
Check [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by RobinElayn** [comment]
Updated color & text styles within component. Checked that all variations were properly linked to Master Component.

**Comment by ExperimentsInHonesty** [comment]
This was created before the microsite workflow was created. The Toggle section in the Figma will need more details. Also, this issue will need a microsite page, or indication of which template to use (if it's similar to other pages).

- [Figma, Design System (WIP), Toggle](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2660-14619&mode=design&t=AKCE5VvNMuGdDJXw-0)
- [Figma, ↳ Microsite Ready for Dev](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-54&mode=design&t=jEcPrUuwVPDSu2EM-0)

**Comment by karina-sato** [comment]
Update: 

Master component template: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=5520%3A29960&mode=design&t=5DTMCAUKfzXoqfJa-1

Use Button microsite template

**Comment by ExperimentsInHonesty** [comment]
@mklmrgn will need to signoff that this is ready to use

**Comment by mklmrgn** [comment]
This is completed

**Comment by KC-skc** [comment]
The design was created before we implemented M3 standards but already comply with M3.

**Comment by mklmrgn** [comment]
Microsite Complete page complete for this component. Issue is Finished and ready  for Dev

![Image](https://github.com/user-attachments/assets/c8f534c7-0ae9-40fc-9ce4-22371906bb65)
