### ISSUE TITLE
TWE Design System Components: Check Boxes

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#411]
### Dependencies
- [ ] https://github.com/hackforla/internship/issues/397

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [ ] Create organized component
- [x] Get sign off from product lead 
- [ ] Link to the Microsite template to be used by devs and copy/paste to Figma page "Ready for dev"
- [ ] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by meetminji** [comment]
<img width="552" alt="Checkbox" src="https://github.com/hackforla/internship/assets/98001179/c954be16-4643-46db-a997-c92201f86e83">

**Comment by RobinElayn** [comment]
Updated layer names and order. Checked that all variations were properly linked to Master Component.

**Comment by karina-sato** [comment]
Hi @meetminji 
Looks great. Can you link this component to the microsite template that will be used by the dev team? Also, copy/paste to the Figma page "Ready for dev". 
-- > Close the issue.
