### ISSUE TITLE
TWE Design System Components: Tags

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#413]
### Dependencies
- [ ] https://github.com/hackforla/internship/issues/397

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

<details><summary>The last image produced by the person who previously worked on this issue</summary>

<img width="524" alt="Screen Shot 2023-05-11 at 10 26 50 AM" src="https://github.com/hackforla/internship/assets/98001179/5f92e200-c26a-4527-9e13-ce913a36807b">
</details>

**Comment by meetminji** [comment]
Check [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by RobinElayn** [comment]
Updated styles within component. Checked that all variations were properly linked to Master Component.

**Comment by ExperimentsInHonesty** [comment]
This was created before the microsite workflow was created. The tags section in the Figma will need more details, and this issue will need a microsite page, or indication of which template to use (if it's similar to other pages).

- [Figma, Design System (WIP), Header](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2660-14685&mode=design&t=WhxwSdqNMwW4rdpw-0)
- [Figma, ↳ Microsite Ready for Dev](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-54&mode=design&t=jEcPrUuwVPDSu2EM-0)

**Comment by ExperimentsInHonesty** [comment]
- Closed as unplanned, replaced by https://github.com/hackforla/internship/issues/622
