### ISSUE TITLE
TWE Design System Components: Input Fields

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#416]
### Dependencies
- [ ] https://github.com/hackforla/internship/issues/397

### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by meetminji** [comment]
Check [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by RobinElayn** [comment]
Updated color & text styles within component. Checked that all variations were properly linked to Master Component.

**Comment by meetminji** [comment]
<img width="618" alt="input fields" src="https://github.com/hackforla/internship/assets/98001179/64e721a1-99f0-44ff-a176-c5dd44731efc">

**Comment by meetminji** [comment]
<img width="617" alt="input fields" src="https://github.com/hackforla/internship/assets/98001179/a0fe18cc-a789-47ba-a42f-8694d495464b">

**Comment by meetminji** [comment]
Make updates following M3 Guidelines 
https://m3.material.io/components/menus/overview

**Comment by meetminji** [comment]
<img width="771" alt="Input Fields" src="https://github.com/hackforla/internship/assets/98001179/9f676dcf-3e02-44b3-9c94-77887731617a">

**Comment by meetminji** [comment]
New Issue created for M3 Guidelines
