### ISSUE TITLE
TWE Design System Components: Tabs

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#423]
### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.
- [ ] Create/indicate microsite for the dev team

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)
   - [Internship Figma File, Design System, Tabs](https://www.figma.com/design/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2790-13406&node-type=frame&t=50bfH3NclibVgqCf-0)

**Comment by RobinElayn** [comment]
Updated styles within component. Checked that all variations were properly linked to Master Component.

**Comment by karina-sato** [comment]
We need to create a master component template and microsite to hand off to dev. Designer working on this issue will also need to assess style and layout to see if re-design is necessary.

Refer to M3 to read more about tabs: https://m3.material.io/components/tabs/specs

**Comment by mklmrgn** [comment]
![Screen Shot 2024-09-20 at 10 23 22 AM](https://github.com/user-attachments/assets/0b47db4e-fb79-4210-b6d1-a2324e998d61)

**Comment by mklmrgn** [comment]
No longer using old design due to no secondary tabs, and issues with how component was made (reusable icons, etc).
- Replaced with #623
