### ISSUE TITLE
TWE Design System Components: Tooltips

### ISSUE THREAD

**Issue by RobinElayn** [hackforla/internship#425]
### Overview
We need to create components for the TWE design system for the future website development & handoff.

### Action Items
- [x] Create mood board 
- [x] Present to the team
- [x] Get feedback
- [x] Incorporate feedback
- [x] Hi-Fi version
- [x] Create variations
- [x] Create organized component
- [x] Get sign off from product lead 
- [x] When this issue is complete, please go #397 and check off the dependency.  If all other dependencies are checked off, move the issue from the icebox to the new issue approval column.
- [ ] Create microsite for dev team

### Resources/Instructions
- [Google Doc](https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit#heading=h.pq5p3t1w1lw2)
- [HfLA Figma File](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/HfLA-Design-System-Template?t=QhvqYQr8sPVUXqCz-0)
- [Internships Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2-45&t=UnquUaQhvcuGgsKH-0)

**Comment by RobinElayn** [comment]
Updated text styles and color styles within component. Checked that all variations were properly linked to Master Component.

**Comment by meetminji** [comment]
updated tooltips

<img width="682" alt="tooltips" src="https://github.com/hackforla/internship/assets/98001179/1f74d479-ab60-4242-945f-e3ac6ac6a7bc">

**Comment by meetminji** [comment]
1. not sure if we need "success" and "warning" for tooltip
2. check for contrast to make sure it passes accesibility test
3. maybe full saturation or border with white background
4. "i" inside circle hard to see 
5. play around with design

**Comment by meetminji** [comment]
<img width="1185" alt="tooltips 2" src="https://github.com/hackforla/internship/assets/98001179/6915cca0-e57d-4f5a-92ed-fc93c0021a72">
1. deleted "success" and "warning" states

2. checked color contrast and passed the accessibility test

3. Tried full saturation with white text

<img width="1163" alt="tooltips 3" src="https://github.com/hackforla/internship/assets/98001179/d8a232b5-0d7b-4790-b56e-d7f3d6150d96">

4. made stroke for "i" thicker

**Comment by meetminji** [comment]
add both options, full saturation and lower opacity.
close issue

**Comment by meetminji** [comment]
finalized tooltips 
<img width="1178" alt="tooltips final" src="https://github.com/hackforla/internship/assets/98001179/4f4df016-b4cd-41c6-99ae-18c497f7ec04">

**Comment by karina-sato** [comment]
Devs, use the Drop [down menu microsite template](https://www.figma.com/design/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=5629-18805&t=cU3l7Dcbskr8s505-1) for this component
