### ISSUE TITLE
Recruit a UI/UX Designer

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#43]
### Dependency

- [ ] ~product writing a requirements document~
- [ ] or needing a new or second designer
- [ ] [at least one month of issues in the prioritized backlog](https://github.com/hackforla/internship/projects/1?card_filter_query=label%3A%22role%3A+ui%2Fux+design%22#column-14736603)

### Overview
We are recruiting a UI/UX designer who will be working on the Internship Program website together with researchers and developers. 

### Action Items
- [ ] Hide all the old comments
- [ ] Create a comment below that has a draft of the wiki page, use the UX researcher wiki page as an example
- [ ] Edit note
- [ ] Post it in opportunities
- [ ] Post on appropriate slack channels
- [ ] Talk to potential UX designers

### Resources
- [Open Role: UX Researcher](https://github.com/hackforla/internship/wiki/Open-Role:-UX-Researcher)
- [UI/UX Design open roles Board](https://github.com/hackforla/UI-UX/projects/3)
- HTML to put at the top of the open role card so that the logo appears above the content
```
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">
```

- [Post for Designer](https://github.com/hackforla/UI-UX/projects/3#card-67378507)
- [Link to original card](https://github.com/hackforla/UI-UX/projects/3#card-67378507)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
A few questions:
How many designers are we recruiting?
I was going to write a more technical Overview but I believe [this](https://github.com/hackforla/civic-opportunity/blob/master/roles-1/ux-designer.md) already provides that. If you want me to be more specific, please let me know. Once you approve, I will proceed.
Thank you.

**Comment by ExperimentsInHonesty** [comment]
1 designer

**Project Name**: [your project name replaces these brackets]

**Volunteer Opportunity**: [your opportunity description replaces these brackets]

**Duration**: 

**Who to communicate your interest to**
- Slack channel link: #
- Slack name of person to contact in the channel

[Read more about the project]([your project home page on hackforla.org website goes here])

**Resources:**

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
The note has been edited and posted in opportunities. I was waiting for you to approve the issue before I did this that is why it wasn't ready. Waiting for feedback. Thanks

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
I also had a few questions about the UX/UI researcher and designer recruitment. I know you said you have a meeting with Snigdha. I can either join in the beginning or in the end, as per convenience, if you give me the timing. I need to understand why we are hiring a UX designer and researcher at this point. Where do the UI people come in? I ask because [this](https://github.com/hackforla/UI-UX/projects/3) has UX/UI,  UX designer and UI designer while [this](https://github.com/hackforla/UI-UX/projects/2) has just UX. Please bear with me as I learn the ropes :) and thank you for your patience :) 
If you think this is something Snigdha can explain to me, I can reach out to her for a meeting.

**Comment by Rabia2219** [comment]
Added dependency [here](https://github.com/hackforla/internship/issues/18#issue-948754800).

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
I pitched for a UX designer [here](https://hackforla.slack.com/archives/C017ESHSMNG/p1629766804097000) and got a response. He has this question: 'I'm curious about learning about what duties a UX designer would have on this project? Will it be end-to-end or only on a specific part of the design process? '
@sniux if you are going to meet with Bonnie today, can you please bring this up? Thanks

**Comment by ExperimentsInHonesty** [comment]
Next opportunity would be to design a page for the HfLA website where it details what we accomplished and invites people to connect with us.  The dependency on this is product writing a requirements document.

**Comment by Rabia2219** [comment]
9/16/2021
Moved issue from Ice Box to In progress.
Pitched for a UX designer [here](https://hackforla.slack.com/archives/C017ESHSMNG/p1631831229059300).
Will attend UI/UX COP meeting next Wednesday (9/22/2021) to pitch if we do not have any response by then.

**Comment by Rabia2219** [comment]
Posted opportunity in Slack on September 17th, 21st, 22nd, 23rd, 27th and 29th.
Did not attend the CoP meeting on the 22nd because of a speaker event (which was not a good call).
Attended CoP meeting on September 29th.
Was contacted by Maricel Dizon via Slack DM before the meeting on September 29th. She will be attending the October 4th onboarding session and will join the team as a UX researcher.

**Comment by Rabia2219** [comment]
Kelly Choe has joined our project as our UX designer.

**Comment by Rabia2219** [comment]
Opportunity posted on slack [here](https://hackforla.slack.com/archives/C017ESHSMNG/p1638801018076200) and [here](https://hackforla.slack.com/archives/C04S7PNCU/p1638800981069800).

**Comment by Rabia2219** [comment]
Got a response from Alice England...she will be attending the Onboarding on Tues Dec 7th...about her:

"A little about me, I completed the UX certificate with Google in April, and I’ve been working freelance ever since. I’m working with a start up at the moment to create a product for case managers and victims to manage, and report cases of image-based abuse. That’s nearly at an end, as we’re in the process of handing off to developers, so I’m looking for a new challenge, and as a large amount of my work is under NDA, I’d love to apply myself to something that gives back, and that I can create a case study around! "

**Comment by priyatalwar** [comment]
Update 12/14

Slack message from Clarissa: Hi Priyanka! I'm a junior ux designer who'd love to hop in and work on the internship project if your team is still in need of a ux/ui designer. I'm fairly new to the ux/ui design and tech field as prior to 2020 my work and education lied heavily on Healthcare and science. In 2020 I decided to make a career change in UX, enrolled and completed Springboard’s UX Design program, and now currently work as the sole product designer at AdGem, a startup company located in Chicago.

She's already attended onboarding . I've let @kellychoe know about her.

**Comment by priyatalwar** [comment]
Update 12/16: Slack conversation between us:
also I just saw that you were on the 311 team?
5:16
We are only allowed to work on one project at a time.
5:18
if you can clarify that, it would be helpful. Thanks!

Priyanka Talwar  7:21 PM
Hi, can you provide an update please on the clarification above?

Clarizza Mendoza  9:59 PM
Hi Priyanka! I apologize for the late response, but yes I am on the 311 team. Thank you for informing me! I will keep to the rules and stick to one project.

Priyanka Talwar  10:15 PM
Sounds good. Thanks!

**Comment by Rabia2219** [comment]
Andrew Shum has reached out on slack. Here's the conversation thus far:

Hi Rabia, I learned about the internship project through Grace Lau at DIA. She tells me you're looking for someone to help with design work. Can you please tell me more about this project?
And the timeline.

Hi Andrew,
The #internship project is looking for a UI/UX designer to join our team. Our project partners with students to give them an opportunity to work on real world problems here at HackforLA. You can read more about our project here.
As a member of our team, you will be collaborating with an experienced designer to bring our brand to life by designing a logo, communications guide and website, in order prepare for our next cohort.
This is the posting for the opportunity.
Meeting schedule: Tues 8 pm PST / Thurs 10 am PST
Please reach out to me @Rabia Shaikh or @Priyanka Talwar if you have any questions.
Important Note: You can only be assigned to one project at a time. (edited)
This will be an ongoing role but you can commit to as much time as you want...
Our meeting times have changed...
The Tuesday meeting timing is 3 - 4 pm PST...Thursday meeting timings are the same...
Do let me know if you have anymore questions...

Andrew Shum  10:35 PM
Okay thanks for sharing that info with me. Can I see what tickets are currently open. On your GitHub board?
I'm looking for some UI work I can do on a short time frame.
I'm also curious how far along your project is at the moment in terms of research and design. And what's the next milestone?

**Comment by Rabia2219** [comment]
Update:
I will reach out to Kelly to make sure she will be attending the Thursday team meeting and then invite Andrew.

**Comment by Rabia2219** [comment]
Update job posting [here](https://github.com/hackforla/UI-UX/projects/3#card-67378507)...

**Comment by Rabia2219** [comment]
> Update: I will reach out to Kelly to make sure she will be attending the Thursday team meeting and then invite Andrew.

Did not work out. Position is still open.

**Comment by Rabia2219** [comment]
> here

Done...

**Comment by Rabia2219** [comment]
> Update job posting [here](https://github.com/hackforla/UI-UX/projects/3#card-67378507)...

Done...

**Comment by Rabia2219** [comment]
Cherilyn  10:14 PM
Hi Rabia!
I recently completed the onboarding process and I'm interested to learn more about the volunteer opportunity as a UX/UI Designer for HfLA Internship Project.
I would like to learn more about the details for the project, such as the project timeline, time commitment, current status of the project, etc.
Thank you!

Rabia Shaikh  9:41 PM
Hi Cherilyn,
Thank you for your interest in our project.
This is an ongoing project but we appreciate any time that you are able to give. Design wise...our main priority is finishing up our logo...we have a very experienced designer working on it and she is looking to collaborate and share work with another designer...once the logo is finalized...we will move very quickly on to the communication guide and style guide...then the website design...
UX research wise...we are currently developing our personas and will be moving on to user stories then...
Do let me know if you have any more questions and what area you are looking to work on specifically so that I can provide you with more information :slightly_smiling_face:
New

Cherilyn  11:39 AM
I'm interested in the website design process - working on the communication guide, style guide and design system
I'm currently interested in working on areas that will help me obtain skills for Product or UX Design so if there's a specific process during this project that you believe may help me, please let me know

**Comment by ExperimentsInHonesty** [comment]
@rabia will write to her asking if she will work on the logo process with Kelly. in order for us all to be able to do the next steps that come after (e.g., what she referenced)

**Comment by Rabia2219** [comment]
Update:
Rabia Shaikh  12:51 PM
Hi Cherilyn,
So right now our main priority is to finish our logo. Our lead designer needs help to wrap that up after which we can move on to the communications guide, style guide and design system. Is that something you are interested in doing to start things off?
Thanks

Cherilyn  11:15 PM
Hi Rabia,
I don't mind providing suggestions and inputs for the logo design but I prefer to start on the project when the logo is complete!

**I've posted the opening again in the UI/UX and New Joiner Orientation channels.**

**Comment by Rabia2219** [comment]
Got another response. Susan looks like a very good fit. Here's our slack conversation. She is on standby to attend today's (01/13/22) meeting.


Susan Zhuang  12:00 PM
Good morning Rabia, this is Susan. I saw your post about an awesome internship opportunity in #ui-ux about the UX/UI Designer role, and I'm really interested! I want to know where can I send my resume or portfolio to be considered as a candidate. Thank you.

Rabia Shaikh  1:43 PM
Hi Susan...
Thanks for reaching out...
Sorry for the confusion...we are not offering an internship...our project is called #internship...we are looking for a UI/UX designer to volunteer on this project...
Let me know if you have any other questions :slightly_smiling_face:

**Susan Zhuang  6:03 PM
Hi Rabia,
Sorry, I misunderstood the words, I actually did a similar project where I built an internship and networking app to help college students to build meaningful relationships while they search for an internship opportunity, here is the link to the case study https://www.susanyuyingz.com/bridge, I think it's really important to build a program or community to help the student feel confident and supportive during the process of finding and actually doing an internship,  and I would love to contribute my UX/UI Design skill to this volunteer project! Let me know if you have any other questions for me, I'll be happy to answer them, or maybe we can hop on a quick call to discuss the project further. Thank you! (edited) 
Susan Zhuang's PortfolioSusan Zhuang's Portfolio
Bridge | Susan Z. | Portfolio
Researched, built, tested, iterated on a mobile app for college students facilitates a successful internship search process through an interactive networking community. (336 kB)
https://www.susanyuyingz.com/bridge**


Rabia Shaikh  6:40 PM
Thank you SO much for sharing this...
We have a team meeting tomorrow and I will share this with Bonnie and get her feedback...
if you don't mind me asking...what is your background?
Also...at this point our main priority is to finish our logo...(our project is fairly new) and our lead designer has done a wonderful job with our creating a brand identity for us...she is strained for time due to outside projects and is looking to collaborate with another designer to help finalize the logo...once that is done...we will be moving on to the communication guide...style guide and website design and content...
does this look like a good fit for you?

Rabia Shaikh  6:46 PM
I really like the work you've done on this app and I think you will be an asset to our team...
Let me know what you think about where we are in our project and if you think you'd like to join...

**Susan Zhuang  6:47 PM
For sure, I do have experience drawing logos for my friends' shop using procreate, I also did logo designs for other projects using Adobe XD or Figma, and I'm looking forward to working with other designers, developers, or pm!**

Rabia Shaikh  6:50 PM
Our designer is using Figma currently...
I'm excited as I think you will be a great fit for us...
The PMs meet at 9:30 am tomorrow and the rest of the team joins in at 10 am...I'll put this as the first item on the agenda and if Bonnie approves...do you think you can make the 10 am meeting tomorrow? It will be a very short notice though...

Susan Zhuang  7:11 PM
Sounds good, I can do 10am tomorrow
7:12
Just want to double check is 10am PST right?

Rabia Shaikh  7:15 PM
yes

Susan Zhuang  7:20 PM
sounds good, I'll wait for your response tomorrow morning
:+1:
7:21
just message me any update, I'll be on Slack from 9:30-10am
:+1

**Comment by Rabia2219** [comment]
Susan has joined our team.

**Comment by Rabia2219** [comment]
This was done on Thursday April 27th by Bonnie. We've updated the note and posted in the UI/UX channel.

**Comment by ExperimentsInHonesty** [comment]
We had added Prakar to the team.

**Comment by Rabia2219** [comment]
@designer2209 
Hi Prakhar,
Could you please copy and paste your correspondence with Alexa in a comment here...thanks :)

**Comment by designer2209** [comment]
[Alejandra Arevalo](https://app.slack.com/team/U038D29ST1C)  [4:12 AM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652136169153499)
:wave: Hi [@Prakhar Singh](https://hackforla.slack.com/team/U038R24FU3S), my name is Alejandra Arevalo and I'm a 2021 grad trying to break into the UX field. I have a background in journalism and some experience doing design for a data journalism publication and nonprofits. I would love to be considered for the opportunity as a UX/UI design intern. Here's my portfolio for your reference: https://alejandra-arevalo.com/ Thank you!


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  [4:26 PM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652180208697969)
Hi [@Alejandra Arevalo](https://hackforla.slack.com/team/U038D29ST1C), I'll take a look at your portfolio. Once I'm done reviewing your work I'll consult the team about what steps to take towards your onboarding process.


[Alejandra Arevalo](https://app.slack.com/team/U038D29ST1C)  [9:46 PM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652199389565129)
Sounds good, thanks Prakhar!


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  [11:15 AM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652247929268769)
Hey [@Alejandra Arevalo](https://hackforla.slack.com/team/U038D29ST1C) have you attended an onboarding meeting/call with HackForLA, yet?


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  [11:22 AM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652248358666349)
In case you haven't, you can go to https://www.hackforla.org/events/ and select whatever day and time is convenient to you.


[Alejandra Arevalo](https://app.slack.com/team/U038D29ST1C)  [10:51 PM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652289668798659)
[@Prakhar Singh](https://hackforla.slack.com/team/U038R24FU3S) yes, I have :slightly_smiling_face:


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  [10:54 PM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652289863525279)
Okay great, can you share your email address with me so that I can invite you to our meeting tomorrow.


Alejandra Arevalo  10:54 PM
alexa22arevalo@gmail.com
10:55
Looking forward to tomorrow's call


Prakhar Singh  10:56 PM
Yea, looking forward to working with you. Oh and I forgot to mention before, great portfolio, very diverse and interesting work!


[Alejandra Arevalo](https://app.slack.com/team/U038D29ST1C)  10:57 PM
Thank you!! It's still work in progress but I'm glad it's looking good thus far.


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  10:58 PM
I've sent a google meet invite, please take a look and let me know if you got it


[Alejandra Arevalo](https://app.slack.com/team/U038D29ST1C)  11:02 PM
Confirmed!


[Prakhar Singh](https://app.slack.com/team/U038R24FU3S)  [11:05 PM](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652290556109849)
Cool
[11:06](https://hackforla.slack.com/archives/D03EMRC0C7P/p1652290605523179)
And if you can, do go through our wiki https://github.com/hackforla/internship/wiki to get a better idea of the project

**Comment by priyatalwar** [comment]
Posted here https://github.com/hackforla/UI-UX/projects/3#card-67378507

**Comment by ExperimentsInHonesty** [comment]
Revised several parts of the text to make it more consise

<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project Name**: HfLA Internship Project

**About the Project**: This team is in its second year of successfully delivering tech internships to High School and Colleges.  We are about to build a website to support and interact with the users (students/guardians/mentors) and need your help.

**Volunteer Opportunity**:  You will collaborate with team designers on the website and communications guide.

**Duration**: Ongoing

**Who to communicate your interest to**
- Slack channel link: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of person to contact : Priyanka Talwar 

Read more: [TWE project](https://github.com/hackforla/internship/wiki/Volunteer-Overview) | [design artifacts](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

**Comment by priyatalwar** [comment]
2/6 Just got a slack message from Robyn
"Hi there, Priyanka.
My name is Robin and I’m a UX/UI Designer. I recently joined Hack for LA and noticed the volunteer UI designer posting for the TWE project. I was curious if you are still seeking designers for this positions? I would love to join the team.
Connect soon,
Robin


Replied " Hi Robin,
Thanks for your message. Have you already attended the HFLA onboarding?"

**Comment by priyatalwar** [comment]
Update 2/6/23: Robin has accepted our team meeting invite for this Thursday.

**Comment by priyatalwar** [comment]
Update 2/8/23: Brynna and Ming will be joining our team meeting tomorrow as designers as well along with Robin.

**Comment by RobinElayn** [comment]
Here is a potential Design Lead position card: 

<img width=“482” alt=“Finalized Logo” src=“https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png”>

**Project:** Hack for LA (HfLA) Internship

**Mission:** Over the past two years, our impactful initiative has opened the doors to the world of tech for high school and college students through rewarding internships. Now, as we refine our design system and gear up to construct a dynamic website, we’re seeking your creative leadership.

**Your Role:** As our Design Lead, you’ll have the opportunity to collaborate closely not only with our design team but also with our dedicated developers. Together, you’ll bring our website and communication strategy to life, ensuring our platform is engaging, intuitive, and effective.

**Commitment:** This is an ongoing opportunity, allowing you to make a meaningful impact and grow alongside our project.

**Express Your Interest:**
- Reach out on Slack: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Contact: Priyanka Talwar

For more info, dive into our [project overview](https://github.com/hackforla/internship/wiki/Volunteer-Overview) and [design process](https://github.com/hackforla/internship/wiki/Design-Process-Overview).



Link to original card: https://github.com/hackforla/UI-UX/projects/3#card-67378507

**Comment by priyatalwar** [comment]
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project:** Tech Work Experience (Internship)

**Mission:** Over the past two years, our impactful initiative has opened the doors to the world of tech for high school and college students through rewarding internships. Now, as we refine our design system and start building tools, we’re seeking your creative leadership.

**Your Role:** As our Design Lead, you’ll have the opportunity to collaborate closely not only with our design team but also with our dedicated developers, researchers, and product managers. Together, you’ll bring our communication strategy to life, ensuring our platform is engaging, intuitive, and effective.

**Commitment:** This is an ongoing opportunity, allowing you to make a meaningful impact

**Express Your Interest:**
- Reach out on Slack: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Contact: Priyanka Talwar

See more [project overview](https://github.com/hackforla/internship/wiki/Volunteer-Overview) and [design process](https://github.com/hackforla/internship/wiki/Design-Process-Overview).

**Comment by priyatalwar** [comment]
Made it concise and posted on 6/28

**Comment by karina-sato** [comment]
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project:** Tech Work Experience (Internship)

**Mission:** The goal of this team is to design and execute an internship project geared toward high school and college students to help them develop the hard (technical) and soft skills (workplace collaboration) required to successfully land STEM careers. Now, as we refine our design system and start building tools, we’re seeking a UX/UI Designer to join our current team.

**Your Role:** As a UX/UI Designer of the TWE Project, you'll have the opportunity to build the Design System, collaborate with other designers, engineers, and product teams. Together, you'll build and ensure our platform is intuitive, consistent, and engaging. 

**Commitment:** This is an ongoing opportunity, allowing you to make a meaningful impact and grow alongside our project.

**Express Your Interest:**
- Reach out on Slack: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Contact: Karina Sato

For more info, dive into our [project overview](https://github.com/hackforla/internship/wiki/Volunteer-Overview) and [design process](https://github.com/hackforla/internship/wiki/Design-Process-Overview).

**Comment by karina-sato** [comment]
Posted on [github](https://github.com/hackforla/UI-UX/projects/3#card-91473587) and [slack](https://hackforla.slack.com/archives/C017ESHSMNG/p1704398117529089)

**Comment by karina-sato** [comment]
Emerald and Michael have joined as UX Designers

**Comment by ExperimentsInHonesty** [comment]
@karina-sato please don't close this issue when the roles are filled, just uncheck the dependency, unassign yourself and put it back in the icebox.

**Comment by ExperimentsInHonesty** [comment]
- We no longer use this format. See https://github.com/hackforla/internship/issues/602
