### ISSUE TITLE
[TEST] TWE: IS22: HfLA Volunteer Research Plans and Goals Chart: Create 

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#445]
### Dependencies
- [ ] ~The research plan(s) needs to be created. See issue #320~ Ying says the draft is available and there is no need for it to be finalized for testing to proceed

### Overview
We need to create/update the Research Plans and Goals chart for HfLA Volunteers on Wiki with the research plan(s) info so we could provide a research plan overview for external use.

During these tasks you will be asked to add links to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them. 

#### Customize Resource Links
- Customize Resource for Wiki Page Links
    - [x] Go to "Research Documents by Participant Type" section on the Research Output Overview Wiki Page (Resources # 1.01)
    - [x] Choose `HfLA Volunteers` so it directs to the `HfLA Volunteers Research Overview` Wiki page
    - [x] Copy the URL of `HfLA Volunteers Research Overview` Wiki page in the browser 
    - [x] In Resources # 2.01, add parentheses `()` at the end of the line with no space in between the right bracket `]`
    - [x] Place the link you just copied between the parentheses  so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    
- Customize Resource for Google Drive Folder by Participant Type
    - [x] Choose the "Research by Participant Type" folder on the shared Google Drive (Resources  # 1.02)
    - [x] Choose `HfLA Volunteers` folder
    - [x] Copy the link of the `HfLA Volunteers` folder
        1. Choose the three vertical dots on the right side of the `HfLA Volunteers` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.02, add parentheses `()` at the end of the line with no space in between the right bracket `]`
    - [x] Place the link you just copied between the parentheses  so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resources for Each of HfLA Volunteers's Research Plan Folder 
    - [x] Open the `HfLA Volunteers` folder (linked in Resources # 2.02)
    - [x] Count the total of each research plan's folder, which starts with `RP### -`
    - In the subsection of Resources # 2.02, 
        - [ ] List each research plan folder as a subheading in a separate line based on the count of the research plan folders 
        - [x] Replace the `Replace RP000` in each subheading with the corresponding research plan number shown in the name of the research plan folder 
            - For example, if there are 5 research plan folders in total, then list 
                2.02.01 [Google Drive Folder: RP003]
                2.02.02 [Google Drive Folder: RP007]
                2.02.03 [Google Drive Folder: RP008]
                2.02.04 [Google Drive Folder: RP012]
                2.02.05 [Google Drive Folder: RP020]
    - [x] Remove the `...` in the resources # 2.02 section because there is no need for the placeholder anymore
    - [x] Copy the link of each research plan folder in the `HfLA Volunteers` folder (Resources # 2.02)
        1. Choose the three vertical dots on the right side of the folder <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In each corresponding line of the research plan folder, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] In each corresponding line of the research plan folder (the subheadings of Resources # 2.02), add parentheses `()` at the end of the line with no space in between the right bracket `]`
    - [x] Place the link you just copied between the parentheses  so it turns into a hyperlink
    - [x] Repeat the steps until you finish copying and pasting the links of each research plan folder
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
  
- Customize Resources for HfLA Volunteers's Research roadmap and Research Plan Google Doc(s) 
    - [x] Open the `HfLA Volunteers` folder if it is not open yet (linked in Resources # 2.02)
    - [x] Locate the `TWE: Research Roadmap: HfLA Volunteers` Google doc in the folder
    - [x] Copy the link of the `TWE: Research Roadmap: HfLA Volunteers` Google doc
        1. Choose the three vertical dots on the top right side of the `TWE: Research Roadmap: HfLA Volunteers` document <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.03, add parentheses `()` at the end of the line with no space in between the right bracket `]`
    - [x] Place the link you just copied between the parentheses  so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
    - In the subsection of Resources # 2.03, 
        - [x] List each research plan Google doc as a subheading in a separate line 
        - [x] Replace the `Replace RP000` in each subheading with the corresponding research plan number
            - For example, if there are 5 research plan folders and each folder has a research plan inside, then list 
                2.03.01 [Research Plan Google Doc: RP003]
                2.03.02 [Research Plan Google Doc: RP007]
                2.03.03 [Research Plan Google Doc: RP008]
                2.03.04 [Research Plan Google Doc: RP012]
                2.03.05 [Research Plan Google Doc: RP020]
    - [x] Remove the `...` in the resources # 2.03 section because there is no need for the placeholder anymore
    - [x] Open each research plan folder you just gathered (linked in the subheadings of Resources # 2.02)
    - [x] Identify if a research plan Google doc exists in the corresponding research plan folder by reading through the content within the folder
        - [x] If a research plan exists, 
            - [x] Copy the link of the research plan Google doc
                1. Choose the three vertical dots on the top right side of the Google doc  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
                1. Choose "Share"
                1. Choose "Copy link" 
        - [x] In each corresponding line of the research plan Google doc (the subheadings of Resources # 2.03), add parentheses `()` at the end of the line with no space in between the right bracket `]`
        - [ ] Place the link you just copied between the parentheses  so it turns into a hyperlink
        - [x] Repeat the steps until you finish copying and pasting the links of each research plan Google Doc
        - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
    - [x] If a research plan is missing, 
        - [x] Choose the gear in the Labels section <img width="500" alt="Screenshot 2023-04-19 at 8 06 27 PM" src="https://user-images.githubusercontent.com/57029070/233248009-99d8d10c-112a-4bc9-8fd5-b1e0098aea23.png">
        - [x] Put on the dependency label
        - [ ] Copy
        ```
        ### Dependencies
        - [ ] The research plan(s) needs to be created. See issue # 
        ```
        - [x] Choose "Edit" under the three dots to access the GitHub Write mode
        - [x] Paste what you just copied to the beginning of the issue above the `Overview` section
        - [x] Choose `Update comment` <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
        - [x] Choose `Issues` located on the top of the GitHub page to open a new tab in your browser <img width="600" alt="Screenshot 2023-06-15 at 5 18 07 PM" src="https://github.com/hackforla/internship/assets/57029070/bcee2deb-8032-4ea3-863f-dd7e5b3bb898">
        - [x] In the search bar, include the corresponding missing research plan number, i.e. RP001, to do a search to see if the research plan has an existing issue. Make sure to check both open and closed issues. <img width="700" alt="Screenshot 2023-06-15 at 4 18 57 PM" src="https://github.com/hackforla/internship/assets/57029070/7ab3bec1-1fa4-4fc3-a801-362785686d53">
        - [x] If there is an existing issue for creating that research plan, add the issue number after "See issue # " in the dependencies section so we can track  the status of the research plan issue
            - [ ] Assign the existing research plan issue to yourself if no one is assigned, so you can start working on that since it is a dependency
        - [ ] If the issue for creating that research plan does not exist among the issues, that means we haven't started drafting a research plan yet. Please go ahead and create a new issue by clicking [research plan template](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+feature%3A+research+plan%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&projects=&template=research--research-plan.md&title=TWE%3A+Create+Research+Plan+for+RP%5B%23%23%23%5D)
            - [ ] Customize the new issue using the missing research plan's number
            - [ ] Once the new issue is created, include the issue number after "See issue # " in the dependencies section above
            - [ ] Assign the new issue to yourself, so you can start working on the new issue since it is a dependency for this issue
            - [ ] Move the new issue to the `In Progress` column on the [TWE Project Management Board](https://github.com/hackforla/internship/projects/1)
        - [ ] Make a comment in this issue as an update to inform the team that there is a missing research plan and include the issue number for creating the research plan
        - [ ] Put this issue back to the icebox         
        - [ ] Remove yourself from this issue
    - [ ] Choose "Update comment" in Github and make sure all the action item you have accompolished above have been checked 

- Customize Resources for `Research Plans and Goals` Wiki Page
    - [x] Open `HfLA Volunteers Research Overview` wiki page (Resources # 2.01) 
    - [x] Select the hyperlink in the `HfLA Volunteers Research Plans and Goals (public page)` section on the wiki page so it directs you to the `HfLA Volunteers Research Plans and Goals` wiki page
    - [x] Copy the URL of `HfLA Volunteers Research Plans & Goals` wiki page in the browser
    - [x] In Resources # 2.04, add parentheses `()` at the end of the line with no space in between the right bracket `]`
    - [x] Place the link you just copied between the parentheses  so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked 

- Customize the spreadsheet for generating the Research Plans and Goals chart
    - [x] Open the template "TWE: Template: Research Plans and Goals Chart Spreadsheet" (Resources # 1.03)
    - [ ] Choose the "Use Template" button to save it to your own drive
    - Rename the file by following the steps:
        - [x] Copy 
        ```
        TWE: IS22: HfLA Volunteers Research Plans and Goals Chart Spreadsheet
        ```
        - [x] Choose "File" > "Rename", and paste the texts you copied into the top field    
       <img width="200" alt="Screenshot 2023-01-30 at 1 35 41 PM" src="https://user-images.githubusercontent.com/57029070/215600780-d8004229-17a3-409a-9d91-e4af9c904824.png"> <img width="400" alt="Screenshot 2023-02-27 at 2 51 11 PM" src="https://user-images.githubusercontent.com/57029070/221705684-e600627e-cbff-4642-ae62-c6db9dd7ea28.png">
    - [x] Move the file into the HfLA Volunteers's Google Drive folder in the Internship's shared drive
        1. Choose File > Move (or Move icon)
        1. Choose the back arrow to access all your drives 
        1. Choose Shared drives > Internship > Internships > Research > Research by Participant Type > HfLA Volunteers
        1. Choose "Move here"
        1. Choose "Move" when it asks if you want to change ownership to a shared drive
        1. Dismiss the notification that says the file is now in the shared drive
    - [x] Update the link in Resources # 2.05
        1. In the Research Plans and Goals Chart Spreadsheet you just created, choose "Share" (upper right corner)
        1. Choose "Copy link" and "Done"
        1. In Resources # 2.05, add parentheses `()` at the end of the line with no space in between the right bracket `]`
        1. Place the link you just copied between the parentheses  so it turns into a hyperlink
        1. Choose "Update comment" in Github and make sure all the checkboxes above have been checked 

#### Customize the Research Plans and Goals Chart Spreadsheet
- [x] Open the Research Plans and Goals Chart Spreadsheet in Resources # 2.05 if it is not open
- [x] Open the Research Roadmap Google doc and Research Plan Google docs in new tabs (Resources # 2.03 and its subsections)
- [x] Read through the Research Roadmap and Research Plan documents to get familiar with all the information because you will need to refer to them to customize the spreadsheet 
- In "All with edit links" tab
    - [x] In Column A, copy and paste each research plan name, starting from Row 2 (research plan names can be found in research plan Google docs in Resources # 2.03's subsections)
    - [x] Fill out Columns B - F based on the research plan and roadmap documents, starting from Row 2
    - [x] Add the links to the research plans in Column G
        1. Copy the matching research plan's URL from Resources 2.03's subsection, such as 2.03.01, 2.03.02, 2.03.03, etc
        1. In Column G, choose the cell that matches the research plan
        1. Click on the link icon <img width="30" alt="Screenshot 2023-02-27 at 3 31 50 PM" src="https://user-images.githubusercontent.com/57029070/221715925-7804635a-49be-45e3-9d81-06c69056f29e.png">
        1. Paste the URL you copied into the box with a magnifying glass. **Update the URL you pasted by removing the `/edit?usp=share_link` string and add `/preview` at the end of the URL so all participants can view the document externally**. <img width="500" alt="Screenshot 2023-02-27 at 3 32 18 PM" src="https://user-images.githubusercontent.com/57029070/221716041-a0d6450e-99b6-442d-a086-39083bc9ecb1.png">
        1. Choose `Apply`
    - [x] If the Google Form survey or interview script exists in the research plan folder(s), add the link(s) in Column H and Column I (if they exist). 
        1. Open each research plan folder in the subsection of Resources # 2.02
        1. Choose the survey or interview script in Google Form format in the research plan folder (if they exist)
        1. Choose "Send" <img width="50" alt="Screenshot 2023-02-27 at 6 07 11 PM" src="https://user-images.githubusercontent.com/57029070/221736079-1cfb9b2a-0bcd-4a1b-a6c7-0e3e868d6ee6.png">
        1. Choose the link icon <img width="50" alt="Screenshot 2023-02-27 at 6 07 31 PM" src="https://user-images.githubusercontent.com/57029070/221735981-a43f935f-7b61-475a-84c7-52803e3bf184.png"> and choose "Copy"
        1. In Column H "Survey/Script", choose the cell that corresponds with the research plan 
        1. Click on the link icon <img width="40" alt="Screenshot 2023-02-27 at 3 31 50 PM" src="https://user-images.githubusercontent.com/57029070/221715925-7804635a-49be-45e3-9d81-06c69056f29e.png">
        1. Paste the URL you copied into the lower box with a magnifying glass <img width="200" alt="Screenshot 2023-02-27 at 3 32 18 PM" src="https://user-images.githubusercontent.com/57029070/221716041-a0d6450e-99b6-442d-a086-39083bc9ecb1.png">
        1. In the first Text box, choose "Survey" and remove "Script" if the research method is survey, or choose "Script" and remove "Survey" if the research method is interview
        1. Choose `Apply` 
        1. Copy the URL from the browser tab in which the Google Form is open
        1. In Column I "Edit form", choose the cell that corresponds with the research plan 
        1. Click on the link icon <img width="40" alt="Screenshot 2023-02-27 at 3 31 50 PM" src="https://user-images.githubusercontent.com/57029070/221715925-7804635a-49be-45e3-9d81-06c69056f29e.png">
        1. Paste the URL you copied from the browser into the lower box with a magnifying glass <img width="200" alt="Screenshot 2023-02-27 at 3 32 18 PM" src="https://user-images.githubusercontent.com/57029070/221716041-a0d6450e-99b6-442d-a086-39083bc9ecb1.png">
        1. Choose `Apply` 
    - [ ] If the Google Form survey/script does not exist in research plan folders 
        1. No edit is needed in Column H or Column I 
        1. Make a comment in this issue as an update to let the team know the survey/interview script needs to be created and added in the Research Plan and Goals chart once it is available
        1. Check in with the team at the next research meeting to get an estimate on when the Google Form will be ready
- [x] If any of the research plans use interviews as the research method, update the "Interviews published version" tab 
    1. In "All with edit links" tab, choose the filter in Research Method(s) (Column C) <img width="80" alt="Screenshot 2023-02-27 at 7 08 02 PM" src="https://user-images.githubusercontent.com/57029070/221744300-2d3d0016-7ab7-4d22-a78c-89c20a26e8bb.png">
    1. Check "Interview" and uncheck the rest of methods <img width="80" alt="Screenshot 2023-02-27 at 7 08 39 PM" src="https://user-images.githubusercontent.com/57029070/221744485-2296af85-e2c2-41c1-8583-39e1ca1f4e3e.png">
    1. Choose "OK" <img width="50" alt="Screenshot 2023-02-27 at 7 09 11 PM" src="https://user-images.githubusercontent.com/57029070/221744604-e6f22e96-b056-4d32-b88a-0aea63b36b62.png">
    1. The research plans using interviews as the research method are populated
    1. Copy the content (texts and URLs) from Columns A-B and Columns D-H with no header from Row 2
    1. Paste the content into the "Interviews published version" tab starting from Row 3
- [ ] If interviews are not used, leave the "Interviews published version" tab blank
- [ ] If any of the research plans use surveys as the research method, update the "Surveys published version" tab 
    1. In "All with edit links" tab, choose the filter in Research Method(s) (Column C) <img width="80" alt="Screenshot 2023-02-27 at 7 08 02 PM" src="https://user-images.githubusercontent.com/57029070/221744300-2d3d0016-7ab7-4d22-a78c-89c20a26e8bb.png"> 
    1. Check "Survey" and uncheck the rest of methods <img width="80" alt="Screenshot 2023-02-27 at 7 08 49 PM" src="https://user-images.githubusercontent.com/57029070/221745301-b75472dc-c360-4ba9-9efe-fef00cfeb54f.png">
    1. Choose "OK" <img width="50" alt="Screenshot 2023-02-27 at 7 09 11 PM" src="https://user-images.githubusercontent.com/57029070/221744604-e6f22e96-b056-4d32-b88a-0aea63b36b62.png">
    1. The research plans using surveys as the research method are populated
    1. Copy the content (texts and URLs) from Columns A-B and Columns D-H with no header from Row 2
    1. Paste the content into the "Surveys published version" tab starting from Row 3
- [ ] If surveys are not used, leave the "Surveys published version" tab blank
- [ ] If there is any other research method to be used or used, choose "[research method] published version" tab 
    - [ ] Click on the green down arrow <img width="150" alt="Screenshot 2023-02-27 at 3 11 35 PM" src="https://user-images.githubusercontent.com/57029070/221710452-3b80bbe3-1545-4a09-8278-03903720ce96.png"> and choose `Rename` <img width="50" alt="Screenshot 2023-02-27 at 3 16 41 PM" src="https://user-images.githubusercontent.com/57029070/221711309-314ee1e9-4864-41fe-a01f-a4160b666bb0.png">
    - [ ] Update `[research method]` in the name of the tab with the method to be used or used, such as "usability test", etc.
    - [ ] Update row 2 `[research method]` with the method to be used or used, such as "usability test", etc.
    - [ ] Populate the research plans using other research method(s) one by one
        1. In "All with edit links" tab, choose the filter in Research Method(s) (Column C) <img width="80" alt="Screenshot 2023-02-27 at 7 08 02 PM" src="https://user-images.githubusercontent.com/57029070/221744300-2d3d0016-7ab7-4d22-a78c-89c20a26e8bb.png">
        1. Check one research method other than interview and survey, and uncheck all other methods 
        1. Choose "OK" <img width="50" alt="Screenshot 2023-02-27 at 7 09 11 PM" src="https://user-images.githubusercontent.com/57029070/221744604-e6f22e96-b056-4d32-b88a-0aea63b36b62.png">
        1. The research plans using that particular research method are populated
        1. Copy the content (texts and URLs) from Columns A-B and Columns D-H with no header from Row 2
        1. Paste the content into the other research method's "published version" tab from Row 3
        1. Make one tab for each of the other research methods other than interviews and surveys if needed
- [ ] If no other research method(s) is used, leave the "[research method] published version" tab blank
- [ ] Update the "Published plans & goals by research methods" tab
    1. Copy the entire spreadsheet starting from Row 2 (no header) in "Interviews published version" tab if interviews are used as a research method. Otherwise, skip the "Interviews published version" spreadsheet.
    1. Paste the spreadsheet into the "Published plans & goals by research methods" tab
    1. Copy the entire spreadsheet starting from Row 2 (no header) in "Surveys published version" tab if surveys are used as a research method. Otherwise, skip the "Surveys published version" spreadsheet.
    1. Paste the spreadsheet into the "Published plans & goals by research methods" tab
    1. Copy the entire spreadsheet starting from Row 2 (no header) in "[research method] published version" tab if any other methods are used. Otherwise, skip the "[research method] published version" spreadsheet.
    1. Paste the spreadsheet into the "Published plans & goals by research methods" tab

#### Update Research Plan and Goals Wiki page
- Convert the spreadsheet into Markdown language
    - [ ] Copy the spreadsheet (with header) in the "Published plans & goals by research methods" tab in Resource # 2.05
    - [ ] Open the link in Resources # 1.04
    - [ ] Paste the spreadsheet you just copied into the box with "Paste Table Here! " being displayed <img width="200" alt="Screenshot 2023-02-27 at 8 04 53 PM" src="https://user-images.githubusercontent.com/57029070/221753856-06d40e21-ee9b-42b9-a464-9c9f978dbbda.png">
    - [ ] Choose "Submit" <img width="50" alt="Screenshot 2023-02-27 at 8 05 47 PM" src="https://user-images.githubusercontent.com/57029070/221751672-af7d145f-5c49-4a5e-a245-3d920b6e1857.png">
    - [ ] Use the default settings once the table is converted to Markdown. By default, "Outer pipes" and "Cell padding" are checked, and "No sorting" is the option selected on the drop down menu <img width="300" alt="Screenshot 2023-02-27 at 8 09 08 PM" src="https://user-images.githubusercontent.com/57029070/221751616-a8453e0f-ce63-446f-88c2-5b25bd55d60f.png">
    - [ ] Copy the converted Markdown table from the box
- Update Wiki page
    - [ ] Open the link in Resources # 2.04
    - [ ] Choose "Edit"
    - [ ] Paste the converted Markdown table into the text box under the `### HfLA Volunteers Research Plans & Goals` section
    - [ ] Remove outdated Research Plans & Goals table if there were any
    - [ ] Choose "Save page"

####
- [ ] Review with UX Lead
- [ ] Product sign-off

#### Resources for creating this issue
1.01 [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.01.01 Examples of the Research Plans and Goals Charts: [Mentor Research Plans and Goals](https://github.com/hackforla/internship/wiki/Mentor-Research-Plans-and-Goals); [Intern-Research-Plans-and-Goals](https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals)
1.01.02 Example of the spreadsheet prior to the Github Wiki chart: [Intern Research List](https://docs.google.com/spreadsheets/d/1Y2VeHEUhmx4UX6y8CtbCHy2ilH76lWO4_xAVoqnLyME/edit#gid=1271462147)
1.02 [Google Drive Folder: Research by Participant Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Research Plans and Goals Chart](https://docs.google.com/spreadsheets/d/1TA0AGHKFhb4b3IbylfGAytoHmaDmfjsSuPPuEVlqCF0/template/preview)
1.04 [Convert spreadsheet to Markdown language](https://tabletomarkdown.com/convert-spreadsheet-to-markdown/)

#### Resources gathered during the completion of this issue
2.01 [HfLA Volunteers Research Overview](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview)
2.02 [Google Drive Folder: HfLA Volunteers](https://drive.google.com/drive/folders/10hqcOE54U71UZd_Vtu4WPsXSopXZnDdk?usp=drive_link)
2.02.01 [Google Drive Folder: RP002](https://drive.google.com/drive/folders/1ZYQfSPRKZXZCZR_F4tVm-vMiPtfK2KTf?usp=drive_link)
2.02.02 [Google Drive Folder: RP020](https://drive.google.com/drive/folders/1Mt099BzsWqhBe-y02ReDIEsRHB7vNdWR?usp=drive_link)
2.03 Research Plan Google Docs [Research Roadmap: HfLA Volunteers](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=drive_link)
2.03.01 [Research Plan Google Doc: RP002](https://docs.google.com/document/d/15jkt2K0k3amrMMCHopNwurRrZpFyXDFhsjZ1YZ0qP9o/edit?usp=drive_link)
2.04 [HfLA Volunteers Research Plans and Goals Chart Wiki Page](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview#hfla-volunteers-research-plans-and-goals-public-page)
2.05 [HfLA Volunteers Research Plans and Goals Chart Spreadsheet](https://docs.google.com/spreadsheets/d/1ACM1P6h1wGpdXW7aSTue4EuPEcqmWaI3EoBarc73lcw/edit?usp=drive_link)

**Comment by pandanista** [comment]
The label we have says "HfLA Team Member", should we change it to "HfLA Volunteers" to be consistent?

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: Still working on it
2. Blockers: Didn't have enough time
3. Availability: 2-3 hours
4. ETA: 9/28

**Comment by priyatalwar** [comment]
I have some questions @pandanista so I'll set up a 1:1 time with you.

**Comment by pandanista** [comment]
The meeting is set at 10/9 at 1:00pm. Please list out any specific questions or feedback you have for this template as a comment. Thank you.

**Comment by priyatalwar** [comment]
Discussed feedback with @pandanista and she made some changes. She's also going to bring up the highlighted part at our next meeting. We couldn't finish so we will meet again once she lets me know her availability.

**Comment by pandanista** [comment]
@priyatalwar Thank you for testing out this issue. I've made drastic changes to template #432 (the wording, the structure, and the instructions) based on our conversation today. I've also incorporated all the changes to this testing issue and kept the part you've tested and approved up-to-date (see all the checkmarks and clickable URLs).  Two options for the wording regarding the parenthesis are included as well. 

Please continue the testing whenever you have time. Since the issue was created based on a template we are still testing—meaning, while working on this issue, you might run into instructions that are not clear enough, or confusing, or direct you to a wrong folder, etc. Therefore, please leave any feedback you have below as comments as you check off the action items. Much appreciated. :) 

Please see below for instructions on providing feedback and examples:
### Action Items for Providing Feedback on Testing Templates
- [ ] Provide feedback for this issue
     - [ ] Add feedback in the form of (1) questions and/or (2) explicit instructions for how the content should be improved. Feedback for GitHub templates, please screenshot the section that needs to be modified and provide written feedback in a comment in this issue thread. Feedback in a Google Doc or spreadsheet should be given in the form of document comments. 
     - [ ] Determine the accuracy of the content for each section (action items listed in the issue above, Google doc, or Google sheet). If you find an inaccuracy, error, or mis-categorization, explain how the information presented could be improved.
     - [ ] For each suggested improvement, provide a link, reference, or a screenshot within your comment to justify your suggestion.
        - Examples:  
        <img width="700" alt="Screenshot 2023-03-06 at 6 37 40 PM" src="https://user-images.githubusercontent.com/57029070/223306823-2a79b9df-c996-4ac7-b1b0-e8aeaf0e9170.png">
        <img width="700" alt="Screenshot 2023-03-06 at 6 37 10 PM" src="https://user-images.githubusercontent.com/57029070/223306826-0d29a792-c4fa-4458-96ab-3614b0b66a76.png">
        <img width="700" alt="Screenshot 2023-03-06 at 6 36 56 PM" src="https://user-images.githubusercontent.com/57029070/223306827-ee6c9cad-9fd4-476f-9e8f-bde64a2da151.png">
        <img width="700" alt="Screenshot 2023-03-06 at 6 36 46 PM" src="https://user-images.githubusercontent.com/57029070/223306831-4105863d-192d-4860-810f-efb17cc15e44.png">
- [ ] Once all the steps have been completed, reach out to the current UX Lead to determine if they can incorporate the feedback in the issue template.

**Comment by pandanista** [comment]
Thank you for your suggestion, @priyatalwar. 

We've decided to go with the two-step instructions on the parenthesis. I've updated the testing template above to reflect the changes.

Please keep us updated on the testing.

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: Still working on it
2. Blockers: no laptop 
3. Availability: 2-3 hours
4. ETA: 10/26

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: 70% done
2. Blockers: doctors appointments
3. Availability: 2-3 hours
4. ETA: 11/2

**Comment by priyatalwar** [comment]
For the goals spreadsheet, the spreadsheet already seems to exist so if I move it to the TWE drive, there will be a duplicate. Please advise.

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: Almost done except for the last two sections
2. Blockers: Please see the above comment
3. Availability: 2 hours
4. ETA: by 11/6

**Comment by pandanista** [comment]
> For the goals spreadsheet, the spreadsheet already seems to exist so if I move it to the TWE drive, there will be a duplicate. I've moved it since I wanted to follow along but for the next section, I don't know which spreadsheet to open. Please advise.

@priyatalwar Thank you for testing on it. When making any asset, i.e. the spreadsheet, for the testing purpose, you can add [Test] at the title of the asset to indicate the asset has been created for a test. Based on the time the asset being created, you can tell which one is for testing too. 

I've added the [Test] to the front of the spreadsheet so you can tell which one was created by you for this template testing.
<img width="2314" alt="Screenshot 2023-11-02 at 10 36 52 AM" src="https://github.com/hackforla/internship/assets/57029070/101f4823-9676-4d5f-b94b-7fdc19a25e48">

**Comment by priyatalwar** [comment]
Sounds good. Thank you @pandanista.

**Comment by sunannie27** [comment]
@priyatalwar When the testing is completed, please release the dependency on #432

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: Almost done except last bit
2. Blockers: Was sick
3. Availability: 2 hours
4. ETA: 2/5

**Comment by sunannie27** [comment]
@priyatalwar 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by priyatalwar** [comment]
Please provide update
1. Progress: Almost done except last bit
2. Blockers: out of power 
3. Availability: 2 hours
4. ETA: 2/12

**Comment by pandanista** [comment]
- Consider this testing done since #374 was completed.
- Closing this issue so we can set up the template on the repo
