### ISSUE TITLE
TWE: Create Template Issue: Update Research Plan

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#447]
### Overview
We need to create a template issue for Research Plan so that we have consistent, transparent, defined and self-supporting structure for people creating them.

### Action Items
- [x] Add to the Project Board
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.
- [x] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for
- [x] Create a draft of new template by copying the content block below to a comment on this issue, which will be known as our Draft
- [x] In your draft, Fill out the top part (called front matter) with the info it needs.  See the Resources section below for definition and example.
- [x] Define any Dependencies (or remove the dependency section)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] the links provided by the issue creator should be in the same order as the Action Items 
- [x] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking the WIKI Templates by role pages.  
  - [x] if there is a template
     - [x] Add a link to the template into the ` ### Resources`  section of your draft
  - [ ] if there is no template yet
    - [ ] put a placeholder into the` ### Resources`  section of the draft `[TWE: Template: [replace with name of type]]`
- [ ] Get sign-off by product on the draft
- [ ] Create the template issue on the repo
- [ ] Add the link to related "Get started" button in the Resources section below.
- [ ] Update the appropriate place in wiki for your template (see resources section)

### Resources/Instructions
~Getting started button link for creating new issue using the ["REPLACE with name and link of template"] template on the "New issue" tab~
- [Meeting Recordings Folder](https://drive.google.com/drive/folders/1lgc0eeDXvqvqvLOgqsT8lu3EsneeH9VS?usp=share_link) -- store recordings of template testing

#### WIKI Templates
- by role pages
  - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
  - [Design]
  - [Product]
  - [Engineering]
- default document templates, in case you don't have one yet can found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Content to copy for draft
```
Draft of [replace with name of type] template issue
---
name: TWE: Create Template Issue: [replace with name of template]
about: 
title: TWE: [replace with action verb] [replace with name of template]
labels: 'feature: board / google drive / tools', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
assignees: 
---
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Find WIKI page for this issue by looking at role pages [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team) - then add the appropriate link to the resources section
- [ ] Find document template that should be used [Templates & Product Branding](https://github.com/hackforla/internship/wiki/Design-Process-Overview) - then add that specific template link into the resources section
- [ ] If no dependencies, delete dependency section
- [ ] any place you see `[replace...]` replace both the text and the brackets with what it is asking for (including in the front matter above but not where it says name, but not where it says title.
- [ ] add appropriate labels and remove the corresponding missing labels
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
```
### Resources
<details>
<summary>Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>Front Matter Field example</summary>

- name: 'Research: Roadmap'
- about: The start of a new roadmap
- title: 'TWE: Research Roadmap [name of type]'
- labels: 'feature: research, feature: roadmap, milestone: missing, role: UI/UX research,
-   size: 0.50pt'
- assignees: ''
</details>

**Comment by pandanista** [comment]
### Action Items
#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [ ] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [ ] Open relevant wiki page for RP[Replace 000]
    - [ ] Copy the link for the RP[Replace 000] wiki page.
    - [ ] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
 - Customize Resource for this Research Plan's Google Drive Folder
    - [ ] Choose the "Research by Plan # and name" folder on the shared Google Drive (Resources  # 1.02)
    - [ ] Right-click on the RP[Replace 000] folder 
    - [ ] Choose "Get Link"
    - [ ] Choose "Copy link" and "Done"
    - [ ] Update Resource # 2.02 with the link you just copied. Paste it inside parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for [Replace TYPE OF PARTICIPANT]'s Research Plans and Goals Chart
    - [ ] Go to Research Output Overview Wiki page (Resources # 1.01) 
    - [ ] Choose `[Replace TYPE OF PARTICIPANT]` in the "Research Documents by User Type" section
    - [ ] Choose the `Research Plans and Goals Chart` in the "[Replace TYPE OF PARTICIPANT] Research Plans and Goals (public page)" section
    - [ ] Copy the URL of `[Replace TYPE OF PARTICIPANT] Research Plans and Goals` wiki page in the browser window
    - [ ] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

**Comment by pandanista** [comment]
The template is made and edited based on one round of internal testing (#398). 

A second round of internal testing will be performed via #431.

**Comment by ExperimentsInHonesty** [comment]
The two issue above are testing in production and this template is good enough at this point to deploy.  

Next steps
- [ ] copy the [draft comment contents](https://github.com/hackforla/internship/issues/447#issuecomment-1624747209) to the [template maker ](https://github.com/hackforla/internship/issues/templates/edit)

**Comment by pandanista** [comment]
- This template draft has been added as an [issue template](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research+plan%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&projects=&template=research--update-an-existing-research-plan-with-new-hfla-branding.md&title=TWE%3A+IS%5BReplace+YY%5D%3A+RP%5BReplace+000%5D%3A+Research+Plan+with+Depreciated+Format%3A+Update) 
- Closing this issue now.
