### ISSUE TITLE
Special Onboarding

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#45]
### Overview
Bonnie will conduct a special onboarding for those who can't make it during our regular meetup timings due to timezone issues

### Action Items

- [x] Set up the zoom link
- [x] Post on Meetup
- [x] Make list of projects to recruit for
   - [ ] Internship
   - [ ] Guides
   - [ ] Open Community Survey
   - [ ] Hack for LA site
   - [ ] Access the Data
   - [ ] Data Science
   - [ ] Admin
   - [ ] 100 Automations
- [ ] Add when they meet and what they are recruiting for

### Resources/Instructions
[Zoom registration link for the event](https://us02web.zoom.us/meeting/register/tZIudOitqj8pH9MowGAlHghwgOrLgOdQTSx_)
Meetup events page: https://www.meetup.com/hackforla/events/
Meetup link for this event: https://www.meetup.com/hackforla/events/280390872/

**Comment by ExperimentsInHonesty** [comment]
I did run one on a saturday (about 5 people came).  I am closing this issue.
