### ISSUE TITLE
Create TWE Github Pages based on MK Docs Jekyll Template

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#452]
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Find WIKI page for this issue by looking at role pages [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team) - then add the appropriate link to the resources section
- [ ] Find document template that should be used [Templates & Product Branding](https://github.com/hackforla/internship/wiki/Design-Process-Overview) - then add that specific template link into the resources section
- [ ] If no dependencies, delete dependency section
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies
#446 

### Overview
We need to create a GitHub Pages based website to host the TWE: Design System
### Action Items

- [x] Create Github Pages Branch
- [x] Add MkDocs to our Repo
- [x] Setup Github Pages
- [ ] Publish Site Beta
- [ ] Create TWE Theme
- [ ] Style MK Docs to match design
- [ ] Add Components to Theme

- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
[Mk Docs](https://www.mkdocs.org/)
[Github Pages Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll)

**Comment by jnomad21** [comment]
Template framework built on personal repo, need to setup Github Actions to deploy pages
![HFLA-TWE-Jekyll-Template-Draft1](https://github.com/hackforla/internship/assets/127683817/3b6faa86-f5ed-4895-a572-244767563b3b)

**Comment by joshfishman** [comment]
wrong site builder used in this ticket

**Comment by joshfishman** [comment]
wrong site builder used in this ticket
