### ISSUE TITLE
Repeat Sophia's Interview

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#46]
### Overview
We need to interview Sophia again so that we can analyze the results of the program from the participants perspective. Related to issue #37

### Action Items
- [x] Schedule interview
- [x] Conduct Interview with Record and transcript turned on
- [x] Upload transcript file to folder and place link to transcript in resources
- [x] Upload recording to folder and place link to recording in resources

### Resources/Instructions
Notes & Insights (TBA)
[Interview notes]
[Sophia's folder](https://drive.google.com/drive/folders/17PmnHB1ys7JyKjQ5E2eOz3qlXBEvfHj8)
[Recording 1](https://drive.google.com/file/d/1bTPD7hI-YAch_jh1o32zc01_S640eGzQ/view?usp=sharing)
[Transcript 1](https://drive.google.com/drive/folders/17PmnHB1ys7JyKjQ5E2eOz3qlXBEvfHj8)
[Transcript 2](https://drive.google.com/file/d/1nMf1jZvSrg1NQh52L_ocSiU49cbPx0F7/view?usp=sharing)
[Recording 2](https://drive.google.com/file/d/1tH6WD1I6g9i-1aivKU69GJCsThf0qdNg/view?usp=sharing)

**Comment by priyatalwar** [comment]
Update 8/31/21: Reached out to Sophia Ling via slack

Priyanka Talwar  9:47 PM
@Sophia Ling Apologies, but turns out we might have to interview you again. Can you let us know your availability this week?

**Comment by priyatalwar** [comment]
Update 9/1/21
Reached out to Sophia via email:

Hello Sophia,

I've been asked to reach out to you to discuss your availability for an interview (sorry we have to interview you again!) about your experience at Hack for LA. Can you please let me know a few available times this week?

Thanks,
Priyanka

**Comment by ExperimentsInHonesty** [comment]
sent her an email about scheduling interview

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty:
@Rabia2219 and I just went over the interview together and didn't find any repetition. We definitely found that a few of the questions were missing according to this [questionaire](https://docs.google.com/document/d/15RI126KEeUqycfGUClKT3Q-xFZScwHuMz8KsYxEnMns/edit)

**Comment by priyatalwar** [comment]
Update 9/5: Heard back from Sophia:
"Hello,
I'm so sorry I didn't reply earlier. School started for me last week, so I've been a bit busy. Would this Tuesday work for you?
-Thank you"

@priyatalwar replied:
No worries. I’m available 9am - 1pm PDT tomorrow. Would any time in that window work for you? 

-Priyanka

**Comment by priyatalwar** [comment]
9/7 update:

Interview scheduled and invite sent for 9/7/21 at 1 pm PDT. @ExperimentsInHonesty has offered to help with recording.

**Comment by priyatalwar** [comment]
9/7 update: Sophia did not show up and tried reaching her via slack, text and email. @ExperimentsInHonesty will try reaching out to her as well, but here is an email I just sent:

Hi Sophia,
Since today did not work out, we'd like to reschedule. Won't need much of your time since they are mostly additional questions that we asked other interns as well. If you can give us 20 minutes of your time, would be great. 
I know school can get so busy, so what is the best way to send you a reminder for our meeting?

Thanks,Priyanka

**Comment by priyatalwar** [comment]
Update: 9/7
Heard back from Sophia and interview scheduled at 5 pm PDT tomorrow
@ExperimentsInHonesty if you can help with the recording. Thanks!

**Comment by priyatalwar** [comment]
Update: 9/8
Interview done; transcript uploaded; @ExperimentsInHonesty please upload recording

**Comment by sniux** [comment]
@ExperimentsInHonesty please upload the interview so that I can proceed with the insights and create a slide deck.

**Comment by ExperimentsInHonesty** [comment]
@sniux I have uploaded the Sophia second interview session recording and transcript link is above

**Comment by priyatalwar** [comment]
Update: @ExperimentsInHonesty @sniux Closing this issue since we have everything we need.
