### ISSUE TITLE
Create Variables SASS file

### ISSUE THREAD

**Issue by sunannie27** [hackforla/internship#462]
### Dependencies
- [ ] #397 
- [ ] #455 

### Overview
We need to create a variables sheet which contains variables for our design system so that it is easily customizable by teams down the road.

### Action Items
- [x] Create a _variables.scss within the sass directory
- [x] Import this file into the main.scss file
- [x] Add all color variables from the design system
- [x] Add typography variables
- [x] Add button styling variables
- [x] Merge changes into the github pages branch

### Resources/Instructions
- Part of epic #444 
- [Sass variables documentation](https://sass-lang.com/documentation/variables/)

**Comment by joshfishman** [comment]
This is being closed, File is created, further variables will be created on a per component basis
