### ISSUE TITLE
TWE Design System Components: Review Figma files from other projects

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#468]
### Overview
We must review all previous Figma files from other projects to assess if we're missing any design components for the Internship Project Design System.

### Action Items
- [x] Go through all the Figma files in the resource section
- [x] Assess which components are missing from our backlog
- [x] Create a new issue for the missing component (if any)
- [x] Add the new issue created to the dependency on https://github.com/hackforla/internship/issues/397
- [x] After reviewing all the Figma files and creating all the necessary issues for the Design System, close this issue

#### Project Figma Files

- [x] [100 Automations](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)
- [x] [311 Data](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5)
- [x] [Access the Data](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A2)
- [x] [Ballot Nav](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=1313%3A56178)
- [x] [BOP](https://www.figma.com/file/XEr9WwIWKCVLaUZh5VQhXw/BOP-Design?type=design&mode=design&t=9EHiNKY6yn4q6WNU-0)
- [x] [Civic Opportunity ](https://www.figma.com/file/ROnzMyb5fgjYp058Po81Y4/Civic-Opportunity?node-id=0%3A1)
- [x] [Civic Tech Index](https://www.figma.com/file/EFoSuj1b9G4aZ7bN8OX8tf/CivicTechIndex---Master-Design-File?node-id=4225%3A16898)
- [x] [Civic Tech Structure](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A6)
- [x] [Design Systems](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma)
- [ ] Engage
- [x] [Expunge Assist](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=0%3A1)
- [x] [Food Oasis](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2591%3A0)
- [x] [Green Earth OS](https://www.figma.com/file/NmGW74xkCaKCZT6VDutPXU/GreenEarthOS?node-id=0%3A1)
- [x] [Guides ](https://www.figma.com/file/Jz8KoGTBIxdx9jRxBWrEsF/Guides-Team-Figma)
- [x] [HackforLA Website](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465)
- [x] [Home Unite US](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1%3A8)
- [x] [Lucky Parking](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=0%3A1)
- [x] [Open Community](https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=0%3A1)
- [x] [TDM Calculator](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=103%3A0)
- [x] [VRMS](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24265%3A2429)
- [ ] Write for All
- [x] [Youth Justice Nav](https://www.figma.com/file/w09Q2qw2HffJLQsyRzCDN1/Untitled?node-id=1%3A2)

**Comment by ExperimentsInHonesty** [comment]
@karina-sato Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by karina-sato** [comment]
Progress: Reviewed 5 project Figma files.
Blockers: n.a.
Availability: 0.5-1h/day
ETA: First week of Nov

**Comment by karina-sato** [comment]
List of missing components:
- Banners (Access the Data project)
- Search bar (Access the Data project)
<img width="853" alt="image" src="https://github.com/hackforla/internship/assets/140572674/718df22f-5056-461c-8bb2-b5e495bd1c1d">
<img width="689" alt="image" src="https://github.com/hackforla/internship/assets/140572674/d310ceab-d2d4-4ce2-b7ef-6d79db43c90c">

Reviewed 24.10.23:
- Civic Opportunity
- Civic Tech Index

**Comment by karina-sato** [comment]
Progress: reviewed: Civic Tech Structure, HfLA Design System

add to list of components: 
- Guide cards
- Large icon page cards
- Side nav
<img width="454" alt="image" src="https://github.com/hackforla/internship/assets/140572674/c7ad5ebd-f79f-4c03-af10-ac0b63be1392">
<img width="250" alt="image" src="https://github.com/hackforla/internship/assets/140572674/5edf7e1f-252d-451d-9aa1-52479900b43b">

**Comment by karina-sato** [comment]
Progress:
- Expunge assist (ref: well organized)
- Food Oasis
- Green Earth
- Guides

add to the list of components:

- n.a.

**Comment by karina-sato** [comment]
**Progress:**
HackforLA Website
Lucky Parking (great example of search bar and banner)
Open Community
TDM Calculator
VRMS

**Blockers:** 
no link on "Engage" and "Write for All"
no access to "Home Unite US"

**Add to the list of components:**
n.a.

**Comment by karina-sato** [comment]
Progress:
- Home Unite US
- Youth Justice Nav

Add to the list of components:
- Feedback
- Stepper
<img width="797" alt="image" src="https://github.com/hackforla/internship/assets/140572674/21da17c2-3361-4ac9-9b06-c707e6ec57e0">
<img width="705" alt="image" src="https://github.com/hackforla/internship/assets/140572674/e86a14d5-7db7-4476-ae6e-a4ae920d2ac6">

Blockers:
no link on "Engage" and "Write for All"

**Comment by karina-sato** [comment]
Issues created: 
- Feedback alert
- Banner
