### ISSUE TITLE
Update Report Template's Footer

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#473]
### Overview
We need to update the TWE Report Template's footer with "a project of Civic Tech Structure"

### Action Items

- [x] Update copywriting in the Figma file
- [x] Export image
- [x] Substitute the old footer with the new exported image into the Report Template

### Resources/Instructions
- [Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/edit)
- [Figma File](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-35&mode=design&t=PZvQFZfmIhNRH6fI-0)

**Comment by karina-sato** [comment]
1. Progress: Updated on Figma and Doc template
2. Blockers: -
3. Availability: -
Link: https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/edit

**Comment by ExperimentsInHonesty** [comment]
LGTM. Thanks!
