### ISSUE TITLE
TWE: IS21: RP001: intern Exit Interview Recordings: De-identify: Intern 004

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#479]
### Dependencies  
~~- [ ] All the user interview issues have been created~~ IS21 didn't set up those issues, but all interviews were conducted. See [TWE: IS21: RP001: Intern Exit Interview Roll Call and Session Table](https://docs.google.com/spreadsheets/d/1dTlIOhtZ5fCNo0GrfKHlOTbdvsRlPUaLIfHk8Cc7Zrw/edit?usp=sharing)
~~- [ ] Interview Recording Upload Form needs to be created~~ The interviews were conducted before we set up the upload form, so it doesn't apply in RP001's case
- [x] Interview recordings have been uploaded and moved into Internship - PII's "My Drive"
- [x] Interview transcripts have been created

### Overview 
We need to clean up and de-identify RP001's Intern Exit interview transcripts so that we can move on to the data analysis and insights generation phase. 

During these tasks, you will be asked to add links to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them.

### Action Items
- [x]  UX lead adds the assignee to the Internship - PII's "My Drive" as a Contributor so that they have access to Internship - PII's My Drive where the recordings and transcripts with PII are stored.
   - [x] UX lead accesses the Internship - PII's "My Drive"
   - [x] Choose "Manage members", which is located towards the top right side of the browser <img width="200" alt="Screenshot 2023-08-09 at 6 09 36 PM" src="https://github.com/hackforla/Internship/assets/57029070/f7cc7fbe-1b00-4ded-8b44-b10fdbccae46">
   - [x] Enter the assignee's email address and select the role as "Contributor" <img width="300" alt="Screenshot 2023-08-09 at 6 11 40 PM" src="https://github.com/hackforla/Internship/assets/57029070/41ab3531-75b1-435a-836a-1b24be3ecb69">
   - [x] Confirm with the assignee that they have access to the Internship - PII's "My Drive" 

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Find relevant wiki page for RP001
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Type Folder (Resources # 1.02)
    - [x] Choose the `Intern` folder
    - [x] Choose the `RP001` folder
    - [x] Copy the link of the `RP001` folder
        1. Choose the three vertical dots on the right side of the `RP[Replace 000]` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recordings and Transcriptions Tracking Sheet
    - [x] Open the Research Plan's Google Drive folder in the Internship's shared drive (Resource # 2.02)
    - [x] Locate the `TWE: IS21: RP001: Intern Exit Interview Recordings and Transcriptions Tracking Sheet` in the folder
    - [x] Copy the link of `TWE: IS21: RP001: Intern Exit Interview Recordings and Transcriptions Tracking Sheet`
        1. Choose the three vertical dots on the top right side of the file  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recording Folder stored in the Internship - PII's `My Drive`
    - [x] Log into your Google account so you will be able to access the Internship - PII's 'My Drive' in the next steps
    - [x] Choose Shared drives > Internship - PII > Internship -PII
    - [x] Choose `TWE Interview Recordings by Plan #` folder in Internship - PII's `My drive` (Resources # 1.03) 
    - [x] Locate the video recording folder for RP001 inside the folder `TWE Interview Recordings by Plan #`
    - [x] Copy the link of the video recording folder for RP001 
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
 
- Customize Resource for the De-identified Transcripts Folder in the Shared Drive 
    - [x] Go to RP001 folder (Resources # 2.02)
    - [x] Locate the `RP001 De-identified Transcripts` folder
    - [x] Copy the link of the folder
        1. Choose the three vertical dots on the right side of the folder <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resources for the Recording and Transcript you are Assigned to
    - [x] Check the title of this issue to identify the participant number, which comes after `De-identify:`
    - [x] Open the `TWE: IS21: RP001: Intern Exit Interview Recordings and Transcriptions Tracking Sheet` (Resources # 2.03)
    - [x] Locate the recording video in .mp4 format that matches the participant number in Column B of the tracking sheet
    - [x] Copy the link of the recording that matches the participant number in Column B of the tracking sheet
    - [x] In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Locate the transcript in .txt format that matches the participant number in Column C of the tracking sheet
    - [x] Copy the link of the .txt file that matches the participant number in Column C of the tracking sheet
    - [x] In Resources # 2.07, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Prepare for cleaning up and de-identification by converting the .txt file into a Google Doc
        1. Click on the link in Column C `Transcription Link` that matches the participant number (Resources # 2.07)
        1. Choose `Open with Google Docs` [![Screenshot 2023-01-06 at 11 04 38 AM](https://user-images.githubusercontent.com/57029070/211081813-b49a22f4-1de2-4a5f-a10a-e7c7686ae1d0.png)](https://user-images.githubusercontent.com/57029070/211081813-b49a22f4-1de2-4a5f-a10a-e7c7686ae1d0.png)
        1. A Google Doc is generated in a new window with the same .txt file name 
        1. The Google Doc is now saved into the same folder with the corresponding video and .txt file
        1. Open the RP001 Interview Recording folder (Resources # 2.04)
        1. Open the corresponding folder for Intern 004 and check to make sure a Google Doc transcript has been created
   - [x] Make a copy of the Google Doc that was just generated and rename it
        1. Choose the three vertical dots on the top right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Make a copy"
        1. A copy of the Google Doc is generated in the same folder       
        1. Copy 
        ```
        To be de-identified-
        ``` 
        1. Go back to the folder where a copy of the Google doc was created
        1. Choose the three vertical dots on the top right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Rename"
        1. Remove `Copy of` from the file name when the Rename text box pops up
        1. Paste what you copied into the beginning of the file name text box
        1.  Choose "Ok" 
    - [x] Copy the link of the "to be de-identified" Google Doc transcript you just created
        1. Choose the three vertical dots on the top right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.08, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### Clean up and de-identify the transcript
- [x] Open the Google Doc transcript if it is not open yet (Resource # 2.08)
- [x] Listen to the recording to get yourself familiar with the transcript
- [x] Listen to the recording again and clean up the inaccuracies in the transcript as you read along
    - [x] Separate the texts based on speakers and timestamps (timestamps should match the video file timestamps in case a researcher needs to go back and double-check the original video)
    - [x] Add any missed words
    - [x] Edit any typos and misidentified words
    - [x] Deleted repeated words
    - [x] Remove verbal filler words such as "um" and "uh" if they don't serve any purpose
        - Sometimes the verbal fillers can indicate the interviewee's emotions or thoughts. In this case, provide context in square brackets to demonstrate the emotions or thoughts (e.g., [The participant hesitated for a while before coming up with the answer]).
    - [x] Where needed, add context in square brackets so that a reader could understand what was happening without watching the video (e.g., [steps off camera])
- Read through the transcripts again and make edits to de-identify any personal information
    - [x] Search for the participant's name 
    - [x] Replace with their participant number, i.e. I001
    - [x] Search for unknown speakers in the transcript
    - [x] Replace unknown speaker with UXR number or other participant type/number
    - [x] Read through the transcripts to search for any identifiable information in the interview
    - [x] Replace any personal identifiable information with non-identifiable terms. For example, if someone's name is mentioned, we should use their roles inside square brackets so the reader knows this information was redacted (e.g., [team member], [peer], [mentor], [manager]). If their specific school is mentioned, we should redact that info with either [high school] or [college].
    - [x] If they mentioned any specific issues they worked on, make sure to remove the issue numbers and rephrase the issues they worked on
- Read through the edited transcripts again
    - [x] Focus on punctuation, readability, and formatting.
- When you're satisfied that the transcript is completely deidentified
    - [x] Click on the version history and select the most current version
    - [x] Click the three dots <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/Internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96"> and select "Make a copy", and the "Copy version" window pops up
    - [x] In the "Name" text box, remove the "Copy of" text at the beginning and the timestamp at the end from the file name
    - [x] Copy 
    ```
    De-identified Interview Transcript-
   ```
    - [x] Paste the text you just copied in front of the file name in the "Name" text box
        - The new file name should be formatted like "De-identified Interview Transcript-RP001-UX Researcher Abbreviation###-Intern Abbreviation###"
        - An example: "De-identified Interview Transcript-RP006-U007-I001" 
    - [x] Save the renamed de-identified Google doc transcript into the `RP001 De-identified Transcripts` folder. This is to make sure that the version history does not include any identifiable information.
        1. Click the folder icon under "Folder"
        1. Choose "All locations"
        1. Choose Shared drives > Internship > Internships > Research > Research by Type > Intern > folder for RP001 > RP001 De-identified Transcripts
        1. Choose "Select"
        1. Select "Make a copy"
        1. The copy of the file is generated in a new browser
        1. Dismiss the notification that says the file is now in the shared drive
    - [x] Copy the link of the de-identified transcript in the shared drive
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] Paste what you copied into the matching participant's cell in Column D `Transcription Link - de-identified` in the tracking sheet (Resources # 2.03)
    - [x] In Resources # 2.09, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

 
#### 
- [x] Review with UX Lead
- [ ] Product sign-off
- [ ] UXR Lead or PM removes the assignee from the Internship - PII's My Drive when closing the issue if the assignee no longer needs to access the PII drive.

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/Internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03* [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=sharing)
1.04 [Guidelines to Interviews Page 8](https://drive.google.com/open?id=19580_-BXfHPC9gTcAj35O2nzAtdNwTxp&disco=AAAA_U2KB_A)
1.04.01 [Brackets vs. Parentheses](https://www.strose.edu/wp-content/uploads/2015/10/Brackets-Handout-Cynthia2.pdf)
1.04.02 [Video folder](https://drive.google.com/drive/folders/1WPzYSrhWYluIqigjsHKpSYIhpQf7XcM5)
1.04.03 [Cleaning Up Zoom Transcriptions for Qualitative Research](https://crdpala.org/2022/10/05/cleaning-up-zoom-transcriptions-for-qualitative-research/)
1.04.04 [Determining Best Practice for Filler Words in Captions and Transcripts](https://blogs.vcu.edu/birdlab/2020/01/09/determining-best-practice-for-filler-words-in-captions-and-transcripts/)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan: RP001](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)
2.02 [Google Drive Folder: RP001](https://drive.google.com/drive/folders/1uKUY_izpds3dHInNkiexZsU32ELF_Hze?usp=sharing)
2.03 [TWE: IS21: RP001: Intern Exit Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1Uw_KFUQ3n8DJrxwbc3vnMD8stgF6kTIwSUn5yP9xFuc/edit?usp=share_link)
2.04* [RP001 Interview Recording Folder](https://drive.google.com/drive/folders/1R8sXXGrx47PNj2GpMSUIpMXYllAEgy19?usp=sharing)
2.05 [RP001 De-identified Transcripts Folder](https://drive.google.com/drive/folders/1A2crr41KWwnoCvdtwmwJnmoP0IzH1Z54?usp=sharing)
2.06 [Intern 004 Recording Link](https://drive.google.com/file/d/1K58phuK_BI5GiCgGRm6V6-_dQkDp2GzP/view?usp=drive_link)
2.07 [Intern 004 Transcript .txt File](https://drive.google.com/file/d/1Yu-2PQsl5QdJAuFNq-lTdCscuY8z7ey4/view?usp=drive_link)
2.08 [Intern 004 To be De-identified Transcript Google Doc](https://docs.google.com/document/d/1Fbe3bJc9SXvzOe066pxRn8GchEngeWRnHvx6HsI39TI/edit?usp=share_link)
2.09 [Intern 004 De-identified Transcript Google Doc](https://docs.google.com/document/d/1KNGoNUrcHg2F0wFJs9yE5_ERU-ro_N52/edit)

*This folder can only be accessed from the Internship - PII's "My Drive"

**Comment by pandanista** [comment]
@jessieliu1219 I am assigning you to this issue. Let me know if you could access it.

**Comment by jessieliu1219** [comment]
@pandanista Hi Ying, I've finished this task. In the final folder for the de-identified file, I accidentally made a copy and don't have access to delete it. When you see it, you can just delete the one with the name start as Copy of...

**Comment by pandanista** [comment]
Hi @jessieliu1219, thank you for working on this issue. I've deleted the copy of the file, thank you for letting me know about this. 

One question and one suggestion:
- There are two de-identified transcripts. One of them is in [intern #4's folder](https://drive.google.com/drive/folders/1P1eLdZOuXjI6V6X9saUOuWpEbPRNx-3g?usp=share_link), and the other one is [de- identified transcripts folder](https://drive.google.com/drive/folders/1A2crr41KWwnoCvdtwmwJnmoP0IzH1Z54?usp=share_link). Any idea what steps caused the transcripts to be made twice? I want to make sure to incorporate any changes needed in the template so there won't be 2 de-identified transcripts in both folders ideally.

-  I reviewed the transcript, and there were parts that still need some cleaning up so the transcript is readable to anyone. Would you please make some more edits while watching the video? See some examples below.
<img width="623" alt="Screenshot 2023-10-24 at 12 36 37 PM" src="https://github.com/hackforla/internship/assets/57029070/02b248cf-ab77-4636-a9af-6ccd39bf8881">
<img width="167" alt="Screenshot 2023-10-24 at 12 36 04 PM" src="https://github.com/hackforla/internship/assets/57029070/4a7728b3-8187-40c3-9a86-4915a8ea4a4e">
    - In the first example, you can take out the redundant part-"but they so".
    - In the second example, there is some punctuation missing, and the grammar part of the second half of the sentence doesn't make sense. Did the interview say "made", "make", or "meet"? 

Thank you so much for your contribution!

**Comment by jessieliu1219** [comment]
Hi @pandanista, Sure, I will double-check again for the grammar issues.
And yes, the duplicate file in a different folder issue: I originally worked in the intern 4 folders, and it seems like I don't have access to move or delete it in this share drive either. See the screenshot below, which shows the move button (it was listed in the instruction above but is grey and doesn't work. I have to download and re-upload to the other share drive. So, it might be an access issue.
<img width="692" alt="Screen Shot 2023-10-24 at 4 39 29 PM" src="https://github.com/hackforla/internship/assets/116132470/ba6ad45c-ae00-47c1-9658-22a1d6349290">

**Comment by pandanista** [comment]
@jessieliu1219 Gotcha. I will remove the duplicated file from the Intern #4 folder.

**Comment by pandanista** [comment]
Also, those videos in the [video folder](https://drive.google.com/drive/folders/1WPzYSrhWYluIqigjsHKpSYIhpQf7XcM5) might be helpful for the de-identification and the cleaning up too.

**Comment by jessieliu1219** [comment]
Hi @pandanista, I've edited the document again (using resource 2.09).

**Comment by pandanista** [comment]
Thank you for working on this issue, @jessieliu1219. I will review it and let you know if I have any questions.

**Comment by pandanista** [comment]
@jessieliu1219: I just reviewed the transcript. Overall, it looks good. I did clean up some more punctuation and added some `[ ]` to either provide some missing information that is important to the context of the transcript or to correct a sentence. 

I know it is your first time doing cleaning up and de-identification on qualitative research, one thing I'd like to point out is to get familiar with the use of brackets `[ ]` and parenthesis `( )` and understand their differences to know when to use which one. Here is [a good source](https://www.strose.edu/wp-content/uploads/2015/10/Brackets-Handout-Cynthia2.pdf) that can help you grasp how to use them properly in the future.

Thank you so much for working on this issue!

**Comment by sunannie27** [comment]
@pandanista We saw the ready for product label but are unclear what you want us to do specifically

**Comment by AndrewSalvatore** [comment]
Hi @jessieliu1219,

In today's all-team, we reviewed the deidentified transcript's format and decided to go with the 'in-line' format with the names "Interviewer" and "Intern ###" seen [here in Intern 001's transcript](https://docs.google.com/document/d/1C8-qEAot7Sw5rhpfuplP0D0SLxypdChUigC1u7LCWJA/edit)

Please go through the deidentified transcript for this subject (004) and correct the formatting to match.

Thank you!
Drew

**Comment by jessieliu1219** [comment]
Hi @AndrewSalvatore, 
I've updated the file in resource 2.09 to make it go with the "in-line format".
Best,
Jessie

**Comment by pandanista** [comment]
Thank you, @jessieliu1219, for the update.

@sunannie27 The changes in formatting have been incorporated, please see the updated de-identified transcript linked in Resources # 2.09. Let me know if there is anything else needed. Otherwise, we can close this issue after Product's final review.

**Comment by sunannie27** [comment]
Bonnie hasn't reviewed the entire thing but she added a bunch of comments, please see the general nature of the comments and look at the document.
- Punctuating things properly
- Use the grammarly add on
- Eliminate verbal tics

**Comment by pandanista** [comment]
@jessieliu1219 We have decided at the all-team meeting today, that instead of Grammarly, please use [LanguageTool Chrome Extension](https://chrome.google.com/webstore/detail/grammar-checker-paraphras/oldceeleldhonbafppcapldpdifcinji) to clean up the punctuation and verbal ticks in the transcript. Thank you very much!

I've copied Resources 1.04 below for easy reference on how to clean up the interview transcripts.
1.04 [Guidelines to Interviews Page 8](https://drive.google.com/open?id=19580_-BXfHPC9gTcAj35O2nzAtdNwTxp&disco=AAAA_U2KB_A)
1.04.01 [Brackets vs. Parentheses](https://www.strose.edu/wp-content/uploads/2015/10/Brackets-Handout-Cynthia2.pdf)
1.04.02 [Video folder](https://drive.google.com/drive/folders/1WPzYSrhWYluIqigjsHKpSYIhpQf7XcM5)
1.04.03 [Cleaning Up Zoom Transcriptions for Qualitative Research](https://crdpala.org/2022/10/05/cleaning-up-zoom-transcriptions-for-qualitative-research/)
1.04.04 [Determining Best Practice for Filler Words in Captions and Transcripts](https://blogs.vcu.edu/birdlab/2020/01/09/determining-best-practice-for-filler-words-in-captions-and-transcripts/)

**Comment by pandanista** [comment]
Also, let's use the following format for all the timestamps: 
00:00:00

**Comment by pandanista** [comment]
@jessieliu1219 Welcome back, and hope your 2024 is off to a good start.

Would you please provide an update?
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" - we know you just came back from break, please just summarize the progress from before then
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by jessieliu1219** [comment]
@pandanista, hi Ying, I have also worked on this Intern 004 file, changed it to six digit timestamp version, checked with the LanguageTool, changed to in-line format, and checked with numerical values.

**Comment by pandanista** [comment]
@jessieliu1219 Hi Jessie, thank you for working on the Intern 004's transcript. I noticed there are still a lot of comments/suggestions that are not resolved on the document in 2.09. Would you please resolve the suggestions?

Please make sure to follow the resources and guidelines in [comment 1](https://github.com/hackforla/internship/issues/479#issuecomment-1834394298) and [comment 2](https://github.com/hackforla/internship/issues/479#issuecomment-1834405446) above to clean up the transcripts so we can stay consistent in cleaning up the transcripts. 

Thank you.
<img width="1396" alt="Screenshot 2024-01-16 at 3 04 50 PM" src="https://github.com/hackforla/internship/assets/57029070/23d13014-37e0-4866-b83d-3301852be006">

**Comment by pandanista** [comment]
### Action Items for Peer Review
- [ ] Review this issue
     - [ ] Read the issue overview to learn about why this document was created.
     - [ ] Locate draft of the document in the Resources.
- [ ] Review resources in 1.04 for easy reference on how to clean up the interview transcripts (those resources are listed below for easier access)
    - [ ] 1.04 [Guidelines to Interviews Page 8](https://drive.google.com/open?id=19580_-BXfHPC9gTcAj35O2nzAtdNwTxp&disco=AAAA_U2KB_A)
        - [ ] 1.04.01 [Brackets vs. Parentheses](https://www.strose.edu/wp-content/uploads/2015/10/Brackets-Handout-Cynthia2.pdf)
        - [ ] 1.04.02 [Video folder](https://drive.google.com/drive/folders/1WPzYSrhWYluIqigjsHKpSYIhpQf7XcM5)
        - [ ] 1.04.03 [Cleaning Up Zoom Transcriptions for Qualitative Research](https://crdpala.org/2022/10/05/cleaning-up-zoom-transcriptions-for-qualitative-research/)
        - [ ] 1.04.04 [Determining Best Practice for Filler Words in Captions and Transcripts](https://blogs.vcu.edu/birdlab/2020/01/09/determining-best-practice-for-filler-words-in-captions-and-transcripts/)
- [ ] Review the de-identified transcript
     - [ ] Preview the draft quickly to get a sense of how the draft is structured and the type of content.
     - [ ] Review the structure of the draft to ensure that the headings (in a Google Doc) or columns (Google Sheet) are clearly identified. 
     - [ ] Install [LanguageTool Chrome Extension](https://chrome.google.com/webstore/detail/grammar-checker-paraphras/oldceeleldhonbafppcapldpdifcinji) to clean up the punctuation and verbal ticks in the transcript.
     - [ ] A few guidelines on the transcript formatting:
         1. Use the 'in-line' format as seen [here in Intern 001's transcript](https://docs.google.com/document/d/1C8-qEAot7Sw5rhpfuplP0D0SLxypdChUigC1u7LCWJA/edit)
         1. Use 6 digit format for all the timestamps, for example, 01:01:01 as hour one/minute one/second one
         1. Use "Interviewer" and "Intern ###" throughout the transcript. See an example [here in Intern 001's transcript](https://docs.google.com/document/d/1C8-qEAot7Sw5rhpfuplP0D0SLxypdChUigC1u7LCWJA/edit).
            - If there were more than two people recorded on the transcript, name the third person based on the interview set-up or context, such as Program Manager, Note Taker, etc. If you are not sure what to name them, ask leads on the project to clarify.
          1. If there are other numerical values in the transcript, transcribe them using texts. For example, if a time such as 6:30 is mentioned, type out six thirty when cleaning up the transcript. Another example is if the interviewee mentioned he mainly sought help from 3 other peers, type out "three" instead of using the number "3".
- [ ] Provide feedback
     - [ ] Add feedback in the form of (1) questions and/or (2) explicit instructions for how the content should be improved. Feedback in a Google Doc should be given in the form of document comments. 
     - [ ] If there are edits to be made, please use "suggesting mode" in Google doc instead of "editing mode".
     - [ ] Determine the accuracy of the content for each section (Google doc). If you find an inaccuracy, error, or mis-categorization, explain how the information presented could be improved.
     - [ ] For each suggested improvement, provide a link or reference within your comment to justify your suggestion (if available).
- [ ] Once all the steps have been completed, reach out to the original owner of this issue or the UX Lead to determine if they can complete the next steps in the issue.

**Comment by adarosh** [comment]
@pandanista Ying and I discussed directions for completing this issue on 2/20. Will provide progress update at next meeting.

**Comment by pandanista** [comment]
There is one minor change for the transcript cleaning up process, and thank you for being so patient with us, @adarosh.

Would you please update "interviewer" with "UXR 002" in [intern 004's transcript](https://docs.google.com/document/d/1KNGoNUrcHg2F0wFJs9yE5_ERU-ro_N52/edit?usp=sharing&ouid=102269205411863065760&rtpof=true&sd=true)? Much appreciated!

We decided to include the UXR numbers in the transcripts because 1). there might be different probing questions for semi-structured interviews from different interviewers, and 2). it will be easier to reference the UXR when doing analysis or making highlight reels (if needed).

**Comment by AndrewSalvatore** [comment]
> There is one minor change for the transcript cleaning up process, and thank you for being so patient with us, @adarosh.
> 
> Would you please update "interviewer" with "UXR 002" in [intern 004's transcript](https://docs.google.com/document/d/1KNGoNUrcHg2F0wFJs9yE5_ERU-ro_N52/edit?usp=sharing&ouid=102269205411863065760&rtpof=true&sd=true)? Much appreciated!
> 
> We decided to include the UXR numbers in the transcripts because 1). there might be different probing questions for semi-structured interviews from different interviewers, and 2). it will be easier to reference the UXR when doing analysis or making highlight reels (if needed).

@pandanista Done

**Comment by pandanista** [comment]
Appreciate it, @AndrewSalvatore!

**Comment by adarosh** [comment]
Updated @pandanista on progress in UXR meeting on 3/12. Will have transcript completed for next meeting.

**Comment by adarosh** [comment]
@pandanista - see below for update. Thanks!

Progress:
Made edits throughout document- there were a lot of corrections needed based on the audio.
Reviewed/resolved suggested edits.
I have some additional feedback and questions- will discuss in UXR meeting.

Blockers: Review edits/feedback with Team Lead at next UXR meeting.

Availability: N/A

ETA: N/A

Pictures or links* (if necessary): N/A

**Comment by pandanista** [comment]
@adarosh Thank you for this thorough review!

@sunannie27 Please review [Intern 004's transcript](https://docs.google.com/document/d/1KNGoNUrcHg2F0wFJs9yE5_ERU-ro_N52/edit?usp=sharing&ouid=102269205411863065760&rtpof=true&sd=true). Let us know if you have any question. Thank you.

**Comment by ExperimentsInHonesty** [comment]
@adarosh The transcript is very readable now.  Thank you for your efforts on this recording as well as improving the overall instructions for doing de-identification.  

There was only one thing that came up, while I was reviewing, and that is, that while we want to de-identify the people who helped them, we still might need to know if the same person helped multiple interns, so we think we need to keep the information on a spreadsheet and give the hack for LA website team members and mentors a number.  We will also use this information to interview them about their experience with the intern.  Ying can provide guidance on where to put this spreadsheet and the information to be collected.

**Comment by pandanista** [comment]
@adarosh Appreciate your wonderful work on the transcript. As a follow-up on this issue, please fill out anyone that was mentioned by the interns in [this spreadsheet](https://docs.google.com/spreadsheets/d/1N76q5QlU8y2O1Eop2iQXWGoQUzTXHQZ2PCDlI6LH2Xc/edit?usp=sharing).

- [ ] Please go through the transcript and identify any name that was mentioned by the intern during the interview
- [ ] Fill out the names being mentioned, and list out all the relavant information in the spreadsheet. No need to include intern and the UXR names since we track them in the roll call and session table.
    - [ ] Please check each participant type's abbreviation under the "Research Documents by Participant Type" section of [the Research Output Overview Wiki Page](https://github.com/hackforla/internship/wiki/Research-Output-Overview). For example, mentor is M.
    - [ ] The participant numbers are sequential based on the time of entry and occurrence of the mention. I.e. if there are already two Hack for LA website team members being listed previously in the spreadsheet, then the next Hack for LA website team member will be HfLAWTM003.
    - [ ] If the name is already included in the sheet because other interns have mentioned them, please still list out their names and relavent informatioon. Also, for the people who were mentioned repeatly, please make sure to use the same role and the same participant number that are already assigned so we can keep track of the people being mentioned across all interviews.
    - [ ] If you are not sure of the roles of any of the names mentioned, please leave the role column and the participant number column blank, and tag the UXR lead for clarification.   
- [ ] After listing out the names and their relavant informatioon, use search and replace function in Google Doc to replace the names with the participant number assigned to them.

Let me know if you have any questions. Thank you.

**Comment by ExperimentsInHonesty** [comment]
@adarosh Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by adarosh** [comment]
Hi @ExperimentsInHonesty and @pandanista - revisions are complete and team members mentioned in the interview have been logged in the spreadsheet. Let me know if any other edits are needed!

Progress: Transcript revisions and de-identification are complete. Team members mentioned in interview have been logged in the spreadsheet.
Blockers: N/A
Availability: N/A
ETA: Revisions are complete.
Pictures or links* (if necessary): N/A

**Comment by pandanista** [comment]
Thank you, @adarosh!

Two spreadsheets are created to track the list of people intern mentioned in their interviews:
- [TWE: IS21: RP001: Participants List from Interviews (Interns & UXR Excluded)](https://docs.google.com/spreadsheets/d/1N76q5QlU8y2O1Eop2iQXWGoQUzTXHQZ2PCDlI6LH2Xc/edit?usp=share_link) is saved in the PII drive since it contains PII
- [TWE: IS21: RP001: De-identified Participants List from Interviews (Interns & UXR Excluded)](https://docs.google.com/spreadsheets/d/1wORsE1sZLtX4T6gbbXqnWEfudJh1ZIE05dE4rpFSoYU/edit?usp=share_link) is saved on the shared Research folder in Google Drive after de-identification.

@sunannie27 We can close this issue if the information from Intern 004's interview are sufficiently documented in the two spreadsheets.

**Comment by sunannie27** [comment]
@pandanista I reviewed the links. Do we need first and last names for participant name in the participants list -- NOT de-identified? Just wondering, if not, it all looks good to me.

**Comment by pandanista** [comment]
@sunannie27 
- Are you referring to this spreadsheet - [TWE: IS21: RP001: Participants List from Interviews (Interns & UXR Excluded)](https://docs.google.com/spreadsheets/d/1N76q5QlU8y2O1Eop2iQXWGoQUzTXHQZ2PCDlI6LH2Xc/edit?usp=share_link)? 
    - This one is saved in the PII drive because it contains PII
    - We have the de-identified sheet saved in the Research folder in Google Drive, see [TWE: IS21: RP001: De-identified Participants List from Interviews (Interns & UXR Excluded)](https://docs.google.com/spreadsheets/d/1wORsE1sZLtX4T6gbbXqnWEfudJh1ZIE05dE4rpFSoYU/edit?usp=share_link).

**Comment by pandanista** [comment]
Closing this issue since it is now completed, and we addresses PM's question above.
