### ISSUE TITLE
TWE Design System: Standardize best practice around including code

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#482]
## Overview

We need to determine the best practices for including the code blocks in the page.

### Action Items 
- [ ] Do we include SASS? Variables
- [ ] Can we automate the code generation?

_Originally posted by @jnomad21 in https://github.com/hackforla/internship/issues/457#issuecomment-1766961745_

**Comment by joshfishman** [comment]
This seems to be the process

**Prequisite**
Add [snippets](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets) and [code block with code numbers and syntax highllighting ](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines-line-ranges
) functionality to the project

**Process**
1. Create HTML and SCSS files for each component.
2. Create this component into the microsite page
4. Include HTML & SCSS files in a tabbed code block

**Comment by joshfishman** [comment]
@jnomad21  Take a look at this and see if it is clear

**Comment by ExperimentsInHonesty** [comment]
- This issue is completed with the creation of #491
