### ISSUE TITLE
Publish Design System Draft to Github pages

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#485]
### Overview
We need to change the settings of our repo so that we can publish our in progress work on the microsite

### Action Items
- [x] Get repo access (Josh now has admin access)
- [ ] Publish Site to github pages

### Resources/Instructions
[Github Pages Quickstart](https://docs.github.com/en/pages/quickstart)

**Comment by ExperimentsInHonesty** [comment]
We decided to create a new repo https://github.com/hackforla/internship-website-design-system, so that the new repository can have ghpages to display the content of the draft design system.

@joshfishman will write a draft of the readme for the new repo.

**Comment by ExperimentsInHonesty** [comment]
Tyler needs admin access

**Comment by ExperimentsInHonesty** [comment]
- Closing this issue as unplanned because it's a duplicate of https://github.com/hackforla/internship/issues/561
