### ISSUE TITLE
TWE Design System: Code Typography 

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#487]
### Dependencies
- #528

### Overview
We need to code the Typography Component for our design system based on the design teams' completed Figma component. Then we need to connect the code to the Figma component

### Action Items
- [x] Pull internship repo
- [x] Create a feature branch
- [x] Determine if any JS or CSS hacks need to be included to style this component
- [x] Include necessary files in the MKdocs docs/ folder and project config
- [x] Code component in its own HTML and sass files
- [x] Create a Microsite Page
- [x] Create component classes and states within the page
- [x] Include Files via code snippets to create the code section
- [ ] Merge branch into master and push to repo
- [ ] Connect component in Figma to Github Files

### Resources

- [Design Systems Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2%3A45&mode=design&t=jgMN8QdoLnh9F7MT-1)
- Link to type scale: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4763%3A3948&mode=design&t=cmjqTUJOXhV9dYip-1
- Link to microsite: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4763%3A3580&mode=design&t=cmjqTUJOXhV9dYip-1

**Comment by kristinstockley** [comment]
Discussed in yesterday's meeting and given direction. Wanted to confirm if this issue should stay in Ice Box, or if I should move it into In progress (actively working) @joshfishman ?

**Comment by aconstas** [comment]
![image](https://github.com/hackforla/internship/assets/82304192/c10ab04e-f256-44ce-b7da-1e48e569f0cd)

Just wanted to verify, are these font-size values for small paragraphs supposed to be **0.75rem** for the regular small paragraph and **1rem** for the semibold small paragraph and italic small paragraph? Or are all small paragraphs **0.75rem**?

https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4763-3742&mode=design&t=byCptG9dD6I2U3wZ-0
@karina-sato

**Comment by ExperimentsInHonesty** [comment]
verbal update from Alex during all team meeting 

> There’s just one little thing I need to fix.. Some general styles that are misaligned with the Figma design. Md-typset heading colors changes, font sizes
