### ISSUE TITLE
TWE Design System - Include code blocks with snippets in microsite

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#491]
### Overview
We need to set the code blocks so that they use the snippet functionality and automatically change when a user changes the elements

### Action Items
- [ ] Review Snippets documentation
- [ ] Include snippets in the TWE Microsite
- [ ] Create separate HTML + SCSS files for current component
- [ ] Include the HTML at the top of the page as the element for display
- [ ] Include the code inside the SCSS / HTML Code blocks at the bottom of the page for code reading/copying

### Resources/Instructions
- [How to include snippets](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets)
- [Snippets Documentation](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/)

**Comment by jnomad21** [comment]
I have enabled the snippets functionality and added it to the code.  We'll just need to discuss and decide on what code needs to be displayed

**Comment by jnomad21** [comment]
Discussed in yesterday's meeting and given direction.  Still in process as far as updating the snippets.

**Comment by aconstas** [comment]
just updated wiki with information about snippets and some general getting started 
https://github.com/hackforla/internship/wiki/Software-Engineer/
@joshfishman

**Comment by ExperimentsInHonesty** [comment]
@aconstas please remake the annotated screenshots in light mode and with more uniform sizing for accessability

**Comment by aconstas** [comment]
Remade annotated screenshots ✅

**Comment by joshfishman** [comment]
This issue is complete thank you
