### ISSUE TITLE
TWE: Role: Issue template for creating issue templates: Create

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#508]
### Overview
We need to create a template issue for creating [Replace NAME OF ISSUE TEMPLATE (named in the format as `TWE: Role: Direct Object: Action Verb`)] so that we have a consistent, transparent, defined, and self-supporting structure for people creating them.

#### Customize this issue
 - Customize this issue by adding the Name of Issue Template. 
    - _Note: An issue template's name is different from the issue title created from the template._
    - [ ] Search for `[Replace NAME OF ISSUE TEMPLATE]` by using the browser search (**Mac**: ⌘+F; **PC**: Ctrl+F)
    - [ ] Replace the keyword string (including text and the brackets) below with the name of your issue template according to the template naming convention: `TWE: Role: Direct object: Action verb`
        - The role is the primary owner of the issue template (e.g., Research, Design, Product)
        - Direct object should be the item that we're updating or working on (e.g., Wiki, Interviews, Roadmap)
        - Action verb should be the main descriptor of the action items (e.g., Update, Create, Transcribe)

#### Customize the issue settings (located in right sidebar)
Change the issue settings to ensure the issue is properly categorized and easy to manage.
- [ ] Under Assignees, assign yourself.
- [ ] Under Projects, choose gear, choose Repository, and choose TWE Project Management.
- [ ] Add the milestone: Project Management
- [ ] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.

#### Customize template draft
Create a draft of new template, which will be known as our "draft".
- [ ] Copy resource 1.01 Content to copy for draft to a new comment on this issue.
- [ ] In your draft, fill out the top part (called front matter) with the following information.  See resource 1.02 Front Matter Resources section below for definitions and examples.
    - [ ] Name
    - [ ] About
    - [ ] Title
    - [ ] Labels
- [ ] Define any Dependencies (or remove the dependency section if there is no dependency)
- [ ] Customize the Overview section
- [ ] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [ ] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [ ] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [ ] The links in the resources section provided by the issue creator should be in the same order as the Action Items 
      - [ ] Refer to resource 1.03 Example Action Items for Finding Wiki Page and Template for an example of how to write clear instructions that avoid compound steps (steps within a step).
   - [ ] Number each resource in the order each resource appears in the Action Items
       - [ ] Group resources into numbers and decimals (e.g., Resource 1.01, Resource 2.01)
       - [ ] Group the resources based on whether they are available when making the issues or they need to be created from this issue
           - If the resource is available, then group it under the Resources for creating this issue section (e.g., Resource 1.01, Resource 1.02, Resource 1.03)
           - If the resource will be delivered or created from this issue, then group it under the Resource links gathered during the making of this issue (e.g., Resource 2.01, Resource 2.02, Resource 2.03)
- [ ] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking resource 1.04 WIKI Templates by role pages.  
  - [ ] If there is a template
     - [ ] Add a link to the template into the ` #### Resources for creating this issue`  section of your draft
  - [ ] If there is no template yet
    - [ ] Put a placeholder into the` #### Resources for creating this issue`  section of the draft `[TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]`
- [ ] Get sign-off by Product on the draft
- [ ] Create the template issue on the repo
- [ ] Add the link to the new issue template once created to resource 2.01.  Find by clicking on the Getting started button to the right of the new template listed on [new issue page](https://github.com/hackforla/internship/issues/new/choose)
- [ ] Update the appropriate place in the wiki for your template (see resources section)

#### Resources for creating this issue
1.01 Content to copy for draft
```
Draft of template issue for `[Replace NAME OF ISSUE TEMPLATE]`
---
**name:** TWE: Template Issue: [Replace ROLE]: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** We are creating a template to complete `[Replace NAME OF ISSUE TEMPLATE]` issue so we can stay consistent in our process
**title:** TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]
**labels:** 'feature: research', 'feature: missing', 'size: missing', 'Participant Type: missing', 'Research 000: missing', 'role:  UI/UX research', 'milestone: missing', 'complexity: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT OBJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
```

1.02 Front Matter Resources
<details>
<summary>1.02.01 Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab)
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
    - Use the naming convention: TWE: Role: Direct object: Action verb
    - If more than one word should go into the direct object spot, use multiple square brackets with the keyword (see example)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>1.02.02 Front Matter Field example</summary>

- name: 'TWE: Template Issue: Research: Create Roadmap'
- about: We are creating a template to complete `[Replace NAME OF ISSUE TEMPLATE]` issue so we can stay consistent in our process 
- title: 'TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: Roadmap : Create'
- labels: 'feature: research', 'feature: roadmap', 'milestone: missing', 'role: UI/UX research', 'Participant Type: missing', 'Research 000: missing', 'complexity: missing'
- 'size: 0.50pt'
- assignees: ''
</details>

1.03 Example Action Items for Finding Wiki Page and Template
<details>
<summary>1.03.01 Example Action Items</summary>

```
### Action Items
- Customize wiki page
     - [ ] Go to link 1.01 Internship Wiki, Join the team page
     - [ ] Find wiki page for this issue by looking at role pages.
     - [ ] Copy the link for the wiki page.
     - [ ] Add the link to Resource 2.01
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
- Customize document template.
    - [ ] Go to link 1.02 Design Process Overview
    - [ ] Find document template that should be used in this issue.
    - [ ] Copy the link for the template.
    - [ ] Add the link to Resource 2.02
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
```

</details>

<details>
<summary>1.03.02 Example Resource Lists</summary>

```
### Resources for creating this issue
1.01. [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
1.02. [Design Process Overview](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

### Resource links gathered during the making of this issue
2.01. [Wiki page for [Replace TYPE OF ROLE]]
2.02. [TWE: Template: [Replace NAME OF TEMPLATE]]
```

</details>

1.04 WIKI Templates
    1.04.01 by role pages
    - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
    - [Design]
    - [Product]
    - [Engineering]
    1.04.02 default document templates, in case you don't have one yet, can be found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Resources gathered during the completion of this issue
2.01 ["Research: [Replace DIRECT OBJECT]: [Replace ACTION VERB]"]([Replace LINK])

**Comment by pandanista** [comment]
Product is testing this template, see #535.

**Comment by pandanista** [comment]
Draft of template issue for `[Replace NAME OF ISSUE TEMPLATE]`
---
**name:** TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** We are creating a template to complete `[Replace NAME OF ISSUE TEMPLATE]` so we can stay consistent in our process
**title:** TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: [Replace DIRECT ONJECT]: [Replace ACTION VERB]
**labels:** 'feature: research', 'feature: missing', 'size: missing', 'Participant Type: missing', 'Research 000: missing', 'role:  UI/UX research', 'milestone: missing', 'complexity: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT ONJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02

**Comment by pandanista** [comment]
Testing is done in #535. 

@sunannie27 and I have one question regarding the Milestone setup. The issue template for all template issues instructed using 03 Project Management. Then in the template itself, it tells the assignee to assign to a more appropriate milestone (In the second comment, in #535's case, it was the roll call and session table, the milestone is 06.01.06 Research Plan Execution). Should we just skip Milestone in the issue template (the first comment)?
<img width="949" alt="Screenshot 2024-03-04 at 3 49 05 PM" src="https://github.com/hackforla/internship/assets/57029070/a9b5ac95-c202-4e05-8a78-fb832d58e1ee">
<img width="949" alt="Screenshot 2024-03-04 at 3 49 32 PM" src="https://github.com/hackforla/internship/assets/57029070/8a8e3fa7-c16f-4692-baf9-6e6776329632">

**Comment by ExperimentsInHonesty** [comment]
@pandanista When you are making a template the milestone is 03, when you are making an issue from the template (once its available), the milestone is whatever is appropriate for that issue template

**Comment by ExperimentsInHonesty** [comment]
Restructure the resources section so that it has numbering and separate the resources into two sections
     - ```
        #### Resources for creating this issue
        ```
     - ```
        #### Resources gathered during the completion of this issue
        ```

**Comment by ExperimentsInHonesty** [comment]
Under Customize template draft section, add instructions for the person who is making the template to specify what milestone it gets.  They won't be able to add it automatically like a label, so it has to be specified under the action items of the template that is being made by our this template.

**Comment by pandanista** [comment]
I have restructured the resources section and updated resource numbers in the template instructions and resources section. The template is ready to be reviewed again. Please let me know if you have other questions.

**Comment by ExperimentsInHonesty** [comment]
### Overview
We need to create a template issue for creating [Replace NAME OF ISSUE TEMPLATE (named in the format as `TWE: Role: Direct Object: Action Verb`)] so that we have a consistent, transparent, defined, and self-supporting structure for people creating them.

### Action Items
#### Customize this issue
 - Customize this issue by adding the Name of Issue Template. 
    - _Note: An issue template's name is different from the issue title created from the template._
    - [ ] Search for `[Replace NAME OF ISSUE TEMPLATE]` by using the browser search (**Mac**: ⌘+F; **PC**: Ctrl+F)
    - [ ] Replace the keyword string (including text and the brackets) below with the name of your issue template according to the template naming convention: `TWE: Role: Direct object: Action verb`
        - The role is the primary owner of the issue template (e.g., Research, Design, Product)
        - Direct object should be the item that we're updating or working on (e.g., Wiki, Interviews, Roadmap)
        - Action verb should be the main descriptor of the action items (e.g., Update, Create, Transcribe)

#### Customize the issue settings (located in right sidebar)
Change the issue settings to ensure the issue is properly categorized and easy to manage.
- [ ] Under Assignees, assign yourself.
- [ ] Under Projects, choose gear, choose Repository, and choose TWE Project Management.
- [ ] Add the milestone: Project Management
- [ ] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.

#### Customize template draft
Create a draft of new template, which will be known as our "draft".
- [ ] Copy resource 1.01 Content to copy for draft to a new comment on this issue.
- [ ] In your draft, fill out the top part (called front matter) with the following information.  See resource 1.02 Front Matter Resources section below for definitions and examples.
    - [ ] Name
    - [ ] About
    - [ ] Title
    - [ ] Labels
- [ ] Define any Dependencies (or remove the dependency section if there is no dependency)
- [ ] Customize the Overview section
- [ ] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [ ] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [ ] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [ ] The links in the resources section provided by the issue creator should be in the same order as the Action Items 
      - [ ] Refer to resource 1.03 Example Action Items for Finding Wiki Page and Template for an example of how to write clear instructions that avoid compound steps (steps within a step).
   - [ ] Number each resource in the order each resource appears in the Action Items
       - [ ] Group resources into numbers and decimals (e.g., Resource 1.01, Resource 2.01)
       - [ ] Group the resources based on whether they are available when making the issues or they need to be created from this issue
           - If the resource is available, then group it under the Resources for creating this issue section (e.g., Resource 1.01, Resource 1.02, Resource 1.03)
           - If the resource will be delivered or created from this issue, then group it under the Resource links gathered during the making of this issue (e.g., Resource 2.01, Resource 2.02, Resource 2.03)
- [ ] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking resource 1.04 WIKI Templates by role pages.  
  - [ ] If there is a template
     - [ ] Add a link to the template into the ` #### Resources for creating this issue`  section of your draft
  - [ ] If there is no template yet
    - [ ] Put a placeholder into the` #### Resources for creating this issue`  section of the draft `[TWE: Template Issue: [Role]: [Replace ACTION VERB][Replace DIRECT OBJECT]`
- [ ] Get sign-off by Product on the draft
- [ ] Create the template issue on the repo
- [ ] Add the link to the new issue template once created to resource 2.01.  Find by clicking on the Getting started button to the right of the new template listed on [new issue page](https://github.com/hackforla/internship/issues/new/choose)
- [ ] Update the appropriate place in the wiki for your template (see resources section)

### Resources/Instructions

#### Resources for creating this issue
1.01 Content to copy for draft
```
Draft of template issue for `[Replace NAME OF ISSUE TEMPLATE]`
---
name: TWE: Template Issue: [Replace ROLE]: [Replace ACTION VERB][Replace DIRECT OBJECT]
about: This issue helps you structure your template issue to be consistent with our
  other template issues
title: 'TWE: Create Template Issue: [name of template]'
labels: 'feature: board / google drive / tools, feature: missing, milestone: missing,
  role: missing, size: missing', 'Participant Type: missing', 'complexity: missing'
assignees: ''
---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT OBJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, coding, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
```

1.02 Front Matter Resources
<details>
<summary>1.02.01 Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab)
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
    - Use the naming convention: TWE: Role: Direct object: Action verb
    - If more than one word should go into the direct object spot, use multiple square brackets with the keyword (see example)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>1.02.02 Front Matter Field example</summary>

- name: 'TWE: Template Issue: Research: Create Roadmap'
- about: We are creating a template to complete `[Replace NAME OF ISSUE TEMPLATE]` issue so we can stay consistent in our process 
- title: 'TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: Roadmap : Create'
- labels: 'feature: research', 'feature: roadmap', 'milestone: missing', 'role: UI/UX research', 'Participant Type: missing', 'Research 000: missing', 'complexity: missing'
- 'size: 0.50pt'
- assignees: ''
</details>


1.03 Example Action Items for Finding Wiki Page and Template
<details>
<summary>1.03.01 Example Action Items</summary>

```
### Action Items
- Customize wiki page
     - [ ] Go to link 1.01 Internship Wiki, Join the team page
     - [ ] Find wiki page for this issue by looking at role pages.
     - [ ] Copy the link for the wiki page.
     - [ ] Add the link to Resource 2.01
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
- Customize document template.
    - [ ] Go to link 1.02 Design Process Overview
    - [ ] Find document template that should be used in this issue.
    - [ ] Copy the link for the template.
    - [ ] Add the link to Resource 2.02
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
```

</details>

<details>
<summary>1.03.02 Example Resource Lists</summary>

```
### Resources for creating this issue
1.01. [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
1.02. [Design Process Overview](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

### Resource links gathered during the making of this issue
2.01. [Wiki page for [Replace TYPE OF ROLE]]
2.02. [TWE: Template: [Replace NAME OF TEMPLATE]]
```

</details>

1.04 WIKI Templates by role pages
- [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
- [Design](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
- [Product](https://github.com/hackforla/internship/wiki/Product)
- [Business Analyst / Data Science]
- [Software Engineer]
- [Marketing]
- default document templates, in case you don't have one yet, can be found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Resources gathered during the completion of this issue
2.01 [TWE: [Replace ROLE]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]]([Replace LINK])

**Comment by Rabia2219** [comment]
---
name: Create a template issue
about: This issue helps you structure your template issue to be consistent with our
  other template issues
title: 'TWE: Create Template Issue: [name of template]'
labels: 'feature: board / google drive / tools, feature: missing, milestone: missing,
  role: missing, size: missing'
assignees: ''

---
