### ISSUE TITLE
Create a Google doc for the survey questions sent by Brentwood

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#51]
### Overview
We need to review the survey questions sent by Brentwood so we can come to a consensus on how to answer them.

### Action Items

- [x] make a Google Doc with the survey questions
- [x] Fill and submit survey

### Resources/Instructions
 [Google doc](https://docs.google.com/document/d/1Wf9gVTV0XrLG0ODfXutvkyorDoDwReNwMMJ0J-dELSo/edit?usp=sharing) for Internship Sponsor Feedback Form

**Comment by Rabia2219** [comment]
Created the[ Google doc](https://docs.google.com/document/d/1Wf9gVTV0XrLG0ODfXutvkyorDoDwReNwMMJ0J-dELSo/edit?usp=sharing) for Internship Sponsor Feedback Form.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
Bonnie, we are done formatting the documents for your input. Just to remind you that the form is **due today!**

**Comment by priyatalwar** [comment]
@Rabia2219 Please update and since the survey has been sent, feel free to close this issue. Thanks!

**Comment by Rabia2219** [comment]
Survey sent on September 30th.

**Comment by Rabia2219** [comment]
Survey sent on September 30th.
