### ISSUE TITLE
Recruit Data Scientist

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#52]
### Overview

We are recruiting a Data Scientist who will be responsible for studying the datasets provided by the researcher with the intent of identifying trends and developing custom data models and algorithms to apply to data sets. The person will also be responsible for formulating and testing hypotheses based on business needs by analyzing and modeling data.

### Action Items

- [x] Edit note
- [x] Review note
- [x] Post it in opportunities
- [x]  Bring it during the Data Science COP on 9/23
- [x] Talk to potential Data Scientists

### Resources / Instructions
https://github.com/hackforla/data-science/projects/2

**Comment by priyatalwar** [comment]
#### Post a Volunteer Opportunity
---

**Project Name**: Internship

**About the Project**: The Internship project provides an opportunity for college and high school students to work in the fields of software, product development, project management, and UI/UX design at LA’s fastest-growing Civic Tech non-profit organization during their summer. The interns work on open source projects gaining confidence, competence, and deliverables which they add to their LinkedIn profiles.

**Volunteer Opportunity**: As a Data Scientist you will be responsible for studying the datasets provided by the researcher with the intent of identifying trends and developing custom data models and algorithms to apply to data sets.
You will also be responsible for formulating and testing hypotheses based on business needs by analyzing and modeling data. 
**Duration**: Ongoing

**Who to communicate your interest to**
- Slack channel link: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of person to contact in the channel : Priyanka

[DRAFT version of One Sheet for the Internship Project
](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/edit) 


Qualifications
Experience or interest in using statistical computer languages (R, Python, SQL, etc.) to manipulate data and draw insights from large data sets.
Experience or interest in visualizing/presenting data for stakeholders using: Periscope, Business Objects, D3, ggplot, etc.

**Comment by priyatalwar** [comment]
@Rabia2219 @ExperimentsInHonesty here is an issue to recruit a data scientist for the HfLA Internship Project. I'll add it to our next meeting's agenda

**Comment by Rabia2219** [comment]
9/20/2021
Reached out to Abe on slack with a DM. Waiting for response.

**Comment by priyatalwar** [comment]
Update 9/23 posted it [here](https://github.com/hackforla/data-science/projects/2#card-53801850) and on [data science ](https://hackforla.slack.com/archives/CGRATJCCF/p1632413297030300) and [new joiner slack](https://hackforla.slack.com/archives/C04S7PNCU/p1632413640009900)

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty @Rabia2219 We found one so closing this issue
