### ISSUE TITLE
TWE Design System: Web Typography Standards Research

### ISSUE THREAD

**Issue by satokarina** [hackforla/internship#528]
### Overview
The research will guide our web typography standards ensuring accessibility, consistency, and readability throughout our website. 

### Action Items
- [x] Research best practices and type scale for web typography from at least 3 different sources (ex: material design, adobe, etc.)
- [x] Compile findings in the Figma file
- [x] Review with Dev and other PMS
   - [x] revise
- [x] Make the Microsite page
- [x] get signoff from Dev and other PMs
- [x] add to Design System> Ready for Dev

### Resources/Instructions
- "Material Design" (https://m3.material.io/styles/typography/type-scale-tokens)
- "Adobe" (https://spectrum.adobe.com/page/typography/)
- "Apple" (https://developer.apple.com/design/human-interface-guidelines/typography) 
- [Microsite figma pages](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4466%3A2793&mode=design&t=J1U8t8tsUMSj17cu-1)
- [Microsite Ready for Dev figma page](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-54&mode=design&t=J1U8t8tsUMSj17cu-0)

**Comment by karina-sato** [comment]
check also:  IBM Carbon, Salesforce Lightning System

**Comment by karina-sato** [comment]
One of the most popular methods for creating a type scale is the Modular Scale. The Modular Scale uses a base number (usually 16) multiplied by 1.125 to calculate various sizes. We round the multiplied numbers to the closest even number for practical reasons. Usually, the type styles have 4-5 levels: display, heading, title, body, label. 

The defined type scale for our design system has 4 headings, 5 paragraphs, 2 links, and 3 subtitles. The subtitles are the same size as the paragraphs - which doesn't create a proper hierarchy for the design system. 

**Proposal:** rename paragraph 4 and 5 to captions; add display type level, adjust subtitle sizes to differentiate from paragraphs

![image](https://github.com/hackforla/internship/assets/140572674/6672352c-f9b1-4065-9c9b-1c2fa8ee40f8)

**Comment by karina-sato** [comment]
New type scale suggestion

<img width="1236" alt="image" src="https://github.com/hackforla/internship/assets/140572674/f6634361-f3b3-4358-95d1-94fafcd73639">

**Comment by karina-sato** [comment]
updated Figma link: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4407%3A2026&mode=design&t=0gJx7SRrPtBp0YyJ-1

**Comment by karina-sato** [comment]
Updates: 
- new typescale page for Hero section
- changed the class names to describe the  different styles
- removed p-link because it will need other states. Suggestion: create a new issue to add "text button" in the variants of buttons

<img width="1000" alt="image" src="https://github.com/hackforla/internship/assets/140572674/3c4b3fc9-49e6-45e8-8cb4-450792ad4c9c">

**Comment by karina-sato** [comment]
Updated the type scale according to Major Third rule (x 1.250) adjusted to a 4-pixel system, base 16px. Divided the type scale into Body Section and Hero Section. 

Link to type scale: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4763%3A3948&mode=design&t=cmjqTUJOXhV9dYip-1
Link to microsite: https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4763%3A3580&mode=design&t=cmjqTUJOXhV9dYip-1

@joshfishman  Does the microsite meet Dev needs? 
<img width="492" alt="image" src="https://github.com/hackforla/internship/assets/140572674/dfa5be68-0a21-40de-b397-b39cedd68d88">

**Comment by ExperimentsInHonesty** [comment]
The dev team accepts the microsite draft.
