### ISSUE TITLE
Finish Research Plan #1

### ISSUE THREAD

**Issue by sniux** [hackforla/internship#53]
### Dependency on 
- #28 
- #68 
- #167 completion of slide template

### Overview
We are in the last steps of finishing our first research plan (#27) to understand our impact on the interns, organization, areas of improvement & intern experience.

### Action Items

- [x] Synthesize interviews
- [x] Fill out interview information 
- [x] Generate insights
- [x] Complete the research plan (document)
- [x] Create a slide deck
- [x] Refine slide deck design https://github.com/hackforla/internship/issues/83

### Resources/Instructions
[Research Plan](https://docs.google.com/document/d/1t98oH0tAFTsiRm8QI75l93thdwjTxQMvXigmVFs7AbA/edit)
[Interview Synthesis Sheet](https://docs.google.com/spreadsheets/d/1j7DJltYPago3pZy_M-H_H_jBwOrBu6AN2LavTWTy2JU/edit#gid=1530446346)
[Research Slide deck](https://docs.google.com/presentation/d/1i83YamHc64eBGIjtkb9PJ-Gnhwkafo-uRFD0qjTZKWo/edit)
[New Slide Deck Template](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/template/preview) - clicking on this link makes a copy from this template
[New Slide Deck Template](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/edit) - this edits the original template

**Comment by sniux** [comment]
@priyatalwar I will need Mateo and Jack's synthesis by Saturday (18th September) 7pm PST evening.

**Comment by Rabia2219** [comment]
@priyatalwar you can connect to the internship gmail account and you should be able to access the Interview Synthesis Sheet without waiting for permission to access.

**Comment by Rabia2219** [comment]
@priyatalwar let me know if you can access it now.

**Comment by sniux** [comment]
@Rabia2219 Yes she can access it now.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty I would like to talk about the access rights to the Interview Synthesis Sheet in order to understand sharing rights for the future.

**Comment by priyatalwar** [comment]
Update: 9/18: @sniux @ExperimentsInHonesty Finished with the interview synthesis for Jack and Sakari.

**Comment by sniux** [comment]
Update 9/21: Finished Jason and Sophia's interview synthesis. All the syntheses are completed.

**Comment by sniux** [comment]
Update 9/27:

@ExperimentsInHonesty @priyatalwar @Rabia2219 
Finished research document and slide deck. Updated the resource link in the issue.

**Comment by sniux** [comment]
Agenda for upcoming meetings with @ExperimentsInHonesty 

10/2
- [ ] Review charts
- [ ] Finish up Objectives & KPIs

10/5
- [ ] Re-do recommendations
- [ ] Review slide deck

10/7
- Buffer

@Rabia2219 @priyatalwar please note.

**Comment by sniux** [comment]
@Rabia2219 I think @kellychoe will be editing the slide deck, so let's not close it just yet.

**Comment by priyatalwar** [comment]
@sniux Please make a new issue pertaining to design.

**Comment by priyatalwar** [comment]
Should we make it an epic instead?

**Comment by ExperimentsInHonesty** [comment]
moved this out of icebox because no dependency label

**Comment by epierotti3** [comment]
A role design label has been added so that this deck can get updated with the new project template. While doing that, please put a comment on any data that would seem to require more de-identification (e.g. "Princeton").

**Comment by ale22arevalo** [comment]
8/25: [Slide deck](https://docs.google.com/presentation/d/1i83YamHc64eBGIjtkb9PJ-Gnhwkafo-uRFD0qjTZKWo/edit?usp=sharing) has been updated with our current brand theme

**Comment by bradyse** [comment]
@priyatalwar This work is done and Bonnie has reviewed it.

**Comment by priyatalwar** [comment]
Thanks @bradyse. Feel free to close this issue then.
