### ISSUE TITLE
TWE: template for revising issue templates [name of template]

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#530]
### Overview
We need to revise all the research templates so that they have the new format of the newest templates being created.

### Details
New features of templates
- section headers (with bullets instead of check boxes)
- resources divided up into ones used to create the issue and ones created by doing the issue.
- expanding instructions on how to do things.

### Action Items

- [x] Create new issues
   - [x] #531
   - [x] ~#532~
      - [x] replaced by #450
   - [x] #533
   - [x] #534
- [x] Copy template
- [x] Customize issues by adding the 1.01 & 1.03 resources to the coresponding issues
   - TWE: Revise Research: Setup Structure Template
      - 1.01 [TWE Research: Setup Structure Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=epic%2C+feature%3A+research%2C+milestone%3A+missing%2C+p-feature%3A+wiki%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--setup-structure.md&title=TWE%3A+Research+Structure+for+%5Bname+of+research%5D) 
      - 1.03 [TWE Research: Setup Structure Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--setup-structure.md)
   - TWE: Revise Research: Create Roadmap Details Template
      - 1.01 [TWE Research:  Create Roadmap Details Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--create-roadmap-details.md&title=TWE%3A+Research%3A+Create+Roadmap+Details+for+RP%5B%23%23%23%5D) 
      - 1.03 [TWE Research:  Create Roadmap Details Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--create-roadmap-details.md)
   - TWE: Revise Research: Research Plan Template
      - 1.01 [TWE Research:  Research Plan Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+feature%3A+research+plan%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--research-plan.md&title=TWE%3A+Create+Research+Plan+for+RP%5B%23%23%23%5D) 
      - 1.03 [TWE Research:  Research Plan Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--research-plan.md)
   - TWE: Revise Research: Update Template
      - 1.01 [TWE Research: Update Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research+audits%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--update.md&title=Update+%5BReplace+with+RP+and+the+number+e.g.%2C+RP008%5D%3A+%5Bname+of+research%5D)
      - 1.03 [TWE Research: Update Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--update.md)
- [ ] 

#### Template
````
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Overview
We need to update the [Replace with name of Template] issue template so it has the same formatting as the most recent templates we have made.

### Action Items
We need to create a template issue for a [Replace with name of Template], so that we can create a [Replace with name of Template], when we are ready and maintain consistency with the org (across projects) and the guides project.

### Action Items
- [ ] Copy the example from Resource 1.01
  - [ ] Paste into a comment below using details to make it collapsible
  - [ ] Use the following text for the summary
```
## Current draft of [Replace with Name of template] Issue Template
```
- [ ] Copy the example from Resource 1.01
  - [ ] Use the following text for the summary
```
## Revised [Replace with Name of Template] Issue Template from the Guides Team
```
  - [ ] Add bullet headers and divide work in to sections
     - example: 
        - If the current template has
        > - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
        >    - [ ] Create a new folder in the drive called [number. name of type]
        - The revised template should have this text and formatting
        > - Create new Google Drive Folder
        >    - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
        >    - [ ] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern) 
        >    - [ ] update the link in the resources below (Resource # 2.02)
  - [ ] Separate the resources into two sections
     - ```
        #### Resources for creating this issue
        ```
     - ```
        #### Resources gathered during the completion of this issue
        ```
  - [ ] Make sure each resource is in order of how it appears in the instructions
  - [ ] Number the resources
     - [ ] Add the numbers to the action items
- [ ] re-review the whole thing, to make sure 
   - [ ] all the instructions make sense
   - [ ] all the links resolve
   - [ ] the work is listed in the most logical order
- [ ] review with UX lead and get sign-off
- [ ] ask UX lead or product to update issue template Resource 1.03

### Resources/Instructions
1.01 [TWE [Replace with name of Template] Issue Template, new issue]
1.02 [Issue templates in the code](https://github.com/hackforla/internship/tree/main/.github/ISSUE_TEMPLATE)
1.03 [[Replace with Name of Template] Issue Template, code]
````

**Comment by pandanista** [comment]
[All the aforementioned templates](https://github.com/hackforla/internship/issues/530#issue-2077287204) are done. I am closing this issue.
@ExperimentsInHonesty for visibility on the template issues.
