### ISSUE TITLE
[TEST] TWE: Role: Issue template for creating issue templates: Create

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#535]
### Overview
We need to create a template issue for creating `TWE: Research: Interview Roll Call and Session Table: Create` (named in the format as `TWE: Role: Direct Object: Action Verb`) so that we have a consistent, transparent, defined, and self-supporting structure for people creating them.

#### Customize this issue
 - Customize this issue by adding the Name of Issue Template. 
    - _Note: An issue template's name is different from the issue title created from the template._
    - [x] Search for `TWE: Research: Interview Roll Call and Session Table: Create` by using the browser search (**Mac**: ⌘+F; **PC**: Ctrl+F)
    - [x] Replace the keyword string (including text and the brackets) below with the name of your issue template according to the template naming convention: `TWE: Role: Direct object: Action verb`
        - The role is the primary owner of the issue template (e.g., Research, Design, Product)
        - Direct object should be the item that we're updating or working on (e.g., Wiki, Interviews, Roadmap)
        - Action verb should be the main descriptor of the action items (e.g., Update, Create, Transcribe)

#### Customize the issue settings (located in right sidebar)
Change the issue settings to ensure the issue is properly categorized and easy to manage.
- [x] Under Assignees, assign yourself.
- [x] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.

#### Customize template draft
Create a draft of new template, which will be known as our "draft".
- [x] Copy the `Content to copy for draft` to a new comment on this issue.
- [x] In your draft, fill out the top part (called front matter) with the following information.  See the Front Matter Resources section below for definitions and examples.
    - [x] Name
    - [x] About
    - [x] Title
    - [x] Labels
- [x] Define any Dependencies (or remove the dependency section)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] The links provided by the issue creator should be in the same order as the Action Items 
      - [x] Refer to the Resource titled `Example Action Items for Finding Wiki Page and Template` for an example of how to write clear instructions that avoid compound steps (steps within a step).
   - [x] Number each Resource in the order each resource appears in the Action Items
       - [x] If there are a lot of Resources that could be organized as a set, group them into numbers and decimals (e.g., Resource 1.01, Resource 2.01)
       - [x] Create Resource headings that collate all the 1s together and so on
- [x] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking the WIKI Templates by role pages (see WIKI Templates section under Resources/Instructions).  
  - [x] If there is a template
     - [x] Add a link to the template into the ` ### Resources`  section of your draft
  - [ ] If there is no template yet
    - [ ] Put a placeholder into the` ### Resources`  section of the draft `[TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]`
- [x] Get sign-off by Product on the draft
- [x] Create the template issue on the repo
- [ ] Add the link to the related "Get started" button in the Resources section below.
- [ ] Update the appropriate place in the wiki for your template (see resources section)

#### Getting started button link
Getting started button link for creating new issue using the ["Research: [Replace DIRECT OBJECT]: [Replace ACTION VERB]"]([Replace LINK]) template on the "New issue" tab

#### WIKI Templates
- by role pages
  - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
  - [Design]
  - [Product]
  - [Engineering]
- default document templates, in case you don't have one yet, can be found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Content to copy for draft
```
Draft of template issue for `TWE: Research: Interview Roll Call and Session Table: Create`
---
**name:** TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** We are creating a template to complete `TWE: Research: Interview Roll Call and Session Table: Create` issue so we can stay consistent in our process
**title:** TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]
**labels:** 'feature: research', 'feature: missing', 'size: missing', 'Participant Type: missing', 'Research 000: missing', 'role:  UI/UX research', 'milestone: missing', 'complexity: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT OBJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
```
#### Front Matter Resources
<details>
<summary>Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab)
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
    - Use the naming convention: TWE: Role: Direct object: Action verb
    - If more than one word should go into the direct object spot, use multiple square brackets with the keyword (see example)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>Front Matter Field example</summary>

- name: 'TWE: Template Issue: Research: Create Roadmap'
- about: We are creating a template to complete `TWE: Research: Interview Roll Call and Session Table: Create` issue so we can stay consistent in our process 
- title: 'TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: Roadmap : Create'
- labels: 'feature: research', 'feature: roadmap', 'milestone: missing', 'role: UI/UX research', 'Participant Type: missing', 'Research 000: missing', 'complexity: missing'
- 'size: 0.50pt'
- assignees: ''
</details>

#### Example Action Items for Finding Wiki Page and Template
<details>
<summary>Example Action Items</summary>

```
### Action Items
- Customize wiki page
     - [ ] Go to link 1.01 Internship Wiki, Join the team page
     - [ ] Find wiki page for this issue by looking at role pages.
     - [ ] Copy the link for the wiki page.
     - [ ] Add the link to Resource 2.01
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
- Customize document template.
    - [ ] Go to link 1.02 Design Process Overview
    - [ ] Find document template that should be used in this issue.
    - [ ] Copy the link for the template.
    - [ ] Add the link to Resource 2.02
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
```

</details>

<details>
<summary>Example Resource Lists</summary>

```
### Resources for creating this issue
1.01. [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
1.02. [Design Process Overview](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

### Resource links gathered during the making of this issue
2.01. [Wiki page for [Replace TYPE OF ROLE]]
2.02. [TWE: Template: [Replace NAME OF TEMPLATE]]
```

</details>

**Comment by sunannie27** [comment]
Draft of template issue for `TWE: IS[YY]: RP[000]: Participant Type Interview Roll Call and Session Table`
---
**name:** TWE: Template Issue: `TWE: IS[YY]: RP[000]: Participant Type Interview Roll Call and Session Table`
**about:** The process to complete `TWE: IS[YY]: RP[000]: Participant Type Interview Roll Call and Session Table` 
**title:** TWE: Research: [Replace DIRECT ONJECT]: [Replace ACTION VERB]
**labels:** 'feature: template', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose Program Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02

**Comment by pandanista** [comment]
Hi @sunannie27, I just realized `[Replace NAME OF ISSUE TEMPLATE]` should be `TWE: Research: Interview Roll Call and Session Table: Create` since our naming convention is in the format as `TWE: Role: Direct Object: Action Verb`. 

I've updated the templates in the first and second comment above and please let me know if you have any questions.

**Comment by sunannie27** [comment]
Draft of template issue for `TWE: Research: Interview Roll Call and Session Table: Create`
---
**name:** TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** We are creating a template to complete `TWE: Research: Interview Roll Call and Session Table: Create` issue so we can stay consistent in our process
**title:** TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: [Replace DIRECT ONJECT]: [Replace ACTION VERB]
**labels:** 'feature: research', 'feature: missing', 'size: missing', 'Participant Type: missing', 'Research 000: missing', 'role:  UI/UX research', 'milestone: missing', 'complexity: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT ONJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
