### ISSUE TITLE
TWE Design System Components: Dropdown with checkbox

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#538]
### Dependency
- [x] #542 

### Overview
We need to create dropdowns with checkboxes to add to input cards (#466)

### Action Items
- [ ] Create organized component
- [ ] Create variations (ex: website, mobile, other states)
- [ ] Organize the handoff layout for dev
- [ ] When these steps are done, go to https://github.com/hackforla/internship/issues/402 and check off the dependency.
- [ ] Identify which micosite template this component will use and create a layout for it
- [ ] When this issue is complete, please check it as "done" and add label "ready for the dev lead"

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline
- Check the VRMS Figma File (https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=3-7&mode=design&t=gi9Y7AceXfIztbdr-0) for reference

**Comment by mklmrgn** [comment]
See my [Sandbox ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4534%3A19148&mode=design&t=tq0ALSIvAH5ci1wa-1) here.

<img width="491" alt="Screen Shot 2024-02-14 at 9 55 03 PM" src="https://github.com/hackforla/internship/assets/81997978/2c79bf31-dfdd-4320-8d1f-3a235a5d5fc7">

Questions/Issues:

Need for "List" Component

What’s the difference between an accordion and a dropdown for our design system?

Why are dropdown list _items_ variants of the dropdown toggle?

Should we have a generic **list item** component?

Do we have standard elevations (I followed

**Comment by karina-sato** [comment]
Hi Michael, I added the dependencies to this issue. As mentioned in our team meeting, we need to finish the dependencies before moving on. Can you update how far you went in this issue, unassign yourself, and put it back in the ice box?

**Comment by mklmrgn** [comment]
Work here has been completed in 
- https://github.com/hackforla/internship/issues/543
