### ISSUE TITLE
TWE Design System Components: Update Checkbox according to M3

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#542]
### Overview
We need to update the components to match M3 Material Design guidelines style

### Action Items
- [x] Use M3 Material Design guidelines to assess the style differences
- [x] Update the component design
- [x] Communicate changes in the issue's comments and with the design team
- [x] Update/create microsite for devs accordingly
- [ ] Get sign-off from Project Manager
- [ ] Add the microsite to the "Ready for Dev" page
- [ ] Close this issue

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline

**Comment by karina-sato** [comment]
Great @mklmrgn. As for the next step, can you create the microsite template for the dev team? In the next team meeting we can present the microsite to get the sign off from this issue.

**Comment by mklmrgn** [comment]
Microsite created for checkbox
https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4776%3A3443&mode=design&t=kXZVrnuuZF9gjS6e-1

**Comment by mklmrgn** [comment]
Updated checkbox component according to Material 3 Guidelines. Added states for both checked and unchecked boxes.

Links to [component](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4758%3A2871&mode=design&t=Zh68ukr4pT6pyPcb-1) and [microsite](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4776%3A3443&mode=design&t=Zh68ukr4pT6pyPcb-1)

Image of Microsite
<img width="657" alt="Screen Shot 2024-03-14 at 9 37 32 AM" src="https://github.com/hackforla/internship/assets/81997978/4e955820-d2aa-4c7f-b004-20efbd1dda98">

**Comment by karina-sato** [comment]
Hi @mklmrgn, 
If you're finished, can you please add the tag "Ready for Dev lead" and move this issue to the Questions/Review column? 

Thanks

**Comment by joshfishman** [comment]
This looks great thank you!
