### ISSUE TITLE
TWE Design System Components: Update Accordion according to M3

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#544]
### Overview
We need to update the components to match M3 Material Design guidelines style

### Action Items
- [x] Use M3 Material Design guidelines to assess the style differences
- [x] Update the component design
- [x] Communicate changes in the issue's comments and with the design team
- [x] Update/create microsite for devs accordingly
- [x] Get sign-off from Project Manager
- [x] Add the microsite to the "Ready for Dev" page
- [ ] Close this issue

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline

**Comment by karina-sato** [comment]
Hey @joshfishman. 
Can you please review and see if we can move on with this issue? Do you have any other input for accordion? 

Link to master component: (https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4848%3A5982&mode=design&t=FdM8HDUsBff2g67Y-1)


Link to microsite: (https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4844%3A7081&mode=design&t=FdM8HDUsBff2g67Y-1)

**Comment by joshfishman** [comment]
Great work thank you!
