### ISSUE TITLE
Audit slack channel: Pins and Bookmarks

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#545]
### Overview
We need to audit the TWE Slack channels and their pins, bookmarks, reminders, so we can make sure new people find what they are looking for, and that information is not out of date.

### Action Items
- [x] Copy the template from resource 1.01 below to a comment
- Create resource 2.0
   - [x] Make a copy of resource 1.02 and add it to the PM folder in the TWE Google Drive
   - [x] Add the link to resource 2.0 below
- [x] Follow the instructions in the comment and check off as you go.  If for some reason you cannot do the instructions, leave a comment on the bottom of the issue and move to questions/review column
- [x] Perform Slack audit

#### Resources for creating this issue
- 1.01 Perform Slack Audit Instructions: https://github.com/hackforla/admin-calendaring/wiki/Perform-Slack-Audit (this link might not be followable as is, but it will be a good start.
- 1.02 [Draft: [Replace PROJECT NAME]: Slack Audit](https://docs.google.com/document/d/1ZxnTM4BwvJYsG5FatQol1tozPqK0G8JquljBZCPA0cI/template/preview)

 #### Resources gathered during the completion of this issue
- 2.0 [TWE: Slack Audit](https://docs.google.com/document/d/1KoJezz2vdlSt-Z4J0SQEYJ1Q0m-ZuhoLjZEAp7Zmiew/edit)

**Comment by KC-skc** [comment]
## Perform Slack Audit
### Open resources
- [ ] open resource 2.0
- [ ] access Hack for LA's Slack workspace through https://hackforla.slack.com/ (use the method you regularly use)
- [ ] view side by side
### Gather meeting data from Slack
_In this step, you will search for a channel name in Slack, copy the relevant data in from the reminders, pins, bookmarks, description and topic of that channel and paste it in resource 2.0, under the appropriate headings for each channel name._
_* If you are not a member of the channel, you can join temporarily to collect the data and then leave_
_* The pins and bookmarks appear on the bar under the channel name_
_> * If there is no pin icon, then there are no pins and therefore, no data to collect_
_> * If there are no bookmarks, the text `+ Add a bookmark` will appear and therefore, no data to collect_
_> > * If there are 3 dots after a bookmark name, there are more bookmarks, so click on the dots for the remaining bookmark names_
_> > * If there are nested bookmarks, there will be a down arrow next to the main bookmark's name_
_* The topic and description appear in a pop up window, which is accessed by selecting the down arrow next to the channel name_
_> * If the text `Add a topic` appears under the `Topic` heading in the pop up window, there is no data to collect_
_> * If the text `Add a description appears under the `Description` heading in the pop up window, there is no data to collect_
#### Repeat for every channel name in resource 2.0
- [ ] in resource 2.0, locate and copy the channel name
- [ ] in Hack for LA's Slack workspace, search for the channel name by pasting it in the search bar
- collect the following data from the channel 
   - [ ] Reminders
      - [ ] in Slack, go to the channel
      - [ ] type `/remind list` in a comment and hit enter
      - [ ] copy the resulting text
      - [ ] in resource 2.0, paste it under the `Reminders` for that channel
      - [ ] write **none** if there's no data
   - [ ] Pins
      - [ ] in Slack, click on the pin icon
      - [ ] copy the messages
      - [ ] in resource 2.0, paste under the Pins for that channel
      - [ ] write **none** if there's no data
  - [ ] Bookmarks
     - [ ] in Slack, locate the bookmark(s)
     - [ ] in resource 2.0, write the name of the bookmark as it appears and the resource type under the Bookmarks for that channel (e.g. Developer Meeting Tuesday - Zoom Link)
       - for nested bookmarks, write the names as indented bullets
     - [ ] in Slack, right click on the bookmark, copy link and link it to the resource name you just wrote
  - [ ] Topic
     - [ ] in Slack, select the down arrow next to the Slack channel name
     - [ ] look for the section named `Topic` in the window that pops up
     - [ ] copy the text
     - [ ] in resource 2.0, paste under the Topic for that channel
     - [ ] for emojis
        - [ ] in Slack, right click on the emoji, copy image
        - [ ] in resource 2.0, paste it with corresponding topic
      - [ ] write **none** if there's no data
  - [ ] Description
     - [ ] in Slack, select the down arrow next to the Slack channel name
     - [ ] look for the section named `Description` in the window that pops up
     - [ ] copy the text
     - [ ] in resource 2.0, paste under the Description for that channel
     - [ ] for emojis
        - [ ] in Slack right click on the emoji, copy image
        - [ ] in resource 2.0, paste it with corresponding description
      - [ ] write **none** if there's no data
#### Format resource 2.0
- [ ] refresh the Table of Contents (TOC) on the first page
- [ ] add the appropriate emojis to each category
   - [ ] go to the Legend on Page 1 of the document
   - [ ] copy the 👁️‍🗨️ (eye emoji) and paste it in front of every category heading (Reminders, Pins, Bookmarks, Topics, Description) for each channel that has any information (e.g. there is information for Reminders in a channel: Reminders 👁️‍🗨️)
   - [ ] copy the 🚫 (no emoji) and paste it in front of every category heading (Reminders, Pins, Bookmarks, Topics, Description) for each channel that doesn't have any information (e.g. there is no information for Pins in a channel: Pins 🚫)
   - [ ] refresh the Table of Contents (TOC) on the first page
    The TOC will look something like this when you are done
    ![image](https://user-images.githubusercontent.com/37763229/209480470-10bf770c-9019-4651-ba64-97039fc70788.png)
- [ ] update the Last Updated date in the footer
- [ ] remove `Draft` from the file name

### Close out this task
_You are done with all the steps in this task. You will now close it out in the main body of the issue._

- [ ] check the box for `Perform Slack Audit` in the `Audit` action items of this issue
- [ ] remove the `status: needs Slack audit` label
- [ ] reminder: if you are not the PM on the project leave all the Slack channels you joined after the audit is complete 
   - Instructions on how to [leave a Slack channel](https://github.com/hackforla/admin/wiki/Slack:-Leave-a-channel)
- [ ] close the tabs you just opened (wiki, document, Slack)
- [ ] hide this comment as RESOLVED, you are finished with this step
