### ISSUE TITLE
Recruit a UX Researcher

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#56]
### Dependency
at least [1 month worth of issues for researchers in the prioritized backlog](https://github.com/hackforla/internship/projects/1?card_filter_query=label%3A%22role%3A+ui%2Fux+research%22#column-14736603)

### Overview
We need to recruit UX Researchers so that can work down our prioritized backlog.

### Action Items

- [ ] Create a comment below that has a draft of the Open Role: UX Researcher wiki page
- [ ] In your comment, edit draft of open roles board card
- [ ] Edit wiki page with any additional information that won't fit on the open roles board card
- [ ] Post it in UI/UX Open Roles Board
- [ ] Post on appropriate Slack channels
- [ ] Talk to potential UX researchers

### Resources
- [Wiki Page Open Role: UX Researcher](https://github.com/hackforla/internship/wiki/Open-Role:-UX-Researcher)
- [UI/UX Research Open Roles Board](https://github.com/hackforla/UI-UX/projects/2)
- HTML to put at the top of the open role card so that the logo appears above the content
```
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">
```

- [Post for Researcher](https://github.com/hackforla/UI-UX/projects/2#card-67150536)

**Comment by Rabia2219** [comment]
9/16/2021
Made a new issue as the previous on was closed.
Pitched for a UX researcher [here](https://hackforla.slack.com/archives/C017ESHSMNG/p1631828482057600).
Will attend UI/UX COP meeting next Wednesday (9/22/2021) to pitch if we do not have any response by then.

**Comment by Rabia2219** [comment]
Please add update using this template (even if you have a pull request)

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel.
Please add update using this template (even if you have a pull request)

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel.
Please add update using this template (even if you have a pull request)

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel.

**Comment by Rabia2219** [comment]
Posted opportunity in Slack on September 17th, 21st, 22nd, 23rd, 27th and 29th.
Did not attend the CoP meeting on the 22nd because of a speaker event (which was not a good call).
Attended CoP meeting on September 29th.
Was contacted by Maricel Dizon via Slack DM before the meeting on September 29th. She will be attending the October 4th onboarding session and will join the team as a UX researcher.

**Comment by ExperimentsInHonesty** [comment]
we just moved the regular research position to filled on the board.

**Comment by priyatalwar** [comment]
@Rabia2219 Please close this issue since we filled it up

**Comment by bradyse** [comment]
### Draft for Open Roles Board 2022-09-29

**Project Name**: Tech Work Experience

**About the Project**: The goal of this team is to design and execute an internship project geared toward high school and college students to help them develop the hard (technical) and soft skills (workplace collaboration) required to successfully land STEM careers.

**Volunteer Opportunity**: Looking for UX researchers to interview volunteers who interacted with the interns

**Duration**: 1- 2 months

**Who to communicate your interest to**
- Slack channel link: #internship
- Slack name of person to contact in the channel: Sara Brady

[Read more about the project](https://github.com/hackforla/internship/wiki/Volunteer-Overview)

**Comment by ExperimentsInHonesty** [comment]
Text is too long, we need room for the logo

**Project Name**:  HfLA Internship Project - This opportunity is for a team member to help us build out next summer's internship program.

**About the Project**: The project provides an opportunity for high school/college students to work in the fields of software, product development, project management, and UI/UX design over summer. They work on open source projects gaining confidence, competence and deliverables which they add to their LinkedIn profiles.

**Volunteer Opportunity**: As a UX Researcher, you will work with various methodologies to analyze the scopes for improvement to enhance the experience of the interns we recruit for the program. You will also work on drafting hypotheses and finding actionable insights for the problem statements, that will solidify the establishment of the program

**Duration**: Ongoing

**Who to communicate your interest to**
- Slack channel link: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of person to contact : Rabia Shaikh

**Comment by ExperimentsInHonesty** [comment]
# This one is the correct length

<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project Name**: Tech Work Experience

**About the Project**: The goal of this team is to design and execute an internship project geared toward high school and college students to help them develop the hard (technical) and soft skills (workplace collaboration) required to successfully land STEM careers.

**Volunteer Opportunity**: Currently seeking UX researchers interested in joining the existing lead in growing the TWE ResearchOps (research operations) at enterprise scale.  

**Duration**: 1- 2 months
[Meeting times](https://github.com/hackforla/internship/wiki/Joining-the-Team#meeting-times)

**Who to communicate your interest to**
- Slack channel link: #internship
- Slack name of person to contact in the channel: Ying O

**Read more about the [role and project](https://github.com/hackforla/internship/wiki/Open-Role:-UX-Researcher).**

**Comment by ExperimentsInHonesty** [comment]
goal for this text is 433 

Project Name: HfLA Internship Project - This opportunity is for a team member to help us build out next summer's internship program.

About the Project: The project provides an opportunity for high school/college students to work in the fields of software, product development, project management, and UI/UX design over summer. They work on open source projects gaining confidence, competence and deliverables which they add to their LinkedIn profiles.

Volunteer Opportunity: As a UX Researcher, you will work with various methodologies to analyze the scopes for improvement to enhance the experience of the interns we recruit for the program. You will also work on drafting hypotheses and finding actionable insights for the problem statements, that will solidify the establishment of the program

**Comment by ExperimentsInHonesty** [comment]
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

**Project Name**: HfLA Internship Project

**About the Project**: The goal of this team is to design and execute an internship project geared toward high school and college students to help them develop the hard (technical) and soft skills (workplace collaboration) required to successfully land STEM careers

**Volunteer Opportunity**: As a UX Researcher, be setting up an auditing the research framework for existing research plans among other research tasks

**Duration**: 1- 2 months
[Meeting times](https://github.com/hackforla/internship/wiki/Joining-the-Team#meeting-times)

**Who to communicate your interest to**
- Slack channel link: #internship
- Person to contact in the channel: Ying O

**Read more about [role and project](https://github.com/hackforla/internship/wiki/Open-Role:-UX-Researcher).**

**Comment by ExperimentsInHonesty** [comment]
UX Researcher: https://github.com/hackforla/UI-UX/projects/2#card-67150536
Research Co lead: https://github.com/hackforla/UI-UX/projects/2#card-86010500

**Comment by pandanista** [comment]
Posted [the recruiting message](https://hackforla.slack.com/archives/C017ESHSMNG/p1674763201787079) on UI-UX slack channel on 1/26/2023. Will keep you posted.

**Comment by pandanista** [comment]
@bonniewolfe Finish a round of recruiting. Onboarded Andrew, Jiah, Bryanna, and Nino as of 2022-02-06. Moving the issue back to the icebox.

**Comment by ExperimentsInHonesty** [comment]
- We no longer use this format. See https://github.com/hackforla/internship/issues/602
