### ISSUE TITLE
Adjust our Development Setup so that the site properly shows on GitHub Pages

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#561]
### Overview
We need to adjust the setup / settings for our gh-pages live site so that it shows the compiled MkDocs site that we are creating. Currently it just shows the index.html file. It should look the same as our local.

### Action Items
- [x] Review the resources to understand where we are with this process
- [x] Determine why the site is not building on gh page
- [x] After site is resolving to the URL, remove Tyler from team

### Resources/Instructions
- [Deploying MkDocs](https://www.mkdocs.org/user-guide/deploying-your-docs/)
- [How to add Jekyll to GH-Pages](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll)
- New Repo: https://github.com/hackforla/internship-website-design-system
- URL for mkdocs design system site: https://hackforla.github.io/internship-website-design-system/
- Admin access for the new repo https://github.com/orgs/hackforla/teams/internship-design-system-admin/membersb

# How the Settings currently Look
<img width="817" alt="Screenshot 2024-04-24 at 10 38 14 AM" src="https://github.com/hackforla/internship-website-design-system/assets/1108221/39661c63-33d3-4af7-9f97-1e30b7fdfe85">

**Comment by ExperimentsInHonesty** [comment]
- I created a new team https://github.com/orgs/hackforla/teams/internship-design-system-admin/members and added @Brayheart to it as admin so that he can change settings to make the mkdocs resolve at https://hackforla.github.io/internship-website-design-system/
- [ ] After that has been accomplished, remove Tyler from team

**Comment by Brayheart** [comment]
I'm not sure if I have admin access but the site is live on github pages
