### ISSUE TITLE
[TEST] TWE: IS22: RP020: Mentor Informed Consent Documents (18 yrs +): Create

### ISSUE THREAD

**Issue by sunannie27** [hackforla/internship#564]
Draft of template issue for Consent Documents Template for Participants over 18 
---
**name:** TWE: Template Issue: Research: Create Consent Documents for Study Participants over the age of 18
**about:** This issue helps you structure your template issue to be consistent with our other template issues in consent documents
**title:** TWE: IS22: RP020: Mentor Informed Consent Documents (18 yrs +): Create
**labels:** 'feature: research', 'Participant Type: missing', 'Research 000: missing', 'size: 1pt', 'role: UI/UX research', 'milestone: missing'
**assignees:**

---
#### Instructions for creating this issue
**Resources/Instructions:** This section is at the bottom of this issue (scroll to the bottom to view it now). The person who creates this issue should use links in the section "Resources for creating this issue" (i.e., 1.01, 1.02, etc.) to customize this issue.

- Customize the issue
    - [x] Open the "Research Overview" wiki page (Resource 1.01)
    - [x] Choose "Research Documents by Participant Type" or "Research by Plan Number" to locate the appropriate research roadmap or research plan folder (ie., RP###) on the wiki page
    - Use the information on the wiki page and in research roadmap or research plan to customize this issue
    - [x] Copy and paste entire template text in this issue into text editor (ie., "TextEdit" on _Mac_, "Wordpad" on _PC_)
    - Use Find/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for and replace the keyword strings (including text and the brackets) below with the appropriate values 
        - Year 
            - [x] Find/Replace `22` with research year (Two digit format, ex: "22" for year "2022") 
        - Research Plan Number
             - [x] Find/Replace `020` with the research plan number (Three digit format, ex: "001" for research plan "RP001") 
        - Type of Participant
            - [x] Find/Replace `Mentor` with the participant type (ex: "Intern" or "Mentor")  
    - [x] Copy and paste the edited template from text editor back into this Github Issue, replacing all original text
    - [x] Re-check all the checkboxes above after copying and pasting the edited template
    - [x] Close the text editor
    - Update the issue title
        - [x] Copy 
        ```
        TWE: IS22: RP020: Mentor Informed Consent Documents (18 yrs +): Create
        ```
        - [x] Choose "Edit" in the title section
        - [x] Paste the texts you copied into the issue title 
        - [x] Choose "Save"
- Customize the issue settings (located in right sidebar)
    - [x] Under Assignees, assign a Researcher if it has been determined. Otherwise, leave it blank.
    - [x] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Research: RP020`
    - [x] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Participant Type: Mentor`
    - [x] Remove the `Research 000: missing` and `Participant Type: missing` labels
    - [x] Under Projects, choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose `Repository`, and choose `Program Management`
    - [x] Add the milestone: choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and choose `Research Plan Execution` 
    - [x] Remove the label `milestone: missing`
- Remove this section
    - [x] After all the checkboxes above are complete and the issue is ready to be worked on, delete all text below the "Instructions for Creating this Issue" (top heading) and above "Overview" (heading below) -- i.e., the issue assignee will never see this part

### Overview
Create informed consent documents for RP020 so that we can keep track of the participants who agree to participant in the study. This process only applies to participants over 18 years old.

### Dependency: 
- [ ] Mentor Research Plans and Goals Chart has been created

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [ ] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [ ] Open relevant wiki page for RP020
    - [ ] Copy the link for the RP020 wiki page.
    - [ ] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
 - Customize Resource for this Research Plan's Google Drive Folder
    - [ ] Choose the "Research by Plan # and name" folder on the shared Google Drive (Resources  # 1.02)
    - [ ] Right-click on the RP020 folder 
    - [ ] Choose "Get Link"
    - [ ] Choose "Copy link" and "Done"
    - [ ] Update Resource # 2.02 with the link you just copied. Paste it inside parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for Mentor's Research Plans and Goals Chart
    - [ ] Go to Research Output Overview Wiki page (Resources # 1.01) 
    - [ ] Choose `Mentor` in the "Research Documents by User Type" section
    - [ ] Choose the `Research Plans and Goals Chart` in the "Mentor Research Plans and Goals (public page)" section
    - [ ] Copy the URL of `Mentor Research Plans and Goals` wiki page in the browser window
    - [ ] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for RP020's Research Informed Consent Overview Google Doc
    - [ ] Open the template "TWE: Template: Research Informed Consent Overview" (Resources 1.03)
    - [ ] Choose the "USE TEMPLATE" button to save it to your own drive
    - Update the file name by following the steps:
        - [ ] Copy the text below
        ```
        TWE: IS22: RP020: Mentor Research Informed Consent Overview
        ```
        - [ ] Choose "File" > "Rename", and paste the text you copied into the top field of the Google Doc to rename the file <img width="700" alt="Screenshot 2023-02-20 at 2 16 31 PM" src="https://user-images.githubusercontent.com/57029070/220206393-59240ec3-80a9-46c0-a5d9-de5fd094d3fd.png"> 
        - [ ] Highlight the texts of the title on the first page of the Google Doc cover page <img width="400" alt="Screenshot 2023-02-20 at 2 17 03 PM" src="https://user-images.githubusercontent.com/57029070/220206807-08fb3b27-a712-4de2-8c37-9fc0b4ddf439.png">
        - [ ] Paste the texts you copied to replace the original title of the Google Doc 
        - [ ] Keep the "Research Informed Consent Overview" Google doc open in a tab for future editing
    - [ ] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder
        1. Choose File > Move (or Move icon)
        1. Choose the back arrow to access all your drives 
        1. Choose Shared drives > Internships > Internships > Research > Research by Plan # and name > folder for RP020
        1. Choose "Move here"
        1. Choose "Move" when it asks if you want to change ownership to a shared drive
        1. Dismiss the notification that says the file is now in the shared drive
    - [ ] Update Resource # 2.04 link
        1. In the "Research Informed Consent Overview" Google Doc you just created, choose "Share" (upper right corner)
        1. Choose "copy link" and "Done"
        1. Update Resource # 2.04 with the link you just copied. Place it into parentheses at the end of the line.
        1. Choose "Update comment" in Github and make sure all the checkboxes above have been checked
  - Customize Resource for RP020's Informed Consent Form
    - [ ] Open the Informed Consent Form in Resources # 1.04
    - [ ] Choose the 3 vertical dots at the top of the Google Form on the left of your profile <img width="50" alt="Screenshot 2023-02-20 at 3 55 20 PM" src="https://user-images.githubusercontent.com/57029070/220215081-08700bd5-3a00-402a-b7ef-5a2919907887.png">
    - [ ] Choose "Make a copy"
    - [ ] Copy the text below
    ```
    TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews
    ```
    - [ ] Paste the texts you copied into the "Name" field 
    - [ ] In the "Folder" field, choose "Consent Form", then choose back arrow to "Templates", back arrow to "Research" folder 
    - [ ] Choose Research > Research by Plan # and name > folder for RP020
    - [ ] Choose "Select"
    - [ ] Choose "Make a copy"
    - [ ] Update Resource # 2.05 link by completing the following steps
        1. Choose "Send"  in the `TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews` you just created
        1. Choose the link icon <img width="50" alt="Screenshot 2023-02-20 at 6 21 51 PM" src="https://user-images.githubusercontent.com/57029070/220231746-a48f29cb-51c5-40ea-bb38-6d9edf042feb.png">
        1. Check the box for "Shorten URL"
        1. Choose "Copy"
        1. Update Resource # 2.05 with the link you just copied. Place it into parentheses at the end of the line.
        1. Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for RP020's Research Consent Email
- [ ]  Open the link in Resources # 1.05
    - [ ] Choose the "USE TEMPLATE" button to save it to your own drive
        - Update the file name by following the steps:
            - [ ] Copy the text below
            ```
            TWE: IS22: RP020: Mentor Research Consent Email
            ```
            - [ ] Choose "File" > "Rename", and paste the text you copied into the top field of the Google Doc <img width="700" alt="Screenshot 2023-02-20 at 7 23 23 PM" src="https://user-images.githubusercontent.com/57029070/220239577-de3eb7a4-c912-4e86-9124-0d56415cdf42.png"> 
    - [ ] Move the file into the Internship's shared drive in this Research Plan's Google Drive folder
        1. Choose File > Move (or Move icon)
        1. Choose the back arrow to access all your drives 
        1. Choose Shared drives > Internships > Internships > Research > Research by Plan # and name > folder for RP020
        1. Choose "Move here"
        1. Choose "Move" when it asks if you want to change ownership to a shared drive
        1. Dismiss the notification that says the file is now in the shared drive
    - [ ] Update Resource # 2.06 link
        1. In the Google Doc, choose "Share" (upper right corner)
        1. Choose "copy link" and "Done"
        1. In Resource # 2.06, place the link you just copied into parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(` so it turns into a hyperlink
        1. Choose "Update comment" in Github and make sure all the checkboxes above have been checked
#### Customize documents needed for RP020's Consent Overview, Form, and Email 
- Customize RP020's Research Informed Consent Overview Google Doc      
    - [ ] Open RP020's Research Informed Consent Overview Google Doc (Resources # 2.04) if it is not open
    - [ ] Copy the text below
    ```
    You are invited to take part in Tech Work Experience’s 2022 Mentor Research
    ```
    - [ ] Highlight the first sentence of the Google Doc (see screenshot) <img width="700" alt="Screenshot 2023-02-20 at 3 19 12 PM" src="https://user-images.githubusercontent.com/57029070/220212025-fcb06211-12ef-4e84-bf68-887e2a4ae216.png">
    - [ ] Paste the texts you copied into the highlighted section to replace the original first sentence of the Google Doc
    - [ ] Copy the hyperlink from Resources # 2.03
    - [ ] Paste into the highlighted section so the document says `Mentor Research Plans and Goals` with a Wiki page link attached <img width="500" alt="Screenshot 2023-02-20 at 1 55 11 PM" src="https://user-images.githubusercontent.com/57029070/220209992-88d6a562-bec5-4e01-a8db-eefac1cba983.png">
    - Update the footer of the Google Doc on page 2
        - [ ] Update the date with the date this Google Doc is created <img width="221" alt="Screenshot 2023-02-20 at 2 45 14 PM" src="https://user-images.githubusercontent.com/57029070/220209057-f67e292b-91ec-4edc-ba8a-602ea459e362.png">
        - [ ] Update participant type with `Mentor` <img width="500" alt="Screenshot 2023-02-20 at 2 45 44 PM" src="https://user-images.githubusercontent.com/57029070/220209143-18410257-ee5c-4f49-8922-9c9ee3165c5c.png">
    - [ ] Update the `LINK TO SIGN INFORMED CONSENT` at the end of the doc with the link labeled 2.05 in Resources 
            1. Copy the link in 2.05
            1. Highlight the `LINK TO SIGN INFORMED CONSENT` <img width="300" alt="Screenshot 2023-02-20 at 4 37 41 PM" src="https://user-images.githubusercontent.com/57029070/220219358-0c31ae21-9e10-4be2-bd67-fd0ffed53194.png">
            1. Choose "Insert link" icon <img width="100" alt="Screenshot 2023-02-20 at 1 55 53 PM" src="https://user-images.githubusercontent.com/57029070/220209935-7ab0a449-da17-4d2f-8f8f-6fca0491edfb.png">
            1. Paste the link you copied into the box and choose `Apply` <img width="300" alt="Screenshot 2023-02-20 at 2 54 26 PM" src="https://user-images.githubusercontent.com/57029070/220209848-8a68657d-fcd5-42b4-a6da-9d3638b089f8.png">
- Customize RP020's Research Informed Consent Form
    - [ ] Open RP020's Research Informed Consent Form (Resources # 2.05) if it is not open
    - [ ] Copy the text below
    ```
    TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews
    ```
    - [ ] Under "Questions" tab, highlight the title section <img width="600" alt="Screenshot 2023-02-20 at 5 01 13 PM" src="https://user-images.githubusercontent.com/57029070/220221980-1513c7ab-2089-422e-9d55-14db263bfe0e.png">
    - [ ] Choose the pencil shaped icon in the lower right of the Google Form
    - [ ] Paste the texts you copied into the title section of the Google Form to replace the original texts  
    - [ ] Copy the hyperlink from Resources # 2.04
    - [ ] Paste the hyperlink you copied to replace the highlighted section (in the screenshot below) so the form says `TWE: IS22: RP020: Mentor Research Informed Consent Overview` with the Google Doc link attached <img width="700" alt="Screenshot 2023-02-20 at 8 35 53 PM" src="https://user-images.githubusercontent.com/57029070/220250286-915bcd52-9619-49bb-909b-7561eab48753.png">
    - [ ] Edit the `TWE: IS22: RP020: Mentor Research Informed Consent Overview` URL you just pasted
    - [ ] Choose "Edit link"
    - [ ] Choose the "Link to" field <img width="300" alt="Screenshot 2023-02-20 at 5 10 49 PM" src="https://user-images.githubusercontent.com/57029070/220225579-90b29b10-3d62-4e10-8fa9-b88df970cf2e.png">
    - [ ] Make sure to delete `edit?usp=sharing` and add `preview` at the end of the link so people outside the TWE Team can view the Google Doc
    - [ ] Choose "OK"
    - [ ] Copy  the text below
    ```
    Mentor #
    ```
    - [ ] Paste into the highlighted area in the participant # question <img width="200" alt="Screenshot 2023-02-20 at 5 04 43 PM" src="https://user-images.githubusercontent.com/57029070/220223551-e0bcb91e-018a-414d-abb4-a2a121a18101.png">
    - [ ] Add or delete participant numbers based on the Research Plan doc in RP020's folder (Resources # 2.02)
    - [ ] Copy  the text below
    ```
    Mentor
    ```
    - [ ] Paste into the highlighted area in the signature section <img width="300" alt="Screenshot 2023-02-20 at 5 05 05 PM" src="https://user-images.githubusercontent.com/57029070/220224319-39bec962-332f-4356-9039-2765e6d95703.png">
    - [ ] Choose the pencil shaped icon in the lower right of the Google Form to make sure you are in the editing mode
    - [ ] Scroll up to the top of the Google Form to select the "Responses" tab <img width="368" alt="Screenshot 2023-04-27 at 11 17 07 AM" src="https://user-images.githubusercontent.com/57029070/234956976-043f9575-3599-4ae1-bb5e-3b5186587760.png">
    - [ ] Under "Responses", choose "Link to Sheets"
    - [ ] Choose "Create a new spreadsheet"
    - [ ] Choose "Create"
    - [ ] Go to RP020 folder (Resources # 2.02)
    - [ ] Locate the `TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews (Responses)` spreadsheet
    - [ ] Choose "Get Link"
    - [ ] Choose "Copy link" and "Done"
    - [ ] Update Resource # 2.07 with the link you just copied. Place it into parentheses at the end of the line.
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
    - [ ] Under "Settings", make sure the "Collect email addresses" and "Allow responses editing" are toggled on. <img width="600" alt="Screenshot 2023-02-20 at 4 27 00 PM" src="https://user-images.githubusercontent.com/57029070/220226050-9c191628-883c-4dec-bd47-d7fb02e25284.png">
- Customize `TWE: IS22: RP020: Mentor Research Consent Email` script 
    - Subject line:
        - [ ] Copy  the text below
        ```
        Mentor
        ```
        - [ ] Paste the texts you copied to replace the highlighted area of the subject line <img width="700" alt="Screenshot 2023-02-20 at 7 34 11 PM" src="https://user-images.githubusercontent.com/57029070/220241223-a658fce5-4eb3-4a99-9a7d-c640f980fb3c.png">
    - Email body:
        - [ ] Copy the text below
        ```
        Mentor in our Summer 2022
        ```
        - [ ] Paste the texts you copied to replace the highlighted area of the email body <img width="700" alt="Screenshot 2023-02-20 at 7 38 16 PM" src="https://user-images.githubusercontent.com/57029070/220241461-bcfd6da1-4244-4eb6-a9ec-bf9cadbbdf91.png">
        - [ ] Copy  the text below
        ```
        Mentor
        ```
        - [ ] Paste the texts you copied to replace the following highlighted area of the email body <img width="700" alt="Screenshot 2023-02-20 at 7 42 10 PM" src="https://user-images.githubusercontent.com/57029070/220242377-5532e8a1-1aa3-4e97-a241-71ae41bea7da.png"> 
        - [ ] Copy the hyperlink from Resources # 2.03
        - [ ] Paste into the highlighted section so the document says `Mentor Research Plans and Goals` with a Wiki page link attached <img width="700" alt="Screenshot 2023-02-20 at 7 43 21 PM" src="https://user-images.githubusercontent.com/57029070/220247483-0c913244-1ead-474f-ac00-6f0884d3ac32.png">
        - [ ] Copy the URL in Resources # 2.05
        - [ ] Choose "this link" <img width="300" alt="Screenshot 2023-02-20 at 7 48 13 PM" src="https://user-images.githubusercontent.com/57029070/220243068-cea638f3-dee5-4da2-a728-450286d726e0.png">
        - [ ] Choose "Edit link"
        - [ ] Paste the link you copied into the box
        - [ ] Choose "Apply"
#### 
- Update the wiki page for this research plan (Resources # 2.01)
    - [ ] Open the link in Resource 2.01
    - [ ] Choose "Edit" to edit the page
    - [ ] Find the "Script" section
    - [ ] Make a new line at the end of the list and add a new bullet by inserting `- ` at the beginning of the line
    - [ ] Copy and paste Resource 2.04 (both the text and URL) from this issue to the right of this new bullet (`- `) in the "Script" section
    - [ ] Copy and paste Resource 2.05 (both the text and URL) from this issue to the right of this new bullet (`- `) in the "Script" section
    - [ ] Choose "Save Page"
- Update [Mentor Research Plans and Goals] on Wiki (Resource 2.03) 
    - [ ] Open the link in Resource 2.03
    - [ ] Choose "Edit" to edit the page
    - [ ] Find the "Consent" Section,  
    - [ ] Make a new line at the end of the list and add a new bullet by inserting `- ` at the beginning of the line
    - [ ] Copy and paste Resource 2.04 (both the text and URL) from this issue to the right of this new bullet (`- `) in the "Consent" section 
    - [ ] Copy and paste Resource 2.05 (both the text and URL) from this issue to the right of this new bullet (`- `) in the "Consent" section
- [ ] Update the research plan doc in [Google Drive Folder: RP020] (Resource 2.02)
    - [ ] Include consent overview (Resources 2.04), form (Resources 2.05), and email (Resources 2.06) in the research plan Google Doc's Appendix
- [ ] Review with UX Lead
- [ ] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link) 
1.03 [TWE: Template: Research Informed Consent Overview](https://docs.google.com/document/d/1FTDCI4QIH4ENtYh6EEdfhv8ozz8EKzoJBQ6PnK3K7Uc/template/preview)
1.04 [TWE: Template: Research Informed Consent Form for Surveys/Interviews](https://docs.google.com/forms/d/1Xzm1TFiJa13Y451L3mLjKXfC0-GHhhX5xk09nxU0hjo/edit) _This consent form is for participants over 18_
1.05 [TWE: Template: Research Consent Email ](https://docs.google.com/document/d/1NFaUx2kUmsfEAtieAmwAdvAXh6CMu_k72PogpKHB4V0/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan 020]
2.02 [Google Drive Folder: RP020]
2.03 [Mentor Research Plans and Goals]
2.04 [TWE: IS22: RP020: Mentor Research Informed Consent Overview]
2.05 [TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews] _This consent form is for participants over 18_
2.06 [TWE: IS22: RP020: Mentor Research Consent Email]
2.07 [TWE: IS22: RP020: Mentor Research Informed Consent Form for Surveys/Interviews (Responses)] _This consent form is for participants over 18_

**Comment by pandanista** [comment]
- [ ] Need to add instructions to add all the labels attached to the template that is being tested.
