### ISSUE TITLE
Create a project card for Internship on Hack for LA website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#57]
### Dependency
- [x] #201
- [x] #28 
- [x] #185
- [x] A method by which people can find out that they are not eligible for the internship, so that people don't inundate our slack channel.

### Overview
We need to have a project card on the hack for LA website, so that we can recruit new team members

### Action Items
- [x] Gather items for project card
  - [x] logo on an image 600x400
  - [x] hero image 1500x700
  - [x] one sheet (called overview on project card)
  - [x] Text draft
- [ ] Add the content to https://github.com/hackforla/website/issues/2288 
   - [ ] Ask Bonnie to remove the dependency and put the issue into the prioritized backlog on hackforla website repo

### Resources/Instructions
- [Project One Sheet](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/edit)
- [PDF of one sheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf)

#### Text draft
The Tech Work Experience project provides an opportunity for college and high school students to work in the fields of software, product development, project management, and UI/UX design at LA’s fastest growing Civic Tech non-profit organization during their summer. The interns work on open source projects, gaining confidence, competence and deliverables which they add to their LinkedIn profiles. 

alt.
The Tech Work Experience project is a scaffolded summer internship program for college and high school students to work on open source projects in the fields of software, product development, project management, and UI/UX design at LA’s fastest growing Civic Tech non-profit organization in order to gain confidence, competence and deliverables to support their future career and personal journeys.

**Comment by ExperimentsInHonesty** [comment]
Technologies

**Comment by ExperimentsInHonesty** [comment]
Tools

**Comment by ExperimentsInHonesty** [comment]
- check on this weekly until it's done https://github.com/hackforla/website/issues/2288
- we are going to provide a new hero, the one we choose was too busy

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty I think we should we all good to close this issue since TWE project card has been added to the HfLA website.
