### ISSUE TITLE
Improve onboarding instructions

### ISSUE THREAD

**Issue by Justlee98** [hackforla/internship#60]
### Overview
As a new team member, I want to understand the overview of the project so that I can understand the whole project 

### Action Items

- [x] create a document in the team's google drive 
- [x] write up notes conversation with Snigdha
- [x] review the [WIKI content](https://github.com/hackforla/VRMS/wiki/Join-the-Team#getting-fully-up-to-speed)

### Resources/Instructions

[google shared drive](https://drive.google.com/drive/folders/1z3I2SLQzYWBHIypNZO-sTdSO0A8c5pvt?usp=sharing)
[IS: New Team member FAQ](https://docs.google.com/document/d/1SP9gu86aXQUldd_SiyIBJ5sGRHS7CzWElZ_kfjTn9hQ/edit)

**Comment by Rabia2219** [comment]
> @Rabia2219 I definitely do think that the instructions need a lot more refinement and further research will bring it up in tomorrow's meeting.

@sniux those are just questions/comments that @Justlee98 put together. You both can collaborate and work on finishing it and yes, it is on the agenda for today.

**Comment by ExperimentsInHonesty** [comment]
this issue is closed because we updated the wiki to have two new sets of instructions
https://github.com/hackforla/internship/wiki/Joining-the-Team
https://github.com/hackforla/internship/wiki/Onboarding-Process-for-Project-Team-Leads
