### ISSUE TITLE
St Joseph Center Questions

### ISSUE THREAD

**Issue by sunannie27** [hackforla/internship#608]
### Overview
We need to come up with questions for the St. Joseph's Center in Venice to see how HfLA can coordinate with them for a tech program.

### Action Items
- Go to the St. Joseph's CodeTalk Program Website in Resources
- Review the program and come up with questions to ask them regarding HfLA collaboration with them

### Resources/Instructions
- [St. Joseph's CodeTalk Program](https://www.stjosephctr.org/codetalk/#sjc)

**Comment by ExperimentsInHonesty** [comment]
What are stats for conversion from existing unemployment, underemployment to post program employment in tech industry

**Comment by ExperimentsInHonesty** [comment]
Can you provide some examples of Practical Group Projects that the students have worked on.

**Comment by ExperimentsInHonesty** [comment]
What is lacking in the program that we could help with 

e.g., 
- more practical experience in a work like environment on public facing websites with users
-

**Comment by ExperimentsInHonesty** [comment]
Do you want to keep working with the same population?

Or add groups such as 
- High school students
- Teenagers in Foster Care
- System Impacted people

**Comment by ExperimentsInHonesty** [comment]
How does St. Joseph's find job opportunities (jobs, internships, or externships) for their graduates?

**Comment by ExperimentsInHonesty** [comment]
The current program is hybrid.  Are you looking for any additional programs or extensions of the existing program to retain the same format, or is fully in person or fully remote an option?

**Comment by ExperimentsInHonesty** [comment]
What percentage of the graduates from the program have a specific interest in being a Software Engineer and potentially continuing their skill development to cover back end?

**Comment by ExperimentsInHonesty** [comment]
1. What is the timing for the 16 weeks as it pertains to the modules, and specifically Module 9, 12 and Professional development
1. What are the stats for conversion from existing unemployment, underemployment to post program employment in tech industry. How has that changed with the tightening of the job market?
1.. Can you provide some examples of Practical Group Projects that the students have worked on?
1. What is lacking in the program that we could help with e.g.:
     - more practical experience in a work like environment on public facing websites with users
     - experience on back end work
     - experience on projects that use React, AWS, etc.
     - working with interdisciplinary teams
     - Program Evaluation: UX Research (qualitative and quantitative) on existing programs or new program
1. Do you want to keep working with the same population? Or address groups such as
     - High school students
     - Youth in Foster Care or Transitioning out
     - System Impacted people
1. How does St. Joseph's find job opportunities (jobs, internships, or externships) for their graduates?
1. Are the graduates solely responsible for finding the opportunities and the program provides coaching, or are there partnerships where they are holding positions for the graduating class? Or a combination of both?
1. The current program is hybrid. Are you looking for any additional programs or extensions of the existing program to retain the same format, or is fully in person or fully remote an option?
1. What percentage of the graduates from the program have a specific interest in being a Software Engineer and potentially continuing their skill development to cover back-end?

**Comment by ExperimentsInHonesty** [comment]
She responded 

Thanks so much, Bonnie!

5 1/2 weeks in my new role, lots to learn and do - and I am loving it!!

As we begin to unpack our Workforce Development program, I will be sure to circle back with you.

Talk soon!
