### ISSUE TITLE
TWE: Open Role for: UI/UX Designer

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#612]
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">

TWE: Open Role for: UI/UX Designer

**Project Name**: TechWorkExperience

**Name of Role**: UI /UX Designer

**Volunteer Opportunity**: You'll have the opportunity to build the Design System and collaborate with cross-functional teams. Together, you'll build and ensure our platform is intuitive, consistent, and engaging.

**Duration**: On-going

**Meeting Times** for Designers
   - Tuesdays 12:30-1:00 pm PST (Design Meeting)
   - Thursdays 10:00-11:00 am PST (All Team Meeting)

**Communicate your interest**
- Slack channel: #[internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack the person who is assigned to this issue in the internship Slack channel (you can hover over their GitHub handle to see their name)

For more info, dive into our [project overview](https://github.com/hackforla/internship/wiki/Volunteer-Overview) and [design process](https://github.com/hackforla/internship/wiki/Design-Process-Overview).

**Comment by pandanista** [comment]
@priyatalwar: Would you please connect Munti (@muntiCloud) with the design team? Her experience and interest might be better aligned with design, and she has already been onboarded with TWE. Thank you.
