### ISSUE TITLE
`[TEST]`  TWE: IS21: RP001:Rapid Qualitative Analysis (RQA): Pre-process

### ISSUE THREAD

**Issue by jinyan0425** [hackforla/internship#621]
### Dependencies
- RP001's research plan needs to be finalized. See https://github.com/hackforla/internship/issues/27
- ~RP001's transcript has been transcribed, de-identified and cleaned up. See https://github.com/hackforla/internship/issues/355, https://github.com/hackforla/internship/issues/476, https://github.com/hackforla/internship/issues/478, https://github.com/hackforla/internship/issues/479, https://github.com/hackforla/internship/issues/480, https://github.com/hackforla/internship/issues/481~
- RP001's research method needs to be researched and step-by-step instructions need to be provided. See https://github.com/hackforla/internship/issues/338

### Overview
We need to pre-process and set up the workflow for RP001's Rapid Qualitative Analysis so we stay consistent in the data analysis process.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Choose the link in the Research by Plan Number section
    - [x] Locate relevant wiki page for RP001
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Type Folder (Resources # 1.02)
    - [x] Choose the `Intern` folder
    - [x] Choose the `RP001` folder
    - [x] Copy the link of the `RP001` folder
        1. Choose the three vertical dots on the right side of the `RP001` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
    - [x] Open the `RP001` folder in Google Drive (Resources # 2.02)
    - [x] Locate the research plan in `RP001` folder  
        - [x] Choose RP001's research plan in Google Doc
        - [x] Copy the link of the `RP001` research plan
            1. Choose the three vertical dots on the right side of the `RP001` research plan  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
            1. Choose "Share"
            1. Choose "Copy Link" 
            1. The "Link copied" notification pops up
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
    - [x] Locate the RP001's de-identified transcript(s) in `RP001` folder (Resources # 2.02)
        - [x] Choose RP001's de-identified transcript(s)
        - [x] Copy the link of the `RP001` de-identified transcript(s)
            1. Choose the three vertical dots on the right side of the `RP001` de-identified transcript(s)  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
            1. Choose "Share"
            1. Choose "Copy Link" 
            1. The "Link copied" notification pops up
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### Review Resources to Get Familiar with the Hamilton's Process of Rapid Qualitative Analysis (RQA)
- [x] If you are new to RQA, review the list of resources to get familiar with the RQA process and techniques (Resources 1.03 - 1.05)
- [x] If you are experienced with RQA, you may skip reviewing the documents or review them for a refresher

#### Create the Rapid Qualitative Analysis Domain Names
- [x] Read through the research plan to get familiar with the study (Resources 2.03 and 2.04)
    - [x] Focus on the interview protocol/interview guide in the research plan Google doc
- Create a neutral domain name spreadsheet that corresponds with each interview question (an example refers to p. 22 in the notes of Hamilton's Process/Approach in Resources 1.03)
    - [x] Go to `TWE: Research: Rapid Qualitative Analysis Domain Names Template` linked in Resources 1.06  
    - [x] Choose `Use Template`
    - [x] Copy the following texts
        ```
        TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Domain Names
        ```
    - [x] Paste the texts you copied into the formula bar of the spreadsheet to replace the default title (see the highlighted part in the screenshot)  <img width="500" alt="Screenshot 2024-08-29 at 2 01 19 PM" src="https://github.com/user-attachments/assets/d3a9d66d-f816-4bad-875c-e68fd6d6b94b">
    - [x] Choose File > Rename
    - [x] Paste the texts you copied into the text box to replace the default name of the file
    - [x] Move the file to RP001's folder in the shared Google Drive
        1. Choose File > Move > All Locations > Shared drives > Internship > Internships > Research > Research by Plan # and Name > RP001> Move
        1. There will be a question to confirm change the ownership of the documents, and choose Move
    - [x] Copy the link of the Rapid Qualitative Analysis Domain Names file of RP001
        1. Choose Share
        1. Choose Copy link and Done
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Fill out a neutral domain name spreadsheet that corresponds with each interview question (an example refers to p. 22 in the notes of Hamilton's Process/Approach in Resources 1.03)
    - [x] Go to the research plan doc (linked in Resources 2.03) to locate the interview protocol/questions
    - [x] Copy and paste each interview question into a row in the Interview Question column (column B) in the Rapid Qualitative Analysis Domain Names file (linked in Resources 2.05 if it is not open already)
    - [x] Provide each interview question with an Interview Question # (column A) based on the interview protocol/interview guide
    - [x] Draft the domain based on the interview question in the Domain column (column C) in the Rapid Qualitative Analysis Domain Names file
    - [x] Leave any comments or questions in Notes column (column E)

#### Peer Review Stage of the Domain Names
- [x] Notify the Research Lead that the domain names are finished by leaving a comment in this issue
- [x] Add `needs peer review` label
- [x] Research Lead assigns a team member to conduct a peer review
- [x] The peer reviewer conducts the review by providing alternative domain names in the Peer Reviewed Domain column (column D) in the Rapid Qualitative Analysis Domain Names file (linked in Resources 2.05)
- [x] The peer reviewer provides any feedback, comments, or rationale in the Notes column (column G) 
- [x] The peer reviewer notifies the Research Lead and the authors of the domain names that the peer review is completed by making a comment in this issue
- [x] The author of the domain names discusses with the peer reviewer and research lead on the feedback and incorporates the feedback if needed
- [x] The author of the domain names lists out revised domain names in Tentative Domain column (column E) after discussion
- [x] The authors of the domain names adds `Ready for Research Lead` label once the domain names are finalized, and move the issue to `Question/Review` column 
- [x] Research lead will review the updated domain names

#### Create the Transcript Summary Template
- Create a transcript summary template for conducting transcript summaries (an example refers to p. 23 in the notes of Hamilton's Process/Approach in Resources 1.03)
  - [x] Go to `TWE: Research: Rapid Qualitative Analysis Transcript Summary Template` linked in Resources 1.07  
  - [x] Choose `Use Template`
  - [x] Copy the following texts
        ```
        TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Transcript Summary
        ```
  - [x] Paste the texts you copied into the formula bar of the spreadsheet to replace the default title (see the highlighted part in the screenshot)  <img width="500" alt="Screenshot 2024-09-23 at 9 34 14 PM" src="https://github.com/user-attachments/assets/2e6dc0b5-abbd-4b05-9d39-0e30f7b93807">
  - [x] Choose File > Rename
  - [x] Paste the texts you copied into the text box to replace the default name of the file
  - [x] Move the file to RP001's folder in the shared Google Drive
       - [x] Choose File > Move > All Locations > Shared drives > Internship > Internships > Research > Research by Plan # and Name > RP001 > Move
       - [x] There will be a question to confirm change the ownership of the documents, and choose Move
  - [x] Copy the link of the Rapid Qualitative Analysis Transcript Summary file of RP001
       - [x] Choose Share
       - [x] Choose Copy link and Done
   - [x] In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

- Populate the domain names according to the finalized domain names provided in Resources 2.05
  - [x] Open **_Spreadsheet A_**: `[TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Domain Names]` linked in Resources 2.05
  - [x] Open **_Spreadsheet B_**: `[TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Transcript Summary]` linked in Resources 2.06
  - [x] Replace the cells labeled `Domain 1`, `Domain 2` and etc. in **_Spreadsheet B_**, with the domain names from the Finalized Domain column in **_Spreadsheet A_**. 
       - [x] Ensure you follow the exact order.
       - [x] Remove any extra cells (e.g., `Domain 10`) if there are fewer finalized domains.
       - [x] Add additional cells if there are more than 10 finalized domains.

#### Resources needed to complete issue
1.01 [Wiki Intern Research Overview Page](https://github.com/hackforla/internship/wiki/Intern-Research-Overview)
1.02 [Research by Participant Type Folder on Google Drive](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=drive_link)
1.03 [Qualitative Methods in Rapid Turn-Around Health Services Research](https://www.hsrd.research.va.gov/for_researchers/cyber_seminars/archives/780-notes.pdf) **MUST READ**
1.04 [Linda's Presentation to UXR Team on How to Conduct Rapid Qualitative Analysis](https://docs.google.com/presentation/d/12j99CF8fnvdb7WOWxDn1_CO_UODjoL23HXZUqujbveA/edit?usp=sharing)
1.05 [a step-by-step checklist for conducting a Rapid Qualitative Analysis](https://github.com/hackforla/internship/issues/338#issuecomment-2192408993) - This issue comment provides more context on the checklist this issue is following 
1.06 [TWE: Research: Rapid Qualitative Analysis Domain Names Template](https://docs.google.com/spreadsheets/d/1O8nU0iKQiecZzkuyGP-uJoqVwIwlFZNSBnUAAKIy6-U/template/preview)
1.07 [TWE: Research: Rapid Qualitative Analysis Transcript Summary Template](https://docs.google.com/spreadsheets/d/1kHnMpIK6AHEoxFY9XhGMb5JRWPBnuDjZzahG2vovGJQ/template/preview)

#### Resources gathered during the completion of the issue
2.01 [RP001 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-1:-IS21-Interns)
2.02 [Google Drive RP001 Folder](https://drive.google.com/drive/folders/1uKUY_izpds3dHInNkiexZsU32ELF_Hze?usp=sharing)
2.03 [RP001 Research Plan](https://docs.google.com/document/d/1t98oH0tAFTsiRm8QI75l93thdwjTxQMvXigmVFs7AbA/edit?usp=sharing)
2.04 [RP001 De-identified Transcript Folder](https://drive.google.com/drive/folders/1A2crr41KWwnoCvdtwmwJnmoP0IzH1Z54?usp=drive_link)
2.05 [TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Domain Names](https://docs.google.com/spreadsheets/d/1JZSRPw7HFjjpgNMk_pGc8jVGbilbKDQitrjg-WgR5XU/edit?usp=drive_link)
2.06  [TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Transcript Summary](https://docs.google.com/spreadsheets/d/1-EtAw4bhh_ev0f1bNaEPnX-0HpONussJjCJzURt3UbY/edit?usp=sharing)

**Comment by jinyan0425** [comment]
@pandanista Ying, I am working on this issue and will leave comments about the template.

**1. Dependencies:**
It may be helpful to guide the future assignee on how to locate the relevant issues requested here. Additionally, if this Rapid Qualitative Analysis (RQA) pre-process is applied to other research plans, the dependencies appear specific to RP001 and may not be universally applicable to other RPs.

**Comment by jinyan0425** [comment]
Hi @pandanista Ying,

I’ve drafted the domains, and they are ready for your review or feedback from another team member. We can discuss them further once you've had a chance to go through the questions.

**Comment by pandanista** [comment]
### Setup for a Peer Review
- [ ] Confirm with UX Lead that this document needs a peer review.
- [ ] Check if the Issue Overview clearly defines why this document needs to be created or updated. If it is not clear, add that information to the overview in 1-2 sentences.
- [ ] In the Resources, clearly identify the link to the document being created or updated that requires a peer review (use subheadings if needed).
- [ ] Copy and paste the Action Items for Peer Review into a comment of the issue.
- [ ] Customize the Action Items according (adding items that are more relevant to this issue and removing items that are less relevant).
- [ ] If you have a specific task that you want the Peer Reviewer to accomplish for their peer review that is nuanced to your issue, add that as a final action item to the list.
- [ ] For a spreadsheet review, add a column and label it "Peer Reviewer Questions and Feedback." If this step is not needed, remove this step.
- [ ] Determine who will do the peer review and unassign yourself to this issue and assign the peer reviewer to this issue.

### Action Items for Peer Review
- [ ] Review this issue
     - [ ] Read the issue overview to learn about why this document was created.
     - [ ] Locate draft of the document or spreadsheet in the Resources.
- [ ] Review draft
     - [ ] Preview the draft quickly to get a sense of how the draft is structured and the type of content.
     - [ ] Review the structure of the draft to ensure that the headings (in a Google Doc) or columns (Google Sheet) are clearly identified. 
     - [ ] Determine if the information is communicated in a way that is concise, precise, and free from jargon.
     - [ ] Identify whether the draft adheres to the basic branding guidelines for the project (see Branding or Design wiki link in Resources).
- [ ] Provide feedback
     - [ ] Add feedback in the form of (1) questions and/or (2) explicit instructions for how the content should be improved. Feedback in a Google Doc should be given in the form of document comments. Feedback in a Google Sheet should be given in a new column labeled for Peer Review. Feedback in a Google Form should be given in screenshots and comments in the issue.
     - [ ] If there are edits to be made, please use "suggesting mode" in Google doc instead of "editing mode".
     - [ ] Determine the accuracy of the content for each section (Google doc, and Google form) or cell (Google sheet). If you find an inaccuracy, error, or mis-categorization, explain how the information presented could be improved.
     - [ ] For each suggested improvement, provide a link or reference within your comment to justify your suggestion (if available).
- [ ] Specific to this issue: 
     - [ ] [REPLACE WITH STEPS THAT ARE SPECIFIC TO THIS ISSUE]
- [ ] Once all the steps have been completed, reach out to the original owner of this issue to determine if they can complete the next steps in the issue.

**Comment by pandanista** [comment]
@jinyan0425 I finished my peer review for the domain names, and also checked the template instructions again.

One minor thing I noticed:
- the title of the spreadsheet wasn't updated. Maybe the instructions were not clear enough? If so, how can we improve it? <img width="500" alt="Screenshot 2024-09-18 at 3 53 47 PM" src="https://github.com/user-attachments/assets/b13f3a6b-fe02-4614-8439-f5c3114d94d0">
    - the instructions in the template: <img width="500" alt="Screenshot 2024-09-18 at 3 33 41 PM" src="https://github.com/user-attachments/assets/871f7ae2-cb37-43a6-9f4b-5c8187dc6912">

- Feedback for the template:
    - Add a number column for readability and easier reference (added to the template and this issue)
    - Add instructions to ask both assignee and peer reviewer to leave comments and feedback in Notes column (added to the template and this issue)

**Comment by jinyan0425** [comment]
@pandanista 

Thanks for catching that. It was my neglect. I have updated the title within the spreadsheet. The template is clear.

I agree with the two feedbacks. Will you update the template accordingly?

**Comment by pandanista** [comment]
@jinyan0425 Yep, I have updated them accordingly.

**Comment by pandanista** [comment]
@jinyan0425, thank you for the feedback!

I've revised the domain name template and the template instructions (both above and in template draft).
- [TWE: Research: Rapid Qualitative Analysis Domain Names Template](https://docs.google.com/spreadsheets/d/1O8nU0iKQiecZzkuyGP-uJoqVwIwlFZNSBnUAAKIy6-U/)
- [TWE: IS21: RP001: Intern Rapid Qualitative Analysis Domain Names](https://docs.google.com/spreadsheets/d/1JZSRPw7HFjjpgNMk_pGc8jVGbilbKDQitrjg-WgR5XU/edit?usp=drive_link)
- [Draft of RQA pro-processing](https://github.com/hackforla/internship/issues/618#issuecomment-2327661203)

Also, I have removed that unnecessary action item.

**Comment by jinyan0425** [comment]
@pandanista 

Thank you, Ying. I just made one comment on [TWE: IS21: RP001: Intern Rapid Qualitative Analysis Domain Names](https://docs.google.com/spreadsheets/d/1JZSRPw7HFjjpgNMk_pGc8jVGbilbKDQitrjg-WgR5XU/edit?usp=drive_link)

Shall we move this issue, and 
- #618   to **In Progress** column?

**Comment by pandanista** [comment]
@jinyan0425
- I edited the round names in the [TWE: IS21: RP001: Intern Rapid Qualitative Analysis Domain Names](https://docs.google.com/spreadsheets/d/1JZSRPw7HFjjpgNMk_pGc8jVGbilbKDQitrjg-WgR5XU/edit?usp=drive_link) and resolved the comment.
- I moved #618 to the in progress column.

**Comment by pandanista** [comment]
@jinyan0425 
- I finished the testing on RP001's RQA pre-processing.
- I left a comment in #618.

**Comment by jinyan0425** [comment]
> @jinyan0425
> 
> * I finished the testing on RP001's RQA pre-processing.
> * I left a comment in [TWE: Create Template Issue: Rapid Qualitative Analysis (RQA): Pre-process #618](https://github.com/hackforla/internship/issues/618).

**Seen and Replied in** 
- #618.

**Comment by jinyan0425** [comment]
@pandanista 

- I am about to close this issue and #620, however, I found **Resource 2.07** [TWE: IS21: RP001: Intern Exit Interview: Rapid Qualitative Analysis Transcript Summary](https://docs.google.com/spreadsheets/d/1vva6zZ6MXhtPPwtNvhwT6VmQcHRczmo7HX-d91o8Hjo/edit?usp=sharing) is linked to an empty spreadsheet. The domains are not added. Can you double check this?

- Then, you can close both issues. Thank you!

**Comment by jinyan0425** [comment]
Ying, it looks great to me. Please close both issues. Thank you so much!
