### ISSUE TITLE
Design: Create an Image for RP025 Participant Recruitment Ads

### ISSUE THREAD

**Issue by jinyan0425** [hackforla/internship#627]
### Overview
We need to design an image for the participant recruitment advertisements for the RP025 Negative Research Experience Study.

### Action Items
- [ ] Refer to the `RP025: Negative Research Experience Research Plan` linked in Resource 1.01 to gain an overview of the Negative Research Experience Research
- [ ] Refer to the Recruitment section of the research plan to locate the `Tentative Recruitment Ads` linked in Resource 1.02. These ads will be posted on social media platforms like LinkedIn to recruit potential participants for the survey. 
- [ ] Design an engaging image to accompany the text-based ads 
    - [ ] The purpose of this image is to enhance visibility and attract attention
    - [ ] The image should convey the message that the survey focuses on negative experiences in interview research. 
    - [ ] Check the sample images linked in Resource 1.03 for reference.
    - [ ] The image should be free for use without any licensing restrictions.
    - [ ] For additional context on designing the image, please refer to the comments in https://github.com/hackforla/internship/issues/614
- [ ] Review the image with Product
- [ ] Product sign-off
#### Resources for creating this issue
1.01 [TWE: IS24: RP025: Negative Research Experience Research Plan](https://docs.google.com/document/d/1C4wbihFYyD6wcQNZ1_MPjGtOkiKK3vkpzYtvL9IQuYM/edit)
1.02 [TWE: IS24: RP025: Negative Research Experience Research Plan - Recruitment](https://docs.google.com/document/d/1C4wbihFYyD6wcQNZ1_MPjGtOkiKK3vkpzYtvL9IQuYM/edit#heading=h.nn3zcy2m07ad)
1.03 [Sample Images](https://github.com/hackforla/internship/issues/614#issuecomment-2375466232)

#### Resources gathered during the completion of this issue
2.01 An image for recruitment ads posted on social media platforms(e.g., LinkedIn, Twitter)

**Comment by jinyan0425** [comment]
@ExperimentsInHonesty 

Bonnie, I have drafted this issue for Design to create an image for RP025 Participant Recruitment Ads. Please let me know if any changes or updates are needed, and feel free to make any edits as you see fit.

By the way, I'm not sure about the appropriate 'milestone' and 'feature' for this issue yet, as they are still missing

**Comment by mklmrgn** [comment]
Progress: Used AI to generate several options
Blockers: Need to fix a few errors in Photoshop
ETA:1 weeks
Used AI to generate several images:
![unnamed-4](https://github.com/user-attachments/assets/a850ded1-dce6-4d3d-8348-f422bfef5d1f)

![unnamed-3](https://github.com/user-attachments/assets/27145582-4986-48a5-9623-1db794dc5fd9)

![unnamed-1](https://github.com/user-attachments/assets/036cdcab-7ac7-4ac6-841b-0ece948686cb)

**Comment by mklmrgn** [comment]
Team agreed on image #3

**Comment by ExperimentsInHonesty** [comment]
@mklmrgn please add the information about where you got the image

**Comment by mklmrgn** [comment]
Generated the image using AI under a free trial of Google's Gemini.
There are no rules in Google's Terms of service or policies for generative AI that prohibit that use of this image for commercial purposes.

https://policies.google.com/terms
https://policies.google.com/terms/generative-ai/use-policy

**Comment by ExperimentsInHonesty** [comment]
This issue can get finished once the credits page issue is made and the info from here added to it.
