### ISSUE TITLE
TWE: Research: Interview Transcripts Needs and Counts

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#630]
### Overview
We need to do a tally on the existing interview files based on research plan numbers, and identify the number of interviews that need to be transcribed per research plan for us to coordinate with org rep on potential transcription software subscription.

### Action Items
- [x] Use `TWE: Template: Spreadsheet`(linked in Resources 1.01) to create a new spreadsheet 
- [x] Rename the spreadsheet as `TWE: Research: Interview Session Counts`
- [x] Save the spreadsheet in the `TWE Interview Recordings by Plan #` folder 
    - The path is internship - PII drive > TWE Interview Recordings by Plan # folder 
- [x] In Resources # 2.01, copy and paste the URL of the spreadsheet between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
- [x] Use the newly created spreadsheet to document research plan numbers, the number of interview sessions, and whether they are transcribed or not (whether the .txt file exists or not)
     - Use one row for a research plan number
     - Add the following columns in the spreadsheet
         - Research Plan Name
         - Interview Recording Locations
         - The number of interview sessions in the folder
         - Transcribed or not
         - Interview duration range (in minutes) (please list out each interview's length in minutes)
         - The number of interview sessions need to be transcribed
    - Add other factors you deem important to this issue
- [x] Go to `TWE Interview Recordings by Plan #` folder (linked in Resources 1.02)
- [x] Check each of those research plan's interview recording folder
- [x] Fill out the `TWE: Research: Interview Session Counts` spreadsheet by going through the interview files in each research plan folder except the `RP025 - Negative Experience Survey` folder
- [x] Go to `Research by Plan # and Name` folder (linked in Resources 1.03)
- [x] Check each research plan folder within the Research by Plan # Name folder
    - [x] See if there are any remaining interview audio or video files that should be moved to PII drive
        - [x] If you have identified any interview audio or video files that should be moved to PII drive, please list them out in Resources gathered during the completion of the issue section using 2.02, 2.03, etc.
        - [x] If no other interview audio or video files that should be moved to PII drive, no need to list anything out
- [x] Review with UXR leads
- [x] Review with Product team
- [x] Product sign-off

#### Resources for creating this issue
1.01 [TWE: Template: Spreadsheet](https://docs.google.com/spreadsheets/d/1yK7U_waj1xfx3KcdQ10uyaLvWCSVVpqLMLHvWonDWL4/template/preview)
1.02 [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=drive_link)
1.03 [Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=drive_link)

#### Resources gathered during the completion of the issue
2.01 [TWE: Research: Interview Session Counts](https://docs.google.com/spreadsheets/d/1zyMaE_9XJ3BXw8U8KMREh2GpZF8tceqRXvxAQyJgcQc/edit?gid=0#gid=0)

**Comment by mh-faraji** [comment]
@pandanista I have completed the tally of the existing interview files based on the research plan numbers, following the provided instructions. The spreadsheet titled **TWE: Research: Interview Session Counts** has been created and saved in the **TWE Interview Recordings by Plan #** folder.

Here’s a summary of what has been done:
•	Documented the number of interview sessions, the number transcribed, those still needing transcription, and the duration (in minutes) of each interview session to be transcribed for each RP folder based on the Research Plan Name.
•	Calculated totals: Out of 47 interview sessions, nine have been transcribed, 38 still require transcription, and approximately 1,040 minutes of interviews need to be transcribed.
•	Reviewed the **Research by Plan # and Name** folder, and no additional audio or video files require moving to the PII drive.

Please let me know if you need any further adjustments.

**Comment by pandanista** [comment]
@mh-faraji: This is great! Thank you for putting this together. Let's review with Product team at the all team meeting.

@sunannie27 @bonniewolfe 
- Based on Mehdi's calculation, 38 interviews still require transcription, and approximately 1,040 minutes of interviews.
- Please see more information Mehdi gathered in the [TWE: Research: Interview Session Counts](https://docs.google.com/spreadsheets/d/1zyMaE_9XJ3BXw8U8KMREh2GpZF8tceqRXvxAQyJgcQc/edit?gid=0#gid=0) sheet.

**Comment by pandanista** [comment]
Closing this issue as this issue is wrapped up, and we will refer to [TWE: Research: Interview Session Counts](https://docs.google.com/spreadsheets/d/1zyMaE_9XJ3BXw8U8KMREh2GpZF8tceqRXvxAQyJgcQc/edit?gid=0#gid=0) for future transcribing needs.
