### ISSUE TITLE
TWE: IS22: RP012: Intern Exit Interview Transcription: Set Up 

### ISSUE THREAD

**Issue by mh-faraji** [hackforla/internship#633]
### Dependencies  
 - [x] The research plan's interview recordings folder has been created on Internship - PII's "My Drive"

### Overview
We need to set up a few spreadsheets and a folder for RP012's Intern Exit interview transcripts so that we can move on to transcribe the interviews. 

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them.

### Action Items
- [x] UX lead asks admin to add the team member working on this issue to the 1Password internship-UX's vault so that they can have access to internship-UX's email and other software account information in case they need it.
- [x] UX lead adds the assignee to the Internship - PII's "My Drive" as a Content Manager so that they have access to internship - PII's My Drive where the recordings and transcriptions with PII are stored.
   - [x] UX lead accesses the Internship - PII's "My Drive"
   - [x] Choose "Manage members", which is located towards the top right side of the browser <img width="100" alt="Screenshot 2023-08-09 at 6 09 36 PM" src="https://github.com/hackforla/internship/assets/57029070/f7cc7fbe-1b00-4ded-8b44-b10fdbccae46">
   - [x] Enter the assignee's email address and select the role as "Content Manager" 
   - [x] Confirm with the assignee that they have access to the Internship - PII's "My Drive" 

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Find relevant wiki page for RP012
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Plan # and Name Folder (Resources # 1.02)
    - [x] Choose the `RP012` folder
    - [x] Copy the link of the `RP012` folder
        1. Choose the three vertical dots on the right side of the `RP012` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recordings and Transcriptions Tracking Sheet 
    - [x] Choose "TWE: Template: Interview Recordings and Transcriptions Tracking Sheet" (Resources # 1.03)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP012: Intern Exit Interview Recordings and Transcriptions Tracking Sheet
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field    
        f<img width="150" alt="Screenshot 2023-01-30 at 1 35 41 PM" src="https://user-images.githubusercontent.com/57029070/215600780-d8004229-17a3-409a-9d91-e4af9c904824.png"> <img width="700" alt="Screenshot 2023-01-30 at 1 34 45 PM" src="https://user-images.githubusercontent.com/57029070/215601015-cefd546c-8496-4b49-8643-ccfae3e4f9ca.png">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP012: Intern Exit Interview Recordings and Transcriptions Tracking Sheet
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="900" alt="Screenshot 2023-01-30 at 1 44 02 PM" src="https://user-images.githubusercontent.com/57029070/215602453-b2f08ba0-156b-4424-be5a-35b1f68b2be8.png">
        - [x] The title of the spreadsheet is now updated
        - [x] Copy 
        ```
        Intern Number
        ```
        - [x] Choose cell A2
        - [x] Choose the formula bar, paste the text you copied <img width="500" alt="Screenshot 2023-01-30 at 1 48 32 PM" src="https://user-images.githubusercontent.com/57029070/215602930-c3933344-d5a4-46df-85ed-3557e8bc6d17.png">
        - [x] The cell of the spreadsheet is now updated
    - [x] Save the spreadsheet into this Research Plan's Google Drive folder in the Internship's shared drive (Resource # 2.02)
        1.  Choose File > Move (or Move icon)
        1.  Choose "All locations"
        1.  Choose Shared drives > Internship > Internships > Research > Research by Type > Intern > folder for RP012
        1.  Choose "Move"
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share"
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

 - Customize Resource for De-identified Participants List Spreadsheet in the Shared Google Drive to Keep Track of Any Stakeholders Mentioned in Interview Sessions
    - [x] Choose "TWE: Template: De-identified Participants List from Interviews (UXR Excluded)" (Resources # 1.04)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP012: De-identified Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field <img width="500" alt="Screenshot 2024-09-25 at 5 52 33 PM" src="https://github.com/user-attachments/assets/936978a5-df0e-47d2-8d7e-30922929f1f2">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP012: De-identified Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="900" alt="Screenshot 2024-09-25 at 4 46 08 PM" src="https://github.com/user-attachments/assets/75f92c89-ecc6-4d37-8e1a-8026464f427a">
        - [x] The title of the spreadsheet is now updated
    - [x] Move the file to RP012's folder in the shared Google Drive
        1. Choose File > Move > All Locations > Shared drives > Internship > Internships > Research > Research by Plan # and Name > RP012 > Move
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share" on the top right corner of the spreadsheet
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recording Folder stored in the Internship - PII's `My Drive`
    - [x] Make sure you are logged into your Google account associated with TWE project so you will be able to access the Internship - PII's 'My Drive' in the next steps 
    - [x] Choose Shared drives > Internship - PII > Internship - PII
    - [x] Choose `TWE Interview Recordings by Plan #` folder in Internship - PII's `My drive` (Resources # 1.05) 
    - [x] Locate the video recording folder for RP012 inside the folder `TWE Interview Recordings by Plan #`
    - [x] Copy the link of the video recording folder for RP012 
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Participants List Spreadsheet to Save in the Video Recording Folder for RP012 in the Internship - PII's `My Drive`
    - [x] Choose "TWE: Template: Participants List from Interviews (UXR Excluded)" (Resources # 1.06)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP012: Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field <img width="500" alt="Screenshot 2024-09-25 at 6 07 00 PM" src="https://github.com/user-attachments/assets/de115851-2be3-4dcb-b69d-11eb44a48715">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP012: Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="1200" alt="Screenshot 2024-09-25 at 5 33 30 PM" src="https://github.com/user-attachments/assets/366e9f87-cf0f-40c6-a840-12824ec2f3f1">
        - [x] The title of the spreadsheet is now updated
    - [x] Save the spreadsheet into RP012 Interview Recording Folder in the Internship's PII drive (Resource # 2.04)
        1.  Choose File > Move (or Move icon)
        1.  Choose "All locations"
        1.  Choose Shared drives > Internship - PII > Internship - PII > TWE Interview Recordings by Plan # > folder for RP012
        1.  Choose "Move"
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share" on the top right corner of the spreadsheet
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Set Up A Folder for De-identified Transcripts in the RP012 folder (Resources # 2.02)
- [x] Go to RP012 folder (Resources # 2.02)
- [x] Create a new folder for the de-identified transcripts in the RP012 folder by choosing "New" and "New folder" on the left side bar  <img width="127" alt="Screenshot 2023-01-27 at 2 34 43 PM" src="https://user-images.githubusercontent.com/57029070/215219196-2e8b1712-6c74-4893-a1aa-7db51ca48e19.png">   <img width="200" alt="Screenshot 2023-01-27 at 2 35 00 PM" src="https://user-images.githubusercontent.com/57029070/215219378-052eefb3-64e5-447f-941d-1c2d04f3f1f2.png">
- [x] Name the "New folder" by copying 
```
RP012 De-identified Transcripts
```
- [x] Paste the text you copied into the folder name
- [x] Copy the link of the folder
    1. Choose the three vertical dots on the right side of the folder <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Get link"
    1. Choose "Copy Link" and "Done"
- [x] Paste the copied link into parentheses at the end of the line in Resources # 2.07
- [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Update the wiki page for this research plan (Resources # 2.01)
- [x] Open the link in Resource 2.01
- [x] Find the "Interview Recordings & Transcripts" section
- [x] Copy and paste Resource 2.07 (both the text and URL) into the "Interview Recordings & Transcripts" section
- [x] Choose "Save Page"

#### Review and hand off
- [x] Review with UXR Leads 
- [x] The assignee checks in with UXR Leads to create new issues for transcribing the interview recordings if needed
- [ ] UXR Lead or PM removes the assignee from the Internship - PII's "My Drive" when closing the issue if the assignee does not need to access the Internship - PII's "My Drive" any longer
- [ ] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [TWE: Template: Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1aeUFd5tZQoJCriTzJc2L-L0KS7sXmwhveewb1dviX3I/template/preview)
1.04 [TWE: Template: De-identified Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/19-jrpj8RxFzAfk09ToxR1H6xNrok_1bgmNfH00CtkxM/template/preview)
1.05* [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=sharing)
1.06 [TWE: Template: Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/1rVk63jdWqjF8sIayo1N4bbfRsCfLUd8YPr1dEdfq6K4/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan: RP012](https://github.com/hackforla/internship/wiki/Research-Plan-12:-Intern-Exit-Interviews)
2.02 [Google Drive Folder: RP012](https://drive.google.com/drive/folders/1Qw1K3uOa-VS25_HkMx-nIKeIy4wlT-OH?usp=drive_link)
2.03 [TWE: IS22: RP012: Intern Exit Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1d0vZ-Rv7G6qcITcUpPg-nchLSECzQDNu8jGBLHxxmF4/edit?usp=sharing)
2.04 [TWE: IS22: RP012: De-identified Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/1jCqWqNm8jcltVj40RRpS7K4AyTmkO2Q3XJW9qGoptw4/edit?usp=sharing)
2.05* [RP012 Interview Recording Folder](https://drive.google.com/drive/folders/1qWR0TkO61o15ccajDOdp-2fglAq77BTm?usp=drive_link)
2.06* [TWE: IS22: RP012: Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/1H94rEGjeQpRBjtZ3QOfIPC9v-pX6t1Lj96_YL0kh4XE/edit?usp=sharing)
2.07 [RP012 De-identified Transcripts](https://drive.google.com/drive/folders/1EtU3yUAHlwZrW2iPQjJruYqOtGrFwL48?usp=drive_link)

* indicates this folder can only be accessed from the Internship - PII's "My Drive"

**Comment by mh-faraji** [comment]
Update:
The setup for RP012's Intern Exit interview transcripts is complete. All spreadsheets, folders, and links have been created and organized as per the instructions. Ready for research lead to review and move on to transcribe the interviews.

**Comment by pandanista** [comment]
@mh-faraji: Thank you very much for getting those done so quickly.
A few follow-up questions:
- How long did it take for you to get those done? A rough estimate is okay.
- What do you think of [the template](https://github.com/hackforla/internship/issues/633#issue-2604089095) you just tested? Is there anything we could make it easier for assignees to follow and complete each task? Any feedback is welcome.

**Comment by mh-faraji** [comment]
@pandanista I'm not sure about the exact time, but I estimate it took around two hours to complete all the tasks. There were many steps involved, but the instructions were precise and detailed, which I really appreciated. I didn’t encounter any serious issues, so great job on designing the instructions!

**Comment by pandanista** [comment]
@mh-faraji Thank you for the feedback. I have updated the size of the issue from 0.25 to 0.5 based on your estimate in [the template](https://github.com/hackforla/internship/issues/335#issuecomment-1760447927). All the files and links you added in the `Resources gathered during the completion of this issue` section look good. Great job accomplishing this one!

@sunannie27 @KC-skc 
If any of you is reviewing this issue, please give us a thumbs up. Thank you.

Mehdi has created a few spreadsheets (see Resources 2.03, 2.04, and 2.06) and a folder (Resources 2.07) so we can have everything set up to move on to the transcribing stage. Please review the deliverables in Resources 2.03, 2.04, 2.06, and 2.07. Let us know if you have any questions. If everything looks good, we can close this issue.

Please don't remove Mehdi from the PII drive yet as he will be working on transcribing issues.

**Comment by sunannie27** [comment]
@pandanista Just reviewed. Looks good to me as well. Great job @mh-faraji ! I will close this issue.
