### ISSUE TITLE
[TEST] TWE: IS22: RP012: Intern I005 Exit Interview Recording: Transcribe: Otter

### ISSUE THREAD

**Issue by mh-faraji** [hackforla/internship#637]
### Dependencies  
 - [x] Org rep has decided on the choice of the transcription software: we are testing using Otter in this issue
 - [x] The assignee is added to 1Password's Internship UI/UX vault
 - [x] Interview transcription set-up phase issue has been completed

### Overview
We need to transcribe RP012's Intern I005 Exit interview recordings so that we can move on to clean up and de-identify the transcripts. 

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them.

### Action Items
- [x] UX lead asks admin to add the team member working on this issue to the 1Password internship-UX's vault so that they can have access to Internship-ux@hackforla.org Google account or other software account if they need it.
- [x]  UX lead adds the assignee to the Internship - PII's "My Drive" as a Content Manager so that they have access to internship - PII's My Drive where the recordings and transcriptions with PII are stored.
   - [x] UX lead accesses the Internship - PII's "My Drive"
   - [x] Choose "Manage members", which is located towards the top right side of the browser <img width="200" alt="Screenshot 2023-08-09 at 6 09 36 PM" src="https://github.com/hackforla/internship/assets/57029070/f7cc7fbe-1b00-4ded-8b44-b10fdbccae46">
   - [x] Enter the assignee's email address and select the role as "Content Manager" 
   - [x] Confirm with the assignee that they have access to the Internship - PII's "My Drive" 

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Find relevant wiki page for RP012
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Plan # and Name Folder (Resources # 1.02)
    - [x] Choose the `RP012` folder
    - [x] Copy the link of the `RP012` folder
        1. Choose the three vertical dots on the right side of the `RP012` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for RP012's Interview Recordings and Transcriptions Tracking Sheet 
    - [x] Open the `RP012` folder if it is not open yet (Resources # 2.02)
    - [x] Copy the link of `TWE: IS22: RP012: Intern Exit Interview Recordings and Transcriptions Tracking Sheet`
        1. Choose the three vertical dots on the right side of the spreadsheet  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Intern I005's interview recording file stored in the Internship - PII's `My Drive`
    - [x] Make sure you are logged into your Google account associated with TWE project so you will be able to access the Internship - PII's 'My Drive' in the next steps 
    - [x] Choose Shared drives > Internship - PII > Internship - PII
    - [x] Choose `TWE Interview Recordings by Plan #` folder in Internship - PII's `My drive` (Resources # 1.03) 
    - [x] Locate the video recording folder for RP012 inside the folder `TWE Interview Recordings by Plan #`
    - [x] Copy the link of the video recording folder for RP012 
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked
    - [x] Open the video recording folder for RP012 if it is not open yet (Resources # 2.04)
    - [x] Locate Intern I005's interview recording file
    - [x] Copy the link of the video recording file for Intern I005
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link"
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Rename Uploaded Recording Video Files If Needed 
- [x] Go to the recording file(s) linked in Resource # 2.05
- [x] Make sure the Intern I005 interview recording video file in the folder is named as `RP012-UX Researcher Abbreviation###-Intern Abbreviation###`
    - If the recording video file is not in the format above, please rename the recording files in the format above first before taking any more actions
    - An example looks like this: `RP006-U007-I001.mp4`, which means this is an interview recording for research plan 006, conducted by UX Researcher 007, and the interviewee is Intern 001
    - In case if you would like to double check to ensure the accuracy, both UX Researcher Abbreviation### and Intern Abbreviation### can be found in `TWE: IS22: RP012: Intern Exit Interview Roll Call and Session Table` in RP012 folder (linked in Resources # 2.02)

#### Transcribe the Interview when transcripts are not available
- [x] Open `RP012 Interview Recording Folder` linked in Resource # 2.04 if it is not open yet
- [x] Check to see if Intern I005's interview recording file has been transcribed or not
    - [x] If yes, move on to `#### Update Interview Recordings and Transcriptions Tracking Sheet` section
    - [x] If no, do the following to transcribe Intern I005's interview file(s)
        - [x] Download Intern I005's interview recording that needs to be transcribed from the Google Drive (Resources # 2.05) to a temporary folder locally
        - [x] Log into 1password (Resources # 1.04) to access the transcription software's account information if needed
            1. Choose internship-UI/UX vault
            1. Choose the transcription software account or the Internship-UX Google account to see login info if needed
        - [x] Access the account by copying and pasting the login info from 1password vault
        - [x] Confirm you can access the account you need
        - Complete the following steps using the transcription software:
            - [x] Import or upload the video file that you need to transcribe
            - [x] Wait for the software to transcribe the file for you
            - [x] Once finished, download the .txt transcript file
            - [x] Rename the .txt transcript file you downloaded in `RP012-UX Researcher Abbreviation###-Intern Abbreviation###` format
                - An example looks like this: `RP006-U007-I001.txt`, which means this is an interview transcript for research plan 006, conducted by UX Researcher 007, and the interviewee is Intern 001
                - Please double-check the UX Researcher number and participant number in `TWE: IS22: RP012: Intern Exit Interview Roll Call and Session Table` in RP012 folder (linked in Resources # 2.02)
            - [x] Upload the .txt file into RP012's interview recording folder (Resources # 2.04)
                - So there will be two types of files named in the `RP012-UX Researcher Abbreviation###-Intern Abbreviation###` format. One is a .mp4 video from the interview while the other one is a transcript in .txt format.
        - [x] Delete the local temporary folder with recording file(s) from your own device, such as your laptop
    
#### Update Interview Recordings and Transcriptions Tracking Sheet
- [x] Open the Interview Recordings and Transcriptions Tracking Sheet (linked in Resources # 2.03) 
- [x] In Column A of the Tracking Sheet, enter the participant number(s)
     1. The participant number is reflected in this issue's title
     1. Refer to the "Session Table" tab of `TWE: IS22: RP012: Intern Exit Interview Roll Call and Session Table` inside `Google Drive Folder: RP012` (Resources # 2.02) if you need a source to double check on participants' information
- [x] In Column B of the Tracking Sheet, enter the recording link(s)
    1. Go to Intern I005's interview recording file (Resources # 2.05) 
    1. Choose the three vertical dots on the right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Copy Link" 
    1. Paste the link of the .mp4 file(s) into the corresponding participant's cell in Column B `Recording Link` of the Tracking Sheet (Resources # 2.03) 
- [x] In Column C, enter the transcription link(s)
    1. Go to RP012's interview recording folder (Resources # 2.04)
    1. Locate the .txt file(s) for Intern I005
    1. Choose the three vertical dots on the right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Copy Link" 
    1. Paste the link of the .txt file(s) into the corresponding participant's cell in Column C `Transcription Link (on Internship - PII's private drive, in .txt format)` of the Tracking Sheet (Resources # 2.03) 
    1. In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    1. Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Review and hand off
- [x] Review with UXR Leads to make sure the transcription is done properly
- [ ] The assignee checks in with UXR Lead to create new issues for cleaning up and de-identifying the transcripts if needed
- [ ] UXR Lead or PM removes the assignee from the Internship - PII's "My Drive" when closing the issue if the assignee does not need to access the Internship - PII's "My Drive" any longer
- [x] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03* [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=sharing)
1.04 [1password](https://start.1password.com/signin?l=en)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan: RP012](https://github.com/hackforla/internship/issues/637#issue-2609916285)
2.02 [Google Drive Folder: RP012](https://drive.google.com/drive/folders/1Qw1K3uOa-VS25_HkMx-nIKeIy4wlT-OH?usp=drive_link)
2.03 [TWE: IS22: RP012: Intern Exit Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1d0vZ-Rv7G6qcITcUpPg-nchLSECzQDNu8jGBLHxxmF4/edit?usp=drive_link)
2.04* [RP012 Interview Recording Folder](https://drive.google.com/drive/folders/1qWR0TkO61o15ccajDOdp-2fglAq77BTm?usp=drive_link)
2.05* [RP012 Intern I005 Interview Recording File](https://drive.google.com/file/d/1YKm_-qj3kE3jdsfVal1mFjcPoGO4-vSm/view?usp=drive_link)
2.06* [RP012 Intern I005 Interview Recording Transcript - Otter](https://drive.google.com/file/d/1B-6pRnnb0QmbGNadHe7Nv4J3uhvUuHld/view?usp=drive_link)

* indicates this folder can only be accessed from the Internship - PII's "My Drive"

**Comment by mh-faraji** [comment]
Update:
The transcription of RP012's Intern I005 Exit interview recordings is completed.
Two transcripts from the file (RP012-U006-I005) are available as samples, processed by Otter.ai (#637) and Torbscribe [(#635).](https://github.com/hackforla/internship/issues/635) Both tools identified the speakers and provided timestamps, which will accelerate the cleaning and de-identification process. However, I believe Otter.ai's output will also benefit the qualitative analysis phase, making it faster, more accurate, and more consistent. In addition to the transcript, it also provides a summary of the interview, it outlines the interviewee's responses, and its AI Chat feature can pose and answer questions about the transcript. The summary and the outline are available at the end of the transcript 2.06* [RP012 Intern I005 Interview Recording Transcript](https://drive.google.com/file/d/1B-6pRnnb0QmbGNadHe7Nv4J3uhvUuHld/view?usp=drive_link). 
The free version of Otter.ai allows up to 300 minutes of downloads per month.

**Comment by pandanista** [comment]
@mh-faraji: Would you provide an estimate on how long it took to accomplish this issue?

According to [Otter.ai](https://otter.ai/pricing),
> 300 monthly transcription minutes; 30 minutes per conversation; Import and transcribe 3 audio or video files lifetime per user
- I think the 300 minutes refers to transcription during the meetings minutes, but I could be wrong here. Would you please look into that? 
- It seems like they still only allow 3 video files uploaded and transcribed lifetime, and the "import and transcribe" is the main function that apply to us.

**Comment by pandanista** [comment]
I am glad we have at least one transcript sample from otter.

Added [RP012 Intern I005 Interview Recording Transcript - Otter](https://drive.google.com/file/d/1B-6pRnnb0QmbGNadHe7Nv4J3uhvUuHld/view?usp=drive_link) to #629 so we can compare the transcript quality.

**Comment by pandanista** [comment]
@mh-faraji Also, was it the internship-ux account?

**Comment by mh-faraji** [comment]
Yes, it was.

**Comment by pandanista** [comment]
- [RP012 Intern I005 Interview Recording Transcript - Otter](https://drive.google.com/file/d/1B-6pRnnb0QmbGNadHe7Nv4J3uhvUuHld/view?usp=drive_link) was done to test the transcribe template and also to have a sample of Otter's transcript to help the team compare transcription tools
- Closing this issue as all the action items are completed, and the testing went well.

Tagging @sunannie27 and @KC-skc for visibility.
