### ISSUE TITLE
Record October 4th Onboarding Session

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#64]
### Overview
We need to record the onboarding session on October 4th and share the link with volunteers who cannot attend the live session due to timing or other constraints.

### Action Items

- [x] Record October 4th on boarding session
- [ ] Upload and share link

### Resources/Instructions
[October 4th Onboarding Recording Folder
](https://drive.google.com/drive/folders/1sYLELmZ03oAjpT2fL7irOuwWL4XpqWss?usp=sharing)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty
Hi Bonnie, if we have a viable recording for the Oct 12th onboarding, can you please upload here so that I can share it? Thanks.

**Comment by ExperimentsInHonesty** [comment]
I am going to close this issue.  I onboarded Kelly directly
