### ISSUE TITLE
TWE: IS22: RP014: Mentor Exit Interview Transcription: Set Up 

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#641]
### Dependencies  
 - [x] The research plan's interview recordings folder has been created on Internship - PII's "My Drive"

### Overview
We need to set up a few spreadsheets and a folder for RP014's Mentor Exit interview transcripts so that we can move on to transcribe the interviews. 

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them.

### Action Items
- [x] UX lead asks admin to add the team member working on this issue to the 1Password internship-UX's vault so that they can have access to internship-UX's email and other software account information in case they need it.
- [x] UX lead adds the assignee to the Internship - PII's "My Drive" as a Content Manager so that they have access to internship - PII's My Drive where the recordings and transcriptions with PII are stored.
   - [x] UX lead accesses the Internship - PII's "My Drive"
   - [x] Choose "Manage members", which is located towards the top right side of the browser <img width="100" alt="Screenshot 2023-08-09 at 6 09 36 PM" src="https://github.com/hackforla/internship/assets/57029070/f7cc7fbe-1b00-4ded-8b44-b10fdbccae46">
   - [x] Enter the assignee's email address and select the role as "Content Manager" 
   - [x] Confirm with the assignee that they have access to the Internship - PII's "My Drive" 

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Find relevant wiki page for RP014
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Plan # and Name Folder (Resources # 1.02)
    - [x] Choose the `RP014` folder
    - [x] Copy the link of the `RP014` folder
        1. Choose the three vertical dots on the right side of the `RP014` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recordings and Transcriptions Tracking Sheet 
    - [x] Choose "TWE: Template: Interview Recordings and Transcriptions Tracking Sheet" (Resources # 1.03)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP014: Mentor Exit Interview Recordings and Transcriptions Tracking Sheet
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field    
        f<img width="150" alt="Screenshot 2023-01-30 at 1 35 41 PM" src="https://user-images.githubusercontent.com/57029070/215600780-d8004229-17a3-409a-9d91-e4af9c904824.png"> <img width="700" alt="Screenshot 2023-01-30 at 1 34 45 PM" src="https://user-images.githubusercontent.com/57029070/215601015-cefd546c-8496-4b49-8643-ccfae3e4f9ca.png">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP014: Mentor Exit Interview Recordings and Transcriptions Tracking Sheet
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="900" alt="Screenshot 2023-01-30 at 1 44 02 PM" src="https://user-images.githubusercontent.com/57029070/215602453-b2f08ba0-156b-4424-be5a-35b1f68b2be8.png">
        - [x] The title of the spreadsheet is now updated
        - [x] Copy 
        ```
        Mentor Number
        ```
        - [x] Choose cell A2
        - [x] Choose the formula bar, paste the text you copied <img width="500" alt="Screenshot 2023-01-30 at 1 48 32 PM" src="https://user-images.githubusercontent.com/57029070/215602930-c3933344-d5a4-46df-85ed-3557e8bc6d17.png">
        - [x] The cell of the spreadsheet is now updated
    - [x] Save the spreadsheet into this Research Plan's Google Drive folder in the Internship's shared drive (Resource # 2.02)
        1.  Choose File > Move (or Move icon)
        1.  Choose "All locations"
        1.  Choose Shared drives > Internship > Internships > Research > Research by Type > Mentor > folder for RP014
        1.  Choose "Move"
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share"
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

 - Customize Resource for De-identified Participants List Spreadsheet in the Shared Google Drive to Keep Track of Any Stakeholders Mentioned in Interview Sessions
    - [x] Choose "TWE: Template: De-identified Participants List from Interviews (UXR Excluded)" (Resources # 1.04)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP014: De-identified Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field <img width="500" alt="Screenshot 2024-09-25 at 5 52 33 PM" src="https://github.com/user-attachments/assets/936978a5-df0e-47d2-8d7e-30922929f1f2">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP014: De-identified Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="900" alt="Screenshot 2024-09-25 at 4 46 08 PM" src="https://github.com/user-attachments/assets/75f92c89-ecc6-4d37-8e1a-8026464f427a">
        - [x] The title of the spreadsheet is now updated
    - [x] Move the file to RP014's folder in the shared Google Drive
        1. Choose File > Move > All Locations > Shared drives > Internship > Internships > Research > Research by Plan # and Name > RP014 > Move
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share" on the top right corner of the spreadsheet
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Interview Recording Folder stored in the Internship - PII's `My Drive`
    - [x] Make sure you are logged into your Google account associated with TWE project so you will be able to access the Internship - PII's 'My Drive' in the next steps 
    - [x] Choose Shared drives > Internship - PII > Internship - PII
    - [x] Choose `TWE Interview Recordings by Plan #` folder in Internship - PII's `My drive` (Resources # 1.05) 
    - [x] Locate the video recording folder for RP014 inside the folder `TWE Interview Recordings by Plan #`
    - [x] Copy the link of the video recording folder for RP014 
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Get link"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Participants List Spreadsheet to Save in the Video Recording Folder for RP014 in the Internship - PII's `My Drive`
    - [x] Choose "TWE: Template: Participants List from Interviews (UXR Excluded)" (Resources # 1.06)
    - [x] Choose "USE TEMPLATE" to make a copy of the document
    - Rename and customize the file by following the steps
        - [x] Copy 
        ```
        TWE: IS22: RP014: Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose "File" > "Rename", and paste the text you copied into the top field <img width="500" alt="Screenshot 2024-09-25 at 6 07 00 PM" src="https://github.com/user-attachments/assets/de115851-2be3-4dcb-b69d-11eb44a48715">
        - [x] The name of the file is now updated
        - [x] Copy 
        ```
        TWE: IS22: RP014: Participants List from Interviews (UXR Excluded)
        ```
        - [x] Choose the header row (row 1)
        - [x] Choose the formula bar, and paste the text you copied into it <img width="1200" alt="Screenshot 2024-09-25 at 5 33 30 PM" src="https://github.com/user-attachments/assets/366e9f87-cf0f-40c6-a840-12824ec2f3f1">
        - [x] The title of the spreadsheet is now updated
    - [x] Save the spreadsheet into RP014 Interview Recording Folder in the Internship's PII drive (Resource # 2.04)
        1.  Choose File > Move (or Move icon)
        1.  Choose "All locations"
        1.  Choose Shared drives > Internship - PII > Internship - PII > TWE Interview Recordings by Plan # > folder for RP014
        1.  Choose "Move"
        1.  Choose "Move" when it asks if you want to change ownership to a shared drive
        1.  Dismiss the notification that says the file in now in the shared drive
    - [x] Choose "Share" on the top right corner of the spreadsheet
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Set Up A Folder for De-identified Transcripts in the RP014 folder (Resources # 2.02)
- [x] Go to RP014 folder (Resources # 2.02)
- [x] Create a new folder for the de-identified transcripts in the RP014 folder by choosing "New" and "New folder" on the left side bar  <img width="127" alt="Screenshot 2023-01-27 at 2 34 43 PM" src="https://user-images.githubusercontent.com/57029070/215219196-2e8b1712-6c74-4893-a1aa-7db51ca48e19.png">   <img width="200" alt="Screenshot 2023-01-27 at 2 35 00 PM" src="https://user-images.githubusercontent.com/57029070/215219378-052eefb3-64e5-447f-941d-1c2d04f3f1f2.png">
- [x] Name the "New folder" by copying 
```
RP014 De-identified Transcripts
```
- [x] Paste the text you copied into the folder name
- [x] Copy the link of the folder
    1. Choose the three vertical dots on the right side of the folder <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Get link"
    1. Choose "Copy Link" and "Done"
- [x] Paste the copied link into parentheses at the end of the line in Resources # 2.07
- [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Rename Uploaded Recording Video Files If Needed
- [x] Go to the interview recording folder linked in Resource # 2.05
- [x] Make sure each recording video file in the folder is named as `RP014-UX Researcher Abbreviation###-Mentor Abbreviation###`
    - If the recording video files are not in the format above, please rename the recording files in the format above first before taking any more actions
    - An example looks like this: `RP006-U007-I001.mp4`, which means this is an interview transcript for research plan 006, conducted by UX Researcher 007, and the interviewee is Intern 001
    - In case if you would like to double check to ensure the accuracy of the interviewer and interviewees' numbers, both UX Researcher Abbreviation### and Mentor Abbreviation### can be found in the `session table` tab of `TWE: IS22: RP014: Mentor Exit Interview Roll Call and Session Table` in RP014 folder (linked in Resources # 2.02)

#### Update the wiki page for this research plan (Resources # 2.01)
- [x] Open the link in Resource 2.01 
- [x] Find the "Interview Recordings & Transcripts" section
- [x] Copy and paste Resource 2.07 (both the text and URL) into the "Interview Recordings & Transcripts" section
- [x] Choose "Save Page"

#### Review and hand off
- [x] Review with UXR Leads on the spreadsheets, de-identified transcript folder setup, renamed recording files, and updated wiki section 
- [x] The assignee checks in with UXR Leads to create new issues for transcribing the interview recordings if needed
- [ ] UXR Lead or PM removes the assignee from the Internship - PII's "My Drive" when closing the issue if the assignee does not need to access the Internship - PII's "My Drive" any longer
- [x] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [TWE: Template: Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1aeUFd5tZQoJCriTzJc2L-L0KS7sXmwhveewb1dviX3I/template/preview)
1.04 [TWE: Template: De-identified Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/19-jrpj8RxFzAfk09ToxR1H6xNrok_1bgmNfH00CtkxM/template/preview)
1.05* [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=sharing)
1.06 [TWE: Template: Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/1rVk63jdWqjF8sIayo1N4bbfRsCfLUd8YPr1dEdfq6K4/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan: RP014](https://github.com/hackforla/internship/wiki/Research-Plan-14:-Mentor-Exit-Interviews)
2.02 [Google Drive Folder: RP014](https://drive.google.com/drive/folders/1VRKUJx75IAQMtDdsyZBTz9HtJeTK8bR0?usp=drive_link)
2.03 [TWE: IS22: RP014: Mentor Exit Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1ZkMgFbIqHmIRr0FsqAXsFdHRRwbitUVVymBh9Rta_H8/edit?usp=sharing)
2.04 [TWE: IS22: RP014: De-identified Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/14ZFsGiMvmLRS9s0sVVoCE1fqoGPFD_-qvrLFcgGNdns/edit?usp=sharing)
2.05* [RP014 Interview Recording Folder](https://drive.google.com/drive/folders/1PyxK1lb6T3qZuU_mzYkRkhTb9Zqwr1os?usp=drive_link)
2.06* [TWE: IS22: RP014: Participants List from Interviews (UXR Excluded)](https://docs.google.com/spreadsheets/d/1w41FI258S82y7uj0VNdKUq2R0nHCHC_QHst8J94uIZ8/edit?usp=sharing)
2.07 [RP014 De-identified Transcripts](https://drive.google.com/drive/folders/1i9s_5uzhRIaI-O0nINO_fn_RZnbW10Xp?usp=drive_link)

* indicates this folder can only be accessed from the Internship - PII's "My Drive"

**Comment by mh-faraji** [comment]
@pandanista I completed the issue. If there is nothing else, please assign the next issue to me.

Just one comment: In the renaming of videos, I think the letter used for Mentor Abbreviation should be "M", not "I".   
![Screenshot 2024-11-01 at 11 04 34 PM](https://github.com/user-attachments/assets/69db3a7c-223b-489e-b3da-75cf34bbac93)

**Comment by pandanista** [comment]
@mh-faraji: Sounds good. I will review the issue, and we will figure out the next steps to create transcribing issues for RP014 next week. Just assigned you a new issue. 

Yes, M stands for mentor. The one you circled above in the instructions is only an example, and the example is not customized per participant type. So if you keep reading till the end of the section, it says I001 means intern 001.

**Comment by pandanista** [comment]
@mh-faraji All the resources gathered from 2.01 to 2.07 look good. Great job. 
Let's create new issues for RP014's transcribing phase using the [transcribe template](https://github.com/hackforla/internship/issues/new?assignees=&labels=complexity%3A+small%2C+feature%3A+recording+transcription%2C+feature%3A+research%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+0.25pt&projects=&template=research--transcribe-user-interview-recordings.md&title=TWE%3A+IS%5BReplace+YY%5D%3A+RP%5BReplace+000%5D%3A+%5BReplace+TYPE+OF+PARTICIPANT%5D+%5BReplace+PARTICIPANT+NUMBER%5D+%5BReplace+TYPE+OF+INTERVIEW%5D+Interview+Recording%3A+Transcribe)
- the template can be found by choosing "New issues" > "Research: Transcribe User Interview Recordings" > "Get started"
- We can discuss more at the UXR meeting.

**Comment by pandanista** [comment]
I will create a new issue as an example.

**Comment by pandanista** [comment]
@mh-faraji 
- An example of the transcribing issue for RP014 is #645.
- Please create new issues for transcribing exit interviews with Mentor 002, Mentor 003, and Mentor 005.
- Once the issues are created, please put them in the prioritized backlog.
- Let me know if you have any questions. 
- I am closing this issue it is now completed.

**Comment by mh-faraji** [comment]
@pandanista I created new issues for transcribing exit interviews with Mentors 002, 003, and 005 and put them in the prioritized backlog. Please let me know if there is anything else.
