### ISSUE TITLE
TWE: IS22: RP014: Mentor 001 Exit Interview Recording: Transcribe 

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#645]
### Dependencies  
 - [x] Org rep has decided on the choice of the transcription software: TurboScribe will be used for transcribing this interview.
 - [x] #641 

### Overview
We need to transcribe RP014's Mentor 001 Exit interview recordings so that we can move on to clean up and de-identify the transcripts. 

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

Another tip is to use split browser windows side by side when working on any GitHub issue, so you can edit the issue on one window, and check the resources or click through links on the other window to avoid a lot of back and forth. Make sure to refresh both windows to reflect any changes you made, including updating the issue or checking the boxes on one of them.

### Action Items
- [x] UX lead asks admin to add the team member working on this issue to the 1Password internship-UX's vault so that they can have access to Internship-ux@hackforla.org Google account or other software account if they need it.
- [x] UX lead adds the assignee to the Internship - PII's "My Drive" as a Content Manager so that they have access to internship - PII's My Drive where the recordings and transcriptions with PII are stored.
   - [x] UX lead accesses the Internship - PII's "My Drive"
   - [x] Choose "Manage members", which is located towards the top right side of the browser <img width="200" alt="Screenshot 2023-08-09 at 6 09 36 PM" src="https://github.com/hackforla/internship/assets/57029070/f7cc7fbe-1b00-4ded-8b44-b10fdbccae46">
   - [x] Enter the assignee's email address and select the role as "Content Manager" 
   - [x] Confirm with the assignee that they have access to the Internship - PII's "My Drive" 

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Find relevant wiki page for RP014
    - [x] Copy the link for the wiki page
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

- Customize Resource for this Research Plan's Google Drive Folder
    - [x] Open the Google Drive's Research by Plan # and Name Folder (Resources # 1.02)
    - [x] Choose the `RP014` folder
    - [x] Copy the link of the `RP014` folder
        1. Choose the three vertical dots on the right side of the `RP014` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link" and "Done"
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for RP014's Interview Recordings and Transcriptions Tracking Sheet 
    - [x] Open the `RP014` folder if it is not open yet (Resources # 2.02)
    - [x] Copy the link of `TWE: IS22: RP014: Mentor Exit Interview Recordings and Transcriptions Tracking Sheet`
        1. Choose the three vertical dots on the right side of the spreadsheet  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

- Customize Resource for Mentor 001's interview recording file stored in the Internship - PII's `My Drive`
    - [x] Make sure you are logged into your Google account associated with TWE project so you will be able to access the Internship - PII's 'My Drive' in the next steps
    - [x] Choose `TWE Interview Recordings by Plan #` folder in Internship - PII's `My drive` (Resources # 1.03) 
    - [x] Locate the video recording folder for RP014 inside the folder `TWE Interview Recordings by Plan #`
    - [x] Copy the link of the video recording folder for RP014 
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked
    - [x] Open the video recording folder for RP014 if it is not open yet (Resources # 2.04)
    - [x] Locate Mentor 001's interview recording file
    - [x] Copy the link of the video recording file for Mentor 001
        1. Choose the three vertical dots on the right side of the folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy Link"
    - [x] In Resources # 2.05, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Transcribe the Interview when transcripts are not available
- [x] Open `RP014 Interview Recording Folder` linked in Resource # 2.04 if it is not open yet
- [x] Check to see if Mentor 001's interview recording has been transcribed or not. If already transcribed, there should be a.txt file matching with the participant's number.
    - [x] If yes, move on to `#### Update Interview Recordings and Transcriptions Tracking Sheet` section
    - [ ] If no, do the following to transcribe Mentor 001's interview file(s)
        - [ ] Download Mentor 001's interview recording that needs to be transcribed from the Google Drive (Resources # 2.05) to a temporary folder locally
        - [ ] Log into 1password (Resources # 1.04) to access the transcription software's account information if needed
            1. Choose internship-UI/UX vault
            1. Choose the transcription software account or the Internship-UX Google account to see login info if needed
        - [ ] Access the account by copying and pasting the login info from 1password vault
        - [ ] Confirm you can access the account you need
        - Complete the following steps using the transcription software:
            - [ ] Import or upload the video file that you need to transcribe
            - [ ] Wait for the software to transcribe the file for you
            - [ ] Once finished, download the .txt transcript file
            - [ ] Rename the .txt transcript file you downloaded in `RP014-UX Researcher Abbreviation###-Mentor Abbreviation###` format
                - An example looks like this: `RP006-U007-I001.txt`, which means this is an interview transcript for research plan 006, conducted by UX Researcher 007, and the interviewee is Intern 001
                - Please double-check the UX Researcher number and the participant's number in the `session table` tab of `TWE: IS22: RP014: Mentor Exit Interview Roll Call and Session Table` in RP014 folder (linked in Resources # 2.02)
            - [ ] Upload the .txt file into RP014's interview recording folder (Resources # 2.04)
                - So there will be two types of files named in the `RP014-UX Researcher Abbreviation###-Mentor Abbreviation###` format. One is a .mp4 video from the interview while the other one is a transcript in .txt format.
        - [ ] Delete the local temporary folder with recording file(s) from your own device, such as your laptop
    
#### Update Interview Recordings and Transcriptions Tracking Sheet
- [x] Open the Interview Recordings and Transcriptions Tracking Sheet (linked in Resources # 2.03) 
- [x] In Column A of the Tracking Sheet, enter the participant number(s)
     1. The participant number is reflected in this issue's title
     1. Refer to the "Session Table" tab of `TWE: IS22: RP014: Mentor Exit Interview Roll Call and Session Table` inside `Google Drive Folder: RP014` (Resources # 2.02) if you need a source to double check on participants' information
- [x] In Column B of the Tracking Sheet, enter the recording link(s)
    1. Go to Mentor 001's interview recording file (Resources # 2.05) 
    1. Choose the three vertical dots on the right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Copy Link" 
    1. Paste the link of the .mp4 file(s) into the corresponding participant's cell in Column B `Recording Link` of the Tracking Sheet (Resources # 2.03) 
- [x] In Column C, enter the transcription link(s)
    1. Go to RP014's interview recording folder (Resources # 2.04)
    1. Locate the .txt file(s) for Mentor 001
    1. Choose the three vertical dots on the right side of the file <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
    1. Choose "Share"
    1. Choose "Copy Link" 
    1. Paste the link of the .txt file(s) into the corresponding participant's cell in Column C `Transcription Link (on Internship - PII's private drive, in .txt format)` of the Tracking Sheet (Resources # 2.03) 
    1. In Resources # 2.06, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    1. Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked

#### Review and hand off
- [ ] Review with UXR Leads to make sure the transcription is done properly
- [ ] The assignee checks in with UXR Lead to create new issues for cleaning up and de-identifying the transcripts if needed
- [ ] UXR Lead or PM removes the assignee from the Internship - PII's "My Drive" when closing the issue if the assignee does not need to access the Internship - PII's "My Drive" any longer
- [ ] Product sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and Name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03* [TWE Interview Recordings by Plan #](https://drive.google.com/drive/folders/1lvP_k4qGKD05QzbHBtIpEl4B3X7ylzoh?usp=sharing)
1.04 [1password](https://start.1password.com/signin?l=en)

#### Resources gathered during the completion of this issue
2.01 [Wiki: Research Plan: RP014](https://github.com/hackforla/internship/wiki/Research-Plan-14:-Mentor-Exit-Interviews)
2.02 [Google Drive Folder: RP014](https://drive.google.com/drive/folders/1VRKUJx75IAQMtDdsyZBTz9HtJeTK8bR0?usp=drive_link)
2.03 [TWE: IS22: RP014: Mentor Exit Interview Recordings and Transcriptions Tracking Sheet](https://docs.google.com/spreadsheets/d/1ZkMgFbIqHmIRr0FsqAXsFdHRRwbitUVVymBh9Rta_H8/edit?usp=drive_link)
2.04* [RP014 Interview Recording Folder](https://drive.google.com/drive/folders/1PyxK1lb6T3qZuU_mzYkRkhTb9Zqwr1os?usp=drive_link)
2.05* [RP014 Mentor 001 Interview Recording File](https://drive.google.com/file/d/1kwzqnTDZ5QYfoZmxmr8ugkMihiDkwlyZ/view?usp=drive_link)
2.06* [RP014 Mentor 001 Interview Recording Transcript](https://drive.google.com/file/d/102J-SCYrQSf0wJvWyqKpr-eit3f_TChg/view?usp=drive_link)

* indicates this folder can only be accessed from the Internship - PII's "My Drive"

**Comment by mh-faraji** [comment]
@pandanista It's done. Please let me know if there is anything else. 

I just noticed that in the Resources section, 3.01 should be 2.01.
![Screenshot 2024-11-12 at 6 42 06 PM](https://github.com/user-attachments/assets/cf4df5db-de42-4fb3-97f9-9c703d4ed0ff)

**Comment by pandanista** [comment]
- Closing this issue as it is a duplicate of #684
