### ISSUE TITLE
Organize Internship Google Drive

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#66]
### Overview
We need to clean up and organize the internship google drive so it is easier to navigate and find what we are looking for

### Action Items
- [x]  Go over all the items on the google drive 
- [x] Move it to folder and if it doesn't have a folder, create one

### Resources/Instructions
[Internship google drive](https://drive.google.com/drive/folders/1z3I2SLQzYWBHIypNZO-sTdSO0A8c5pvt)

**Comment by Rabia2219** [comment]
@priyatalwar how do we want to proceed with this?

**Comment by sniux** [comment]
@priyatalwar you can create a miscellaneous folder.

**Comment by ExperimentsInHonesty** [comment]
Priyanka will place the images that are in the main folder into appropriate subfolders or ask the team where they go during the next meeting.

**Comment by priyatalwar** [comment]
- Ask snigdha about the recording and put it in a folder
- make a list of files and extensions of the files that can't be opened

**Comment by ExperimentsInHonesty** [comment]
I sent Snigdha a slack message now, with the following

> @Snigdha hope you had a good trip and are safely in the US.  Gentle reminder the following things are still outstanding:
https://github.com/hackforla/internship/issues/48#issuecomment-1009241025

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by priyatalwar** [comment]
Update: Singdha moved the recordings so I'll close this issue.
