### ISSUE TITLE
Audit: Research Question form

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#67]
### Overview
We need to audit the questions from the research plan and form in order to make sure they are the same, or which wording we are keeping and to be able to categorize them, so that we can redesign the form (including numbering)

### Action Items
- [x] Create a spreadsheet
  - [x] #
  - [x] Research Plan Question
  - [x] Form Question
  - [x] Match (yes/no)
  - [x] Category (e.g. before, after, level2, etc)
- [x] Copy the questions from the current research plan
- [x] Copy in the questions from the Form
- [x] Categorize
- [x] Order and number the research questions

### Resources/Instructions
[Interview form/Script](https://docs.google.com/forms/d/1kk6vuus8TbtZTjD9zP5KHrH1_VITnVDJwH3OZrut0xw/edit)
[Research Plan](https://docs.google.com/document/d/15jkt2K0k3amrMMCHopNwurRrZpFyXDFhsjZ1YZ0qP9o/edit)
[spreadsheet](https://docs.google.com/spreadsheets/d/1eKwWw71aXEZDpyjB3qK8p1faZL_Ofak9wbx6fH1VZe0/edit#gid=0)

**Comment by tonydo95** [comment]
I have finished my tasks. If you need to me to change something, message me about them.

**Comment by sniux** [comment]
@priyatalwar @ExperimentsInHonesty @tonydo95 I have reordered some questions and numbered them.
