### ISSUE TITLE
Add feature label to each issue

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#72]
### Overview
We need to be able to sort the  github board and issues by feature labels so that we can see the status and progress of any given feature

### Action Items
 - [x] Create a feature label  based on objectives and what is needed to achieve them
 - [ ]  Assign a Feature missing' label to all issues without a feature label
    - [ ] For all 'Feature missing' issues, assign the appropriate feature label or create a new label if needed

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1GijHiK_DRmlU8U0fZKsV9cjYhy9h3pZ5_OYQVx_mbgo/edit#gid=1055226176

**Comment by ExperimentsInHonesty** [comment]
Closing this issue because there is already an issue made for this #23
