### ISSUE TITLE
Send Intern Status to BWS

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#8]
### Dependency
- [x] End of internship IS21
- [ ] communications Guide #5 

### Overview
We want to send the Status of our Brentwood Interns to BWS to maintain our relationship with them and keep a steady supply of interns for following years.

### Action Items

- [x] Aggregate status in google sheets
- [x] Send to BWS a final count

### Resources/Instructions
[Email](https://mail.google.com/mail/u/3/#inbox)
[Internship Status](https://docs.google.com/spreadsheets/d/1Q6YCQVv6czLTEVF-mZ0LGx1Pr5x_TxFp8Pau25aiTn4/edit#gid=0)
[Internship Role Call](https://docs.google.com/spreadsheets/d/11KC6P07dr_DEIq5lGZ_vqyakq-rfOEBSTqqduFLiVbs/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
We missed the window to send them anything about Summer 2021 before they started their next planning session.

**Comment by ExperimentsInHonesty** [comment]
We did respond to the docs they sent us, so we didnt miss any requirements, we were just wanting to send more, and we didn't have time
