### ISSUE TITLE
Recruit a UX Research Lead

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#82]
### Dependency
When we need another UX research lead

### Overview
We are trying to recruit a UX Research lead who has an advanced degree, preferably PhD with 1+ years of experience. 

### Action Items

- [x] Edit note
- [x] Post it in opportunities
- [ ] Talk to potential UX researchers
- [x] post on open roles board 
- [ ] If needed, recruit outside our org by using the pipelines doc to find other places to post
- [ ] Once onboarded to our team, move the issue to filled on UX open roles board if we don't need anymore of them

### Resources
- UI/UX open research roles board: https://github.com/hackforla/UI-UX/projects/2
- [UI/UX pipelines](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/preview)
- HTML to put at the top of the open role card so that the logo appears above the content
```
<img width="482" alt="Finalized Logo" src="https://user-images.githubusercontent.com/29762834/165822892-edadce5d-9c69-42e1-80d3-ec18e7b37fa4.png">
```
- Posting 1: https://github.com/hackforla/UI-UX/projects/2#card-72190081
- Posting 2: https://github.com/hackforla/UI-UX/projects/2#card-86010500
```
**Project Name**:  HfLA Internship Project - This opportunity is for a team member to help us build out next summer's internship program.

**About the Project**: The project provides an opportunity for high school/college students to work in the fields of software, product development, project management, and UI/UX design over summer. They work on open source projects gaining confidence, competence and deliverables which they add to their LinkedIn profiles.

**Volunteer Opportunity**: As a UX Research Lead, you will oversee all research roles and lead main research team meetings. Collaborate with Project Lead for resource management, process improvement, support, etc. Create, prioritize, assign and ensure weekly follow-ups of tasks and the advancement of the team’s work based on deliverables.

**Duration**: Ongoing

**Who to communicate your interest to**
- Slack channel link: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack name of person to contact : Priyanka Talwar

[Read more about the project](https://github.com/hackforla/internship/wiki) 
```

```
**Project Name**: Tech Work Experience

**About the Project**: The goal of this team is to design and execute an internship project geared toward high school and college students to help them develop the hard (technical) and soft skills (workplace collaboration) required to successfully land STEM careers.

**Volunteer Opportunity**: If you are a researcher who wants to gain experience running a team and grow the TWE ResearchOps (research operations) at the enterprise scale, please join us.  

**Duration**: open-ended
[Meeting times](https://github.com/hackforla/internship/wiki/Joining-the-Team#meeting-times)

**Who to communicate your interest to**
- Slack channel link: #internship
- Slack name of person to contact in the channel: Ying O

**Read more about the [role and project](https://github.com/hackforla/internship/wiki/Open-Role:-UX-Researcher)
```

**Comment by sniux** [comment]
Changed the role from: _We are recruiting a UX researcher who will be working with various methodologies to analyze the various scopes for improvement in enhancing the experience of the interns we have recruited for the program. They will also be working on drafting hypotheses and finding actionable insights for the problem statements, that will solidify the establishment of the program._ to _**We are recruiting a UX research lead who will be guiding the UX Research team of the project by examining various methodologies to analyze the areas for improvement in enhancing the experience of the interns. They will also be on drafting hypotheses and finding actionable insights for the problem statements, that will solidify the establishment of the program.**_

**Comment by priyatalwar** [comment]
I changed the role completely. Please review @sniux

**Comment by sniux** [comment]
Looks great @priyatalwar.

**Comment by priyatalwar** [comment]
@sniux @Rabia2219 posted the opportunity

**Comment by priyatalwar** [comment]
Posted opportunity on slack

**Comment by priyatalwar** [comment]
Update 11/16: Slack message:
from Tammy Yung: She has a PhD in psychology, but does not seem to have UX Research experience. here is her LinkedIn profile https://www.linkedin.com/in/tammy-yung/. @sniux @ExperimentsInHonesty please review at tonight's meeting and lmk if I should get back to her.

**Comment by priyatalwar** [comment]
@sniux @ExperimentsInHonesty did you get a chance to discuss Tammy? I'd like to let her know by tomorrow.

**Comment by ExperimentsInHonesty** [comment]
Recent post edit
```
Project Name: Internship Project

**About the Project**: Program that provides opportunity for high school/college students to work in the fields of software, product development, project management, and UI/UX design. 

**Volunteer Opportunity**: We are trying to recruit a UX Research lead who has an advanced degree, preferably PhD with 1+ years of supervisory experience.  You will oversee all research roles and lead main research team meetings. Receive guidance & mentorship and collaborate with Project Leads for resource management, process improvement, support, etc. Create, prioritize, assign and ensure weekly follow-ups of tasks and the advancement of the team’s work based on deliverables.

Note: This is not an internship

**Duration**: Ongoing

**Who to communicate your interest to**
- Slack channel link: [#internship](https://hackforla.slack.com/archives/C01VAUPU788)
- Slack contact : Priyanka Talwar

[Read more about the project](https://github.com/hackforla/internship)
```

**Comment by sniux** [comment]
@priyatalwar Looks good. Did you talk to Tammy yet?

**Comment by ExperimentsInHonesty** [comment]
@sniux Tammy went to another team.

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar we need to update the link for finding out more, to go to the onesheet, set to anyone can view.  Please make sure one sheet has a draft in the title.

**Comment by priyatalwar** [comment]
Update 12/13: Slack messages
[Aditi Paul ](https://www.linkedin.com/in/aditipaulphd/) : From aditi:  have conducted 7 independent research projects examining the impact of social technologies on end users using a variety of research methodologies including surveys, experiments, and contextual analysis" 
She will attend onboarding on 12/13

Slack message from [Maria Sailo](https://www.linkedin.com/in/maria-s-3318b58/) "Hi Priyanka. Maria here. I volunteered as UX researcher at Code for San Jose and completed project 311 with the UX team earlier this year. I have a PhD in social sciences and 7 years research experience. I would loved to send you my research & would be happy to assist in user experience research project.
Thank you!"

**Comment by priyatalwar** [comment]
Priyanka to send a leetucemeet Bonnie's availability: 7:30 am - 9 pm PST M - S, set it up and send to Bonnie first and then have Snigdha fill it out and the potential candidates.

**Comment by priyatalwar** [comment]
Update 12/13: Position has been filled and Aditi Paul (the new Research Lead) will attend the UX meeting tomorrow @sniux

**Comment by priyatalwar** [comment]
Need to recruit again

**Comment by priyatalwar** [comment]
update 1/16: Here is the posting https://github.com/hackforla/UI-UX/projects/2#card-72190081

**Comment by ExperimentsInHonesty** [comment]
Priyanka will come to onboarding at 7pm

**Comment by ExperimentsInHonesty** [comment]
Priyanka will post again.

**Comment by priyatalwar** [comment]
Update 1/27 Reached out to Maria (she contacted us before and was interested in the UX Research Lead position), can share her resume, and decide if we want to pursue it.

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar do we need anymore people in this role, or can we mark it as filled?  See new task items at the top of this issue

**Comment by priyatalwar** [comment]
@ExperimentsInHonesty Hopefully we don't need any more people in this role. I'll close the issue once Maria is onboarded.

**Comment by Rabia2219** [comment]
@priyatalwar...reminder...we don't close recruitment issues...just unassign and move to Ice Box...

**Comment by priyatalwar** [comment]
Thanks, will do it once Maria attends onboarding next week.

**Comment by ExperimentsInHonesty** [comment]
We are going to leave this in progress and see what happens with Maria.

**Comment by Rabia2219** [comment]
Unassigned Priyanka from this issue. Will pick it up after discussing with Bonnie.

**Comment by ExperimentsInHonesty** [comment]
We are currently in need of a UX lead.  We have updated the post so that people will reach out to Priyanka.

**Comment by priyatalwar** [comment]
Christine is the new research lead. We don't have a need for co-leads, but we need additional UX researchers.

**Comment by ExperimentsInHonesty** [comment]
- We no longer use this format. See https://github.com/hackforla/internship/issues/602
