### ISSUE TITLE
Polish up the slide deck according to the branding guidelines

### ISSUE THREAD

**Issue by sniux** [hackforla/internship#83]
### Dependencies
- [x] #68 
- [x] #167 

### Overview
We need to revamp the Research 1 slide deck to have a consistent tone with the branding guidelines. 

### Action Items

- [ ] Finalize the brand identity #68 
- [ ] Edit the slide deck accordingly
- [ ] Check off the box in the epic that refers to this issue #53

### Resources/Instructions
[Slide deck
](https://docs.google.com/presentation/d/1i83YamHc64eBGIjtkb9PJ-Gnhwkafo-uRFD0qjTZKWo/edit)[Brand Identity Figjam](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
@ale22arevalo Thanks for your work on this.  I am closing this issue.  Your work was fantastic!
