### ISSUE TITLE
Bonnie: Create Brand Values

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#88]
### Overview
We need to marry the brand attributes that we identified and define them as our values.

### Action Items
Brand Values Part 2

- [ ] See examples on the [ FigJam for Brand Identity](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1)
- [ ] Take the Attributes we've identified
- [ ] Define them as our values.  

Examples: See Cars.com for ref. and will add the Hotel ; Chocolate Values for reference in the Figjam.

Our Brand Attributes:
Supportive
Collaboration
Practical 
Innovative
Structured / Adaptive
Inclusive
Fun

[ FigJam for Brand Identity](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1)
[Brand and Style Development](https://github.com/hackforla/internship/issues/68)

**Comment by ExperimentsInHonesty** [comment]
We finished this portion.  We came up with the follow values

### Supportive
We incorporate mentorship into our culture.  It supports through defined interaction with peers, pros and managers

### Collaboration
 We share ideas and knowledge on diverse cross functional teams to make better software.

### Practical, Impactful & Fun
We have fun while work on visible projects addressing real world problems.

### Innovative
 We use Agile techniques, open source and ethical structures to achieve extraordinary results. 

### Structured / Adaptive
 We believe a program should be structured to reach your goals, and adaptive to your learning methodologies and creative thinking.

###  Inclusivity
We create a place of kindness, generosity and belonging, where you can feel welcome and confident irrespective of age, skill, background, and experience.
